.github/workflows/codeql-analysis.yml

Add CodeQL code scanning to repo (yml file was auto generated with no modifications made)
For catching security vulnerabilities. More info: https://codeql.github.com/docs/
See PR checks on this PR

Add CodeQL code scanning to repo

---

change/react-composites-bd5cbc6f-3561-4293-a395-b767ba02affd.json
packages/react-composites/src/composites/CallComposite/CallScreen.tsx
packages/react-composites/src/composites/OneToOneCall/CallScreen.tsx
packages/react-composites/src/composites/common/PermissionsBanner.test.ts
packages/react-composites/src/composites/common/PermissionsBanner.tsx
packages/react-composites/src/composites/common/styles/PermissionsBanner.styles.ts
samples/Calling/src/app/CallScreen.tsx
samples/Calling/src/app/PermissionsBanner.test.ts
samples/Calling/src/app/PermissionsBanner.tsx
samples/Calling/src/app/styles/PermissionsBanner.styles.ts

Add a permissions banner to warn user if the app has no camera/microphone permission.
Follow this reference design from Alex P:
Screenshots:
Tested using unit test and also manual verification of Calling Sample, Calling Composite in Storybook, and OneToOne Call Sample.

Add a permissions banner to warn user if the app has no camera/microphone permission

---

change/calling-stateful-client-ce9d64b8-7b9a-448d-af42-b05b364abdfc.json
packages/calling-stateful-client/review/calling-stateful-client.api.md
packages/calling-stateful-client/src/StatefulCallClient.ts
packages/calling-stateful-client/src/StreamUtils.ts
packages/communication-react/review/communication-react.api.md

Instead of `CommunicationUserKind | PhoneNumberKind | MicrosoftTeamsUserKind | UnknownIdentifierKind` use `CommunicationIdentifierKind` as it is a type designed to contain all the kinds of identifiers.
Follow up for code review feedback: https://github.com/Azure/communication-ui-library/pull/293#discussion_r635586193.
Manually tested using Calling Sample and verify existing functionality works.

Use CommunicationIdentifierKind instead of the list of types

---

packages/storybook/.storybook/TOC.tsx
packages/storybook/.storybook/preview.tsx

Table of contents is more stylized now. Looks sharper and has consistent fonts.
TOC has 
- reduced font sized 
- tighter margins
- Margins between list items.
- Margins between anchors.
- responsive. Will be hidden if the screen is not wide enough (1200px).
If viewport is wider than 1200px
If viewport width is between 900px and 1200px
If viewport is smaller than 900px
For narrow screens, TOC would overlap content making it impossible to read.

Making Table of contents more usable.

---

common/config/jest/jest.config.js

Minor update for the collectCoverageFrom directory as it wasn't picking up any files.
I think because we specify a rootDir, the collectCoverageFrom paths are build starting from the root dir. For example we had a rootDir of './src' and a collectCoverage path of 'src/...' the final path ended up being something like './src/src/...' which is not a folder we have and no files are there.
Run rushx test:coverage and view the coverage:

Minor fix for collectCoverageFrom directory

---

change/calling-stateful-client-fd252e0a-f601-4c87-ae6a-06b7284e6614.json
packages/calling-stateful-client/review/calling-stateful-client.api.md
packages/calling-stateful-client/src/StatefulCallClient.ts
packages/communication-react/review/communication-react.api.md

The only argument this takes currently is a `userId`. This user ID is a Contoso supplied string that is merely persisted in the state. The documentation states that Contoso doesn't have to provide it. So make it so. The simplest way to create the object now is simply:
createStatefulCallClient()
Make the types say what the documentation says.
`rush build`
`rush test`

Make arguments to CreateStatefulCallClient optional

---

change/react-composites-ab0efec4-3f3e-4f24-904a-931a619f4e2f.json
packages/react-composites/src/composites/CallComposite/Lobby.tsx
packages/react-composites/src/composites/CallComposite/selectors/lobbySelector.ts

* Drop a spurious reference to userId in CallComposite
* A step towards removing the use of `getIdFromToken` hack from `CallComposite`.
* Manually verified `CallComposite` stories.

CallComposite: Drop spurious use of composite supplied userId

---

packages/storybook/.storybook/preview.tsx

Storybook will now automatically scroll to the top if a user changes a page.
It is a smooth scroll.
https://user-images.githubusercontent.com/9782747/120379587-d35ee900-c2d4-11eb-9242-49831d2a050b.mp4
If a user was halfway in a storybook doc and switched to another page, the scrollbar remained at the same position requiring the user to manually scroll to the top.

Auto Smooth Scroll to the top on storybook page change

---

packages/storybook/stories/UseCases.stories.mdx

> Outgoing screen sharing is only supported on desktop iOS.
Current storybook describes desktop iOS instead of desktop (macOS). Should here be a mention that screensharing on iOS is only supported via the native SDK? (if that is supported)
does not apply 

Update UseCases.stories to clarify iOS vs macOS screensharing support

---

change/react-composites-56d1f128-3f50-4329-85fb-63c17b6c13bc.json
packages/communication-react/review/communication-react.api.md
packages/react-composites/review/react-composites.api.md
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
packages/storybook/stories/ChatComposite/CustomBehaviorExampleContainer.tsx
packages/storybook/stories/ChatComposite/snippets/Container.snippet.tsx
packages/storybook/stories/ChatComposite/snippets/CustomDataModelExampleContainer.snippet.tsx
packages/storybook/stories/ChatComposite/snippets/CustomizeBehavior.snippet.tsx
packages/storybook/stories/ChatComposite/snippets/JoinExistingChatThread.tsx
packages/storybook/stories/ChatComposite/snippets/Server.snippet.tsx
packages/storybook/stories/QuickStarts/snippets/QuickstartCompositeAdapter.snippet.tsx
packages/storybook/stories/QuickStarts/snippets/QuickstartCompositeComplete.snippet.tsx

A step towards deleting `getIdFromToken` hack.
Played with various `ChatComposite` canvases on local storybook.

Add userId to ChatAdapter factory function

---

change/react-composites-681ee3e4-d90b-4c15-a798-18d86ef06e95.json
packages/react-composites/src/index.ts
samples/Calling/src/app/App.tsx
samples/Calling/src/app/Lobby.tsx
samples/Calling/src/app/selectors/baseSelectors.ts
samples/Calling/src/app/selectors/lobbySelector.ts
samples/Chat/src/app/App.tsx

Drop use of `getIdFromToken` and stop (non-release) exporting it from `react-composites`.
This is an unnecessasry hack going from token -> ID, when the ID is both already available in the sample, and not even required.
Joined a Teams meeting from Calling sample and ensured Lobby looks good with / without video turned on.

Drop use of `getIdFromToken` in sample app

---

.github/workflows/azure-pipeline-action-fork/package-lock.json
.github/workflows/azure-pipeline-action-fork/package.json

Bump underscore dependency to >= 1.12.1 (required bumping the dependent library as well), more info: https://github.com/microsoft/azure-devops-node-api/pull/435
The package underscore from 1.3.2 and before 1.12.1 are vulnerable to Arbitrary Code Execution via the template function, particularly when a variable property is passed as an argument as it is not sanitized.
Details of the vulnerability cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23358

Update underscore dependency to >=1.12.1

---

change/react-composites-c5ab2478-d32f-4d95-8a87-968283d3029e.json
packages/react-composites/src/composites/OneToOneCall/OneToOneCall.tsx
packages/react-composites/src/composites/OneToOneCall/providers/CallingProvider.tsx
packages/react-composites/src/composites/OneToOneCall/utils/SDKUtils.ts
packages/react-composites/src/utils/SDKUtils.test.ts
packages/react-composites/src/utils/SDKUtils.ts

* `getIdFromToken` has been excised from the rest of the codebase.
* Cleanup of this composite is pending decision about its future.
`rush build`
`rush test`

Make `getIdFromToken` internal to OneToOneCallComposite

---

.github/workflows/alpha-release.yml
.github/workflows/nightly-ci.yml
docs/infrastructure/creating-a-release.md
docs/references/updating-npm-publishing-credentials.md

Docs
* Update publishing documentation around alpha releases
* Add documentation regarding the keys and tokens used in creating npm releases from github
Improvements
* Get the package version from the npm package package.json instead of using a hardcoded value.
* Run `npm ci` for forked github action dependencies instead of `npm i`
Docs are needed.
Using version from package.json was a needed, fast follow up from #418.
`npm ci` will use the package-lock versions of packages so is more stable (`npm i` grabs new dependency versions if available).
Tested the `jq` command worked locally.
End-to-end test: https://github.com/Azure/communication-ui-library/actions/runs/903529260

Add documentation (+small improvements) to alpha release and npm package publishing

---

change/calling-component-bindings-44281a38-e134-4110-a5b0-9366d8f50544.json
change/calling-stateful-client-70134a8e-add0-473c-b5d7-c57db46f2829.json
change/react-composites-94269ab5-208b-4951-a650-ceb061ae966e.json
packages/calling-component-bindings/src/baseSelectors.ts
packages/calling-stateful-client/review/calling-stateful-client.api.md
packages/calling-stateful-client/src/CallAgentDeclarative.test.ts
packages/calling-stateful-client/src/CallClientState.ts
packages/calling-stateful-client/src/CallContext.ts
packages/calling-stateful-client/src/CallDeclarative.test.ts
packages/calling-stateful-client/src/DeviceManagerDeclarative.test.ts
packages/calling-stateful-client/src/StatefulCallClient.test.ts
packages/calling-stateful-client/src/StatefulCallClient.ts
packages/calling-stateful-client/src/StreamUtils.test.ts
packages/communication-react/review/communication-react.api.md
packages/react-composites/review/react-composites.api.md
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
packages/react-composites/src/composites/CallComposite/hooks/useAdaptedSelector.ts
packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
packages/react-composites/src/composites/OneToOneCall/providers/CallingProvider.tsx
samples/Calling/src/app/App.tsx

* Store userId as CommunicationUserKind in both StatefulCallClient and CallAdapter
* State uses backend DTOs. Using structured userId makes the type clear.
* Brings StatefulCallClient on par with StatefulChatClient, which already stores userId as CommunicationUserKind.
`rush build`
`rush test`

Store and expose userId in call state as structured object

---

change/calling-stateful-client-82655838-6d98-474f-af21-dfcb0b74fea1.json
change/react-components-f5b8a61a-362e-422c-874d-672850b696dc.json
packages/calling-stateful-client/src/CallContext.ts
packages/react-components/src/components/VideoGallery.tsx
packages/storybook/stories/UseCases.stories.mdx

Replace memoizeFn with react.memo
- There is one memoizeFn could be replaced by react built in memoization function React.memo
- This will unlock the ability for us to call useEffect for unmounting
- Add unmounting function to VideoTile so no memory leak anymore
Also this PR fixes maxListener warning by setting a practical default number of maxListener(yea, it comes back)

Replace memoizeFn with react.memo

---

.github/workflows/alpha-release.yml
.github/workflows/nightly-ci.yml

Remove quote marks when getting the version number from the package.json by using `-r` in the jq query (i.e. `--raw-output`)
Alpha build failing because of this:
Example failing action: https://github.com/Azure/communication-ui-library/runs/2750588822?check_suite_focus=true
Just locally in wsl:

Fix alpha release - remove unintended quote marks

---

samples/Chat/package.json
samples/Chat/src/app/ConfigurationScreen.tsx

Remove dependency on `office-ui-fabric-react` in chat sample
This is no longer needed as focus zones are exported from fluentui/react package

tiny cleanup - remove office-ui-fabric usage

---

.github/workflows/publish-chromatic.yml

Trigger publishing to chromatic after each PR completes
So https://aka.ms/acsstorybookdev will always be a latest version link

Update dev storybook after each PR 

---

change/react-composites-6c97b79f-e3c0-4a93-919b-47caccb0c918.json
packages/react-composites/src/composites/CallComposite/CallControls.tsx

Add device options button in the calling composite
This was missing from the composite and removed from the calling sample when we switched the sample to using the calling composite in #486 
Ran locally

Add device options to calling composite

---

change/calling-stateful-client-a070dce9-f5e7-4d54-b7d0-0fe17fcb2edc.json
packages/calling-stateful-client/src/CallContext.ts

SDK initializes cameras with one dummy camera:
`{ id: 'camera:id', name: '', deviceType: 'USBCamera' }`
So selectedCamera will have this value { id: 'camera:id', name: '', deviceType: 'USBCamera' } before new cameras are updated. So it makes sense that we only reset selectedCamera to the first camera if we don't see it in the new list of cameras.
Video where I also test adding a new camera and showing that selectedCamera is NOT set again because it is still on the list.
https://user-images.githubusercontent.com/79475487/122629625-49a07100-d073-11eb-928d-4b4778f20584.mp4
https://skype.visualstudio.com/SPOOL/_workitems/edit/2475044

Selected camera bug fix

---

change/calling-stateful-client-95dd015d-8ef1-46c3-b56b-e99bad22cb27.json
packages/calling-stateful-client/src/CallContext.ts

Assigning the selected camera on the same draft.deviceManager instead of calling this.setDeviceManagerSelectedCamera seems to fix the issue.
Fixes #497 
To fix bug where cameras were not being in the OptionsButton during a call.
https://user-images.githubusercontent.com/79475487/123460174-16db0900-d59c-11eb-8fc6-d5db6b35ff85.mp4
because selectedCamera is undefined in this [line of code](https://github.com/Azure/communication-ui-library/blob/main/packages/react-components/src/components/OptionsButton.tsx#L99)
After this one-line fix
https://user-images.githubusercontent.com/79475487/123460248-33774100-d59c-11eb-879a-cd3ab48f8482.mp4
Manually on sample app

Fix undefined selected camera

---

change/react-components-abdd529f-6afe-4f5b-971a-97443379f1db.json
packages/react-components/src/components/MessageThread.tsx

Remove `any` types on message thread and fix null checks
I recall @ddematheu2 hitting an error when playing around with composites that scrollTop was called on an undefined object after hiding a chat window.
Looks to be because we have an async function performing work on a ref that will have been cleaned up - fixing the `any` types as these would've caught this error.
🤞

Fix: scrollTop does not exist on undefined object

---

change/chat-stateful-client-081fed3a-3527-4bfa-b623-7da85ea465f4.json
packages/chat-stateful-client/src/StatefulChatClient.test.ts
packages/chat-stateful-client/src/StatefulChatThreadClient.test.ts
packages/chat-stateful-client/src/TestHelpers.ts

Refactor some test helpers in their own module
* Before this PR, helpers were imported from one test module to another. This import confuses jest and it ends up running the tests from the imported module twice. This makes the tests run longer / adds confusion on failure.
* The mocks / helpers here could be cleaned up quite a bit, but restricting myself (mostly) to just moving the helpers for now.
`rush test`

Extract test helpers module

---

change/react-composites-178141e7-610a-457e-bff0-4f0b5cec4b3d.json
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts

Some stateful methods, e.g. `getChatThreadClient()`, will never tee errors to state. Before this PR, the composite error handling code would blow up for these errors. Instead, we now ignore those errors when triggering `'errror'` event. This makes the error reporting more consistent in state vs events.
Unittests.

Only trigger 'error' event on errors teed to state

---

change/calling-component-bindings-be768872-ddf9-4c11-b21b-9bef1247242a.json
change/calling-stateful-client-6f9c5303-b90d-4c32-b60d-defebd39ce2d.json
change/react-composites-f300868a-32e7-4052-90cd-a7aa36274b38.json
common/config/rush/pnpm-lock.yaml
packages/calling-component-bindings/package.json
packages/calling-stateful-client/package.json
packages/communication-react/package.json
packages/react-composites/package.json
packages/react-composites/src/mocks/CallingTypeMocks.ts
packages/storybook/package.json
samples/Calling/package.json

Upgrade to calling sdk v1.2.0-beta.1
* Fix some test errors
* The SDK `Call` object now has a beta property `totalParticipantCount`. Moved to our mock object using our mock call instead of the underlying sdk call object.
Ask from calling SDK team.
See changelog here: https://github.com/Azure/Communication/blob/master/releasenotes/acs-javascript-calling-library-release-notes.md
* Unit tests
* verified call composite in PR storybook.

Upgrade to calling sdk v1.2.0-beta.1

---

packages/storybook/stories/Examples/TeamsInterop/snippets/Lobby.snippet.tsx

Fix Lobby story page to use the local video feed when the video is started
Starting video in the lobby page causes an exception:
Now:
Locally (see screenshot above) very quickly (no extensive testing performed)

Quick Fix: Video in lobby story should use local video instead of throwing an exception

---

.github/workflows/publish-chromatic.yml

Remove `iframe.html` from the storybook url.
i.e.
URL that was posted to the PR comment before
```
60c7ae6891f0e90039d7cd54-lmzgyjpbjk.chromatic.com/iframe.html
```
URL that is now posted to the PR comment
```
60c7ae6891f0e90039d7cd54-lmzgyjpbjk.chromatic.com/
```
Seems like a bug in the github action, but their repo doesn't have an issues section to post issues.
See storybook link in this PR

Remove iframe.html from the storybook PR url

---

change/@internal-react-composites-778b3a8d-478b-49b5-9f0c-1ab07aef4974.json
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/hooks/useHandlers.ts

* Bind public methods of `ChatAdaptor` in constructor.
* Bind private methods when being passed as callbacks.
Fixes a bug where the ChatAdaptor wasn't getting notifications from the stateful client.
Storybook ChatAdaptor story.

Bind all methods of ChatAdaptor on construction

---

change/@internal-react-composites-778b3a8d-478b-49b5-9f0c-1ab07aef4974.json
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/hooks/useHandlers.ts

Cherry-pick of #557
Fixes serious correctness problem -- without this PR, Chat composite does not get notifications from the SDK.
storybook.

Cherry-Pick: Bind all methods of ChatAdapter on construction

---

packages/storybook/stories/IdentityManagement/snippets/ChatBackend.snippet.ts

Storybook: Use a different API method to add participants to thread.
Avoids a bug: The user that creates the thread gets added automatically to the thread, without a display name. Display name can't be changed after that.
Storybook.

Provide participants when creating chat thread

---

packages/storybook/stories/ChatComposite/snippets/Server.snippet.tsx

Another place where first chat thread participant didn't have a name.
This one was benign because the only participant who would see users without names was the bot.

Add first participant directly when creating thread

---

common/config/rush/pnpm-lock.yaml
docs/references/release-checklist.md
packages/storybook/.storybook/main.js
packages/storybook/.storybook/manager.tsx
packages/storybook/package.json

Add a console log that prints the npm package version the storybook was built for
Note: storybook core uses webpack4 so to inject this in the manager code we also had to use webpack4
After deploying a new npm package we also deploy a new version of storybook. However, we need to verify that the public storybook site did indeed update and matches that npm version or our documentation could be out of sync with the npm package.
Locally running storybook
PR storybook:

Add ability to check storybook version deployed matches the npm version deployed

---

packages/storybook/stories/ChatComposite/ThemesExample.tsx
packages/storybook/stories/ChatComposite/snippets/CustomDataModelExampleContainer.snippet.tsx
packages/storybook/stories/ChatComposite/snippets/CustomizeBehavior.snippet.tsx
packages/storybook/stories/ChatComposite/snippets/JoinExistingChatThread.tsx

Show participants in ChatComposite stories. 
The basic canvas allows turning the participants pane off, but it's useful to have it on in the other canvases.
Local storybook

Show participants in ChatComposite stories

---

change/@internal-react-components-99932551-eb89-4750-895f-0f11b2c9777f.json
change/@internal-react-composites-b0437ad7-242c-4712-93cc-81e04687e21d.json
packages/react-components/src/components/OptionsButton.test.tsx
packages/react-components/src/components/ParticipantsButton.test.tsx
packages/react-composites/src/composites/common/ErrorBar.test.tsx
packages/storybook/stories/Examples/Layouts/OneToOneCallLayout.tsx
packages/storybook/stories/MessageStatusIndicator/MessageStatusIndicator.stories.tsx

Fix icon warnings by suppressing them in tests (we don't want to fetch icons from a cdn during tests).
Two other small build errors
Cleaning up test warnings - ideally all warnings will fail tests but that is proving to be a longer work item so putting this PR up to quickly clean up some (but not all) existing warnings.
Locally, npm run test

Fix icon warnings in tests (and two other v. small test errors)

---

change/@internal-react-components-fbf28d65-dbdf-4d2d-83c4-af232ec4bf21.json
packages/react-components/src/components/SystemMessage.tsx
packages/react-components/src/components/styles/SystemMessage.styles.ts
packages/storybook/stories/CallComposite/__snapshots__/CallComposite.stories.storyshot
packages/storybook/stories/ChatComposite/__snapshots__/ChatComposite.stories.storyshot
packages/storybook/stories/ControlBar/Buttons/EndCall/__snapshots__/EndCall.stories.storyshot
packages/storybook/stories/ControlBar/Buttons/Microphone/__snapshots__/Microphone.stories.storyshot
packages/storybook/stories/ControlBar/Buttons/Options/__snapshots__/Options.stories.storyshot
packages/storybook/stories/ControlBar/Buttons/Participants/__snapshots__/Participants.stories.storyshot
packages/storybook/stories/ControlBar/Buttons/ScreenShare/__snapshots__/ScreenShare.stories.storyshot
packages/storybook/stories/ControlBar/__snapshots__/ControlBar.stories.storyshot
packages/storybook/stories/Examples/DevicesDropdown/__snapshots__/DeviceSettingsDropDown.stories.storyshot
packages/storybook/stories/Examples/IncomingCallAlerts/__snapshots__/IncomingCallAlerts.stories.storyshot
packages/storybook/stories/Examples/Layouts/__snapshots__/Layouts.stories.storyshot
packages/storybook/stories/Examples/LocalPreview/__snapshots__/LocalPreview.stories.storyshot
packages/storybook/stories/Examples/TeamsInterop/__snapshots__/ComplianceBanner.stories.storyshot
packages/storybook/stories/Examples/TeamsInterop/__snapshots__/Lobby.stories.storyshot
packages/storybook/stories/Examples/Themes/__snapshots__/TeamsTheme.stories.storyshot
packages/storybook/stories/GridLayout/__snapshots__/GridLayout.stories.storyshot
packages/storybook/stories/MessageStatusIndicator/__snapshots__/MessageStatusIndicator.stories.storyshot
packages/storybook/stories/ParticipantItem/__snapshots__/ParticipantItem.stories.storyshot
packages/storybook/stories/ParticipantList/__snapshots__/ParticipantList.stories.storyshot
packages/storybook/stories/SendBox/__snapshots__/SendBox.stories.storyshot
packages/storybook/stories/TypingIndicator/__snapshots__/TypingIndicator.stories.storyshot
packages/storybook/stories/VideoGallery/__snapshots__/VideoGallery.stories.storyshot
packages/storybook/stories/VideoTile/__snapshots__/VideoTile.stories.storyshot

After confirming with Alex P., we should allow text wrapping in system message like so 
Fix #573 
https://skype.visualstudio.com/SPOOL/_workitems/edit/2506625R
Manual testing on storybook.

[Github issue] Remove truncation of MessageThread system message

---

.github/workflows/ci.yml
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
packages/check-treeshaking/package.json
packages/check-treeshaking/webpack.config.js
rush.json

Re-enable check treeshaking project by allowing that project webpack version 4
This was disabled when we upgraded to webpack 5 but it has a blocking issue to upgrading.
Turns out in rush you can allow some mismatching version numbers - so allowing it for this case
Ran `rush build -t @internal/check-treeshaking`

Re-enable check treeshaking project

---

change/@internal-react-composites-a411978b-2d9a-46dc-ba8d-5d1c4bdf7df6.json
packages/communication-react/review/communication-react.api.md
packages/react-composites/review/react-composites.api.md
packages/react-composites/src/composites/ChatComposite/ChatComposite.tsx
packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx

Remove sendBoxMaxLength option from chat composite.
This doesn't follow responsive design and assumes that the REM value is 16px which it mightn't be.

Remove sendBoxMaxLength from chat composite

---

change/@internal-chat-component-bindings-21410ea3-fee1-45bc-aa89-e114ece3a38d.json
packages/chat-component-bindings/src/chatThreadSelector.ts

We are parsing 'html' type messages in MessageThread here: https://github.com/Azure/communication-ui-library/blob/7ecfabab6d4ef3a6e6b2466c07093288c8154253/packages/react-components/src/components/MessageThread.tsx#L245
So the MessageThread selector should also allow type 'html'
I also confirmed that messages from Teams can either be 'html' or 'richtext/html'
Fix #583 
Using the meetings composite in this PR: https://github.com/Azure/communication-ui-library/pull/511

[Github issue] Allow 'html' type messages

---

.github/workflows/publish-chromatic.yml

Update GitHub action workflow file to create storybook URLs on all PRs not just PRs into main
The primary (possibly only) PRs that aren't directly into main are stacked PRs and release branch PRs. For both of these we still want the storybook URL feature.
Didn't, but same syntax as: https://github.com/Azure/communication-ui-library/blob/1fe8f23718cb98a847df798da3682fae3d132f9e/.github/workflows/ci.yml#L8

Have storybook URLs on all PRs

---

change/@internal-react-composites-5054ce4b-aa3d-4d15-bdd8-ad01edd627cc.json
packages/react-composites/src/composites/CallComposite/CallControls.tsx

Persist the options button to avoid hiding it on re-renders.

Persisting options button in sample app to avoid hiding

---

change/@internal-react-composites-491ad7ca-2c02-400c-9cb9-752fa7f42a5e.json
packages/communication-react/review/communication-react.api.md
packages/react-composites/review/react-composites.api.md
packages/react-composites/src/composites/ChatComposite/ChatComposite.tsx
packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
packages/react-composites/tests/browser/chat/app/index.tsx
packages/storybook/stories/ErrorBar/ErrorBar.stories.tsx

Disable `ErrorBar` in `ChatComposite` and add a feature flag to enable it.
Also enable it in automated tests, so that `ErrorBar` tests continue to provide coverage.
Error reporting work is still WIP so we don't want to include it in the next beta release.
Automated tests with/without feature flag to enable the ErrorBar.

Disable `ErrorBar` in `ChatComposite` by default

---

change/@internal-react-composites-462d1b30-ad2c-4c9e-9dbe-c3ae13bc6da3.json
packages/react-composites/src/composites/CallComposite/CallScreen.tsx
packages/react-composites/src/composites/CallComposite/MediaGallery.tsx
packages/react-composites/src/composites/CallComposite/styles/CallScreen.styles.ts
packages/storybook/stories/CallComposite/CallComposite.stories.tsx
packages/storybook/stories/CallComposite/snippets/Container.snippet.tsx

* Ensure media gallery has a minimum height - below which the composite is not usable so this still fits in our responsive design
* Update the composite documentation to ensure it has a set height and width by default so users copying and pasting have a good experience
* Mention this issue in the call composite styling documentation
If the parent of the call composite doesn't have a height set, the video gallery was not visible.
In storybook
| before (if no height is set) | after (if no height is set) | default experience
| -- | -- | -- |
| ![image](https://user-images.githubusercontent.com/2684369/126572555-021dc284-f598-402e-8c6e-ac64fbf8d273.png) | ![image](https://user-images.githubusercontent.com/2684369/126572499-de1407b1-a724-4b81-83e1-22c71a3d68eb.png) | …

Add min height to call composite media gallery

---

change/@internal-react-composites-97fd5fa3-9485-48c4-9d3d-9d3b2b673be5.json
packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
packages/react-composites/src/composites/ChatComposite/styles/Chat.styles.ts
packages/react-composites/src/composites/MeetingComposite/MeetingComposite.tsx
packages/react-composites/src/composites/MeetingComposite/SidePane.tsx
packages/react-composites/src/composites/MeetingComposite/styles/MeetingCompositeStyles.ts
packages/react-composites/src/composites/MeetingComposite/styles/SidePane.styles.ts

Fix styling to ensure the meeting pane is a scrollable container whilst still spanning the height of its parent
Codepen to play around with how this works: https://codepen.io/jaburnsi/pen/ZEKaoLo
Credit to this users codepen for getting the solution: https://codepen.io/anon/pen/gpjReQ
We had an ugly issue where the chat/people pane was overlapping the call control bar (see "before" screenshot below)
Validation screenshots:
| test | screenshot |
| -- | -- |
| before | ![image](https://user-images.githubusercontent.com/2684369/126857927-d8d33878-c337-4c29-b7fa-06b11e05b9cd.png) |
| after - chat pane open | ![image](https://user-images.githubusercontent.com/2684369/126857898-f577c413-d66f-449a-b788-a62b00b5aa8d.png) |
| after - people pane open | …

Fix meeting pane overlapping the call control bar

---

packages/storybook/stories/NonReact/NonReactComposites.stories.mdx

The link was not correctly formatted in the how-to non-react storybook page
It is rendering out in the documentation incorrectly
Tested locally

fixing markdown syntax for link

---

change/@internal-chat-stateful-client-1590f6eb-8e49-4add-8856-500109777482.json
change/@internal-chat-stateful-client-4ab8067f-e02d-4ae7-af21-7644e44a1c93.json
packages/chat-stateful-client/review/chat-stateful-client.api.md
packages/chat-stateful-client/src/ChatClientState.ts
packages/chat-stateful-client/src/TypeAssertions.ts
packages/chat-stateful-client/src/index.ts
packages/communication-react/review/communication-react.api.md

Re-introduce the string literal union of all error targets.
Instead of exposing advanced types to infer the literals, explicitly list them and internally assert that they're the exact error targets from the base SDK.
Useful features like intellisense for customers && ensures that the list of targets is accurate.
`rush build`

Explicitly list error targets in chat stateful client

---

change/@internal-calling-component-bindings-a155b314-74c8-422d-957e-d04dcc2cfe84.json
change/@internal-calling-stateful-client-20f63968-c3c3-4534-85a8-7e11634744d3.json
change/@internal-chat-stateful-client-f5a05abe-efe5-4541-9124-fa0d81d7ce8b.json
change/@internal-react-components-9f9f7dcd-11d8-4778-a6f0-8fe2d51f52c6.json
change/@internal-react-composites-93b7e61d-3f1b-43d0-aac0-5d18c36333de.json
packages/calling-component-bindings/src/handlers/createHandlers.ts
packages/calling-stateful-client/src/CallClientState.ts
packages/calling-stateful-client/src/DeviceManagerDeclarative.ts
packages/calling-stateful-client/src/RequestedTransferSubscriber.ts
packages/calling-stateful-client/src/StatefulCallClient.ts
packages/chat-stateful-client/src/ChatClientState.ts
packages/chat-stateful-client/src/StatefulChatClient.ts
packages/chat-stateful-client/src/TypeAssertions.ts
packages/chat-stateful-client/src/iterators/createDecoratedIterator.ts
packages/react-components/src/components/ErrorBar.tsx
packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapter.ts
packages/react-composites/src/composites/common/PermissionsBanner.tsx

Update typos where we have `@Link` instead of `@link`
(just a big find and replace)
Our docs our available on dcom and `@Link` does not work. Also fixes documentation links in vscode intellisense.

Fix tsdoc comments in codebase: `@Link` -> `@link`

---

change/@internal-react-components-c63ff8cf-fd22-4351-af00-1ab51186a30a.json
packages/react-components/src/components/OptionsButton.tsx
packages/react-components/src/components/ParticipantsButton.tsx
samples/Calling/src/index.css

Confine button flyouts to parents width
Button flyouts can exceed the screen/parent (see screenshots)
More info: https://github.com/microsoft/fluentui/issues/18835
| -- | -- |
| ![image](https://user-images.githubusercontent.com/2684369/129073478-6efcdb47-18ed-4715-bca6-cbcbbe6b5d9f.png) | ![image](https://user-images.githubusercontent.com/2684369/129073470-9f91601f-5987-48ac-8b40-064d1be54f2e.png) |
| ![image](https://user-images.githubusercontent.com/2684369/129073496-f766001a-5638-41f9-8a67-fd89d75396bc.png) | ![image](https://user-images.githubusercontent.com/2684369/129073490-595a6706-895e-4f85-8664-9f135022deb5.png) |

Fix button flyouts going out of bounds of the screen

---

samples/Calling/src/app/theming/SwitchableFluentThemeProvider.tsx

Changed default value of rtl to false.
The default value was left true for testing and was not changed back by me.
Tested on calling sample

Calling sample RTL fix

---

change/@internal-react-composites-fab28728-d56a-40cf-b435-18423977bd20.json
packages/react-composites/src/composites/CallComposite/Lobby.tsx
packages/react-composites/src/composites/CallComposite/ScreenShare.tsx
packages/storybook/stories/Examples/TeamsInterop/__snapshots__/Lobby.stories.storyshot
packages/storybook/stories/Examples/TeamsInterop/snippets/Lobby.snippet.tsx
packages/storybook/stories/Examples/Themes/snippets/TeamsTheme.snippet.tsx
packages/storybook/stories/GridLayout/GridLayout.stories.tsx
packages/storybook/stories/GridLayout/__snapshots__/GridLayout.stories.storyshot
packages/storybook/stories/QuickStarts/snippets/CallingComponents.tsx

* Fix more places where I'd missed replacing trivial render elements with undefined values props
* Undefined prop is used to detect when avatar should be shown instead of the rendered video.
storybook

Fix more instances of trivial VideoTile render elements

---

.github/workflows/ci.yml

Quick fix to ensure github action only comments about visual regression tests when the tests fail and not the build fails
When the packages build fails you would get a PR comment saying that you should update the UI tests. This comment should only happen if the _tests_ fail and not if the build step fails
Many CI runs, verified:
* All passes - no comment
* Build failes - no comment
* Build passes but tests fail - adds the comment

Update GitHub action to not comment about visual regression tests if build fails

---

change/@internal-react-components-270d0b69-fa01-489e-bd3e-cef7519b37c1.json
change/@internal-react-composites-cc4ebb09-c9c3-409a-86a2-ee9187fd5fef.json
common/config/rush/pnpm-lock.yaml
packages/communication-react/package.json
packages/react-components/package.json
packages/react-composites/package.json
packages/storybook/package.json
packages/storybook/stories/ControlBar/Buttons/ControlBarButton/__snapshots__/ControlBarButton.stories.storyshot
packages/storybook/stories/ControlBar/Buttons/EndCall/__snapshots__/EndCall.stories.storyshot
packages/storybook/stories/ControlBar/Buttons/Microphone/__snapshots__/Microphone.stories.storyshot
packages/storybook/stories/ControlBar/Buttons/Options/__snapshots__/Options.stories.storyshot
packages/storybook/stories/ControlBar/Buttons/Participants/__snapshots__/Participants.stories.storyshot
packages/storybook/stories/ControlBar/Buttons/ScreenShare/__snapshots__/ScreenShare.stories.storyshot
packages/storybook/stories/ControlBar/__snapshots__/ControlBar.stories.storyshot
packages/storybook/stories/Examples/IncomingCallAlerts/__snapshots__/IncomingCallModal.stories.storyshot
packages/storybook/stories/Examples/IncomingCallAlerts/__snapshots__/IncomingCallToast.stories.storyshot
packages/storybook/stories/Examples/LocalPreview/__snapshots__/LocalPreview.stories.storyshot
packages/storybook/stories/Examples/TeamsInterop/__snapshots__/Lobby.stories.storyshot
packages/storybook/stories/Examples/Themes/__snapshots__/TeamsTheme.stories.storyshot
packages/storybook/stories/MessageStatusIndicator/__snapshots__/MessageStatusIndicator.stories.storyshot
packages/storybook/stories/SendBox/__snapshots__/SendBox.stories.storyshot
packages/storybook/stories/VideoGallery/__snapshots__/VideoGallery.stories.storyshot
packages/storybook/stories/VideoTile/__snapshots__/VideoTile.stories.storyshot
samples/Calling/package.json
samples/Chat/package.json
samples/StaticHtmlComposites/package-lock.json

Update to @fluent/react-icons 1.1.137 that has fix for setting primaryFill prop
Was fixed by: https://github.com/microsoft/fluentui-system-icons/pull/301
Fix this console error happening all the time:
More info: https://github.com/microsoft/fluentui/issues/17804
No longer present in unit test output

Fix: "Warning: React does not recognize the `primaryFill` prop on a DOM element"

---

packages/storybook/stories/ControlBar/Buttons/Participants/Participants.stories.tsx
packages/storybook/stories/CustomUserDataModel.stories.mdx
packages/storybook/stories/IdentityManagement/IdentityManagement.stories.mdx
packages/storybook/stories/NonReact/NonReactComposites.stories.mdx
packages/storybook/stories/Overview.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartComposite.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartStateful.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartUIComponents.stories.mdx
packages/storybook/stories/Stateful Client/Adapters.stories.mdx
packages/storybook/stories/Stateful Client/OverviewStateful.stories.mdx
packages/storybook/stories/Stateful Client/SettingUpReactHooks.stories.mdx
packages/storybook/stories/Stateful Client/UsePropsForHook.stories.mdx
packages/storybook/stories/UseCases.stories.mdx

changed path of internal links in storybook (from '/?path=/' to './?path=/')
all links in storybook were broken. URL was with '.../?path=/?path=/...'
bug: https://skype.visualstudio.com/SPOOL/_workitems/edit/2553576
Ran storybook locally and also tested through this PR Storybook link :)

fix broken internal links in storybook

---

.github/workflows/touchdown-pipeline/touchdown-build-components.yml
.github/workflows/touchdown-pipeline/touchdown-build-composites.yml

Disable TD builds on pushes and PRs because too many jobs are being queued and holding up the checks for our PRs.
Based on YAML schema docs:
-https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#push-trigger
-https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#pr-trigger
Stop holding up the PRs with unnecessary checks

Disable TD builds on pushes and PRs. Reduce PR checks time.

---

change/@internal-react-composites-fd451fd1-2cca-4264-92ef-e597effabb14.json
packages/communication-react/review/communication-react.api.md
packages/react-composites/review/react-composites.api.md
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
packages/react-composites/src/composites/CallComposite/adapter/index.ts
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.test.ts
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/index.ts
packages/react-composites/src/composites/common/adapters.ts
packages/react-composites/src/composites/index.ts

* Add types for errors emitted from adapters
* Use same types for errors stored in adapter state
* Change field name: `operation` -> `target` to align with stateful error objects.
Allows for better client code.
Using the same name makes for easy conversion to-fro stateful and adapter errors and also avoids user confusion.
`rush test`
Changes error related adapter API signature

Strongly type errors from adapters

---

common/scripts/ensure-consistent-versions.js

* Temporarily allow inconsisten package version for storybook while I figure out the actual fix.
* Unblock release. We haven't versioned storybook with the NPM package yet, so this will not be a regression.
* Locally ran all the scripts needed to create a release branch.
* Will validate by creating a new release branch.

Temporarily allow different package version for storybook

---

change/@internal-storybook-07ac2e33-211b-4b5a-8631-e380b8f440ac.json
packages/storybook/package.json

Cleanup
* Remove references to internal packlets in storybook 
* Remove unused dependencies
Storybook should only reference exports from the meta package

Remove references to internal packlets in storybook package.json

---

change/@internal-storybook-fc4b2436-5929-4a2a-95ee-37d87395cf23.json
packages/storybook/stories/ErrorBar/ErrorBar.stories.tsx
packages/storybook/stories/ErrorHandling.stories.mdx

Cherry-pick https://github.com/Azure/communication-ui-library/pull/778 to release.
Document the error related functionality going out this release.
storybook via chromatic

Cherry pick: Document error handling setup (#778)

---

packages/communication-react/review/communication-react.api.md
packages/communication-react/src/index.ts

Quickly add package documentation for tsdoc/api-extractor documentation.
Text copied from aka.ms/acsstorybook intro paragraph
API extractor complains we don't have package documentation:
https://skype.visualstudio.com/SPOOL/_workitems/edit/2581874

Add package documentation

---

change/@internal-react-composites-6626f18d-d45f-4bd7-9a8c-7d643c52e120.json
packages/react-composites/package.json
packages/react-composites/tests/browser/call/CallComposite.test.ts
packages/react-composites/tests/browser/utils.ts

Wait for video ready state when testing if videos have loaded
Also:
* Add awaits to all page.bringtofront and page clicks that were missing them
* Remove retries to highlight these issues quicker
We have incredibly flakey ui tests currently
**Note**: There is still flakiness where isSpeaking border still appears - despite our tests not sending any sound. This could be a logic or SDK bug 
Ran many times locally - before ~40% would fail. Now 100% pass locally (from ~10-20 local runs)

Try fix flakey video rendering results - wait for video ready state

---

samples/Calling/src/app/views/CallScreen.tsx

Stop exiting call on all errors from adapters.
The CallComposite already acts on errors. The `error` event handler is intended for top-level error handling (e.g., showing the error in another place in the app). If the error is critical enough that the call should be dropped, the underlying SDK should do so (we haven't seen errors of that sort in practice).
Fixes the problem where starting video fails due to device permission issues. The right response is to show an error bar UI, which is the responsibility of the CallComposite, not the sample app.
Join a call with video off from Edge and Chrome, then turn on video on both. The second attempt will fail, but we will stay in the call (with video disabled).

samples: Don't exit call on all errors

---

.github/workflows/ci.yml
.github/workflows/update-snapshot.yml
change/@internal-react-composites-a708dbdf-a283-42c5-9f51-d9b6cfc2d361.json
packages/react-composites/tests/browser/common/testapp.webpack.config.js

Don't wait for packlets to be built when building code for UI tests - instead link directly to src
Should reduce CI task by 1-2minutes. Shouldn't increase the build time of ui tests. Also extends hot reloading locally to all packlets.
PR tests pass

CI optimization: don't wait for packlets to be built in ui tests

---

change/@internal-react-composites-95954aec-78d8-4793-bc19-f0454f6ab813.json
packages/communication-react/review/communication-react.api.md
packages/react-components/review/react-components.api.md
packages/react-components/src/identifiers/IdentifierProvider.tsx
packages/react-components/src/index.ts
packages/react-composites/src/composites/common/BaseComposite.tsx
packages/react-composites/tests/browser/call/app/index.tsx
packages/react-composites/tests/browser/chat/app/index.tsx
packages/react-composites/tests/browser/meeting/app/index.tsx

`IdentifierProvider` is intended for e2e testing needs. It's not part of the stable public API. So mark it @internal and rename as indicated by api-extrator.
No, 'cause @internal ;)

Mark IdentifierProvider and friends internal

---

.github/workflows/create-release-branch.yml

Use machine account that nan had created for the update-snapshots. Use it for the create release branch action so when the branch is created a CI action will be subsequently triggered
Actions by default cannot trigger other actions to prevent infinite loops.

Update create release branch to using machine account

---

.github/workflows/ci.yml
.github/workflows/update-snapshot.yml

Calling UI tests are failing frequently from a 500 calling service error.
Running only chat tests while this is being investigated.

Disable Calling UI tests while issues are being fixed

---

samples/Chat/src/app/HomeScreen.tsx

Start button in Chat sample Home page had its role defined as "main" so screen reader was announcing 'Start chat Main Landmark' instead of 'Start chat Button'.
Just removed this definition to keep the default one ("button")
bug https://skype.visualstudio.com/SPOOL/_workitems/edit/2582638
ran Chat sample locally, opened Narrator , navigated to "Start chat" button and listen to screen reader

removed button role re-definition to keep default

---

samples/Chat/src/app/HomeScreen.tsx
samples/Chat/src/app/styles/HomeScreen.styles.ts

Removed the 'tabindex' property defined on non-interactive elements to keep only interactive elements (link, buttons) focusable.
And also used FluentUI component List to defined the list of explanation instead of creating our own list structure.
a11y bug https://skype.visualstudio.com/SPOOL/_workitems/edit/2582668
Navigation keyboard (Tab key) was landing first on 'Exceptionally simple chat app' then going through the list of explanation, which all are non-interactive elements, before going to the sample doc link (first interactive element).
Ran Chat sample locally and verified that focus is on interactive elements only (link then buttons)

removed tabindex on non-interactive elements in Chat sample Home screen

---

change/@internal-calling-stateful-client-f840350e-3bbc-4bef-8146-cf3ea8c07c22.json
change/@internal-react-composites-4538a96e-03cb-464b-9cc3-e13ac6c5264c.json
packages/calling-stateful-client/review/calling-stateful-client.api.md
packages/calling-stateful-client/src/CallClientState.ts
packages/calling-stateful-client/src/CallContext.ts
packages/calling-stateful-client/src/StatefulCallClient.ts
packages/communication-react/review/communication-react.api.md
packages/react-composites/review/react-composites.api.md
packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
packages/react-composites/src/composites/CallComposite/hooks/useAdaptedSelector.ts
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/hooks/useAdaptedSelector.ts
packages/react-composites/src/composites/MeetingComposite/adapter/AzureCommunicationMeetingAdapter.ts
packages/react-composites/src/composites/MeetingComposite/adapter/MeetingBackedCallAdapter.ts
packages/react-composites/src/composites/MeetingComposite/adapter/MeetingBackedChatAdapter.ts
packages/react-composites/src/composites/MeetingComposite/state/MeetingAdapterState.ts
packages/react-composites/tests/browser/call/app/index.tsx

* Consistency in our API -- all constructors / factory functions expect `CommunictionUserIdentifier` and all state fields are `CommunicationIdentifierKind`.
* Make our API future proof. Although currently we only ever work with a CommunicationUserIdentifier for the local participant, we might accept other identifiers in the future (especially Teams). While it is backward compatible to accept a broader type of participant in the constructor, changing the state.userId field later would be a backwards incompatible change.
* Reduces the need to convert the identifier between different types in our implementation because of the increased consistency across our interfaces.
* Chat sample
* Calling sample
* `rush test`

Genearlize `*state.userId` type to be `CommunicationIdentifierKind`

---

change/@internal-react-components-4527ddaa-b6a6-420b-b4de-2b7d7d8da6a8.json
packages/react-components/src/components/CameraButton.tsx

Fixes the bug where camera button gets permanently disabled when clicking on it causes an error.
More info here:
https://skype.visualstudio.com/SPOOL/_workitems/edit/2622518
Users were not able to click toggle camera even if the camera device became available.

Bugfix camera permanently disabled

---

change/@internal-react-components-cbe01186-9d40-416f-8399-622b6a3efc2e.json
change/@internal-storybook-713b031e-24e4-451b-b86f-124ed3692ba9.json
packages/react-components/src/components/VideoGallery.tsx
packages/storybook/.eslintrc.js
packages/storybook/stories/ControlBar/Buttons/Camera/Camera.stories.tsx
packages/storybook/stories/ControlBar/Buttons/ControlBarButton/ControlBarButton.stories.tsx
packages/storybook/stories/ControlBar/Buttons/EndCall/EndCall.stories.tsx
packages/storybook/stories/ControlBar/Buttons/Microphone/Microphone.stories.tsx
packages/storybook/stories/ControlBar/Buttons/Options/Options.stories.tsx
packages/storybook/stories/ControlBar/Buttons/Participants/Participants.stories.tsx
packages/storybook/stories/ControlBar/Buttons/ScreenShare/ScreenShare.stories.tsx
packages/storybook/stories/ControlBar/ControlBar.stories.tsx
packages/storybook/stories/MessageThread/MessageThread.stories.tsx
packages/storybook/stories/ParticipantItem/ParticipantItem.stories.tsx
packages/storybook/stories/ParticipantItem/__snapshots__/ParticipantItem.stories.storyshot
packages/storybook/stories/ParticipantList/ParticipantList.stories.tsx
packages/storybook/stories/ParticipantList/__snapshots__/ParticipantList.stories.storyshot
packages/storybook/stories/SendBox/SendBox.stories.tsx
packages/storybook/stories/TypingIndicator/TypingIndicator.stories.tsx
packages/storybook/stories/VideoGallery/VideoGallery.stories.tsx

* Have descriptions set manually instead of using `<Description of=Component />`
* Quickly update participant item canvas defaults to make it nicer when landing on that component:
* |before | after |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/2684369/141157530-d91937f6-4b69-43bc-88fa-c02c9fb7e6bc.png) | ![image](https://user-images.githubusercontent.com/2684369/141157538-0c03cce5-4a74-4109-abd2-613e1565ec1f.png) |
Before `@public` and `@link` would show which isn't ideal. Can't find a way for the docs addon to handle these
Please see storybook link created by PR and check out the changes.

Remove `@public` from storybook component docs

---

change/@internal-react-components-66785bee-ce56-4bbe-9b39-f3cc727ae934.json
packages/communication-react/review/communication-react.api.md
packages/react-components/review/react-components.api.md
packages/react-components/src/components/CameraButton.tsx

Revert #968
This was a test change to see how DCOM would handle it. Turns out not how we would like, further work is being done here.

Revert PR #968 (A test change to the Camera Button function signature) 

---

change/@internal-calling-stateful-client-bc80be50-1716-4828-9324-104277dc5434.json
common/config/api-extractor/api-extractor.json
packages/calling-stateful-client/review/calling-stateful-client.api.md
packages/calling-stateful-client/src/CallClientState.ts
packages/communication-react/review/communication-react.api.md

* Re-enable failing compilation for incomaptible release tags
* Mark StatefulCallClient `diagnostics` and `transfer` as beta to fix errors
We want this to error

Re-enable `ae-incompatible-release-tags` - Mark StatefulCallClient `diagnostics` as public and `transfer` beta

---

change/@internal-react-composites-83011ace-47f1-4d6b-882c-838ded213672.json
change/@internal-storybook-1ee464fd-124d-463c-8fcd-d80f6e7aa87d.json
packages/communication-react/review/communication-react.api.md
packages/react-composites/review/react-composites.api.md
packages/react-composites/src/composites/CallComposite/CallComposite.tsx
packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx
packages/react-composites/src/composites/CallComposite/pages/LobbyPage.tsx
packages/react-composites/src/composites/MeetingComposite/MeetingCallControlBar.tsx
packages/react-composites/src/composites/MeetingComposite/MeetingComposite.tsx
packages/react-composites/tests/browser/call/app/index.tsx
packages/react-composites/tests/browser/meeting/app/index.tsx
packages/storybook/stories/CallComposite/BasicExample.stories.tsx
packages/storybook/stories/CallComposite/CallCompositeDocs.tsx
packages/storybook/stories/CallComposite/CustomDataModelExample.stories.tsx
packages/storybook/stories/CallComposite/JoinExistingCall.stories.tsx
packages/storybook/stories/CallComposite/ThemeExample.stories.tsx
packages/storybook/stories/CallComposite/snippets/Container.snippet.tsx
packages/storybook/stories/MeetingComposite/MeetingCompositeDocs.tsx
samples/Calling/src/app/views/CallScreen.tsx

Move mobileView prop to top level (i.e. not a sub-prop inside options)
The likes of theme and locale are top level - so I think mobileView makes more sense here
Verified running sample locally

Move mobileView prop to top level

---

samples/Calling/src/app/views/DisplayNameField.tsx
samples/Calling/src/app/views/HomeScreen.tsx
samples/Chat/src/app/ConfigurationScreen.tsx
samples/Chat/src/app/DisplayNameField.tsx
samples/Chat/src/app/utils/constants.ts

Removed the display name length check from our chat and call samples
bug https://skype.visualstudio.com/SPOOL/_workitems/edit/2641755
extended to Call sample
ran call and chat sample locally.
* Chat:
* Call:
mobile view: 

Alcail/removing chat/call samples display name length check

---

change/@internal-storybook-9814385c-5de0-4f94-91c8-5cdd586ac211.json
packages/storybook/stories/CallComposite/CallCompositeDocs.tsx
packages/storybook/stories/MeetingComposite/MeetingCompositeDocs.tsx

Add storybook doc note to highlight that landscape is unsupported when formfactor is mobile

Add storybook doc note to highlight that landscape is unsupported when formfactor is mobile

---

change/@internal-react-components-3b7d3c1d-edeb-44af-b63c-5fb2924ff2f4.json
packages/react-components/src/components/SystemMessage.tsx

| -- | -- |
|![image](https://user-images.githubusercontent.com/2684369/142510265-4b6514bf-aaec-4691-a050-50cb19d5dad8.png) |![image](https://user-images.githubusercontent.com/2684369/142510228-c232f60e-f29f-47fb-afab-f51cda4101f4.png)|
Causes no bueno scrollbars
See above screenshots

Wrap system messages that are too long

---

change/@internal-react-components-d0f8a112-6819-410e-a2fb-2455f3f3894d.json
packages/communication-react/package.json
packages/react-components/package.json
packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx

Remove press hold gesture message thread - instead open context menu when the message is touch clicked
UX wasn't great
Storybook web only
Touch: 
Keyboard:
Mouse:

Remove press hold gesture message thread

---

change/@internal-react-components-c81978de-a215-42da-93ca-6f19ccb76f86.json
packages/react-components/src/components/MessageThread.tsx

Fix the math, if this repros for someone again we can add a tolerance here also.
Example of when this failed:
Scrolling to the bottom didn't always dismiss the New messages button:
Storybook on web only - can no longer repro bug

Fix "New Messages" button not disappearing when scrolling to the bottom of the message thread

---

samples/Chat/src/app/utils/utils.ts

* ensure emoji background on chat sample are not transparent
Ultra low-hanging fruit bug
Ran chat sample locally

ensure emoji background on chat sample are not transparent

---

samples/Chat/src/app/ConfigurationScreen.tsx
samples/Chat/src/app/DisplayNameField.tsx
samples/Chat/src/app/styles/DisplayNameField.styles.ts

* updated text field label of Configuration page of Chat sample to be a prop of this component and not a separated text so now the narrator can read it properly
* added page heading and aria-label to Avatar list so Narrator announce what the list is for
No visual change
bug https://skype.visualstudio.com/SPOOL/_workitems/edit/2583860
ran sample Chat locally and used Narrator

Chat sample - Config page - a11y label issue on display name TextField

---

change/@internal-storybook-05a1606e-de4e-4508-a60b-0581adc5578e.json
packages/storybook/stories/MeetingComposite/snippets/Server.snippet.tsx

Replacing all occurrences of '%40' in thread ID and not just the first one
issue: https://github.com/Azure/communication-ui-library/security/code-scanning/7?query=ref%3Arefs%2Fheads%2Fmain

fix security issue on incomplete string encoding

---

change/@internal-react-composites-a2b7623e-f6db-43d8-b2db-2066a520f634.json
packages/communication-react/review/communication-react.api.md
packages/react-composites/review/react-composites.api.md
packages/react-composites/src/composites/CallComposite/Strings.tsx
packages/react-composites/src/composites/CallComposite/components/CallControls.tsx
packages/react-composites/src/composites/localization/locales/en-GB/strings.json
packages/react-composites/src/composites/localization/locales/en-US/strings.json

Display a microphone tooltip in lobby informing users that it can not be toggled. 
Headless SDK doesn't support toggling mute/unmute while a call is in lobby.

Display a microphone tooltip in lobby informing users that it can not be toggled. 

---

change/@internal-storybook-d213f68d-8259-4efc-99e0-099e65c9dff5.json
packages/storybook/stories/CallComposite/__snapshots__/BasicExample.stories.storyshot
packages/storybook/stories/CallComposite/__snapshots__/CustomDataModelExample.stories.storyshot
packages/storybook/stories/CallComposite/__snapshots__/ThemeExample.stories.storyshot
packages/storybook/stories/CallComposite/snippets/Utils.tsx
packages/storybook/stories/ChatComposite/__snapshots__/BasicExample.stories.storyshot
packages/storybook/stories/ChatComposite/__snapshots__/CustomBehavior.stories.storyshot
packages/storybook/stories/ChatComposite/__snapshots__/CustomDataModelExample.stories.storyshot
packages/storybook/stories/ChatComposite/__snapshots__/ThemesExample.stories.storyshot
packages/storybook/stories/ChatComposite/snippets/Utils.tsx
packages/storybook/stories/MeetingComposite/Utils.tsx.REMOVED
packages/storybook/stories/VideoTile/__snapshots__/VideoTile.stories.storyshot
packages/storybook/stories/controlsUtils.ts

set a display name by default when needed in Storybook and updated required data messages for composites
task https://skype.visualstudio.com/SPOOL/_workitems/edit/2653791
Ran Storybook locally
* Call (display name is not required for Calling)
* Chat
* Meeting

set default composite display name in Storybook

---

change/@internal-react-components-0109ca59-ff94-4777-93b3-3236d097c7e3.json
packages/react-components/src/components/ParticipantItem.tsx

Resize events occur due to `VideoGallery` refresh and automatically dismiss the flyout.

Do not dismiss the "remove" flyout in `ParticipantList` on resize events

---

change/@internal-react-components-c6119c1d-a695-4a82-bf20-fd3eb6370db0.json
packages/react-components/src/localization/locales/en-US/strings.json

Update stop screen sharing label to `Stop sharing`
https://skype.visualstudio.com/SPOOL/_workitems/edit/2633102
| not screensharing | screensharing |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/2684369/143494722-062a95df-4e4d-4364-8a82-cce07899a432.png) | ![image](https://user-images.githubusercontent.com/2684369/143494727-c698dd73-50cb-4765-9c54-99a4c766176d.png) |

Update stop screen sharing label to `Stop sharing`

---

change/@internal-react-composites-b180611a-ab99-4ff8-83ac-2a71c26ec1b7.json
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts

When creating chatAdapter, immediately call `chatAdapter->fetchInitialData()`
Otherwise you can create a chat composite with missing information
* Chat composite will load with no topic header (then suddenly populate it)
* Chat composite will load with no previous messages (then suddenly populate them)
* We have had flakey UI tests from this for over a month now and tripped us up - likely will trip up others.
* Chat adapter will now takes longer to construct as it has to wait for fetchInitialData to complete
Flakey ui test where previous messages hadn't loaded before screenshot was taken:

Immediately fetch initial chat data in adapter (+fix customDataModel flakey UI test)

---

change/@internal-react-composites-05c7878d-2e39-4a68-856b-13bb72b4e090.json
packages/react-composites/src/composites/CallComposite/components/LocalDeviceSettings.tsx

replace mic label by a common label for both mic and speakers dropdown
bug: https://skype.visualstudio.com/SPOOL/_workitems/edit/2565537
Ran calling sample locally and checked with Accessibility Insights

aria label missing in Call composite configuration page

---

change/@internal-calling-stateful-client-64bff3c3-0a50-41ae-b701-843bd426722e.json
packages/calling-stateful-client/src/StreamUtils.ts

This is a fairly common situation as rendering a video takes a while and the VideoGallery rerenders frequently.

Remove spammy console log when rendering video

---

.github/workflows/nightly-cd.yml

Release nightly alpha package off of `feature/conditional-compilation` instead of `main`.
We've removed all beta features from main in preparation for GA. But we'd like our alpha packages to include those.
Not tested. Will observe the nightly release after this lands.

Release alpha package off of feature branch

---

.github/workflows/alpha-release.yml
.github/workflows/nightly-cd.yml
change/@internal-acs-ui-common-211738ef-0a03-4f87-8ac9-35f9121d035c.json
docs/infrastructure/beachball.md
docs/references/creating-a-release.md
packages/acs-ui-common/src/telemetry.test.ts

Use yyymmddHHMM format instead to avoid trailing zeros and revert #1192 
Using `+` is **silently** stripped away when the npm publish happens, see alpha package published last night: https://www.npmjs.com/package/@azure/communication-react/v/1.0.0-alpha
More info: https://github.com/npm/npm/issues/12825
So we are removing the `.` between yyymmdd and HHMM as HHMM might have trailing zeros, the original reason for #1192 
Triggered alpha release to verify:
* https://github.com/Azure/communication-ui-library/runs/4412163364
* https://dev.azure.com/azure-sdk/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=19900
Result:
* https://www.npmjs.com/package/@azure/communication-react/v/1.0.0-alpha-202112031922.0

Fix alpha releases again - Use yyymmddHHMM format instead to avoid trailing zeros

---

change/@internal-react-composites-7962b1f6-6f34-4f1c-af4b-d6b4b88d3214.json
packages/communication-react/review/communication-react.api.md
packages/react-composites/review/react-composites.api.md
packages/react-composites/src/composites/CallComposite/Strings.tsx
packages/react-composites/src/composites/CallComposite/components/ComplianceBanner.tsx
packages/react-composites/src/composites/localization/locales/de-DE/strings.json
packages/react-composites/src/composites/localization/locales/en-GB/strings.json
packages/react-composites/src/composites/localization/locales/en-US/strings.json
packages/react-composites/src/composites/localization/locales/es-ES/strings.json
packages/react-composites/src/composites/localization/locales/fr-FR/strings.json
packages/react-composites/src/composites/localization/locales/it-IT/strings.json
packages/react-composites/src/composites/localization/locales/ja-JP/strings.json
packages/react-composites/src/composites/localization/locales/ko-KR/strings.json
packages/react-composites/src/composites/localization/locales/nl-NL/strings.json
packages/react-composites/src/composites/localization/locales/pt-BR/strings.json
packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
packages/react-composites/src/composites/localization/locales/zh-CN/strings.json
packages/react-composites/src/composites/localization/locales/zh-TW/strings.json

Fix a typo in `complianceBannerTranscriptionStarted`.
D'oh!

Fix typo in exposed Strings field

---

change/@internal-storybook-1f46df55-363a-4361-9586-fe5b06dbf1ef.json
packages/storybook/stories/QuickStarts/snippets/ChatAppStateful.snippet.tsx
packages/storybook/stories/QuickStarts/snippets/ChatAppStatefulComplete.snippet.tsx
packages/storybook/stories/QuickStarts/snippets/ChatAppStatefulProviders.snippet.tsx

* Initialize thread state in stateful chat quickstart
* It's non-trivial to know that this initialization is necessary. In the absence of this initialization, it's easy to be confused by the non-deterministic behaviour of when the thread properties are updated (depends on how events are received etc.)
Tried out quickstart in a scratch app.

stateful quickstart: initialize thread state

---

change/@internal-react-components-7d849dc3-28a5-41bd-a4f5-159ed4d49b8e.json
packages/react-components/src/components/styles/ControlBar.styles.ts

Maximum width of ControlBar and ControlBarButton to 8rem after discussing with Alex P. Truncating long ControlBarButton labels after discussing with Alex P . Vertical ControlBar width set to fit-content. 
https://skype.visualstudio.com/SPOOL/_workitems/edit/2657885
On storybook canvas in German in various layouts:
https://user-images.githubusercontent.com/79475487/145080644-3772ec37-f709-4713-ade7-081450ecb62f.mp4

Vertical control bar fix

---

samples/Calling/src/app/views/DisplayNameField.tsx

A previous bugfix introduced a minor bug in our calling sample where display name input is showing long display name validation error even when it is empty

Bugfix for display name input showing "long name" validation error when it is empty

---

change/@internal-react-composites-504ab3cc-e042-4936-86bd-af658c9eab74.json
packages/react-composites/src/composites/CallComposite/utils/Utils.ts

Delay transitional call page from 'configuration' to 'lobby' until call enters 'Connecting' state.
When the call object has been created, but is still in state 'None', we have observed that some properties have default values that don't reflect reality. This is problematic for local device state (e.g., whether the local participant is muted or not) as the default may not be correct, but the UI in configuration screen might already be showing the correct state. This creates an incorrect transitional UI update showing the wrong value.
Bug bash it.

Delay entering 'lobby' state till underlying 'Call' object stabilizes

---

change/@internal-react-components-2ea92f02-8df3-4e0b-9ce9-fa5687ba6cb1.json
packages/react-components/src/components/EndCallButton.tsx
packages/react-components/src/components/HighContrastAwareIcon.tsx

Fixed end call button to have red background in all accessibility modes 
Fixed contrast issues for icons in dark window accessibility modes when using light theme
This is a fix for the high contrast accessibility error.
https://skype.visualstudio.com/SPOOL/_workitems/edit/2564703
Check Calling sample in different Windows accessibility modes and see if there are any contrast issues 
Please test all four modes in light/dark settings

Fixed end call button to have red background in all accessibility modes 

---

change/@internal-react-components-59dbe480-1613-47b6-a865-6464220a7cd3.json
packages/react-components/src/components/styles/HorizontalGallery.styles.ts

Horizontal Gallery button height fixed
https://skype.visualstudio.com/SPOOL/_workitems/edit/2674356
Tested storybook manually.

Horizontal Gallery left/right button height fixed

---

change/@internal-react-components-39662025-b3a6-41b3-b4db-0a8af3cc2d99.json
packages/react-components/src/components/ScreenShareButton.tsx
packages/storybook/stories/ControlBar/Buttons/ScreenShare/__snapshots__/ScreenShare.stories.storyshot
packages/storybook/stories/ControlBar/__snapshots__/ControlBar.stories.storyshot
packages/storybook/stories/Examples/Themes/__snapshots__/TeamsTheme.stories.storyshot

Fixed ScreenShareButton component to allow custom styles BUG 2677269.
ScreenShareButton component not applying custom styles.
https://skype.visualstudio.com/SPOOL/_workitems/edit/2677269 
Applied and removed custom styles to all buttons in ControlBar in Storybook to see if styles were being applied correctly.

BUG 2677269 - Fixed ScreenShareButton component to allow custom styles

---

change/@internal-react-components-36765647-e480-42d7-a08a-f51645dec1d3.json
packages/react-components/src/components/styles/VideoGallery.styles.ts

Fixed inability to click the horizontal gallery left/right button by changing pointerEvents of LayerHost
https://skype.visualstudio.com/SPOOL/_queries/edit/2674355/?fullScreen=true&triage=true
Manually

Fixed inability to click the horizontal gallery left/right button by changing pointerEvents of LayerHost

---

change/@internal-storybook-be26839f-8828-4631-8911-5f9d225abb12.json
packages/storybook/stories/NonReact/NonReactComposites.stories.mdx
samples/Server/appsettings.json
samples/Server/src/lib/envHelper.ts

Added entry for endpointUrl in appsettings.json instead of using connectionString twice
https://skype.visualstudio.com/SPOOL/_workitems/edit/2691366

Added entry for endpointUrl in appsettings.json instead of using connectionString twice

---

samples/Chat/src/app/App.tsx
samples/Chat/src/app/utils/utils.ts
samples/Meeting/src/app/utils/utils.ts

[Sample/Chat]  Pull Chat SDK version from version made in webpack and not at runtime in the Chat utils
Should not be reaching out to external folders to get version information

[Sample/Chat]  Pull Chat SDK version from version made in webpack and not at runtime in the Chat utils

---

samples/Calling/src/app/theming/SwitchableFluentThemeProvider.tsx
samples/Calling/src/app/utils/localStorage.ts
samples/Chat/src/app/theming/SwitchableFluentThemeProvider.tsx
samples/Chat/src/app/utils/localStorage.ts
samples/Meeting/src/app/theming/SwitchableFluentThemeProvider.tsx
samples/Meeting/src/app/utils/localStorage.ts

In the sample Calling, Chat, and Meeting apps, `SwitchableFluentThemeProvider` was refactored to use local storage from utils file.
https://skype.visualstudio.com/SPOOL/_workitems/edit/2693380
Tested Calling, Chat, and Meeting apps by changing themes and seeing if they persist.
Ran 

Theme local storage refactor

---

change/@internal-storybook-417ec129-0071-4ad4-a19a-b66986a8c0ac.json
packages/communication-react/README.md
packages/storybook/stories/Overview.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartComposite.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartStatefulCall.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartStatefulChat.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartUIComponents.stories.mdx
packages/storybook/stories/Stateful Client/OverviewStateful.stories.mdx

With `1.0.1-beta.2`, clients will need to install ACS SDKs themselves.
The stable packages still install those SDKs internally.
This PR updates the documentation to point out  this difference.

Update install instructions for beta channel

---

samples/Meeting/src/app/views/MeetingScreen.tsx

Simplified use of ref in MeetingScreen.tsx by relocating Call Id console log in samples/Meeting 
Simplified code as callid is a ref and won't retrigger a re-render. 
https://skype.visualstudio.com/SPOOL/_workitems/edit/2711297
Tested on local chrome browser. 
Entered, exited, rejoined, and started a new meeting session to confirm if id gets logged upon joining a call.

[samples/Meeting] Simplified Call Id ref by relocating console log in MeetingScreen.tsx

---

change/@internal-react-components-9df18ef2-48d8-4efa-86b8-160c29620aa6.json
packages/react-components/src/components/VideoGallery.tsx

Remove VideoGallery UUID assignment to the container since we are now using a layer host. This generates its own unique id.
Remove unnecessary code and useEffect()
Tested two snippets on storybook with their own floating local video and verified each floating local video is uniquely anchored.

Remove VideoGallery UUID for container

---

samples/Calling/src/app/views/CallScreen.tsx

Simplified use of ref in CallScreen.tsx by relocating Call Id console log in samples/Calling 
Simplified code as callid is a ref and won't retrigger a re-render. 
https://skype.visualstudio.com/SPOOL/_workitems/edit/2693381/
Tested on local chrome browser. 
Entered, exited, rejoined, and started a new call session to confirm if id gets logged upon joining a call.

[samples/Calling] Simplified Call Id ref by relocating console log in CallScreen.tsx

---

common/config/api-extractor/api-extractor.json
common/config/api-extractor/api-extractor.stable.json

Removing ae-incompatible-release-tags for beta builds
Beta builds will always encounter scenarios where a public API contains beta features.
Current checks result in errors causing build failures.
Keeping this check for beta doesn't make sense.

Removing ae-incompatible-release-tags for beta builds

---

samples/Chat/src/app/ChatHeader.tsx

Conditionally removing participant button from chat sample header
Participant button  stops working for stable builds as it is being conditionally compiled (meeting composite)
https://skype.visualstudio.com/SPOOL/_workitems/edit/2767067

[Bugfix][Release 1.1.0] Conditionally removing participant button from chat sample header

---

change/@internal-react-components-4d2e6ba5-f7fa-466d-9fa2-7fd862965ae4.json
packages/react-components/src/components/ChatMessage/ChatMessageComponentAsEditBox.tsx
packages/react-components/src/components/styles/EditBox.styles.ts

Fixed editbox border that disappeared after adding wrapper div for file sharing changes
https://skype.visualstudio.com/SPOOL/_workitems/edit/2770107

Fixed editbox border that disappeared after adding wrapper div for file sharing changes

---

change/@internal-react-components-a5fd2b69-6c60-4d4f-a510-14908ed361c4.json
packages/react-components/src/components/Drawer/DrawerMenu.tsx
packages/react-components/src/components/Drawer/DrawerSurface.tsx

Change how we know we are showing a sub menu in the DrawerMenu.
Before we would set new `menuItems` when an item with a submenu was clicked, this meant if a menu item had a prop like its icon updated - this wouldn't be reflected in our cache of `menuItems` and thus wouldn't be updated.
Now we store an array of keys that result in the submenu using the mandatory itemKey field.
Menu item content like text or icon wouldn't update unless the whole menu was closed and reopened.
Locally running callwithchat sample (see how then chosen microphone icon updates when selected):
https://user-images.githubusercontent.com/2684369/155231402-82604e93-f87f-4e68-9a4c-eaf9ed46fb67.mp4

Fix drawer menu items' content not updating dynamically while the menu was open

---

change/@internal-react-components-b2c9bd47-c161-49b8-adb2-98aa648d39bd.json
change/@internal-storybook-55bc3ef5-8978-4ee8-9b1c-b64085226e27.json
packages/react-components/src/components/Drawer/DrawerMenuItem.tsx
packages/storybook/stories/INTERNAL/Drawer/DrawerMenu.stories.tsx

Apply some styling to ensure menuitem icons are vertically centered
Icons by default were not vertically centered in the DrawerMenu
* Storybook (check out PR link when generated)
* Local sample (tbd screenshot)

Vertically center menuitem icons

---

change/@internal-acs-ui-common-b3e501bf-fec9-4958-9ab0-3e5acd854892.json
change/@internal-calling-stateful-client-563d8d8e-11c8-4a1f-90b9-f36dbcbf879e.json
change/@internal-chat-stateful-client-3863a9d0-f774-4976-8bed-f33498dffa51.json
packages/acs-ui-common/review/acs-ui-common.api.md
packages/acs-ui-common/src/index.ts
packages/acs-ui-common/src/safeStringify.ts
packages/acs-ui-common/stable-review/acs-ui-common.api.md
packages/calling-stateful-client/src/CallContext.ts
packages/chat-stateful-client/src/ChatContext.ts

* Wrap state changes in verbose logging with a try catch
* Causing exceptions:
This error was seen when updating the selfhosting app. Still investigating _why_ the selfhost app sees this but the samples in this repo are not.
n/a

Hotfix: Wrap JSON.stringify in try-catch when logging state changes

---

change/@internal-storybook-486cb5cd-dbbb-4138-84ad-71266f8d2637.json
packages/storybook/.storybook/main.js

* update glob path check to include top-level stories
Storybook was not showing all mdx files that are not in folders in the code structure (e.g. the homepage)
Locally:
| development | production |
| -- | -- |
| Correctly shows all *including* internal ![image](https://user-images.githubusercontent.com/2684369/156037655-3829e180-93ca-4ce7-b0d7-66dfd6b12180.png) | Correctly shows all *excluding* internal ![image](https://user-images.githubusercontent.com/2684369/156037627-330a8e9a-860e-48d9-a9fa-95d4cb4a97f5.png) |

Fix missing storybook stories by updating the story glob path check

---

change/@internal-react-components-85ee03eb-b6a4-4c20-8679-0856d6124c70.json
packages/react-components/src/components/styles/MessageThread.styles.ts

There is a case that img from iPhone client size wouldn't be limited because it is directly defined in element
This fix uses an important tag to override it
Before:
After(because we don't have the actual file, so it img is tented to be showed as a small icon instead of full size, which is correct):
Thanks @alkwa-msft for help in testing!

Fix img size for style defined element

---

change/@internal-calling-stateful-client-79107d63-6480-404c-af2c-8c9afc81094b.json
change/@internal-react-composites-ebd1d56e-81f3-4a56-a879-a7a0f3d2f2ef.json
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
packages/calling-stateful-client/package.json
packages/communication-react/package.json
packages/react-composites/package.json

Update everywhere still using the previous 1.3.2-beta.1
Some places these weren't full updated
n/a (CI will test this)

Update calling dependencies to 1.4.2-beta.1 that were missed

---

change/@internal-calling-component-bindings-7000ef8d-bfac-4ca8-8394-9d55de340323.json
change/@internal-calling-stateful-client-2c86a0ae-ec23-4a11-8b74-0c7cb5048296.json
change/@internal-react-composites-0b7ebfa3-5289-4d84-ba16-0008ae2bf3dd.json
change/@internal-storybook-e533c5b6-8118-41fb-9b23-c8a3402c174a.json
common/config/babel/.babelrc.js
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
packages/calling-component-bindings/package.json
packages/calling-stateful-client/package.json
packages/calling-stateful-client/src/CallAgentDeclarative.test.ts
packages/calling-stateful-client/src/TestUtils.ts
packages/communication-react/package.json
packages/react-composites/package.json
packages/storybook/package.json
samples/CallWithChat/package.json
samples/Calling/package.json
samples/ComponentExamples/package.json
samples/StaticHtmlComposites/package.json
samples/tests/package.json

Upgrading calling to 1.4.3-beta.1
We want to make sure our customers are on the latest and greatest calling offering.
Customer request to have Calling updated from 1.4.2-beta.1 to 1.4.3-beta.1

Updating calling sdk for beta to 1.4.3-beta.1

---

change/@internal-react-composites-7d731dcb-276f-4bb3-bc2f-036764ec4d2b.json
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts

Discovered bug while working on `useAzureCommunicationCallAdapter` -- if the parent component unmounts, we need to dispose the adapter.
`rush build`

`useAzureCommunicationCallWithChatAdapter`: Dispose adapter on unmount

---

change/@internal-calling-component-bindings-9654ac72-bace-418e-831b-ba2fb11261b3.json
change/@internal-calling-stateful-client-cdf97a1e-7c2f-4512-b7f7-5cc5dd442df5.json
change/@internal-react-composites-1ab3de8c-14a2-4d9e-80c6-39395bfd8a72.json
change/@internal-storybook-3d25be32-5f0f-48fa-9876-2ce86df205c6.json
common/config/rush/variants/stable/pnpm-lock.yaml
packages/calling-component-bindings/package.json
packages/calling-stateful-client/package.json
packages/calling-stateful-client/src/TestUtils.ts
packages/communication-react/package.json
packages/react-composites/package.json
packages/storybook/package.json
samples/CallWithChat/package.json
samples/Calling/package.json
samples/ComponentExamples/package.json
samples/StaticHtmlComposites/package.json
samples/tests/package.json

Bump stable headless calling SDK.
Has loads of bug fixes and improvements that we'd want our customers to get in our own stable release next.
CI, local calling sample smoke test.

Bump `@azure/communication-calling` to `1.4.4`

---

change/@internal-react-composites-a452ee02-2e0c-48a2-acf0-1046466876e9.json
packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedChatAdapter.ts

Converting filesharing functions to arrow functions in CallWithChatBackendChatAdapter
Need to implicitly bind this to the functions so that they can be called from components

Converting filesharing functions to arrow functions in CallWithChatBackendChatAdapter

---

change/@internal-acs-ui-common-77c4eaed-5848-4790-b44f-981c9b93cbcc.json
change/@internal-calling-component-bindings-6152ab4d-a0a4-4ef5-843c-665c11aa070b.json
change/@internal-calling-stateful-client-81e635b4-5d23-49c3-92d3-3ebaccc7517e.json
change/@internal-chat-component-bindings-e1e97081-cd94-460c-9e5d-d9e875a6da8e.json
change/@internal-chat-stateful-client-7f1ec708-1cd1-47c3-a488-236e73d8e1ea.json
change/@internal-react-components-44cb5573-fffb-4168-989b-81275bb99b0b.json
change/@internal-react-composites-8b7b0f6b-6b8d-4e18-8431-13a4d58ce9b7.json
change/@internal-storybook-9784a90e-d674-4220-b304-6726fb61e32c.json
common/config/rush/pnpm-lock.yaml

* Generate release branch no-op changelogs
* Update primary lockfile as this branch has choosen just stable deps.
CI still failing as potentially it should only build stable on the stable release branch?

Unblock release/1.2.0 ci

---

.github/workflows/update-snapshot.yml

Same as https://github.com/Azure/communication-ui-library/pull/1642 but now we need to also update snapshots on the release branch.

Skip beta snapshots in update-snapshot

---

change/@internal-react-composites-cfcad608-226c-417d-8a2d-92d86c376774.json
packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx

FileSharing props in CallWithChat composite got removed by this PR
https://github.com/Azure/communication-ui-library/pull/1617
Need to add them again to make it work

Re-add filesharing to callwithchat composite

---

change/@internal-react-components-b71e396e-6a46-40e0-b136-e2babce007d5.json
packages/react-components/src/components/FileCard.tsx

Fix text wrapping onto next line

---

change/@internal-react-composites-304ee089-2333-4a7b-a9d2-4cccdb4707c6.json
packages/react-composites/src/composites/ChatComposite/styles/Chat.styles.ts

Update syles for the chat screen
removes the double scroll bar in mobile when file sharing is turned on
https://skype.visualstudio.com/SPOOL/_workitems/edit/2791136
Ran locally and visually inspected

Fix Double scroll bar in CallWithChatComposite (#1689)

---

change/@internal-chat-component-bindings-82459451-1502-436b-bf85-94bc70a93fc2.json
packages/chat-component-bindings/src/messageThreadSelector.ts

Disable RR details in meeting interop 
This is to not introduce problematic behavior into 1.2.0 when it is teams interop
Currently we can't get display name when it is meeting interop - because teams user are not joining using ACS, so the display name roster doesn't include displayName for teams user.
There are 2 solutions we might want to consider for future work:
1. Get display name from calling side when it is callWithChat component - no extra setup, but will only work for meeting scenarios
2. Provide our customers snippet on render custom display name and connect teams user name using AAD (extra set up and coding needed, but a more general solution)
Why

Disable RR details in meeting interop

---

change/@internal-react-components-a34ce727-b847-411c-a3d9-f2ccfe0911b1.json
packages/react-components/src/components/ModalClone/ModalClone.tsx
packages/react-components/src/components/ModalClone/README.md
packages/react-components/src/components/VideoGallery.tsx
packages/react-components/src/components/styles/VideoGallery.styles.ts

Fix floating local video tile going offscreen in `VideoGallery`:
https://user-images.githubusercontent.com/2684369/160202304-25bf07fc-9ff4-4d15-84cc-139e9a3069d3.mp4
The issue is because fluent assumes the modal is in the center of the screen when it calculates the bounds, more info: https://github.com/microsoft/fluentui/issues/20122
https://user-images.githubusercontent.com/2684369/160202333-ff62b88f-62d5-4506-a49e-653998639981.mp4
If you resize the screen the bounds need recalculated (not a regression from this PR, just another bug)

Fix: Prevent floating local video being dragged offscreen in `VideoGallery`

---

.github/workflows/ci.yml

Upload the beta and stable generated api.json files during CI builds
For easy access to upload to APIView
See artifacts uploaded in test run: https://github.com/Azure/communication-ui-library/runs/5745695409?check_suite_focus=true

Upload `api.json` files in ci build action

---

change/@internal-chat-component-bindings-cdf4f9b9-4292-41f0-b43e-c287b82c2ffd.json
packages/chat-component-bindings/src/errorBarSelector.ts

Filter out a specific rest error from being presented to the user
Currently we are showing a miscellanous "User no longer has access to this thread" Error Banner shown to user when they do in fact still have access.
This is because of a Chat SDK issue when a BotContact is a participant in Teams Interop Chats
Locally ran and no longer shows the Not In Thread error

[mitigation] Squelch "Not In Thread" Error shown to user

---

change/@internal-storybook-06e85c4f-f784-4063-99a3-6f747fa69e1d.json
packages/communication-react/README.md
packages/storybook/stories/QuickStarts/QuickstartComposite.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartStatefulCall.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartStatefulChat.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartUIComponents.stories.mdx
packages/storybook/stories/Stateful Client/OverviewStateful.stories.mdx

Our `peerDependencies` still refer to a specific headless SDK dependency, so our documentation should follow suite.

Storybook: Update references to the correct @azure/communication-calling version

---

change/@internal-react-components-973a8fae-95c5-4409-8eee-91ba9ac3b00d.json
packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx

Fixes a bug where we always showed that 0 remote participants have read a message.
Local `CallWithChat` sample.

Correctly set readBy count when `mobileView` is set

---

change/@internal-react-components-643acc17-d0ce-4f2c-bc52-9caa63bc9f54.json
packages/react-components/src/components/ControlBarButton.tsx

Set menu role for split buttons in control bar
Split buttons were voicing out two roles, split button and button. A11y recommends that only one role should be read.
https://skype.visualstudio.com/SPOOL/_workitems/edit/2790837/
Tested locally on MacOS voiceover.

[CallWithChat][A11y] Set menu role for split buttons in control bar

---

change/@internal-react-components-3094709f-e16b-4a4e-8fa1-95ea7869f00a.json
packages/communication-react/review/communication-react.api.md
packages/communication-react/stable-review/communication-react.api.md
packages/react-components/review/react-components.api.md
packages/react-components/src/components/LocalVideoCameraButton.tsx
packages/react-components/src/components/VideoGallery.tsx
packages/react-components/src/localization/locales/en-US/strings.json
packages/react-components/stable-review/react-components.api.md

Indicate which camera is currently selected in LocalVideoCameraButton using ariaDescription.
Update "Cycle camera" string to "Switch camera" as indicated by A11y bug.
https://skype.visualstudio.com/SPOOL/_workitems/edit/2791846/
Test locally on MacOS using VoiceOver

[CallWithChat][A11y] Update label and indicate selected camera in LocalVideoCameraButton 

---

samples/StaticHtmlComposites/webpack.config.js

Fixed the dev server path (oops!)
dev-server for static html composites is pointed at the right folder.
Ran locally with all other samples as well to verify fix.

fix static html sample config

---

change/@internal-react-components-a6c127ee-d965-43d5-9c30-3977b9f4822b.json
change/@internal-react-composites-caac35d4-c319-4bde-884a-85db2c432a24.json
packages/react-components/review/react-components.api.md
packages/react-components/src/components/MessageThread.tsx
packages/react-components/src/components/ResponsiveHorizontalGallery.tsx
packages/react-components/src/components/VideoGallery.tsx
packages/react-components/src/components/index.ts
packages/react-components/src/components/utils/responsive.ts
packages/react-components/stable-review/react-components.api.md
packages/react-composites/src/composites/CallWithChatComposite/CallWithChatPane.tsx

On container resize, recalculate the min and max bounds
**note: ** no change to the bounds calculations (just pulled out into a useMemo)
After resize (e.g. rotate portrait to landscape) the min and max bounds were incorrect:
https://user-images.githubusercontent.com/2684369/163233356-d647009a-81ea-46cf-a62f-bf58d0f4a3ff.mp4
https://user-images.githubusercontent.com/2684369/163233343-e20be12a-e15b-4be6-bc40-44604e6d6b96.mp4

Fix PiPiP being dragged outside the window bounds after container resize

---

change/@internal-storybook-4d997d45-9308-47af-a0af-cce5ff7bb33d.json
packages/storybook/stories/ControlBar/Buttons/Participants/snippets/WithCustomRender.snippet.tsx
packages/storybook/stories/ControlBar/Buttons/ScreenShare/snippets/Custom.snippet.tsx

Remarks | Before | After
:-- | ---       | ---
Notice highlight on hover | ![image](https://user-images.githubusercontent.com/82062616/164556821-e2a408ab-5aa0-49d4-a492-c4b6a58e59fe.png) | ![image](https://user-images.githubusercontent.com/82062616/164556900-36de58ad-713e-40e4-a31c-2134447cac00.png)
Notice the scrollbar | ![image](https://user-images.githubusercontent.com/82062616/164557028-70a76c4f-d83a-4f90-8160-fb33b2237083.png) | ![image](https://user-images.githubusercontent.com/82062616/164557051-9ff62c0a-5031-4486-bb6f-7e00dfc7dfc6.png)

Fix styling of some custom button examples in storybook

---

change/@internal-react-components-0f7a218c-6127-44ec-99fa-3ad1059951e0.json
packages/communication-react/review/communication-react.api.md
packages/communication-react/stable-review/communication-react.api.md
packages/react-components/review/react-components.api.md
packages/react-components/src/components/CameraButton.tsx
packages/react-components/src/components/ControlBarButton.tsx
packages/react-components/src/components/MicrophoneButton.tsx
packages/react-components/src/localization/locales/en-US/strings.json
packages/react-components/stable-review/react-components.api.md

Add split button aria fix to release
fixes issue where windows narrator can't interact with camera and mic buttons. Also adds split button aria labels for camera and mic buttons to have labels indicating there is a menu in the button.
https://github.com/Azure/communication-ui-library/pull/1829

Cherry pick split button fix into release/1.2.2.beta.1

---

change/@internal-react-components-eb226ab8-dad0-4116-b8b9-12e6dd4692e0.json
docs/references/quick-code-reviews.md
packages/react-components/src/components/FileDownloadCards.tsx

File download cards to use `fileSharingMetadata` file extension instead of parsing the extension from name.
This allows contoso to explicitly specify an extension for an uploaded file in case they want to render different icons.

File download cards to use fileSharingMetadata file extension

---

change/@internal-calling-component-bindings-b4315fda-dc84-4d8f-9b26-ce98d82f29f3.json
change/@internal-react-components-823865be-6866-4956-88e2-642afe84e137.json
change/@internal-react-composites-646778f8-53ed-499f-a646-3eb8649fef64.json
common/config/babel/.babelrc.js
docs/references/quick-code-reviews.md
packages/calling-component-bindings/src/callControlSelectors.ts
packages/communication-react/src/index.ts
packages/react-components/src/components/CameraButton.tsx
packages/react-components/src/components/MicrophoneButton.tsx
packages/react-components/src/components/index.ts
packages/react-composites/src/composites/CallComposite/components/buttons/Camera.tsx
packages/react-composites/src/composites/CallComposite/components/buttons/Microphone.tsx

The feature was stabilized in the `1.2.0` release.
This PR removes the feature flags and cleans up any logic that existed specifically to support this feature flag.

Remove stabilized feature flag `control-bar-split-buttons`

---

packages/react-composites/tests/browser/chat/ErrorBar.test.ts

Noticed an unsafe use of `page.click` while working on e2e tests. FIXIT.

Use pageClick so that we get screenshot on timeout

---

change/@internal-acs-ui-common-9e7f3931-cbb8-46ad-9201-f6a886eb27ae.json
common/scripts/babel-conditional-preprocess.js
packages/acs-ui-common/src/conditional-compilation-sample/index.tsx

Add support for function type in conditional compilation
From:
To:

Add support for function type in conditional compilation

---

change/@internal-react-composites-3aa92495-9ca8-4039-bd8d-43e019864bd6.json
common/config/api-extractor/api-extractor.json
packages/communication-react/review/communication-react.api.md
packages/react-composites/review/react-composites.api.md

Disable ae-incompatible-tags warning in beta
In beta builds, ae-incompatible-tags warning creates friction since it is possible to have unmatching tags in beta build but we take care of those in stable builds by conditionally removing them.

Disable ae-incompatible-tags warning in beta

---

.github/workflows/alpha-release.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/create-beta-release-branch.yml
.github/workflows/create-prerelease-branch.yml
.github/workflows/create-release-branch.yml
.github/workflows/create-stable-release-branch.yml
.github/workflows/deploy-azure-webapps.yml
.github/workflows/deploy-release-azure-webapps.yml
.github/workflows/deploy-storybook.yml
.github/workflows/nightly-cd.yml
.github/workflows/npm-release-publish.yml
.github/workflows/publish-chromatic.yml
.github/workflows/run-td-build.yml
.github/workflows/stress-test-ui-tests.yml
.github/workflows/update-api-files.yml
.github/workflows/update-snapshot.yml

Cancel previous CI runs when newer changes are pushed in a PR.
https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre/67939898#67939898
Code snippet being added:
```
concurrency: 
group: ${{ github.workflow }}-${{ github.ref }}
cancel-in-progress: true
```
This creates a "concurrency grouping" with `cancel-in-progress: true` where if another action is triggered in that concurrency group, it will cancel any in progress ones.
To ensure the correct action is cancelled, it creates a group name using:
* `github.workflow` id to ensure it only cancels runs of the same github action
* `github.ref` to ensure only runs targeting the same branch/PR are cancelled.
Put those together and we cancel runs of the same action on the same …

Cancel previous CI runs when newer changes are pushed in a PR

---

change/@internal-react-composites-b9a6780a-3131-4e9f-b1f2-671b9db680b5.json
packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
packages/react-composites/src/composites/CallWithChatComposite/CallWithChatPane.tsx

Bugfix that prevents CallWithChat Composite from reloading whenever Chat/Participant pane is toggled.
Should greatly improve perf on mobile devices since it doesn't recreate the entire call arrangement when side pane is toggled
Fixes the following bug
https://skype.visualstudio.com/SPOOL/_workitems/edit/2835161
Improves performance of callwithchat
Manually

Prevent CallWithChat reload when toggling side panes

---

change/@internal-react-components-b27b5494-8f72-4392-b9b2-532acb5bb66b.json
packages/react-components/src/components/VideoGallery/useVideoStreamLifecycleMaintainer.ts

Revert directly calling updateScalingMode in the VideoGallery VideoTiles
Causing a bad rendering bug where the remote stream is recreated on first render. Supporting both view.updateScalingMode  and recreation of the tile if view.updateScalingMode does not exist is proving very complex, see abandoned #1955 .
Yes! Either soon if I can carve out more time to implement the complex situation of handling both above scenarios, or when we do a breaking change in this lib.
However this revert is necessary for to unblock beta package check in (#1925) as it will fix the flaky rendering issue.
Locally - remote participants render correctly, also screenshare streams, and changing scaling mode.

Revert directly calling updateScalingMode in the VideoGallery VideoTiles

---

change/@internal-acs-ui-common-e865738b-2097-4c41-9a5d-c7c5138c826a.json
common/scripts/babel-conditional-preprocess.js
packages/acs-ui-common/src/conditional-compilation-sample/index.tsx
packages/acs-ui-common/src/conditional-compilation-sample/utils.tsx

`GetSelector` needs it.
Added examples to live documentation.

Support ternary type definitions in conditional compilation

---

packages/react-composites/tests/browser/call/CallComposite.test.ts
packages/react-composites/tests/browser/call/ErrorBar.test.ts
packages/react-composites/tests/browser/call/HorizontalGallery.test.ts
packages/react-composites/tests/browser/call/PageState.test.ts
packages/react-composites/tests/browser/call/Screenshare.test.ts
packages/react-composites/tests/browser/callwithchat/CallWithChatComposite.test.ts
packages/react-composites/tests/browser/common/utils.ts

Using the new `stableSnapshot` util function to ensure tooltips are not showing before snapshots are taken in calling UI tests.
Our PR's are failing miserably on UI tests :(
Testing against CI

Fix flaky tooltips in calling UI tests

---

change/@internal-react-components-7891fe1d-c0a9-4de7-986a-815fe42fa3e1.json
packages/react-components/src/components/MessageThread.tsx

Ensure New Messages button is tab navigated to before the chat body
New Messages floats on top of the chat body (so is in a higher zindex) and thus should be tabbed to before the chat body
tested in callwithchat and tab behavior has updated: now goes chat pane header -> new messages -> message body

Fix tab ordering of the new messages button in chat composite

---

.github/workflows/ci.yml
.github/workflows/update-snapshot.yml

Disable the beta CI matrix and beta update snapshots
cherry picks will only run against the stable CI flavor

disable beta ci

---

samples/Chat/README.md

There is a typo on readme, should be cd samples/Chat not cd samples\Chat
https://github.com/Azure/communication-ui-library/issues/2020

Update read me cd samples\Chat to cd samples/Chat

---

change/@internal-react-components-2fe1fb24-49b7-43c5-99fd-a48c0348cf53.json
packages/react-components/src/components/styles/MessageThread.styles.ts

Changed z-index so new message button shows on top of chat bubble
https://skype.visualstudio.com/SPOOL/_workitems/edit/2915516

Changed z-index so new message button shows on top of chat bubble

---

packages/react-composites/src/composites/CallComposite/CallComposite.tsx
packages/react-composites/src/composites/CallComposite/styles/CallPage.styles.ts

Added UI changes to reflect role on the call screen

Added UI changes to reflect role on the call screen

---

packages/storybook/.storybook/preview.tsx
packages/storybook/stories/INTERNAL/PictureInPictureInPicture/PictureInPictureInPicture.stories.tsx

Hid PictureInPictureInPicture story page for release. 
Filed this bug to fix this issue: https://skype.visualstudio.com/SPOOL/_workitems/edit/2918197
To ensure the storybook publish for release does not timeout
Locally

Hide PictureInPictureInPicture story page for release

---

change/@internal-react-components-e8878b2e-95c0-441d-a922-4e347a14f81b.json
packages/react-components/src/components/DevicesButton.tsx

Fixed bug where voice over is not announcing menu item checked 
https://skype.visualstudio.com/SPOOL/_workitems/edit/2908125
est your change.

Fixed bug where voice over is not announcing menu item checked 

---

change/@internal-react-composites-ad65e724-4108-421e-845e-9a87741e4196.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
packages/react-composites/package.json
samples/CallWithChat/package.json
samples/Calling/package.json
samples/Chat/package.json
samples/ComponentExamples/package.json
samples/Server/package.json
samples/StaticHtmlComposites/package.json
tools/check-treeshaking/package.json

Update webpack-cli to `4.10.x`
Error running samples:
Likely after we updated our pnpm lock file in https://github.com/Azure/communication-ui-library/pull/2090
More details on fix: https://stackoverflow.com/a/72693567/3047190
Can run Calling sample locally again now

Update webpack-cli version to fix sample rushx start error

---

change/@internal-react-composites-5fa1435e-62af-451a-89b4-7ae6ed70f2a9.json
packages/react-composites/src/composites/CallComposite/CallComposite.tsx
packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx
packages/react-composites/src/composites/CallComposite/pages/LobbyPage.tsx

Move LayerHost for ModalLocalAndRemotePIP outside of CallArrangement into CallComposite file
Boundaries properly set 
https://user-images.githubusercontent.com/97130533/181358663-73aef1ce-3b27-4d06-86dd-edb785091f26.mov
Resolve boundary issue with pip when in mobile view with people pane open. 
LayerHost needs to be rendered before useMinMaxDragPosition in common/utils is called. 
Cannot be in CallArrangement as previously done as CallArrangement is rendered when callStatus is connected, causing useRef reference to the ModalLayerHost to be initialized as null.
Clipping and boundaries not properly set
https://user-images.githubusercontent.com/97130533/181358591-c6cbf8d0-f824-494d-985c-d43ce2506467.mov
Test locally on MacOS on Chrome mobile view.

Resolve ModalPip boundary issue in callpane in Call Composite

---

.github/workflows/ci.yml
.github/workflows/stress-test-ui-tests.yml
.github/workflows/update-snapshot.yml
samples/tests/package.json

The browser tests use dependencies of `@internal/react-composites`  in the *test code*. Before this PR, the CI actions did not build these dependencies. When a [recent PR](https://github.com/Azure/communication-ui-library/pull/2076) introduced an import that needed to import from `@internal/acs-ui-common`, the tests started failing at runtime because of missing dependencies.
FixIt.

CI: Build packlets used by browser tests

---

.github/workflows/ci.yml
change/@internal-react-composites-68759da2-c6eb-4a8d-a970-b8e68e51c912.json
packages/react-composites/playwright.config.common.ts
packages/react-composites/scripts/runBrowserTests.mjs

Starting with https://github.com/Azure/communication-ui-library/pull/2072, browser tests involve multiple invocations of playwright. Before this PR, the multiple invocations end up overwriting the output directory from previous invocations.
* Use a new output directory for each invocation. This PR simply adds a sub-directory with the current Unix timestamp for each invocation.
* Update workflow to upload all playwright test stats from all the invocations.
* Add a new flag `runBrowserTests.mjs -x` to skip further invocations on failure (builds atop `playwright -x`)
* Missing snapshots from some test failures in CI.
* Missing per-test metrics for analysis.
Does *not* affect the results of CI runs.
https://github.com/prprabhu-ms/acr-e2e-analysis/commit/dd0b0e0b0e3265dab170e8eef0051c021deef3b8 …

Separate out output directories for multiple playwright runs

---

packages/react-composites/src/composites/CallComposite/CallComposite.test.tsx
packages/react-composites/src/composites/CallComposite/CallComposite.tsx
packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
packages/react-composites/tests/browser/call/TestCallingState.ts
packages/react-composites/tests/browser/call/app/mocks/MockCallAdapter.ts
packages/storybook/stories/CallComposite/snippets/Container.snippet.tsx
samples/Calling/src/app/App.tsx
samples/Calling/src/app/utils/AppUtils.ts

If role is Consumer, then only request for audio permissions. 
- Need to do access audio devices to show speaker options in dropdown. 
- Also we disable the 'Start Call' button in the configuration page if microphonePermissionGranted is false.
Request for audio and video permissions for other roles or no role at all.
Let me know if there are changes needed.
https://skype.visualstudio.com/SPOOL/_workitems/edit/2919171
https://skype.visualstudio.com/SPOOL/_workitems/edit/2919172
Tested on local rooms sample:
https://user-images.githubusercontent.com/79475487/179336360-790989e5-52b0-4dd6-8c63-68a690aa8088.mp4
Note: There is a ComplianceBanner showing camera device permissions are not granted for the Consumer role. This probably is confusing for the user. Let me know if I should remove this …

Ask device permissions based on role

---

common/scripts/poll-npm-package-published.mjs

* Update npm script to wait for 5 minutes instead of 12 seconds (which was just for testing and not meant to be committed to code)
* Added `await main()` to ensure the exit code is propagated and ensure the github action actually fails
Currently, despite not finding the package, the action still passed:
https://github.com/Azure/communication-ui-library/runs/7700649145?check_suite_focus=true
Will be tested in nightly CD

Fix poll script timing and exit code

---

common/scripts/babel-conditional-preprocess.js
common/scripts/force-build-flavor.mjs
common/scripts/lib/constants.mjs
common/scripts/lib/exec.mjs
common/scripts/lib/getBuildFlavor.mjs
common/scripts/lib/index.mjs
common/scripts/poll-npm-package-published.mjs
common/scripts/workflow-read-matrix.mjs

`1.3.1` is a hotfix release off of the `1.3.0` tag.
The release workflows all run off of `main` (old workflows have missing features / don't match current processes for release etc.) but the `1.3.0` tag is missing some scripts needed by the workflows.
This PR backports those scripts so that the workflows can be used to manage the release.

Backport scripts needed by latest workflows

---

change/@internal-react-components-269980ac-ec3f-4f91-a760-7ffcfd8551e3.json
packages/react-components/src/components/RemoteVideoTile.tsx
packages/react-components/src/components/VideoGallery/RemoteScreenShare.tsx

Fix infinite spinner bug during screenshare (#2191)
Co-authored-by: Nan Jiang <jinan@microsoft.com>

Fix infinite spinner bug during screenshare (#2191)

---

samples/CallWithChat/src/app/views/HomeScreen.tsx
samples/Calling/src/app/views/HomeScreen.tsx

Dialpad delete button was missing in homescreen, now it's visible 
https://skype.visualstudio.com/SPOOL/_workitems/edit/2960136
Open calling and callwithchat sample, selete PSTN, type in dialpad and see if delete button pops up

register icons so they show in sample homescreen

---

.github/workflows/ci.yml
change/@internal-fake-backends-b249fcd5-81f6-4250-8523-ecafe7beeee7.json
change/@internal-react-composites-4fb23d44-d5ff-40e8-8151-659e1a3a6541.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
packages/fake-backends/.babelrc.js
packages/fake-backends/api-extractor.json
packages/fake-backends/api-extractor.stable.json
packages/fake-backends/package.json
packages/fake-backends/rollup.config.js
packages/fake-backends/src/index.ts
packages/fake-backends/tsconfig.preprocess.json
packages/react-composites/package.json
packages/react-composites/tests/browser/call/app/mocks/MockCallAdapter.ts
packages/react-composites/tests/browser/call/hermetic/ConfigurationPage.test.ts
packages/react-composites/tests/browser/chat/app/CustomDataModel.tsx
packages/react-composites/tests/browser/chat/app/FakeAdapterApp.tsx
packages/react-composites/tests/browser/chat/app/FakeChatAdapterArgs.ts
packages/react-composites/tests/browser/chat/app/LiveTestApp.tsx
packages/react-composites/tests/browser/common/utils.ts
packages/react-composites/tests/tsconfig.json

* Fix typo in `packages/react-composites/tests/tsconfig.json` that resulted in the test code never getting type checked.
* Fix uncovered type errors
In particular, fix the problems caused by `@internal/fake-backends` packlet not being setup properly:
* Drop source maps in `react-composites/tests/tsconfig.json` -- source maps don't work with stable flavor builds (the only other `tsconfig.json` that has source maps is `storybook`, but that is never built in stable flavor)
* Fix the build setup of `@internal/fake-backends` so that it correctly generates the rolled up types file for both beta and stable flavor builds.

Actually typecheck browser test code

---

change/@internal-react-composites-9386fdf7-ecb9-41bf-aa8f-577124303c52.json
packages/react-composites/src/composites/common/CallingDialpad.styles.ts
packages/react-composites/src/composites/common/SendDtmfDialpad.styles.ts

Moves Ellipsis to left side of dialpad overflow
makes sure end user can see the last numbers they were typing
https://skype.visualstudio.com/SPOOL/_workitems/edit/2958039
Ran locally

Dialpad overflow ellipsis fix

---

change/@internal-react-components-8a640ab7-f76f-4826-ae80-f26044d265d6.json
change/@internal-storybook-625d5539-f0cc-4445-bc18-900dd7f4939a.json
packages/communication-react/review/beta/communication-react.api.md
packages/react-components/review/beta/react-components.api.md
packages/react-components/review/stable/react-components.api.md
packages/react-components/src/components/Dialpad/Dialpad.tsx
packages/storybook/stories/Dialpad/Dialpad.stories.tsx
packages/storybook/stories/Dialpad/snippets/CustomDialpad.snippet.tsx

removed ondisplaydialpadinput, add textFieldValue for contoso to directly set the value inside textfield
Change made according to internal review recommendations 
storybook example showing how to use those 2 props to customized textfield format

Allow contoso to directly set the value inside textfield 

---

change/@internal-react-composites-03770501-1787-429f-97a6-03dec1bf9d48.json
packages/react-composites/src/composites/common/CallingDialpad.styles.ts
packages/react-composites/src/composites/common/SendDtmfDialpad.styles.ts

Fixed input order bug on calling dialpad and dtmf dialpad
before: 
https://user-images.githubusercontent.com/96077406/187010118-5f6521bf-63ac-4e84-9753-fac1cf92cbde.mov
after: 
https://user-images.githubusercontent.com/96077406/187010113-9d664fc8-cc95-41af-9bbb-273b9947bfdc.mov

Fixed input order bug on calling dialpad and dtmf dialpad

---

.github/workflows/update-snapshots.yml

Fix a typo in parts of a new GitHub action. These parts are hard to test before merging to `main` :(

Fix typo in GitHub action to update snapshots

---

samples/Chat/src/app/DisplayNameField.tsx

Add required attribute to DisplayNameField on chat configuration page.
Results in asterisk and voiceover "required" announcement for the field.
Required fields should be announced and labeled with an asterisk.
https://skype.visualstudio.com/SPOOL/_workitems/edit/2908415
MacOS chrome browser

[A11y][bugfix] Add "required" attribute to chat sample DisplayNameField in configuration page

---

common/config/beachball/changelog-config.ts
package.json

* Change the beachball config to use the default repo origin specified in a root package json
* Add a root level package.json that specifies this repo as the root repo to use
`rush changelog` is not working for forks of the repo (as origin/main on a fork of the repo is the forked repo and not this repo, we need rush changelog to check new changes against _this_ repo)
More information: https://github.com/Azure/communication-ui-library/pull/2285#issuecomment-1258756974
* Upon pulling the branch first verified running without this change rush changelog did not work, then manually applying this change it now works.
* Locally a branch on this repo still detects changes

Fix rush changelog not working for forks of the repo

---

change/@internal-react-composites-825c806c-7788-4a9c-be79-e02c2c17464f.json
packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
packages/react-composites/src/composites/CallComposite/pages/ConfigurationPage.tsx

Suppress camera access error bar error for consumer.
The errorBarSelector pushes the error message with type 'callCameraAccessDenied' when the DeviceManagerState property deviceAccess.video is false. It is NOT from Calling SDK UFD
https://skype.visualstudio.com/SPOOL/_workitems/edit/3015756
https://user-images.githubusercontent.com/79475487/195479583-c808c065-a7e4-4be1-b5f6-3a7f9ccd8aa2.mp4

Suppress camera access error bar error for consumer

---

change/@internal-react-composites-7452c589-eca7-482e-b144-0572503ede0e.json
packages/communication-react/review/beta/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/src/composites/CallComposite/Strings.tsx
packages/react-composites/src/composites/CallComposite/components/LobbyTile.tsx
packages/react-composites/src/composites/CallComposite/pages/LobbyPage.tsx
packages/react-composites/src/composites/localization/locales/en-US/strings.json

PSTN
ACS
Communicates to the end user who they are calling in the Call composite lobby screen
https://skype.visualstudio.com/SPOOL/_workitems/edit/2968937
Ran locally with PSTN and ACS call

[PSTN 1-N calling] Update lobby page with new strings

---

change/@internal-react-composites-5c5b138d-56e9-4522-8fd5-640b55398642.json
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts

Bugfix for Config screen flashing for 2 seconds after leaving a call
This bug happens because we set the callId to undefined in the adapter inside the leaveCall function.
However, call client state takes a while to add that call to endedCalls array and remove it from the active call.
Hence, we need to only set call id to undefined once that operation has completed.
Manually

Bugfix for Config screen flashing for 2 seconds after leaving a call

---

common/config/rush/pnpm-lock.yaml

`1.4.0` is a stable release, but the GitHub workflows are failing in an early step where then need to install beta build's dependencies.
Fix it first while I try to figure out how we got into this state.

Regenerate the PNPM shrinkwrap files for beta flavor

---

change/@internal-react-components-d1226ee2-d5ac-43b5-bd50-021d08c81673.json
change/@internal-react-composites-93739eae-6467-4523-af0e-4afbe6d8c5c9.json
change/@internal-storybook-129a9fcb-bbc7-4af3-a5bf-d762a10c02d0.json
packages/react-components/review/beta/react-components.api.md
packages/react-components/review/stable/react-components.api.md
packages/react-components/src/components/TroubleshootingGuideErrorBar.tsx
packages/react-composites/src/composites/CallComposite/CallComposite.tsx
packages/react-composites/src/composites/CallComposite/components/ConfigurationpageErrorBar.tsx
packages/react-composites/src/composites/CallComposite/pages/ConfigurationPage.tsx
packages/storybook/stories/INTERNAL/CallReadiness/TroubleshootingGuideErrorBar/TroubleshootingGuideErrorBar.stories.tsx
samples/Calling/src/app/views/CallScreen.tsx

Add troubleshooting guide error bar to call composite config screen 
call readiness work

Add troubleshooting guide error bar to call composite config screen 

---

change/@internal-calling-stateful-client-feff7329-c8ce-4585-83f1-f9817a635084.json
packages/calling-stateful-client/review/stable/calling-stateful-client.api.md
packages/calling-stateful-client/src/StatefulCallClient.ts
packages/communication-react/review/stable/communication-react.api.md

This is new API needed for a beta-only feature. Let's remove it from stable builds for now.

Remove DeclarativeCallAgent from stable API

---

change/@internal-react-components-e29d9f96-5622-4039-9a8e-bfceb9a045f2.json
packages/react-components/src/components/VideoTile.tsx
packages/react-components/src/components/styles/VideoTile.styles.ts

Cherry Pick mute indicator bug fix into stable 1.4.0
Original PR https://github.com/Azure/communication-ui-library/pull/2451

Cherry Pick mute indicator bug fix into stable 1.4.0

---

packages/calling-component-bindings/src/handlers/createHandlers.ts

Hotfix for regression caused by #2412 (more details: https://skype.visualstudio.com/SPOOL/_workitems/edit/3030558). See code comment for details.
Joined acs call with:
* Camera on, then toggled off and on on call page
* Camera off, then toggled on and off on call page
* Camera off, then camera turned on in connecting screen, then toggled off and on on call page
* Camera on, then camera turned off in connecting screen, then toggled on and off on call page
* Switching camera source during the connecting screen
* Turning on camera in connecting screen, but ensuring call had connected before the camera had finished turning on (scenario of #2412 )
Teams interop testing:
* Camera on, then toggled off and on on call page
* Camera off, then toggled on and off on call page
* Camera off, then …

Stable release branch hotfix: Fix camera turning back on when turned off on connecting screen

---

packages/calling-component-bindings/package.json
packages/calling-stateful-client/package.json
packages/chat-component-bindings/package.json
packages/chat-stateful-client/package.json
packages/communication-react/package.json
packages/fake-backends/package.json
packages/react-composites/package.json
packages/storybook/package.json
samples/CallWithChat/package.json
samples/Calling/package.json
samples/Chat/package.json
samples/ComponentExamples/package.json
samples/Server/package.json
samples/StaticHtmlComposites/package.json
samples/tests/package.json

This is conceptually a cherry pick of #2457.
The PR can't be cherry-picked directly because only the stable package dependencies are chosen on this release branch.

[release] Allow a range of @azure/communication-calling and @azure/communication-chat versions as peerDependency

---

change/@internal-react-composites-4588bf72-bbfd-44d0-bd37-38ce8574b55e.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/review/stable/react-composites.api.md
packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts

Realized while working on a stable release that we had inadvertently introduced a breaking API change. Revert that change.

Revert breaking API change in `CallEndedListener` callback

---

change/@internal-react-composites-fcfc34c7-0f03-4336-9e24-518abb812687.json
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts

Increase max event listener limit for call and callwithchat composite
This removes the max event listener warnings for our composites 
load the sample, check if still see warnings in console
load storybook and check if still see warnings in console

Increase max event listener limit for call and callwithchat samples

---

change/@internal-react-composites-89afdbf7-dd01-4781-86a4-1b1a376fe1be.json
packages/react-composites/src/composites/CallComposite/pages/ConfigurationPage.tsx
packages/react-composites/src/composites/CallComposite/utils/Utils.ts

Add permission API to config screen
Use permission API to get device permissions
Go to samples, enable call readiness, click on permission trouble shooting link, check console and see if correct permission state is logged out 
If permission api is not supported ,both audio state and video state will remain as undefined, and in this case we fall back to using calling's SDK to determine if permission is denied/ granted

Add permission API to config screen

---

.github/workflows/alpha-release.yml
.github/workflows/ci.yml
.github/workflows/create-prerelease-branch.yml
.github/workflows/create-release-branch.yml
.github/workflows/nightly-cd.yml
.github/workflows/npm-release-publish.yml
.github/workflows/publish-chromatic.yml
.github/workflows/update-api-files.yml
.github/workflows/update-snapshots.yml

Update to use the newer github action syntax for setting output variables of jobs
GitHub is deprecating the old syntax on May 31st 2023: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
CI will verify the ci.yml, nightly alpha will do further useful tests. And hopefully given its the name change to all everything will auto work if they both pass.

Update to newer syntax for github actions job outputs

---

change/@internal-storybook-a6d95240-9957-4057-a6ce-6d2a50b18088.json
packages/storybook/stories/CallComposite/snippets/Quickstart1ToN.snippet.tsx
packages/storybook/stories/CallComposite/snippets/QuickstartPSTN.snippet.tsx

After this PR, the quickstart applications show icons correctly out of the box.

`initializeIcons()` in PSTN and 1:N quickstarts

---

change/@internal-react-composites-6ab13215-de2b-44fb-8e89-a21bd5e62667.json
packages/react-composites/src/composites/CallComposite/utils/Utils.ts
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts

There are 3 warnings popping up after doing a `rush update` and it seems because of lib.dom update, which changes some type definition, this PR is to do the right type cast for bypass warnings
Check this build for those 3 warnings: https://github.com/Azure/communication-ui-library/actions/runs/3434222284/jobs/5725340021

Add type cast to support latest lib.dom version

---

change-beta/@azure-communication-react-d695a8c5-053e-460b-981d-869bb36383bb.json
change/@azure-communication-react-d695a8c5-053e-460b-981d-869bb36383bb.json
packages/communication-react/CHANGELOG.beta.md

Update Changelog for bumping Calling sdk to 1.9.1-beta.1 

Release/1.4.1 beta.1 update cherrypick changelog for bumping Calling SDK

---

change-beta/@azure-communication-react-aed327b7-449f-4d86-8730-ba8e16d8d2a1.json
change/@azure-communication-react-aed327b7-449f-4d86-8730-ba8e16d8d2a1.json
packages/storybook/stories/BetaBanners/DetailedBetaBanner.tsx
packages/storybook/stories/BetaBanners/SingleLineBetaBanner.tsx
packages/storybook/stories/CallComposite/CallCompositeDocs.tsx
packages/storybook/stories/CallComposite/Quickstart1ToNDocs.stories.mdx
packages/storybook/stories/CallComposite/QuickstartPSTNDocs.stories.mdx
packages/storybook/stories/Dialpad/Dialpad.stories.tsx
packages/storybook/stories/Rooms.stories.mdx

Add beta banner version options for storybook.
Customers need clarity on which @azure/communication-react version public preview features are available in.
https://github.com/Azure/communication-ui-library/issues/2521
Locally ran storybook

Add beta version option for beta banners in Storybook

---

change-beta/@azure-communication-react-aed327b7-449f-4d86-8730-ba8e16d8d2a1.json
change/@azure-communication-react-aed327b7-449f-4d86-8730-ba8e16d8d2a1.json
packages/storybook/stories/BetaBanners/DetailedBetaBanner.tsx
packages/storybook/stories/BetaBanners/SingleLineBetaBanner.tsx
packages/storybook/stories/CallComposite/CallCompositeDocs.tsx
packages/storybook/stories/CallComposite/Quickstart1ToNDocs.stories.mdx
packages/storybook/stories/CallComposite/QuickstartPSTNDocs.stories.mdx
packages/storybook/stories/Dialpad/Dialpad.stories.tsx
packages/storybook/stories/Rooms.stories.mdx

Add beta version option for beta banners in Storybook
Customers need clarity on which @azure/communication-react version public preview features are available in.
https://github.com/Azure/communication-ui-library/issues/2521

[1.4.1-beta.1][cherrypick]Add beta version option for beta banners in Storybook (#2544)

---

change-beta/@azure-communication-react-a027e775-198b-494f-b12e-924fe099880b.json
change/@azure-communication-react-a027e775-198b-494f-b12e-924fe099880b.json
change/@internal-react-components-072cc54d-a247-459c-b8a8-8101ff98f2e2.json
change/@internal-storybook-f359b390-2a8f-472c-9495-a2bcf93f3068.json
common/config/rush/pnpm-lock.yaml
packages/communication-react/package.json
packages/react-components/package.json
packages/storybook/.storybook/main.js
packages/storybook/package.json
packages/storybook/stories/Setup.stories.mdx
packages/storybook/stories/Troubleshooting.stories.mdx
tools/check-treeshaking/package.json

Revert webpack 5 change.
No features/functionality is impacted with this revert int his beta release 1.4.1-beta.1
Tested locally. Rebuilt and ran through codespace.

Revert "Require webpack 5 in our lib... (#2428)" from release/1.4.1-beta.1

---

change-beta/@azure-communication-react-71abe466-ebd2-4420-b2ea-8f7a9a5a1ee2.json
change/@azure-communication-react-71abe466-ebd2-4420-b2ea-8f7a9a5a1ee2.json
packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
packages/communication-react/review/beta/communication-react.api.md
packages/react-components/review/beta/react-components.api.md
packages/react-components/src/types/VideoGalleryParticipant.ts

Add scalingMode to videoGallerySelector
This is required to detect the current scaling mode of a remote participant and change the menu item from "Fit" to "Fill" and vice versa in Video Tile contextual menu

Add scalingMode to videoGallerySelector

---

change-beta/@azure-communication-react-d74c9c67-8c1e-4d3c-a629-38ddfa99a3fb.json
change/@azure-communication-react-d74c9c67-8c1e-4d3c-a629-38ddfa99a3fb.json
packages/react-composites/src/composites/CallComposite/components/CallReadinessModal.tsx
packages/react-composites/src/composites/CallComposite/pages/ConfigurationPage.tsx

Device denied screen should show on safari when don't allow is clicked 
When don't allow is clicked on safari, permissionsAPI returns prompt instead of denied (that is because inside safari settings it's still set to ask when don't allow is clicked.) Calling SDK returns false in this case
So we add an extra layer of checking to make sure we always show the denied screen when calling sdk returns false. 
https://user-images.githubusercontent.com/96077406/207913061-04132871-dabb-4ffc-a9ba-1ce46785b40d.mov

Device denied screen should show on safari when don't allow is clicked 

---

change-beta/@azure-communication-react-adc390fc-919f-499c-a08e-e2d69c702a3b.json
change/@azure-communication-react-adc390fc-919f-499c-a08e-e2d69c702a3b.json
packages/communication-react/review/beta/communication-react.api.md
packages/react-components/review/beta/react-components.api.md
packages/react-components/src/components/DevicePermissions/DomainPermissions.tsx
packages/react-composites/src/composites/CallComposite/components/CallReadinessModal.tsx

Change is Safari prop to browserHint to allow more customization
In this way if we want to display some specific text for firefox we don't need to add a new prop
Made sure safari is showing the right text
Chrome and firefox is showing the right text

Change is Safari prop to browserHint to allow more customization

---

change-beta/@azure-communication-react-bfa2f596-77a0-40fd-82ce-dd9beae0b2e2.json
change/@azure-communication-react-bfa2f596-77a0-40fd-82ce-dd9beae0b2e2.json
packages/storybook/stories/CallWithChatComposite/CallWithChatCompositeDocs.tsx
packages/storybook/stories/ChatComposite/ChatCompositeDocs.tsx
samples/CallWithChat/src/app/views/CallScreen.tsx
samples/Chat/src/app/ChatScreen.tsx

Disable pull-down to refresh on samples and document best practice in storybook on how to handle accidental pull down to refresh triggers on mobile
On IOS Safari Chat and CallWithChat scrolling on chat page can sometimes cause the whole page view to refresh/scroll.
This can cause accidental page refresh.
https://skype.visualstudio.com/SPOOL/_workitems/edit/3069029
Tested on iPhone SE on CallWIthChat and Chat sample.

[bugfix] Update storybook and samples to disable mobile feature "pull-down to refresh"

---

change-beta/@azure-communication-react-36ec4564-2251-434f-b7be-e7ce7be9828d.json
change/@azure-communication-react-36ec4564-2251-434f-b7be-e7ce7be9828d.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
packages/fake-backends/package.json
packages/react-components/package.json
packages/react-composites/package.json
packages/storybook/package.json
samples/CallWithChat/package.json
samples/Calling/package.json
samples/Chat/package.json
samples/ComponentExamples/package.json
samples/Server/package.json
samples/StaticHtmlComposites/package.json
tools/check-treeshaking/package.json

Update the webpack version from 5.38.1 -> 5.61.0
this fixes the classic 'unsupported digital envelopes' error caused when updating with a node version > 16
https://skype.visualstudio.com/SPOOL/_workitems/edit/3024365
built and deployed the calling hero app using node 18.3.0

[bugfix] Fix the "classic" unsupported digital envelopes error.

---

change-beta/@azure-communication-react-cbefab17-73bb-4853-9e8f-9d7a6cc4ab87.json
change/@azure-communication-react-cbefab17-73bb-4853-9e8f-9d7a6cc4ab87.json
packages/react-components/src/components/VideoTile.tsx
samples/Calling/src/app/App.tsx

Remove use of `<Ref>` tag from fluent nothstar
fixes findDOMNode warning caused by strict mode in the video tile. Under the hood the `<Ref>` tag probably uses `findDOMNode()`. According to react's documentation about the function it should not be used with React.FunctionalComponents. `<Ref>` is a React.FunctionalComponent according the the api file provided by fluent-northstar.
https://skype.visualstudio.com/SPOOL/_workitems/edit/3090254
Ran app locally with new reference structure to make sure the video gallery still works

[Bugfix] Fix video tile strict mode findDOMNode warning

---

change-beta/@azure-communication-react-f4c0356d-b472-4b5b-92fc-4963a7121bf9.json
change/@azure-communication-react-f4c0356d-b472-4b5b-92fc-4963a7121bf9.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml

json5 vulnerability detected by dependabot alert.
vulnerability was patched and backported to json5 versions 1 that are >= 1.0.2 and versions >= 2.2.2. 
rush update pnpm-lock files to use 1.0.2 json5 versions. 
https://github.com/Azure/communication-ui-library/security/dependabot/77

Update dependency to resolve json5 dependabot alert

---

change-beta/@azure-communication-react-2bb97c65-cf5e-4b4d-be84-293770c51d61.json
change/@azure-communication-react-2bb97c65-cf5e-4b4d-be84-293770c51d61.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
common/scripts/force-build-flavor.mjs
common/scripts/package-utils.js
packages/communication-react/package.json
packages/react-composites/package.json

* Add `@azure/communication-calling-effects` package to beta releases only
* Added as a **peer dep**
* Update `force-build-versions` script to _remove_ beta-only packages
Needed for background effects feature
Verified when running `force-build-versions` script does indeed remove the calling-effects package:

Add `@azure/communication-calling-effects` package

---

.github/workflows/ci.yml
change-beta/@azure-communication-react-9715359a-9ad3-42e2-b63f-b145d60cf9a1.json
change/@azure-communication-react-9715359a-9ad3-42e2-b63f-b145d60cf9a1.json

* Run `force-build-versions` in CI at all times when switching to stable
* Run `rush update:stable` to ensure the new version definitions are picked up
`force-build-versions` ensures the crafted package.json only has the required versions.
This is only run on creating a release branch, we should be running it on all CI.
Related, this ensures the remove of #2689 from stable builds will be tested at CI time.
CI runs
Also ran these commands locally
```sh
rush install
node ./common/scripts/force-build-flavor.mjs stable
rush switch-flavor:stable
```
And confirmed `@azure/communication-calling-effects` was removed in the node_modules:

Run `force-build-versions` in CI at all times when switching to stable

---

GROOMME.md
change-beta/@azure-communication-react-ab927468-a366-4193-a41d-c668b780b10b.json
change-beta/@azure-communication-react-cebf8018-dd7a-415e-b1d1-130b8ac927d7.json
change/@azure-communication-react-ab927468-a366-4193-a41d-c668b780b10b.json
change/@azure-communication-react-cebf8018-dd7a-415e-b1d1-130b8ac927d7.json
packages/communication-react/review/beta/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
packages/react-composites/src/composites/CallComposite/adapter/OnFetchProfileCallback.ts
packages/react-composites/src/composites/CallComposite/adapter/index.ts
packages/react-composites/src/composites/CallComposite/index.ts
packages/react-composites/src/composites/CallComposite/utils/Utils.ts

Cherry pick from #2680
* Add onFetchProfile to teams adapter
---------
Co-authored-by: Nan Jiang <jinan@microsoft.com>

Add onFetchProfile to teams adapter option (#2680)

---

change-beta/@azure-communication-react-6a375515-cc06-4886-b1c8-b13fd2933b74.json
change/@azure-communication-react-6a375515-cc06-4886-b1c8-b13fd2933b74.json
packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
packages/calling-stateful-client/src/StreamUtils.ts

… (#2713)
* stop streamUtils from having 3 horse race
* Change files
* update comment
Update stream utils to better handle disposal of local stream.

[cherrypick] Stream utils fix for local video disposal

---

change-beta/@azure-communication-react-529cbe65-72af-44b2-9808-55e373e9fb18.json
change/@azure-communication-react-529cbe65-72af-44b2-9808-55e373e9fb18.json
packages/storybook/stories/MessageThread/MessageThread.stories.tsx
packages/storybook/stories/MessageThread/placeholdermessages.ts

Define message status for storybook message thread 
https://skype.visualstudio.com/SPOOL/_workitems/edit/3132408

Define message status for storybook message thread to make sure 'try send again' does not show up in fly out menu

---

change-beta/@azure-communication-react-77512195-cb86-4a65-8c90-1fd39cfac690.json
change/@azure-communication-react-77512195-cb86-4a65-8c90-1fd39cfac690.json
packages/acs-ui-common/src/identifier.test.ts
packages/acs-ui-common/src/identifier.ts

Update `fromFlatCommunicationIdentifier` function to handle E.164 format phone numbers as Id's
Allows for startCall handler in Adapter to parse out correct id type.
https://skype.visualstudio.com/SPOOL/_workitems/edit/3141060
Validated calls can be connected again locally. added unit test for util function that parses id

[BugFix BetaBlocking] Fix PSTN start Call

---

change-beta/@azure-communication-react-37ee124e-8580-46f7-afd6-05b566f06b18.json
change/@azure-communication-react-37ee124e-8580-46f7-afd6-05b566f06b18.json
packages/react-composites/src/composites/CallWithChatComposite/CallWithChatControlBar.tsx
packages/react-composites/src/composites/CallWithChatComposite/CustomButton.tsx
packages/react-composites/src/composites/CallWithChatComposite/components/DesktopMoreButton.tsx

* Update `DesktopMoreButton` to take in custom buttons from composite > options > custom buttons
* This was broken but shouldn't have been
Ran locally:

Fix: Add support for overflow button in desktop callwithchat

---

.github/workflows/create-prerelease-branch.yml
.github/workflows/create-release-branch.yml
change-beta/@azure-communication-react-6693b657-05ee-4c41-9330-8e4e6d0a04bd.json
change/@azure-communication-react-6693b657-05ee-4c41-9330-8e4e6d0a04bd.json
docs/releases/creating-a-release.md

* No longer create PRs during release actions.
* Update workflow to instead have some text where the PR creation was
* Update release instructions to do this manually
Due to a security issue we can no longer have github actions put up PRs:
https://aka.ms/opensource/actions-changes-230217
n/a

Update github actions to no longer create PRs

---

change-beta/@azure-communication-react-b3573c06-f7c3-42a4-a963-9a49eeb23b0c.json
change/@azure-communication-react-b3573c06-f7c3-42a4-a963-9a49eeb23b0c.json
packages/react-components/src/components/VideoGallery.tsx

Content gets selected when I pressed and hold on video tile
https://skype.visualstudio.com/SPOOL/_workitems/edit/3113208

Disable the selectivity of a text in video gallery for long touch to function properly

---

change-beta/@azure-communication-react-b53e8f77-e59f-44cc-a569-fb73e3f4c750.json
change/@azure-communication-react-b53e8f77-e59f-44cc-a569-fb73e3f4c750.json
packages/storybook/stories/CallComposite/CustomDataModelExample.stories.tsx

Wrap userId as a communicationIdentifier
Calling Custom Data Model Example failed to initialize cause userId was being passed in a string and not a proper identifier.
https://skype.visualstudio.com/SPOOL/_workitems/edit/3166070
Locally ran storybook on macOS

[bugfix][storybook] Update Calling Custom Data Model Example's userId identifier

---

change-beta/@azure-communication-react-3e9cd036-f8fa-4914-9d4d-9677bd166a14.json
change/@azure-communication-react-3e9cd036-f8fa-4914-9d4d-9677bd166a14.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-components/review/beta/react-components.api.md
packages/react-components/review/stable/react-components.api.md
packages/react-components/src/components/ChatMessage/ChatMessageComponent.tsx
packages/react-components/src/components/MessageThread.tsx

The `MessageThread` component has an `onMessageSend` property, which is documented as passing the message ID.
This is not the case, it is passed through to the underlying component and the parameter is the message body to send
Sending the message needs the body to send, the API should behave in the same way as all the other onSendMessage implementations and should behave as documented.

Correct MessageThread API definition and underlying logic

---

change-beta/@azure-communication-react-53fc64d1-9d91-4879-b51f-df54f9caf649.json
change/@azure-communication-react-53fc64d1-9d91-4879-b51f-df54f9caf649.json
packages/react-components/src/components/ResponsiveHorizontalGallery.tsx
packages/react-components/src/components/ResponsiveVerticalGallery.tsx
packages/react-components/src/components/VideoGallery.test.tsx
packages/react-components/src/components/VideoGallery/DefaultLayout.tsx
packages/react-components/src/components/VideoGallery/FloatingLocalVideoLayout.tsx
packages/react-components/src/components/VideoGallery/Layout.ts
packages/react-components/src/components/VideoGallery/utils/OverflowGalleryUtils.ts

Move children per page functions to utils to enable mocking of them in tests due to DOM constraints.
Fixes performance issues and testing issues around using a indexes array to determine which tiles in overflow gallery can be rendered.
https://skype.visualstudio.com/SPOOL/_workitems/edit/3115448
Ran tests and apps locally to see passing tests and performance results

[Vertical Gallery] Calculate children utils

---

change-beta/@azure-communication-react-ea81f159-4460-4f1a-96b4-5ce8dde4044b.json
change/@azure-communication-react-696ca73a-856e-4a9a-97e4-b6b66b3099b4.json
change/@azure-communication-react-ea81f159-4460-4f1a-96b4-5ce8dde4044b.json
packages/react-composites/src/composites/CallComposite/components/CallControls.tsx
packages/react-composites/src/composites/CallWithChatComposite/CallWithChatControlBar.tsx

Update Aria strings on people buttons in both composites to be their label
Allows windows users using voice access to open the people pane.
https://skype.visualstudio.com/SPOOL/_workitems/edit/3118291
Tested windows feature locally (Very cool!)

[A11y bugfix] Allow voice controls to action people button in Call and CallWithChat

---

change-beta/@azure-communication-react-5f766f7d-6096-4af1-8577-4685bbaac4e9.json
change/@azure-communication-react-5f766f7d-6096-4af1-8577-4685bbaac4e9.json
packages/storybook/stories/snippets/CommunicationAsTeamsUser.snippet.tsx

Memoize Teams call adapter args for CTE storybook sample code to avoid re-render of CallComposite.
To fix #2801 
In my own CRA sample

Fix CTE storybook sample code

---

change-beta/@azure-communication-react-241d9d8a-edc9-473e-8bf4-dd5b13a034f1.json
change/@azure-communication-react-241d9d8a-edc9-473e-8bf4-dd5b13a034f1.json
packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx

Prevent video gallery overflow when side pane is open in CallComposite by setting min-width to 0 as suggested by the top answer here: https://stackoverflow.com/questions/36230944/prevent-flex-items-from-overflowing-a-container
<------------- Flex container ------------->
<----Video Gallery---><---Side Pane---->
Video Gallery is wrapped in a Stack with grow property set to true which allows overflow. When the width is narrow enough the VideoGallery uses the ScrollableHorizontalGallery causing overflow to the width of the VideoGallery.
Issue seen in Calling hero sample in this post:
https://teams.microsoft.com/l/message/19:5e150d250f724d1089c949305efdc8cc@thread.skype/1679940265587?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e9c1fc3-39df-4486-a26a-456d80e80f82&parentMessageId=1679 …

Prevent video gallery overflow when side pane is open in CallComposite

---

change-beta/@azure-communication-react-7909e747-88b6-4ea5-a557-48c27fc54d84.json
change/@azure-communication-react-7909e747-88b6-4ea5-a557-48c27fc54d84.json
packages/storybook/stories/ControlBar/Buttons/Camera/Camera.stories.tsx
packages/storybook/stories/ControlBar/Buttons/ScreenShare/ScreenShare.stories.tsx

Fix import statements to be `@azure/communication-react` instead of `@azure/communication-react` 
Fixes wrong imports that might confuse contoso.
N/A found while OCE
Inspected locally

[Storybook bug] Fix import snippets for screenshare and camera buttons.

---

change-beta/@azure-communication-react-d0d9fb45-5c61-4302-bae6-b5f8c43c4f97.json
change/@azure-communication-react-d0d9fb45-5c61-4302-bae6-b5f8c43c4f97.json
packages/react-composites/src/composites/CallWithChatComposite/styles/CallWithChatCompositeStyles.ts

Fix call with chat flickering cause by CallComposite overflow when side pane is open in CallWithChatComposite by setting min-width to 0 as suggested by the top answer here: https://stackoverflow.com/questions/36230944/prevent-flex-items-from-overflowing-a-container
Similar observation seen on CallWithChat composite seen in Calling hero sample in this post:
https://teams.microsoft.com/l/message/19:5e150d250f724d1089c949305efdc8cc@thread.skype/1679940265587?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e9c1fc3-39df-4486-a26a-456d80e80f82&parentMessageId=1679940265587&teamName=Azure%20Communication%20Services&channelName=Web%20UI%20-%20Team&createdTime=1679940265587
Tested on local sample

Fix call with chat flickering

---

change-beta/@azure-communication-react-a44490ad-73fc-48b8-9ca5-47be397384fd.json
change/@azure-communication-react-a44490ad-73fc-48b8-9ca5-47be397384fd.json
packages/react-components/src/components/VideoGallery.tsx
packages/react-components/src/components/VideoGallery/FloatingLocalVideoLayout.tsx
packages/react-components/src/components/VideoGallery/styles/VideoGalleryResponsiveVerticalGallery.styles.ts

Revert PR #2822 
Reopen bug https://skype.visualstudio.com/SPOOL/_workitems/edit/3135146 after merging this
Leaving when screensharing results in blank screen and console error: https://skype.visualstudio.com/SPOOL/_workitems/edit/3207595
Tiles off center when there is no page counter: https://skype.visualstudio.com/SPOOL/_workitems/edit/3207597
Tested on local CallWithChat sample
https://user-images.githubusercontent.com/79475487/229065066-b01f9b95-b0cf-40d7-a02a-0aa24d0664c1.mp4

Fix leaving with screenshare error and off center tiles in vertical gallery

---

change-beta/@azure-communication-react-4d44c168-24d8-4c6e-891e-35e81c0b818d.json
change/@azure-communication-react-4d44c168-24d8-4c6e-891e-35e81c0b818d.json
change/@azure-communication-react-722b988d-e27c-4c5d-92fe-104c456fcf23.json
common/config/babel/.babelrc.js
packages/communication-react/CHANGELOG.beta.md
packages/communication-react/review/beta/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationFileUploadAdapter.ts

Revert this PR #2827 from beta release 1.5.1-beta.2 as discussed with @JoshuaLai and @PorterNan. The API changes from inline images will very likely have more iterations.
beta release ARB review comments have concerns with the naming so we will pull it out from the beta release
https://apiview.dev/Assemblies/Review/42fe51ace1e24184a42351ff89044352/845d376ba6994d87a3d02a3aee6a1c14?diffRevisionId=b0c9851682b3416da8d054c8993c77ea&doc=False&diffOnly=True

Revert inline images from beta release

---

change-beta/@azure-communication-react-d7d147bb-8b7d-422e-a1a7-f39a76b2682f.json
change/@azure-communication-react-d7d147bb-8b7d-422e-a1a7-f39a76b2682f.json
packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx

Remove video effects button from CallWithChat control bar in release 1.5.1 beta.2

Remove video effects button from CallWithChat in release 1.5.1 beta.2

---

packages/calling-stateful-client/src/CallContext.ts

Fix bug where non final captions are displayed as final captions 
https://skype.visualstudio.com/SPOOL/_workitems/edit/3211438
Tested with samples

Fix bug where non final captions are displayed as final captions 

---

change-beta/@azure-communication-react-7b99dd72-2469-48b3-bb48-59ccd5f14cb1.json
change/@azure-communication-react-7b99dd72-2469-48b3-bb48-59ccd5f14cb1.json
packages/react-composites/playwright.config.common.ts
packages/storybook/stories/QuickStarts/snippets/CallAppStateful.snippet.tsx
packages/storybook/stories/QuickStarts/snippets/CallAppStatefulComplete.snippet.tsx
packages/storybook/stories/QuickStarts/snippets/CallAppStatefulProviders.snippet.tsx
samples/tests/playwright.config.ts

Update user agent used in e2e tests to chrome 112.0.0.0
e2e tests are failing because they are showing 'browser out of date' warning.
This is a quick fix, a longer term solution will be worked on as well
CI Should pass once more

Unblock PR failures by updating user agent used in e2e tests

---

change-beta/@azure-communication-react-07df2784-1e1f-44a6-b409-996ac1b3f58e.json
change/@azure-communication-react-07df2784-1e1f-44a6-b409-996ac1b3f58e.json
common/config/webpack/sampleapp.webpack.config.js

Update the webpack config to copy background files to build directory in production builds
Otherwise we do not bundle the images
(Currently deploying): https://github.com/Azure/communication-ui-library/actions/runs/4682106077

Fix no sample backgrounds in production builds

---

packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts

Fix caption event - only subscribe when connected

Fix caption events subscription

---

packages/react-components/src/components/styles/Captions.style.ts

When user scroll up to read captions, sometimes the scroll bar will auto move down a little bit when new captions come in, and this is due to scroll bar auto anchoring when container size change
Added a css line to prevent auto anchoring 

Fix Bug when captions scroll bar moves down automatically when scroll back everytime new captions is received 

---

change-beta/@azure-communication-react-0ed41d98-eeea-4e2a-9fd9-3f513b6cfc3f.json
change/@azure-communication-react-0ed41d98-eeea-4e2a-9fd9-3f513b6cfc3f.json
packages/storybook/.storybook/preview.tsx
packages/storybook/stories/Examples/TeamsInterop/TeamsInteropDocs.tsx

fixed storybook ordering: 
to be aligned with file content
storybook link

[Chat][Storybook] Fixed the story ordering

---

change-beta/@azure-communication-react-0eac1278-418b-4cd6-a54d-00324f005570.json
change/@azure-communication-react-0eac1278-418b-4cd6-a54d-00324f005570.json
packages/storybook/stories/Stateful Client/UsePropsForHook.stories.mdx

`usePropsFor` snippet for Calling example in storybook should not say "ChatScreen"

Fix usePropsFor hook storybook snippet

---

change-beta/@azure-communication-react-46cbf89c-7094-4b7d-b374-951e2d5f9121.json
change/@azure-communication-react-46cbf89c-7094-4b7d-b374-951e2d5f9121.json
packages/communication-react/review/beta/communication-react.api.md
packages/react-components/review/beta/react-components.api.md
packages/react-components/src/components/ChatMessage/ChatMessageComponent.tsx
packages/react-components/src/components/ChatMessage/ChatMessageComponentAsEditBox.tsx
packages/react-components/src/components/MessageThread.tsx
packages/storybook/stories/MessageThread/snippets/Default.snippet.tsx

As per feedback from Azure Review, removing extra arguments in CancelEditCallback
New method should not expose so many arguments, we will expose them if we find a need for them 

[Chat] Remove extra arguments on CancelEditCallback

---

change-beta/@azure-communication-react-f6b4b8a1-c762-4136-8285-d8cd9166436f.json
change/@azure-communication-react-f6b4b8a1-c762-4136-8285-d8cd9166436f.json
packages/communication-react/review/beta/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/index.ts
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/index.ts
packages/storybook/stories/Adapters/Adapters.stories.mdx

Included new options bags in the factory method when creating from stateful client
Chat adapter needs the credential in the options bag to perform inline image download. 
So we need a new argument to be able to pass that downstream. 

[CallWithChat] Updating the factory method for creating callwithchatadapter from stateful clients. 

---

.github/workflows/publish-chromatic.yml
change-beta/@azure-communication-react-8336f938-69cf-4b1c-a707-0f9ae06a0d08.json
change/@azure-communication-react-8336f938-69cf-4b1c-a707-0f9ae06a0d08.json

Update fetch-depth of publish storybook github action
Regression after #2981
Applying suggested fix:
CI should pass

Fix publish stroybook action - update checkout fetch depth

---

.github/workflows/update-snapshots.yml
change-beta/@azure-communication-react-73f1fd32-cbbc-494e-8559-a7697bd3429d.json
change/@azure-communication-react-73f1fd32-cbbc-494e-8559-a7697bd3429d.json

Revise the `update_snapshot.yml` file to commit and push component examples snapshots
The `component_examples` job used to generate a patch file named `component-examples.patch` containing the changes and uploads it as an artifact. Unlike other packages, it does not directly commit the changes and push them to the repository.
As per discussion with @PorterNan, we update the `component_examples` same to other packages. 

Revise the update_snapshot.yml file 

---

change-beta/@azure-communication-react-72bcd241-0e7c-489d-bda4-ecec6f5d31d6.json
change/@azure-communication-react-72bcd241-0e7c-489d-bda4-ecec6f5d31d6.json
packages/storybook/stories/SendBox/snippets/Mentions.snippet.tsx

In the Sendbox page of the Storybook, `Docs` tab and `Mentioning Users` section,
Users should be able to see the message content via alert after tap on the send button

[Chat] Show message content in an alert after sending mention messages in Storybook

---

change-beta/@azure-communication-react-0ce62415-d370-4337-9592-750d9a1fd06e.json
change/@azure-communication-react-0ce62415-d370-4337-9592-750d9a1fd06e.json
packages/react-composites/src/composites/CallComposite/components/SidePane/SidePane.tsx
packages/react-composites/src/composites/common/styles/ParticipantContainer.styles.ts

Cherrypick https://github.com/Azure/communication-ui-library/pull/3116 to 1.5.1-beta.5 release branch

Cherry-pick `safari sidepane chat scroll, new message, and input box position bugfix` to 1.5.1-beta.5 release branch

---

change-beta/@azure-communication-react-4832ab9d-9a4a-4fb9-8da2-940e895a6aca.json
change/@azure-communication-react-4832ab9d-9a4a-4fb9-8da2-940e895a6aca.json
packages/storybook/stories/SitePermissions/snippets/SitePermissionsCheckModal.snippet.tsx
packages/storybook/stories/SitePermissions/snippets/SitePermissionsDeniedModal.snippet.tsx
packages/storybook/stories/SitePermissions/snippets/SitePermissionsExample.snippet.tsx
packages/storybook/stories/SitePermissions/snippets/SitePermissionsRequestModal.snippet.tsx
packages/storybook/stories/UnsupportedBrowser/snippets/UnsupportedBrowserExamples.snippet.tsx
packages/storybook/stories/UnsupportedBrowser/snippets/UnsupportedEnvironmentModal.snippet.tsx

- These components have built in local usage with localization provider same as all components so remove bad reference to `useLocale`.
- Ensure registerIcons is called
Stories were broken to external users
Locally:

Fix browser permissions storybook snippets

---

change-beta/@azure-communication-react-26897390-5615-4ae3-8818-289d5617a094.json
change-beta/@azure-communication-react-6469303f-f7dd-44ab-8b8c-f0ad6cc58d53.json
change/@azure-communication-react-26897390-5615-4ae3-8818-289d5617a094.json
change/@azure-communication-react-6469303f-f7dd-44ab-8b8c-f0ad6cc58d53.json
packages/react-components/src/components/ChatMessage/MentionRenderer.tsx
packages/react-components/src/components/InputBoxComponent.tsx
packages/storybook/stories/MessageThread/MessageThread.stories.tsx
packages/storybook/stories/MessageThread/snippets/MessageWithCustomMentionRenderer.snippet.tsx

The displayText parameter from the msft-mention tag is not used and is duplicated by the tag-enclosed text, which is what is rendered.
Redundant and confusing API removed
Storybook

[Chat][Mention] Remove displayText from <msft-mention> tag

---

change-beta/@azure-communication-react-0c909297-6088-46e5-81f3-e8d36a61aee4.json
change-beta/@azure-communication-react-8458eacc-fcc0-4685-923e-6f80fcf76e06.json
change-beta/@azure-communication-react-c9db9219-24bd-48b1-aed2-376a92043bd3.json
change-beta/@azure-communication-react-f23b0c54-c582-468b-b3c0-5745dc93c7e8.json
change/@azure-communication-react-0c909297-6088-46e5-81f3-e8d36a61aee4.json
change/@azure-communication-react-8458eacc-fcc0-4685-923e-6f80fcf76e06.json
change/@azure-communication-react-c9db9219-24bd-48b1-aed2-376a92043bd3.json
change/@azure-communication-react-f23b0c54-c582-468b-b3c0-5745dc93c7e8.json
common/config/babel/.babelrc.js

Mark call transfer to in progress feature before beta release as precaution
We do not want API changes from call transfer leaking into the beta release if it is not ready
Data point conditional compilation squared

Mark call transfer to in-progress feature

---

.github/workflows/deploy-feature-azure-webapps.yml
.github/workflows/deploy-release-azure-webapps.yml
change-beta/@azure-communication-react-b1501d76-e2dc-4c64-b72b-a86f6b328e00.json
change/@azure-communication-react-b1501d76-e2dc-4c64-b72b-a86f6b328e00.json

- Update release to do an azure login instead of publish profile
- Split apps across multiple jobs, **drops time from 27minutes --> 8minutes**
New security requirement ([more info](https://eng.ms/docs/cloud-ai-platform/devdiv/serverless-paas-balam/serverless-paas-benbyrd/app-service-web-apps/antares-trouble-shooting-guides-tsg/partnertsgs/basicauth#how-to-enable-oidc-authentication-for-github-actions-instead-of-basic-authentication))
https://github.com/Azure/communication-ui-library/actions/runs/5257696739

Update release validation for new security requirements

---

change-beta/@azure-communication-react-dedbc6a1-ca23-4689-b1e4-19f00c12c238.json
change/@azure-communication-react-dedbc6a1-ca23-4689-b1e4-19f00c12c238.json
packages/react-components/src/components/TextFieldWithMention/TextFieldWithMention.tsx

Fix an issue with mouse selection and editing.
Steps to test: 
1. paste long text in the input box
2. add mention
3. click on the middle of the pasted text
4. click at the end of the text
5. start typing
Expected result: the typed text is added without any issues
Editing for text with mentions didn't work as expected
Storybook

[Chat] Fixed selection indexes for mouse click events on mention

---

change-beta/@azure-communication-react-ef4473ae-6b96-450d-b4ef-9df5d467dc38.json
change/@azure-communication-react-ef4473ae-6b96-450d-b4ef-9df5d467dc38.json
packages/storybook/stories/SendBox/snippets/Mentions.snippet.tsx

- Margin fix for mention send box example in Storybook
- when long text was pasted and a mention trigger was added, the suggestions popover wasn't fully visible
Storybook

[Chat] Margin fix for mention send box example in Storybook

---

change-beta/@azure-communication-react-2d9563fb-07b5-48e2-bb80-232218358820.json
change/@azure-communication-react-2d9563fb-07b5-48e2-bb80-232218358820.json
packages/react-components/src/components/TextFieldWithMention/mentionTagUtils.ts

Updated initial index value in findStringsDiffIndexes to include the last symbol in the strings
Previously when changed a selected value at the end of the string, the last symbol wasn't included but it should be.
Steps to reproduce:
1. Type '@1 bla' with selectinon @1 as a mention
2. Select 'bla'
3. Paste 'Paste' or 'bbb' or 'bb' (different cases will be handled for different difference between old text and new text length)
Previous result: The text is not changed as expected
Storybook

[Chat] Updated initial index value in findStringsDiffIndexes

---

.github/workflows/ci.yml
change-beta/@azure-communication-react-bb34f268-20c3-4cda-bc86-d5e07b44cfe6.json
change/@azure-communication-react-bb34f268-20c3-4cda-bc86-d5e07b44cfe6.json
common/config/webpack/sampleapp.webpack.config.js

Get treeshaked build in production mode
The current webpack mapping supports hot reload really well for daily development, but it blocks webpack treeshaking. So we conditionally choose the mapping when it is in development mode for getting more production-like bundles

Get treeshaked build in production mode

---

change-beta/@azure-communication-react-9119d37c-a257-4f03-8516-1b51b3e4eb1d.json
change/@azure-communication-react-9119d37c-a257-4f03-8516-1b51b3e4eb1d.json
packages/communication-react/README.md

Point readme instructions to install non-fixed versions of peer deps
Currently they point to specific versions they shouldn't:
n/a

Point readme instructions to install non-fixed versions of peer deps

---

change-beta/@azure-communication-react-29e3b3f9-3d78-4851-a761-6c65b0a42c8a.json
change/@azure-communication-react-29e3b3f9-3d78-4851-a761-6c65b0a42c8a.json
packages/react-components/src/components/InputBoxComponent.tsx

- Fixed an issue with a cursor position when multiline parameter is set to true
The cursor position should be set to the end of the string instead of the beggining of it when edit is started
Storybook

[Chat] Fix for a cursor position during message editing

---

change-beta/@azure-communication-react-2bf80130-8dc8-4708-9008-ab2469cd7806.json
change/@azure-communication-react-2bf80130-8dc8-4708-9008-ab2469cd7806.json
packages/react-components/src/components/TextFieldWithMention/TextFieldWithMention.tsx
packages/react-components/src/components/TextFieldWithMention/mentionTagUtils.ts

- Fix for inconsistencies in cursor position during mention editing
1. Add mention to input field => type any other symbol without space => remove the symbol => only symbol should be removed and mention should stay as it is
2. Type 'Hello @Patricia Adams' => select 'lo @Patricia' => delete or input a symbol => cursor shouldn't be moved to the end of the string
3. Type 'Hello @Patricia Adams and' => select ' Adams a' => delete or input a symbol => cursor shouldn't be moved to the end of the string
Storybook

[Chat] Fix for inconsistencies in cursor position during mention editing

---

change-beta/@azure-communication-react-93b4d593-4a04-460d-94b0-ffc7624c89ab.json
change/@azure-communication-react-93b4d593-4a04-460d-94b0-ffc7624c89ab.json
packages/react-components/src/components/TextFieldWithMention/TextFieldWithMention.tsx
packages/react-components/src/components/styles/MentionPopover.style.ts

When the text content is long enough to make the text input field scrollable, then try to mention someone on the first line of the text causing the mention popover's position being too high up.
Also fixed:
1. changed the hover background color of mention popover item from neutralLight to neutralLighter
2. when a mention suggestion is active, the item UI shrunk a bit due to the border
1. Paste in some long text message to make the text input field scrollable
2. Scroll to the first line of the message
3. Mention someone in the first line

[Chat] Fix mention popover position being incorrect in long text

---

change-beta/@azure-communication-react-a215f5dd-d4db-42f8-ab2d-00c83dff20ba.json
change/@azure-communication-react-a215f5dd-d4db-42f8-ab2d-00c83dff20ba.json
common/config/babel/.babelrc.js

- Remove call-transfer feature from in-progress features 
- Add pre-release changelog
Call transfer feature is ready for Public Preview. We will release it in our June release

[Release] Remove call-transfer feature from in-progress features and add pre-release changelog

---

change-beta/@azure-communication-react-0548d4a9-d7d1-4987-9858-8a3a6520c8e8.json
change/@azure-communication-react-0548d4a9-d7d1-4987-9858-8a3a6520c8e8.json
common/scripts/bump-beta-version.js
common/scripts/package.json

Update script to bump beta version based on the discussion in 'Web UI group' chat
We have been doing our beta version bumps incorrectly. Need this to create pre-release branch for 1.7.0-beta.1 release
Tested new function in playcode:
https://github.com/Azure/communication-ui-library/assets/79475487/dbb17351-20cf-4dfb-ba6f-b6f8de4d1c2c
Tested script locally:
https://github.com/Azure/communication-ui-library/assets/79475487/31c0db19-001a-4b3f-a72f-65faf27932a2

[Release] Update script to bump beta version

---

change-beta/@azure-communication-react-1db7a146-c037-4934-90f8-c3564535e671.json
change/@azure-communication-react-1db7a146-c037-4934-90f8-c3564535e671.json
packages/react-components/src/components/MentionPopover.test.tsx
packages/react-components/src/components/MentionPopover.tsx

Increase vertical offset for 4px
| Previously | Now |
| --- | --- |
| ![image](https://github.com/Azure/communication-ui-library/assets/98852890/d7645003-ceaa-4f1d-90db-7fb68696cf6b) | ![image](https://github.com/Azure/communication-ui-library/assets/98852890/5332fe4e-1d35-4a3c-a6e2-1305f41ad419) | 
Storybook

[Chat] Add vertical offset for mention popover

---

change-beta/@azure-communication-react-e2c245ba-da68-430e-ac6e-eecb6a37bfe0.json
change/@azure-communication-react-e2c245ba-da68-430e-ac6e-eecb6a37bfe0.json
packages/react-components/src/components/styles/MessageThread.styles.ts

Addressed the issue where video messages not being scaled properly in message container.
Note that currently the video content would appear to be blank and this is expected and it needs to be addressed in the backend.
|  Before  | After  |
|---|---|
|  <img width="358" alt="image" src="https://github.com/Azure/communication-ui-library/assets/109105353/779db6a9-85a3-43f2-8250-e96ee876fdda"> | <img width="371" alt="image" src="https://github.com/Azure/communication-ui-library/assets/109105353/51a73afa-63e3-4ffc-a2c5-8549c7373a1d">  |
run call with chat sample, join a Teams call, send a video message from Teams side, verify if blank video tag is scaled properly in container.

[Chat] Fixed Video Not Scale Properly

---

change-beta/@azure-communication-react-bce96543-9731-4d9f-8522-6c7e6c6f203d.json
change/@azure-communication-react-bce96543-9731-4d9f-8522-6c7e6c6f203d.json
packages/storybook/stories/Adapters/Adapters.stories.mdx

-Storybook Adapter page add beta property (downloadAttachments) for chatAdapter

[Chat] Storybook Adapter page add beta property for chatAdapter

---

change-beta/@azure-communication-react-a56e6b1d-2716-41ea-ba11-ee89ebeb0812.json
change/@azure-communication-react-a56e6b1d-2716-41ea-ba11-ee89ebeb0812.json
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts

Fixed mobile apdater bug fail to query speakers 
Tested on mobile device 

Fixed mobile adapter bug querying speakers 

---

change-beta/@azure-communication-react-3c8b4d1b-4194-4793-8046-30135c6dcb08.json
change/@azure-communication-react-3c8b4d1b-4194-4793-8046-30135c6dcb08.json
packages/react-components/src/components/MentionPopover.tsx

Mention suggestions caused a brief visual flicker during rendering.
The offset position was not calculated prior to the first render and rendered it at 0,0 - inside the text area. It then very quickly jumped to the correct calculated location. 
Storybook.

[BugFix] Remove visual flicker on presenting mention suggestions popover

---

change-beta/@azure-communication-react-7b4814b9-efd9-4260-80cb-d88667c8e5d7.json
change/@azure-communication-react-7b4814b9-efd9-4260-80cb-d88667c8e5d7.json
packages/react-components/src/components/SendBox.test.tsx
packages/react-components/src/components/TextFieldWithMention/TextFieldWithMention.tsx

- Fixed functionality to handle triple click selection
- Added unit test to check this behavior
Previously, when a mention is added in the beginning of the text and triple action was done, only mention was selected.
Storybook

[Chat] Fix triple click selection for TextFieldithMention when mention is added in the beginning of the text

---

change-beta/@azure-communication-react-00d721c4-8922-4e27-a504-61ec5546c6e1.json
change/@azure-communication-react-00d721c4-8922-4e27-a504-61ec5546c6e1.json
packages/react-components/src/components/styles/MentionPopover.style.ts
packages/storybook/stories/SendBox/snippets/Mentions.snippet.tsx

1. Adding more mention suggestions to the Storybook page
2. Fix on the Storybook page, the top of the mentionPopover is cut off
3. Fix the content view is not wrapped up in the scroll view
Before: 
After:

[Chat] Fix mention popover content view is not wrapped up in the scroll view when the list is long

---

change-beta/@azure-communication-react-070ad661-6c41-4d60-9193-0d4e915431da.json
change/@azure-communication-react-070ad661-6c41-4d60-9193-0d4e915431da.json
packages/communication-react/review/beta/communication-react.api.md
packages/react-components/review/beta/react-components.api.md
packages/react-components/src/components/FileDownloadCards.tsx
packages/react-components/src/components/MessageThread.test.tsx

Clean up unused properties in the API 

[Chat] cleaning up some unused property for FileMetaData

---

change-beta/@azure-communication-react-5d3c3a90-b296-4be7-b53a-e813450aed36.json
change/@azure-communication-react-5d3c3a90-b296-4be7-b53a-e813450aed36.json
packages/react-components/src/components/TextFieldWithMention/TextFieldWithMention.tsx

The top prop of the relativePosition we get back from the Caret library is the distance between the top of the scroll view to the cursor position.
We use to adjust this value by subtract the difference between the scrollView height - the contentHeight.
The problem of this approach is that it's not considering the current scroll position.
Instead, when the view is scrollable, we should use relativePosition.top subtracted by scrollTop to get the relative position to the content view
From MDN:
The Element.scrollTop property gets or sets the number of pixels that an element's content is scrolled vertically.
An element's scrollTop value is a measurement of the distance from the element's top to its topmost visible content. When an element's content does not generate a vertical scrollbar, then …

[Chat] Fix mention popover position incorrect when insert mention in the middle of long text

---

.github/workflows/breaking-change-check.yml
change-beta/@azure-communication-react-586ff6a3-bf98-423f-8819-d7be4a298b8e.json
change/@azure-communication-react-586ff6a3-bf98-423f-8819-d7be4a298b8e.json

- Ensure dependencies are installed for the base branch before generating base branch api
- If dependencies vary significantly (e.g. updating a new SDK beta version) then the base branch build could break
Unblocks #3355 
n/a

Fix breaking change check by ensuring dependencies are installed for the base branch

---

.github/ISSUE_TEMPLATE/config.yml
change-beta/@azure-communication-react-94e1394d-e16f-434e-bf0c-043a6847cd2f.json
change/@azure-communication-react-94e1394d-e16f-434e-bf0c-043a6847cd2f.json

Adding in a suggest a Feature button that will take us to Microsoft Q&A instead
We have support engineers monitoring microsoft Q&A and we can better support our developers in Microsoft Q&A instead. While this may be different from most open source repositories, we need to be able to scale and make best use of Microsoft in order for us to be successful.
Unable to test till this change goes into main :(

Adding Feature request through Microsoft Q&A template

---

change-beta/@azure-communication-react-50491160-50c0-4fc1-9859-a7d602b846c1.json
change/@azure-communication-react-50491160-50c0-4fc1-9859-a7d602b846c1.json
packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
packages/react-composites/src/composites/CallComposite/components/SidePane/usePeoplePane.tsx
packages/react-composites/src/composites/CallComposite/components/SidePane/useVideoEffectsPane.tsx
packages/react-composites/src/composites/CallComposite/components/buttons/Camera.tsx
packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx

adds a ref to the people button that causes the sidepane to pull focus there when it closes the people pane.
fixes this problem for both side panes:
- people <- returns to people button
- calling effects <- returns to camera button
https://github.com/Azure/communication-ui-library/assets/94866715/44c42af8-9e33-44b9-af4d-18bf6a52c3ea
https://skype.visualstudio.com/SPOOL/_workitems/edit/3330754
Tested locally, see video

[A11y bugfix] Refocus the people button when closing side pane with keyboard

---

change-beta/@azure-communication-react-2f4b1682-b27a-4bc5-89ad-80ee84944a36.json
change/@azure-communication-react-2f4b1682-b27a-4bc5-89ad-80ee84944a36.json
samples/Calling/src/app/views/HomeScreen.tsx

Redo fix for #3390. Component has to be last when using Logical AND (&&).
Local calling sample test (beta and stable)

Fix calling sample displayname field logic

---

.github/workflows/create-release-branch.yml
change-beta/@azure-communication-react-47707f0a-52e6-473f-89c0-fad8f3944926.json
change/@azure-communication-react-47707f0a-52e6-473f-89c0-fad8f3944926.json

create-release-branch script update
The changelog command can't be used as it is right now as it requires some manual input

Disable Changelog step for create-release-branch script

---

change-beta/@azure-communication-react-bdd7d2d2-2b19-4885-ab15-7a87c29a0d34.json
change/@azure-communication-react-bdd7d2d2-2b19-4885-ab15-7a87c29a0d34.json
packages/chat-component-bindings/package.json
packages/chat-stateful-client/package.json
packages/communication-react/package.json
packages/fake-backends/package.json
packages/react-composites/package.json
packages/storybook/package.json
rush.json
samples/CallWithChat/package.json
samples/Chat/package.json
samples/ComponentExamples/package.json
samples/Server/package.json
samples/StaticHtmlComposites/package.json
samples/tests/package.json

Bump stable chat dependency to current release version
Enable node 20 tooling
rush-managed version was set but not the package version.
CI

[Release] Update dependencies

---

change-beta/@azure-communication-react-2d3598be-3496-4902-b267-bfb73127740f.json
change/@azure-communication-react-2d3598be-3496-4902-b267-bfb73127740f.json
samples/CallWithChat/src/app/utils/ShakeToSendLogs.tsx
samples/Calling/src/app/utils/ShakeToSendLogs.tsx
samples/Chat/src/app/utils/ShakeToSendLogs.tsx
samples/Server/src/app.ts

Continuation of #3425 
- Cap log lines to 1000 characters each
- Retry when 413 upload err occurs with smaller payload
- Increase the server post body allowance (default is 100KB)
Server returns 413 if there's a lot of logs. Alternative would be to stream logs instead

Handle 413 err and increase the allowed server POST body amount

---

change-beta/@azure-communication-react-8c219df0-b5f2-4d9e-b223-48941bbfe427.json
change/@azure-communication-react-8c219df0-b5f2-4d9e-b223-48941bbfe427.json
packages/calling-component-bindings/review/stable/calling-component-bindings.api.md
packages/calling-component-bindings/src/participantListSelector.ts
packages/communication-react/review/stable/communication-react.api.md

Removes the selector value from the participant list selector
Should not be in the stable API view
found in stable review for 1.7.0
Build files

[total participant count] Remove the count from participant list selector

---

change-beta/@azure-communication-react-ce15e597-ba9e-498e-81cb-df162e374aa1.json
change/@azure-communication-react-ce15e597-ba9e-498e-81cb-df162e374aa1.json
packages/storybook/stories/ChatComposite/snippets/Utils.tsx

Fix storybook ChatComposite preview page for bot missing displayName
Before
After

[Storybook] Fix storybook ChatComposite preview page for bot missing displayName

---

change-beta/@azure-communication-react-53c802f6-0258-42c6-a58c-405cb2e63b30.json
change/@azure-communication-react-53c802f6-0258-42c6-a58c-405cb2e63b30.json
packages/react-components/src/components/styles/MentionPopover.style.ts

Temporary set to a hardcoded high number to make sure it is on top of the other components
Will be replaced by a proper z-index solution after the Fluent 9 migration

[Chat] Increase mention popover's z-index

---

change-beta/@azure-communication-react-b4ca5447-c3fe-4a3e-9186-ccc4c1ecb181.json
change/@azure-communication-react-b4ca5447-c3fe-4a3e-9186-ccc4c1ecb181.json
packages/react-components/review/beta/react-components.api.md
packages/react-components/review/stable/react-components.api.md
packages/react-components/src/components/RemoteVideoTile.tsx
packages/react-components/src/components/VideoGallery.tsx
packages/react-components/src/components/VideoGallery/useVideoTileContextualMenuProps.ts

Fix for scaling mode of participants update when screen sharing is turned off by remote user

Fix for scaling mode of participants update when screen sharing is turned off by remote user

---

change-beta/@azure-communication-react-0bcf85c5-e5db-4296-96f4-2269902570cb.json
change/@azure-communication-react-0bcf85c5-e5db-4296-96f4-2269902570cb.json
packages/storybook/stories/INTERNAL/ImageGallery/ImageGallery.stories.tsx

To have the image gallery covers the safeArea on iOS devices, the only way is through modifying the global meta tag.
We don't want to add this to our composite since the control should be given to the Contoso's app.
Adding documentation to demo how Contosos can make Image Gallery covers the safe area on iOS devices.

[Chat] Add documentation for how to cover the safe area on iOS devices

---

change-beta/@azure-communication-react-ba9de2fd-3971-48e6-aeed-1bf9a933c7de.json
change/@azure-communication-react-ba9de2fd-3971-48e6-aeed-1bf9a933c7de.json
packages/react-components/src/components/MessageThread.tsx
packages/react-components/src/theming/FluentV9ThemeProvider.tsx
packages/react-components/src/theming/v9ThemeShim.ts

Added FluentV9ThemeProvider that can be reused during the future development of new v9 components (before breaking changes)
Storybook

Add FluentV9ThemeProvider for future v9 components

---

change-beta/@azure-communication-react-5027666e-56a5-4502-a203-3a671c79dfa2.json
change/@azure-communication-react-5027666e-56a5-4502-a203-3a671c79dfa2.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/review/stable/react-composites.api.md
packages/react-composites/src/composites/CallComposite/CallComposite.tsx
packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx

Adds the missing options to CallWithChatComposite options interface:
- LocalVideoTile position
- RemoteVideoTileOptions
Aligns CallWithChat with CallComposite
https://skype.visualstudio.com/SPOOL/_workitems/edit/3403921
https://skype.visualstudio.com/SPOOL/_workitems/edit/3403911
Fixes #3556

[BugFix] Add missing composite options to CallWithChatComposite

---

change-beta/@azure-communication-react-80c141a0-4ad2-4bb9-874a-482819959723.json
change/@azure-communication-react-80c141a0-4ad2-4bb9-874a-482819959723.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/review/stable/react-composites.api.md
packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts

Cherry pick https://github.com/Azure/communication-ui-library/pull/3570 to release/1.8.0
Also add capabilities changed event to CallWithChatAdapter

Cherry pick #3570 to release/1.8.0

---

change-beta/@azure-communication-react-305a826e-1a08-49b8-8647-c1d2f8860af5.json
change/@azure-communication-react-305a826e-1a08-49b8-8647-c1d2f8860af5.json
packages/react-composites/src/composites/CallComposite/utils/TrackCapabilityChangedNotifications.ts

Fix redundant presenter role notification when joining Teams interop. The capability changed info comes from the Calling SDK
at the start of a Teams interop call and is now ignored as it is redundant and assumed.
https://skype.visualstudio.com/SPOOL/_workitems/edit/3405770
Local calling sample testing:
https://github.com/Azure/communication-ui-library/assets/79475487/3f159cd5-c1dc-4f64-aad4-01609727a669

[Stable release blocking] Fix redundant presenter role notification when joining Teams interop

---

change-beta/@azure-communication-react-9e4c6c5c-4ada-4684-ba24-abc8a8aa1281.json
change/@azure-communication-react-9e4c6c5c-4ada-4684-ba24-abc8a8aa1281.json
packages/react-components/src/components/utils/Datetime.test.ts
packages/react-components/src/components/utils/Datetime.ts

Use the `toLocale[Time/Date]String()` methods on `Date` to obtain a properly localized default message timestamp string
Current implementation is English 12hr format only and for anything else, users must override the renderer.
Storybook, CI

[BugFix] Default message timestamp to use locales

---

change-beta/@azure-communication-react-890b72a5-482b-4c71-886b-39cf867a49d9.json
change/@azure-communication-react-890b72a5-482b-4c71-886b-39cf867a49d9.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
packages/react-composites/package.json
samples/StaticHtmlComposites/package.json
samples/tests/package.json

^ changes had us getting a new minor version of playwright this returns it to ~
something in the new minor version `1.38.1`  breaks the static tests
Validated the package downgrade fixes the tests locally

[CI fix] downgrade playwright

---

change-beta/@azure-communication-react-bb6d5502-a3b8-44ea-8d64-ca46a6b009a9.json
change/@azure-communication-react-bb6d5502-a3b8-44ea-8d64-ca46a6b009a9.json
packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx

Ensure that menu options are the correct size and consistent
Refactor to fluent-contrib-chat meant some changes
Storybook; browser emulation of mobile

[BugFix] Update MyMessage options menu to correct size/visibility on mobile browsers

---

change-beta/@azure-communication-react-9a4850dd-bc1a-4842-a3e9-d7c01705b2f7.json
change/@azure-communication-react-9a4850dd-bc1a-4842-a3e9-d7c01705b2f7.json
packages/react-composites/src/composites/common/CaptionsBanner.tsx

Decrease captions banner width when screen is too small to prevent more button overlapping with scroll bar 
https://skype.visualstudio.com/SPOOL/_workitems/edit/3413763
https://github.com/Azure/communication-ui-library/assets/96077406/1ac53032-744e-4d7a-b22c-2e66ae4f1cd6

[Bug fix]Decrease captions banner width when screen is too small to prevent more button overlapping with scroll bar 

---

change-beta/@azure-communication-react-d0492f53-bae0-4425-bbad-a83d039c3ad2.json
change/@azure-communication-react-d0492f53-bae0-4425-bbad-a83d039c3ad2.json
packages/react-components/src/components/SendBox.test.tsx
packages/react-components/src/components/utils/testUtils.tsx
samples/Calling/src/app/App.tsx

- Removed workaround for mouseDown event in jest tests
- Removed duplicated strict mode from Calling sample app
Ran tests

Removed workaround for mouseDown event in jest tests

---

packages/calling-component-bindings/review/beta/calling-component-bindings.api.md
packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
packages/communication-react/review/beta/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
packages/react-composites/src/composites/CallComposite/components/StarSurvey.tsx
packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts
packages/react-composites/src/composites/CallComposite/pages/NoticePage.tsx
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts

Star Survey inside call composite 
End of call survey 
Tested with samples 

Star Survey inside call composite 

---

change-beta/@azure-communication-react-ef1fe0ea-3e79-4e37-b27c-2557fc692c38.json
change/@azure-communication-react-ef1fe0ea-3e79-4e37-b27c-2557fc692c38.json
packages/react-components/src/components/FileDownloadCards.tsx
packages/react-components/src/components/MessageThread.test.tsx

- Add missing DownloadFileCards tooltip (with existing localization support
- Tooltip is not working on Samples due to RestrictMode (related PR: https://github.com/Azure/communication-ui-library/pull/3659/files)

[Bugfix] Fix missing DownloadFileCards tooltip

---

change-beta/@azure-communication-react-88b901bc-e801-48a5-9ebd-f2f41a2f9308.json
change/@azure-communication-react-88b901bc-e801-48a5-9ebd-f2f41a2f9308.json
packages/react-composites/src/composites/common/PeoplePaneContent.tsx

Fixes issue where more button drawer is hidden depending on the role ACS Users in a groupcall do not have roles
Lets participants remove others
https://skype.visualstudio.com/SPOOL/_workitems/edit/3440612

[Bugfix] Fix mobile participant removal

---

change-beta/@azure-communication-react-fa44ad02-5cf3-420c-ae72-89e84b8103ca.json
change/@azure-communication-react-fa44ad02-5cf3-420c-ae72-89e84b8103ca.json
packages/react-composites/src/composites/CallComposite/CallComposite.tsx
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
packages/react-composites/src/composites/CallComposite/components/MediaGallery.tsx
packages/react-composites/src/composites/CallComposite/components/NetworkReconnectTile.tsx
packages/react-composites/src/composites/CallComposite/pages/LobbyPage.tsx

- Remove hook where we manually restarted the video if the camera was on in the configuration page
- Instead correctly pass the localvideostream into the call agent when starting a call.
In react18 strict mode the double hook execution was causing errors
Locally, verified joining a call with and without both camera and mic.

Fix erroneous error saying failed to turn off video when starting a call in react18 strict mode

---

change-beta/@azure-communication-react-e0ab483b-96d9-4102-8c37-dbc0727c3d61.json
change/@azure-communication-react-e0ab483b-96d9-4102-8c37-dbc0727c3d61.json
packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx

* render gallery when sidepane is closed
* Change files
* fix render for desktop as well
* update re-render logic
* fix defined check
* fix cc

[BugFix] Grey Tile fix (#3754)

---

change-beta/@azure-communication-react-887bd6cb-d577-4bed-ac4d-45f58e6824ef.json
change/@azure-communication-react-887bd6cb-d577-4bed-ac4d-45f58e6824ef.json
packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx

Allows toggle on parent of mobile more drawer
Allows keyboard on mobile to directly action it without navigating to secondary button component.
https://skype.visualstudio.com/SPOOL/_workitems/edit/3386878
Tested locally

[Bugfix] Add keyboard actioning 

---

change-beta/@azure-communication-react-d35069aa-4be5-488f-853f-41d2034d2621.json
change/@azure-communication-react-d35069aa-4be5-488f-853f-41d2034d2621.json
packages/communication-react/review/beta/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts

Add role changed event to CallAdapter
Give Contoso the ability to listen for this event from the Calling SDK
Tested on sample Calling app by listening to event and logging to console

[Rooms] Add role changed event to CallAdapter

---

change-beta/@azure-communication-react-bd803e15-0466-423a-9236-286d712b34b1.json
change/@azure-communication-react-bd803e15-0466-423a-9236-286d712b34b1.json
packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx
packages/react-components/src/components/styles/MessageThread.styles.ts

Fixed an issue when grey placeholder was shown for images for GA release
Current implementation with the fix:
- beta
https://github.com/Azure/communication-ui-library/assets/98852890/c942809a-0fcb-459a-b868-8bfa7fdec780
- stable:
https://github.com/Azure/communication-ui-library/assets/98852890/73aa8813-ba89-42af-a8d3-bd684a630ad8

[Chat] Fix for image placeholder issue for GA release

---

change-beta/@azure-communication-react-0267f342-dc2c-4146-8fd9-5ed3013dd2ae.json
change-beta/@azure-communication-react-5ff8daf3-f304-4bf6-b675-1e442ec92406.json
change/@azure-communication-react-0267f342-dc2c-4146-8fd9-5ed3013dd2ae.json
change/@azure-communication-react-5ff8daf3-f304-4bf6-b675-1e442ec92406.json
packages/acs-ui-common/src/telemetry.ts
packages/acs-ui-common/tsconfig.json
packages/acs-ui-common/tsconfig.preprocess.json
packages/calling-component-bindings/src/participantListSelector.ts
packages/calling-component-bindings/src/videoGallerySelector.ts
packages/calling-component-bindings/tsconfig.json
packages/calling-stateful-client/review/beta/calling-stateful-client.api.md
packages/calling-stateful-client/review/stable/calling-stateful-client.api.md
packages/calling-stateful-client/src/CallAgentDeclarative.test.ts
packages/calling-stateful-client/src/Converter.ts
packages/calling-stateful-client/src/DeviceManager.test.ts
packages/calling-stateful-client/src/DeviceManagerDeclarative.ts
packages/calling-stateful-client/src/TestUtils.ts
packages/calling-stateful-client/tsconfig.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md

- Enable `noImplicitAny` for acs-ui-common, calling-stateful-client and calling-component-bindings packlets
- **Important: Exposed a necessary stable breaking change in the StatefulCallClient.selectCamera.**
- ARB should approve this as its type narrowing for functional safety
Work to enable noImplicitAny throughout repo
n/a - CI will run necessary tests.

Enable `noImplicitAny` for acs-ui-common, calling-stateful-client and calling-component-bindings packlets

---

change-beta/@azure-communication-react-d4e5981c-8336-4d9c-90fe-9d787ce6e874.json
change/@azure-communication-react-d4e5981c-8336-4d9c-90fe-9d787ce6e874.json
packages/calling-component-bindings/src/handlers/createCommonHandlers.ts
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts

Cherry picked from commit https://github.com/Azure/communication-ui-library/commit/cf280998d3b36108f0c6a63c2b8fd9c7de0afb7c
See https://github.com/Azure/communication-ui-library/pull/3917 for more details

[Cherry-Pick] Update device behavior on connecting and lobby screens

---

change-beta/@azure-communication-react-814eca6b-6f1a-44e2-bc6a-7c372c6192c4.json
change/@azure-communication-react-814eca6b-6f1a-44e2-bc6a-7c372c6192c4.json
packages/react-composites/src/composites/CallComposite/components/CallControls.tsx
packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
samples/CallWithChat/src/app/views/CallScreen.tsx
samples/Calling/src/app/views/CallCompositeContainer.tsx

Cherry picked from commit https://github.com/Azure/communication-ui-library/commit/cf8225f95851d51f1c973453671dce6b427fd251
See https://github.com/Azure/communication-ui-library/pull/3915 for more details

[Cherry-pick] Prevent showing screenShareButton when formFactor is set to mobile

---

change-beta/@azure-communication-react-e3181cc7-3ce8-44d3-ae27-f595b8a93efe.json
change/@azure-communication-react-e3181cc7-3ce8-44d3-ae27-f595b8a93efe.json
packages/react-composites/src/composites/common/SidePaneHeader.tsx

Add heading role to SidePaneHeader
https://skype.visualstudio.com/SPOOL/_workitems/edit/3323329
No role was defined for SidePaneHeaders like People and Effects
MacOS Chrome Calling sample

[bugfix] Add heading role to SidePaneHeader

---

change-beta/@azure-communication-react-271e1156-3766-4b14-99c4-12db881e1dad.json
change/@azure-communication-react-271e1156-3766-4b14-99c4-12db881e1dad.json
packages/communication-react/review/stable/communication-react.api.md
packages/react-components/review/stable/react-components.api.md
packages/react-components/src/components/FileDownloadCards.tsx
packages/react-components/src/components/MessageThread.tsx

Remove FileCardGroupMessage From Stable API

[Chat] Remove file card group message from stable API

---

change-beta/@azure-communication-react-d32b8e1a-2e27-466c-a5b9-7e5829712cd2.json
change/@azure-communication-react-d32b8e1a-2e27-466c-a5b9-7e5829712cd2.json
packages/react-components/src/components/MessageThread.tsx

Fixed an issue when scrolling caused all previous messages to be delted.
Steps to test:
- open a chat with a lot of messages
- scroll to top
- see that only some of the messages are loadded and they continue be loaded when YOU scroll more
sample app, tests

[Chat] MessageThread scolling fix

---

change-beta/@azure-communication-react-09bb9bd5-6808-44dd-94d1-4a6bc9cc2581.json
change/@azure-communication-react-09bb9bd5-6808-44dd-94d1-4a6bc9cc2581.json
packages/react-components/src/components/MessageThread.tsx

A race condition for lastDeletedMessageId was found in 1 of the partners app, this PR will fix it.
Checked with the partner team that solution works for them. Tested with sample that it didn't break things for us.

[Chat] Fix for a race condition for "The message is deleted" announcement

---

change-beta/@azure-communication-react-1c094de5-9a94-40bf-ac5c-a3d94cdb3dda.json
change/@azure-communication-react-1c094de5-9a94-40bf-ac5c-a3d94cdb3dda.json
packages/react-composites/src/composites/CallComposite/CallComposite.tsx
packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
packages/react-composites/tests/app/lib/MockCallAdapter.ts

Listen to the callEnded event and set the sidepane's to closed when the call is ended
Existing behavior was that if the side pane was closed, and the call is ended and rejoined the pane would be open - which we don't want.
Locally, checked the side pane was closed on rejoin for video effects, people and chat panes.

Ensure the CallComposite and CallWithChatComposite side pane's are closed if the call is rejoined

---

change-beta/@azure-communication-react-ca5238f1-98ce-4db0-814c-1a041c63dc06.json
change/@azure-communication-react-ca5238f1-98ce-4db0-814c-1a041c63dc06.json
packages/react-components/src/components/VideoTile.tsx
packages/react-components/src/components/styles/VideoTile.styles.ts

Update the local video tile to show the raise hand at the bottom center
Mobile users could not see their own position in the raise hand queue
Locally
| -- | -- |
| ![image](https://github.com/Azure/communication-ui-library/assets/2684369/2d34fa01-44e9-47e6-9557-5b34ed499f78) | ![image](https://github.com/Azure/communication-ui-library/assets/2684369/bc86332e-afa1-4740-964f-1ad6ce66d9c1) |

Show the hand raise order on the local video tile when on mobile

---

change-beta/@azure-communication-react-f2d5b939-144b-4b28-a777-ba67ba032548.json
change/@azure-communication-react-f2d5b939-144b-4b28-a777-ba67ba032548.json
packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
packages/react-composites/src/composites/CallComposite/components/SidePane/SidePane.tsx
packages/react-composites/src/composites/CallComposite/pages/ConfigurationPage.tsx
packages/react-composites/src/composites/ChatComposite/styles/Chat.styles.ts
packages/react-composites/src/composites/common/constants.ts
packages/react-composites/src/composites/common/styles/Pane.styles.ts

Set appropriate minWidths and pull out and document constants
At 200+% zoom and 1024x768 resolution, the side panes were super small and incredibly difficult to interact with
Local testing at 200+% zoom levels at a 1024x768 resolution
| -- | -- |
| ![image](https://github.com/Azure/communication-ui-library/assets/2684369/c6002ce3-63f0-40f9-bb85-47b7efdc4e1d) | ![image](https://github.com/Azure/communication-ui-library/assets/2684369/8796c28e-1f8d-4625-9b72-1b724862f17f) |

Fix side pane content being clipped on a small screen at 200% zoom

---

change-beta/@azure-communication-react-edeccae0-dcdf-4a87-b2ca-465f6367ffc6.json
change/@azure-communication-react-edeccae0-dcdf-4a87-b2ca-465f6367ffc6.json
packages/react-composites/src/composites/CallComposite/components/LocalPreview.tsx

Enable devices button on localpreview on mobile configuration page when either microphone or camera is available
https://skype.visualstudio.com/SPOOL/_workitems/edit/3520771
|  Before | After | 
|---|---|
| ![image](https://github.com/Azure/communication-ui-library/assets/97130533/a92d40b8-6ed3-403a-9726-a8e7eecfadc4) |  ![device button enabled](https://github.com/Azure/communication-ui-library/assets/97130533/35229dc0-138d-464a-93a5-5ec9d2f146ea) |
MacOS - Chrome - Calling Sample - Mobile view

[bugfix] Mobile configuration page enable devices button when camera or microphone is available

---

change-beta/@azure-communication-react-de18a1d1-f6af-4c23-8d77-b50dfedde3bc.json
change/@azure-communication-react-de18a1d1-f6af-4c23-8d77-b50dfedde3bc.json
packages/storybook/stories/CallComposite/Quickstart1ToNDocs.stories.mdx
packages/storybook/stories/CallComposite/QuickstartPSTNDocs.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartComposite.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartStatefulCall.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartStatefulChat.stories.mdx
packages/storybook/stories/QuickStarts/QuickstartUIComponents.stories.mdx
packages/storybook/stories/Setup.stories.mdx

With latest versions of communcation-react, node 18 is required.
Also removed references to not supported React 18

[Storybook] Update min node version in storybook and remove references to not supported react 18

---

change-beta/@azure-communication-react-86e71514-bc0f-4749-9d8e-64a16f09068a.json
change/@azure-communication-react-86e71514-bc0f-4749-9d8e-64a16f09068a.json
packages/react-components/src/components/VideoGallery.tsx
packages/react-components/src/components/VideoGallery/RemoteScreenShare.tsx

Make the RemoteScreenshare component respect the scaling mode of the remote participant sharing their screen
Allows the local participant to always be able to update the scaling mode of the remote participant
https://skype.visualstudio.com/SPOOL/_workitems/edit/3519631
Inspected locally

[Bugfix] Remote screenshare scalingmode fix

---

change-beta/@azure-communication-react-75bc78d9-1466-4d47-b1bc-3163704eb990.json
change/@azure-communication-react-75bc78d9-1466-4d47-b1bc-3163704eb990.json
packages/react-composites/src/composites/common/TabHeader.tsx

- Apply `tablist` role to mobile side pane headings
- Move tablist inside a focus zone to correctly follow A11y keyboard nav
A11y bugs:
- needed to read out "1 of 2" and "2 of 2" correctly instead of saying "1 of 1" (this is done by tablist)
- needed to correctly apply navigation using arrow keys on keyboard per https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tablist_Role#keyboard_interactions (this is done by focus zone)
https://skype.visualstudio.com/SPOOL/_workitems/edit/2790321
Verified locally narrator says: "People tab item, 2 of 2, selected"

Correctly apply tablist and tablist behavior to mobile side pane tab headings

---

change-beta/@azure-communication-react-0bde713d-dea9-4c4f-818d-5bcde6286354.json
change-beta/@azure-communication-react-9086d50f-1734-491f-b814-ea14a009446e.json
change/@azure-communication-react-0bde713d-dea9-4c4f-818d-5bcde6286354.json
change/@azure-communication-react-9086d50f-1734-491f-b814-ea14a009446e.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/review/stable/react-composites.api.md
packages/react-composites/src/composites/CallWithChatComposite/ChatButton/useUnreadMessagesTracker.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/index.ts

- Add messageEdited and messagedDeleted events to the ChatAdapter.
- Use these events to update the unread message badge in the callwithchat composite when a message is deleted.
Unread messages badge should update when an unread chat message is deleted.
Verified locally deleting a chat messages decrements the unread message count to other participants in the callwithchat

Add messageEdited and messagedDeleted events to ChatAdapter. Update the unread message badge when a message is deleted.

---

change-beta/@azure-communication-react-a79595ca-bfaa-49a2-9a05-7e9549d6f012.json
change/@azure-communication-react-a79595ca-bfaa-49a2-9a05-7e9549d6f012.json
packages/react-components/src/components/Dialpad/Dialpad.test.tsx
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts

Introduces blocking error when passing teams id to CallAdapter and acs id to Teams adapter
Stops bad id's from being added to the wrong adapters. this causes strange behaviour with CTE for example that we want to stop
https://skype.visualstudio.com/SPOOL/_workitems/edit/3541196
Tested locally

[Bugfix] CallAdapter id checking

---

change-beta/@azure-communication-react-c4a56c27-3634-4cef-9aa2-3521b8f9078f.json
change/@azure-communication-react-c4a56c27-3634-4cef-9aa2-3521b8f9078f.json
common/config/babel/features.js
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/review/stable/react-composites.api.md
packages/react-composites/src/composites/CallComposite/Strings.tsx
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.test.ts
packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts

Stabilizes the Calling sounds feature
Time to release in next stable
https://skype.visualstudio.com/SPOOL/_workitems/edit/3127814
Feature stabilized tests pass

[Calling sounds] Stabilize Calling sounds feature

---

.devcontainer/devcontainer.json
change-beta/@azure-communication-react-7665db60-acd2-46d1-9f24-fc3d3853e856.json
change/@azure-communication-react-7665db60-acd2-46d1-9f24-fc3d3853e856.json
packages/chat-stateful-client/src/index.ts
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/ChatButton/NotificationIcon.tsx
packages/react-composites/src/composites/CallWithChatComposite/ChatButton/useUnreadMessagesTracker.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts
packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
packages/react-composites/src/composites/ChatComposite/adapter/StubChatClient.ts
packages/react-composites/src/composites/common/BaseComposite.tsx
packages/react-composites/src/mocks/MockChatClient.ts
packages/react-composites/src/mocks/useFakeChatAdapters.ts

`noInvalidAny` warnings are muted for code. This PR fixes the react-composite packlet chat files.

Fix `noInvalidAny` chat composites

---

change-beta/@azure-communication-react-9dbf5871-898c-403d-b5e7-99a29e88b117.json
change/@azure-communication-react-9dbf5871-898c-403d-b5e7-99a29e88b117.json
packages/communication-react/review/beta/communication-react.api.md
packages/react-components/review/beta/react-components.api.md
packages/react-components/review/stable/react-components.api.md
packages/react-components/src/components/Dialpad/Dialpad.test.tsx
packages/react-components/src/components/Dialpad/Dialpad.tsx
packages/storybook/stories/Dialpad/snippets/CustomDialpad.snippet.tsx

Remove code that forces user's keyboard to end of phone number
allows contoso to edit the phone number with the devices keyboard
https://skype.visualstudio.com/SPOOL/_workitems/edit/3553803
Locally in sample and storybook

[DTMF Dialler] Enable DTMF mode and dialing out mode in dialpad

---

change-beta/@azure-communication-react-b9775229-d90b-4d3d-8453-7751d837ce3d.json
change/@azure-communication-react-b9775229-d90b-4d3d-8453-7751d837ce3d.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
packages/communication-react/package.json
packages/react-components/package.json
packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx

Replace non-typescript html-to-react with a the html-react-parser.
html-to-react has typings that are too loose and the html-react-parser seems to be the more widely used solution with more github stars.
https://npmtrends.com/html-react-parser-vs-html-to-react.
The html-react-parser has a clearer API and seems to reduce our bundle size considerably.
CI and storybook

Replace html-to-react with html-react-parser

---

change-beta/@azure-communication-react-6b674465-0af5-403c-8825-1461c8c69fc7.json
change/@azure-communication-react-6b674465-0af5-403c-8825-1461c8c69fc7.json
samples/Chat/src/app/utils/ShakeToSendLogs.tsx
samples/Chat/src/app/utils/shake.js.d.ts
samples/Chat/tsconfig.json
samples/Chat/tsconfig.preprocess.json

Ensure types are available and allow `noImplicitAny` to be true.
NOTE: it can only be truly enabled once the entire UI library is enabled, as the code is referenced directly from the sample apps.
Stricter TS
CI

Enable noImplicitAny in the chat sample

---

change-beta/@azure-communication-react-08c687d3-39ac-414b-adff-8a43ba554b1f.json
change/@azure-communication-react-08c687d3-39ac-414b-adff-8a43ba554b1f.json
packages/storybook/stories/AddingSounds.stories.mdx

Remove beta banner for features that are stable
Properly represents the features in storybook that are no longer in public preview
Validated storybook locally, will go with next beta

[OCE] Remove beta banner for features that are stable

---

change-beta/@azure-communication-react-bc13ce86-f3fc-4e7d-a8f5-529950278c3c.json
change/@azure-communication-react-bc13ce86-f3fc-4e7d-a8f5-529950278c3c.json
samples/Calling/src/app/App.tsx
samples/Calling/src/app/utils/AppUtils.ts

Fix calling sample when it is joining a room with room id query arg.
The roomId query arg was not being properly assigned to the callLocator of the CallComposite of the Calling sample app and would join a group call instead.
https://github.com/Azure/communication-ui-library/assets/79475487/1114d79f-5adc-4305-9956-38028b05ccc5
Local calling sample testing.
https://github.com/Azure/communication-ui-library/assets/79475487/a1f4a6e2-e14b-41b2-91fa-e0790f288837

Fix calling sample joining room with room id query arg

---

change-beta/@azure-communication-react-050d4869-a611-4569-b4e3-379a73dddeff.json
change/@azure-communication-react-050d4869-a611-4569-b4e3-379a73dddeff.json
packages/react-components/src/components/Dialpad/Dialpad.tsx
packages/react-components/src/components/styles/Dialpad.styles.ts

Fix issue where back button over laps dialed number
allows for even spacing between button and phone number entered
https://skype.visualstudio.com/SPOOL/_workitems/edit/3588391

[DTMF Dialer] Dialpad back button overlap fix

---

change-beta/@azure-communication-react-1466d23d-73bc-4aa9-8a92-4537c310db9c.json
change/@azure-communication-react-1466d23d-73bc-4aa9-8a92-4537c310db9c.json
packages/chat-component-bindings/src/messageThreadSelector.ts
packages/chat-stateful-client/src/ChatContext.ts

Images being shared via file share (drag and drop) with no message content was not being displayed in the message bubbles
Bug where we were check for valid content before making a request to download inline images. 
Teams side:
- Drag and drop an file img into the chat box without a message content
CallWithChatComposite
- Notice message bubble loads inline image

[Chat] Bug fix Img via file share with no message content

---

change-beta/@azure-communication-react-74550d0c-51e2-4584-8fb7-77fbe2539615.json
change/@azure-communication-react-74550d0c-51e2-4584-8fb7-77fbe2539615.json
packages/chat-stateful-client/src/convertChatMessage.ts

In the case of an edited message with no message content, but a few attachments via file sharing, triggers DLP. 
The policy violation check did not validate against the existence of attachments 
Teams side: 
Send a message with message content and drag and drop an image.
Edit the message to delete the message content. 
CallWithChatComposite:
Message should display as expected

[Chat] Inline image displayed DLP

---

change-beta/@azure-communication-react-c5f6e075-2be5-419d-aab6-1b5fd99a9644.json
change/@azure-communication-react-c5f6e075-2be5-419d-aab6-1b5fd99a9644.json
packages/calling-stateful-client/src/Converter.ts

Set hide attendee name option to 'False' until replaced by SDK
https://skype.visualstudio.com/SPOOL/_workitems/edit/3563552

Set hide attendee name option to 'False' until replaced by SDK

---

change-beta/@azure-communication-react-d9aca1ca-75ba-4151-a46c-4250ca29f78f.json
change/@azure-communication-react-d9aca1ca-75ba-4151-a46c-4250ca29f78f.json
samples/Server/src/lib/envHelper.ts

envhelper returns/errors early if appsettings.json doesn't exist on an azure hosted instance.

Resolve issue with appsettings.json error

---

change-beta/@azure-communication-react-768ea75f-4ebc-45d0-8586-516c5f93cfe9.json
change/@azure-communication-react-768ea75f-4ebc-45d0-8586-516c5f93cfe9.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
packages/acs-ui-common/package.json
packages/calling-component-bindings/package.json
packages/calling-stateful-client/package.json
packages/chat-component-bindings/package.json
packages/chat-stateful-client/package.json
packages/communication-react/package.json
packages/fake-backends/package.json
packages/react-components/package.json
packages/react-composites/package.json
packages/storybook/package.json

Updated minor version of microsoft/api-extractor version to 7.40.6 when running the command `rush upgrade-interactive` for the communication-react package, and selected dependency microsoft/api-extractor.
OCE task of updating UI library https://skype.visualstudio.com/SPOOL/_wiki/wikis/SPOOL.wiki/47006/Updating-Dependencies?anchor=review-rush-available-updates
Ran `rush update:full && rush build:all-flavors` and testing if CI will pass here

Update minor version of microsoft/api-extractor version to 7.40.6

---

change/@azure-communication-react-678df3f7-61a2-47ba-8113-6d292930a836.json
packages/communication-react/CHANGELOG.beta.md
packages/communication-react/review/beta/communication-react.api.md
packages/react-components/review/beta/react-components.api.md
packages/react-components/src/components/MentionPopover.tsx

Mention popover API was missing a type definition

Cherry Pick PR 4183 into release branch

---

change-beta/@azure-communication-react-59eec3cf-e49f-41a8-85b2-ebe38a4ea973.json
change/@azure-communication-react-59eec3cf-e49f-41a8-85b2-ebe38a4ea973.json
packages/chat-component-bindings/src/messageThreadSelector.ts
packages/react-components/src/components/MessageThread.test.tsx
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts

Add more CCs for inline image. That way, when we generate API views for beta-release by putting inline image and image overlay features to the in progress features, the build would not fail

[Chat] Add more CCs for inline image beta-release build

---

change-beta/@azure-communication-react-45c5859b-a0f7-4174-861c-0ba461ebf681.json
change/@azure-communication-react-45c5859b-a0f7-4174-861c-0ba461ebf681.json
packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx
packages/react-components/src/components/ChatMessage/MentionRenderer.tsx
packages/storybook/stories/MessageThread/snippets/MessageWithCustomMentionRenderer.snippet.tsx

This fix is only for Contosos who're not using the onRenderMention callback, or in the onRenderMention callback, directly returns the defaultOnMentionRender.
For Contosos who wraps the defaultOnMentionRender in another element, they also need to set the key to the wrapper component as shown in our Storybook page:
```
displayOptions: {
onRenderMention: (mention, defaultOnMentionRender) => {
return <button key={Math.random().toString()}>{defaultOnMentionRender(mention)}</button>;
}
},
```

[Chat] Add key attr to MsftMention tag for Contosos who uses the defaultOnMentionRender

---

change-beta/@azure-communication-react-44cd578f-f084-4d4e-9c9a-8c58fde157f2.json
change/@azure-communication-react-44cd578f-f084-4d4e-9c9a-8c58fde157f2.json
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts

As per gitissue: https://github.com/Azure/communication-ui-library/issues/4209
Metadata was not being sent downstream to the handlers. 
When the options property was missing we were incorrectly dropping the metadata argument. 
as per git issue: https://github.com/Azure/communication-ui-library/issues/4209

[Chat] UpdateMessage not sending metadata

---

change-beta/@azure-communication-react-2d4cbac7-aa49-4ce4-a5ea-8bcc25602f9c.json
change/@azure-communication-react-2d4cbac7-aa49-4ce4-a5ea-8bcc25602f9c.json
packages/react-components/src/components/CaptionsSettingsModal.tsx

Fixed bug where spoken and caption language show up empty on initiation 

Fixed bug where spoken and caption language show up empty on initiation 

---

change/@azure-communication-react-d2ee527f-6fd5-45c6-9081-7ad8c09d2e40.json
common/scripts/changelog/change.mjs
common/scripts/changelog/check.mjs

- If change log type is none - do not duplicate the change file - one is sufficient.
- If change log type is prerelease - delete the stable changelog - it is not relevant to stable release.
- Reduce PR noise.
- Improve stable changelog generation.
- Tested `rush changelog` with all 4 change types.
- Have **not** tested CI action as it v. difficult locally - please scrutinize changes here in this review. This CI run will at least test the none passes the CI successfully.
Adding two chat and two calling devs for review

Only generate one change file if change type is none or prerelease

---

change-beta/@azure-communication-react-f0b19205-a257-486a-b592-4b8ea9130a39.json
change/@azure-communication-react-f0b19205-a257-486a-b592-4b8ea9130a39.json
packages/chat-component-bindings/src/messageThreadSelector.ts
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-components/review/beta/react-components.api.md
packages/react-components/review/stable/react-components.api.md
packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx
packages/react-components/src/components/FileDownloadCards.tsx
packages/react-components/src/components/ImageOverlay.tsx
packages/react-components/src/components/MessageThread.tsx
packages/react-components/src/theming/themes.ts
packages/react-composites/review/beta/react-composites.api.md
packages/react-composites/review/stable/react-composites.api.md
packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts

- When adding the feature flag to stabilizedFeatures, the flags that combined with other flags are not generated correctly.
This PR is to remove the inlineImage ones
- Change beta to public
- Rename the inlineImage type of ChatAttachmentType into image to align with ChatSDK

[Chat] Remove inline image CCs that's combined with other flags

---

change/@azure-communication-react-d20fa102-7159-4cd6-aecf-1493fcad9972.json
packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx

In the case of errors the image gallery should display a broken img icon
Regression when introducing the new error scenarios 
When launching the img gallery, mock no network connection in the network tab. 

[Chat] Bug fix for the image gallery not displaying the broken img

---

change-beta/@azure-communication-react-db28d87d-f40a-4ef9-904f-c1f1c5429adb.json
change/@azure-communication-react-db28d87d-f40a-4ef9-904f-c1f1c5429adb.json
packages/calling-stateful-client/src/CallContext.ts
packages/calling-stateful-client/src/CallSubscriber.ts
packages/calling-stateful-client/src/PPTLiveSubscriber.ts

Need to stop the local screen share when remote pptlive is active 
Web calling SDK is missing this logic which will include in the next release as well 
TODO: Need to refactor after the next release is ready. 

[Calling][Bug] Fix the local screen share and PPTLive Conflict

---

change-beta/@azure-communication-react-723875ce-ed0a-456a-a98d-97d2cbb83df5.json
change-beta/@azure-communication-react-b4bd7243-4950-4fee-b9c5-6c42c93b84a4.json
change/@azure-communication-react-723875ce-ed0a-456a-a98d-97d2cbb83df5.json
change/@azure-communication-react-b4bd7243-4950-4fee-b9c5-6c42c93b84a4.json
common/config/babel/features.js
packages/calling-stateful-client/review/beta/calling-stateful-client.api.md
packages/calling-stateful-client/review/stable/calling-stateful-client.api.md
packages/calling-stateful-client/src/CallClientState.ts
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md

Release note for PPTLive  GA
We are excited to announce that the Azure Communication Services Web UI Library now can view PowerPoint Live sessions initiated by a Teams client. Users can follow along with the current slide the presenter is sharing and view presenter annotations. Developers can use this functionality today through our composites (e.g CallComposite, CallWithChatComposite) as well as through components (e.g VideoGallery).

[Calling] Release note for PPTLive  GA

---

GROOMME.md
packages/communication-react/CHANGELOG.stable.md

Changelog refinement for our stable release
We want to prune the changelog so developers can understand what bug fixes, features, and improvements they will have access to with 1.14.0
It would be helpful for people to mainly review the stable changelog in communication-react packlet
packages/communication-react/CHANGELOG.stable.md

Groom changelog /1.14.0

---

change-beta/@azure-communication-react-04072408-0390-46c8-b8ce-1aa004cf6dae.json
change-beta/@azure-communication-react-9ee3f1a0-b296-45d4-b15a-5ab2c0a067e2.json
change/@azure-communication-react-04072408-0390-46c8-b8ce-1aa004cf6dae.json
change/@azure-communication-react-9ee3f1a0-b296-45d4-b15a-5ab2c0a067e2.json
packages/chat-component-bindings/src/messageThreadSelector.ts
packages/chat-stateful-client/review/beta/chat-stateful-client.api.md
packages/chat-stateful-client/review/stable/chat-stateful-client.api.md
packages/chat-stateful-client/src/ChatContext.ts
packages/chat-stateful-client/src/types/ChatMessageWithStatus.ts
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx

For the new ResourceFetchResult making sourceUrl optional in the case of an error
In the case of an error `undefined` is sent back up from the stateful client instead of an ''
Test inline images and in the network tab turn off network while making call

[Chat] Making sourceUrl optional

---

change-beta/@azure-communication-react-1606ed6b-b308-4259-85d6-4e742ed2e4ae.json
change/@azure-communication-react-1606ed6b-b308-4259-85d6-4e742ed2e4ae.json
packages/react-components/src/components/VideoGallery/utils/videoGalleryLayoutUtils.ts
packages/react-components/src/gallery/dominantSpeaker.test.ts
packages/react-components/src/gallery/dominantSpeaker.ts

- Fix dominant speakers to be placed in first page of overflow gallery (commit: https://github.com/Azure/communication-ui-library/pull/4276/commits/e70dc8941f2f6bf2b469bc8239d1620343b0a36f)
- Clean up useOrganizedParticipants hook (commit: https://github.com/Azure/communication-ui-library/pull/4276/commits/9d3840145e34510268c55fa636e13fafe04762ad)
https://skype.visualstudio.com/SPOOL/_workitems/edit/3575666
Local calling sample testing:
https://github.com/Azure/communication-ui-library/assets/79475487/596de893-d783-4943-beb9-ca90d6136dc4

Fix dominant speakers to be placed in first page of overflow gallery

---

change/@azure-communication-react-0fff92fd-8d3f-4441-a5d5-d1e83a03fe3a.json
packages/react-composites/tests/browser/call/hermetic/VideoGallery.test.ts

Ensure first menu item is focused so that VideoGallery UI test is stable
https://skype.visualstudio.com/SPOOL/_workitems/edit/3607280
Tested by focusing on second menu item and it worked

Stabilize video gallery UI test

---

change-beta/@azure-communication-react-30ceae58-a866-4095-8c53-86fef5c19b5d.json
change/@azure-communication-react-30ceae58-a866-4095-8c53-86fef5c19b5d.json
packages/react-composites/src/composites/common/PeoplePaneContent.tsx

Fix the absence of remove participant drawer menu item in group calls and interop due to the capability for removeParticipant being undefined.
Bug introduced from my PR: https://github.com/Azure/communication-ui-library/pull/4312/files#diff-f58bdd76c9f8e75269e3e181a242a9e249fa15c77497d9cfddbe0c93f051c295R72
Remove participant menu item is not showing up on mobile during bug bash for 1.15.0-beta.1 release
Verified the fix on Android phone

Fix missing remove participant drawer menu item

---

packages/communication-react/CHANGELOG.beta.md

Update beta 1.5.0-beta.1 changelog to exclude pptlive
Team has decided to pull out pptlive from 1.5.0-beta.1 release
Just a changelog update. No testing needed

Update beta 1.5.0-beta.1 changelog to exclude pptlive

---

change-beta/@azure-communication-react-e07ac585-a2a7-490b-9b4c-41edf4847a6e.json
change/@azure-communication-react-e07ac585-a2a7-490b-9b4c-41edf4847a6e.json
packages/react-components/src/components/AttachmentDownloadCards.tsx
packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx

Fixed the issue where live messages don't announce file attachments
A11Y bug fix
there are 3 scenarios:
- message with attachments only and no content
- message with attachments and text content
- message with attachments and image content

[Chat] Announce File Attachments in New Messages

---

change-beta/@azure-communication-react-df23adda-292c-4c34-b37a-8315971a735f.json
change/@azure-communication-react-df23adda-292c-4c34-b37a-8315971a735f.json
packages/react-components/src/components/VideoTile.tsx
packages/react-components/src/components/styles/VideoGallery.styles.ts

- Delete original logic adding overlay
- Add the observer to add tabIndex to iframe to avoid the keyboard navigation 

[Calling][Bug] Fix PPTLive Keyboard navigation 

---

change/@azure-communication-react-b13010d5-a240-4452-81e7-01aefadef278.json
packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBoxPicker.tsx
packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
packages/react-components/src/components/ErrorBoundary.tsx
packages/react-components/src/components/MessageThread.tsx
packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx

Add import for the edit box in MessageThread to load RoosterJS dependencies early
improve UX
Chat Sample app for 3g and 2g throttling.
To test:
- set `richTextEditor` to true in ChatScreen (composites folder) for MessageThread component 
- start the Chat sample app. 
- enable throttling
- check that when `richTextEditor` = true, an additional js file is loaded for rich text editor and rich edit box is loaded during message edit without any delays.

[RTE] Updated how RoosterJS dependencies are loaded for MessageThread

---

change-beta/@azure-communication-react-7eb8d133-2621-4733-8d1d-40f6110430aa.json
change/@azure-communication-react-7eb8d133-2621-4733-8d1d-40f6110430aa.json
samples/Server/src/routes/uploadToAzureBlobStorage.ts

This PR fixes the issue where sample app failed to upload the completed files to azure blob. 
it was getting the first batch of array buffer (15 bytes) instead of a completed buffer
clone this PR
provide connection string for communication and azure blob
go to chat sample
upload a valid file
download it to confirm it's still valid

[Chat] Fix Sample App Uploading Incomplete File

---

change/@azure-communication-react-822d1d28-ec07-459a-838e-b38cb01d5e5f.json
packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx

- Fix for an issue where focus is set incorrectly for Safari
Steps:
In Safari: 
- Open toolbar
- Increase indentation and enter some text
- Hide toolbar
Expected/Current result: cursor should be at the end of the text
Previous result: cursor is before the text
Storybook in Chrome/Safari/Edge

[RTE] Fix for an issue where focus is set incorrectly for Safari

---

packages/react-components/src/components/ChatMessage/MessageComponents/ChatMessageComponentAsMessageBubble.tsx
packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponentAsMessageBubble.tsx
packages/react-components/src/components/styles/MessageThread.styles.ts

- Add missed styles for tables in my message component
- create a common styles to reuse between messages and my messages
CallWithChatComposite and storybook

[RTE] Add styles for tables in my message component

---

change/@azure-communication-react-cf02895f-28af-4425-ad05-042fb83f20cd.json
packages/react-components/src/components/styles/RichTextEditor.styles.ts

Fix an issue where the insert table grid was shown incorrectly when zoom is less than 100%
Previously:
Now: 
Storybook + different browser with different zoom value

[RTE] Table insert menu fix when zooming in or out

---

change-beta/@azure-communication-react-f37ae78c-b007-4768-9d4f-4fefdefdb7d7.json
packages/storybook/stories/ClosedCaptions/ClosedCaptions.stories.tsx
packages/storybook/stories/Survey/Survey.stories.tsx

Move survey and captions to storybook concept page 

Move survey and captions to storybook concept page 

---

change-beta/@azure-communication-react-ad973b68-7c17-42c1-8545-6c23b7c4aadc.json
change/@azure-communication-react-ad973b68-7c17-42c1-8545-6c23b7c4aadc.json
packages/react-components/src/components/styles/MessageThread.styles.ts

- fluentui contrib set default max width value to 1056px, this PR resets it to 100% of the containing block's width so the containing component can set the value. This value can also be updated by Contoso by setting `chatContainer` in `styles` prop for `MessageThread`.
Storybook and Chat.
To test this:
- for Chat Composite, find the component that has maxWidth =  41.25 rem (CHAT_CONTAINER_MAX_WIDTH_REM) and disble it
- for MessageThread update `MessageThreadStoryContainerStyles` to
```
export const MessageThreadStoryContainerStyles = {
width: '100%',
height: '100%',
maxWidth: '100%', // or any other value
padding: '1rem'
};
```

[Chat] Fix default constant maxWidth value for fluent chat components

---

change-beta/@azure-communication-react-eea4451a-68af-4a1d-922c-77adaa3bb833.json
change/@azure-communication-react-eea4451a-68af-4a1d-922c-77adaa3bb833.json
packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx

When incoming messages contain encoded HTML entities such as `&amp`, it would be passed to aria-label as is without any formatting and it would cause confusion to the user since they are not supposed to be announced directly, we should decode them first, then pass it over to aria-label.
|before | after |
|---------|---------|
|        <img width="332" alt="Screenshot 2024-04-25 at 12 20 27 AM" src="https://github.com/Azure/communication-ui-library/assets/109105353/af790315-d2cf-4797-85bb-80dab71cc547">|       <img width="358" alt="Screenshot 2024-04-25 at 12 21 32 AM" src="https://github.com/Azure/communication-ui-library/assets/109105353/7c24b40e-6b31-45a8-90a5-7670dad6ac91">|
reported by A11y team
1. run the storybook sample
2. join a meeting
3. send couple of inline images from teams …

[Chat] Sanitize Message Content for Aria Label

---

change-beta/@azure-communication-react-1d59fe3a-65d3-45a6-bee8-01c68420eb06.json
change/@azure-communication-react-1d59fe3a-65d3-45a6-bee8-01c68420eb06.json
packages/react-components/src/components/InputBoxButton.tsx
packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
packages/react-components/src/components/SendBox.tsx
packages/react-components/src/components/utils/SendBoxUtils.ts

Fix an accessibility issue where a send box button disabled state wasn't announced. `aria-disabled` prop is used for this and different screen readers may announce this state in different ways. For example, Narrator on Windows might say "dimmed", while VoiceOver on macOS might say "dimmed" or "disabled". This is determined by the screen reader software and is not something that can be changed from the web page.
Stoybook, Chat sample app

Fix an accessibility issue where a send box button disabled state wasn't announced

---

packages/storybook/stories/MessageThread/MessageThread.stories.tsx

[Cherry-pick] Add documentation to indicate the RTE edit box doesn't support mention

---

change-beta/@azure-communication-react-2f860295-be05-4ebd-99da-6de2c1361d33.json
change/@azure-communication-react-2f860295-be05-4ebd-99da-6de2c1361d33.json
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/common-versions.json
common/config/rush/variants/stable/pnpm-lock.yaml
packages/calling-component-bindings/package.json
packages/calling-stateful-client/package.json
packages/communication-react/package.json
packages/react-composites/package.json
packages/storybook/package.json
packages/storybook8/package.json
samples/CallWithChat/package.json
samples/Calling/package.json
samples/ComponentExamples/package.json
samples/StaticHtmlComposites/package.json
samples/tests/package.json

Update `@azure/communication-calling` to `1.24.1` for stable builds and `1.24.2-beta.1` for beta builds
Has support for short meeting URLs amongst other things.
CI only

Update @azure/communication-calling to 1.24.1 and 1.24.2-beta.1

---

packages/react-composites/src/composites/common/SidePaneHeader.tsx

Add aria-level which is required when role="heading" is set
accessibility requirement with heading roles

[bugfix][a11y] Add aria level to sidepane header with role heading

---

packages/storybook8/.storybook/main.ts
packages/storybook8/stories/Components/MessageThread/MessageThread.mdx
packages/storybook8/stories/Components/MessageThread/MessageThread.story.tsx
packages/storybook8/stories/Components/MessageThread/index.stories.tsx
packages/storybook8/stories/Components/MessageThread/snippets/CustomBlockedMessage.snippet.tsx

Add ability to show/hide stories in the layout tree; implement MessageThread stories
Allows show/hide of storybook stories via naming `*DocsOnly`
Breaks out snippets of `MessageThread` to showcase properly

[Storybook 8] MessageThread updates and story visibility control

---

change-beta/@azure-communication-react-fd1835e0-c025-40f4-8268-e05e3ca0bcbf.json
change/@azure-communication-react-fd1835e0-c025-40f4-8268-e05e3ca0bcbf.json
packages/react-components/src/components/styles/MessageThread.styles.ts

|Previously|Now|
|---|---|
|![image](https://github.com/Azure/communication-ui-library/assets/98852890/37ae1cc9-3e92-451e-a43d-59d494e27c44)|![image](https://github.com/Azure/communication-ui-library/assets/98852890/10028849-12aa-4047-9c93-e09ab6b48935)|

Fix width for code snippets sent in messages

---

change-beta/@azure-communication-react-65051319-8cfd-4640-8453-20b68de47ab8.json
change/@azure-communication-react-65051319-8cfd-4640-8453-20b68de47ab8.json
packages/react-components/src/components/ReactionButton.tsx

Add aria labels to each of the reaction items
Allows for the different narrators to read out each name
https://skype.visualstudio.com/SPOOL/_workitems/edit/3674307

[A11y bugfix] reaction item aria narration

---

change-beta/@azure-communication-react-709b49ae-fd98-4efd-9a58-645221215a26.json
change/@azure-communication-react-709b49ae-fd98-4efd-9a58-645221215a26.json
packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx

- process anchor elemets and updatehow the links will be opened 
CallWithChat sample app. To test:
- create a loop component
- create a Teams meeting
- join it
- - open a loop component from loop.microsoft.com page
- share it (try both options) 
- the link should always be opened in a new tab

Fix for an issue where links were opened in the same tab

---

change-beta/@azure-communication-react-e5b907bd-8132-45e5-9417-690d3c85acc6.json
change/@azure-communication-react-e5b907bd-8132-45e5-9417-690d3c85acc6.json
packages/react-components/src/components/ErrorBar.tsx

Resolve screen narrator missing context for button

[A11y] Add context to error bar close button

---

change-beta/@azure-communication-react-df473728-79d9-43a2-a609-34c30d17ca0b.json
change/@azure-communication-react-df473728-79d9-43a2-a609-34c30d17ca0b.json
packages/react-components/src/theming/v9ThemeShim.ts

Fix A11y issue for the [ticket
](https://skype.visualstudio.com/SPOOL/_workitems/edit/3740660)
The v9 theme pattern has the correct schema based on Alex P's input. So remove the v8 color theme overwrite in the token. 

[A11y][chat]Remove theme8 color palette for <Link>

---

packages/react-components/src/components/ReactionButton.tsx

Change reactions button to actionable divs and add roles
Accessibility requirements that do not allow buttons to be children nor menuitems under a menu parent

[bugfix][a11y] Add reactions role and change Reactions button to div

---

change-beta/@azure-communication-react-cc2ef409-ce98-484f-8b0e-d047cc26af08.json
change/@azure-communication-react-cc2ef409-ce98-484f-8b0e-d047cc26af08.json
packages/chat-component-bindings/src/handlers/createHandlers.ts

when sending messages with attachments via RTE, raw HTML would be sending out and this PR address this issue:
|   before |   after |
|-----|-----|
| <img width="314" alt="image" src="https://github.com/Azure/communication-ui-library/assets/109105353/8a04aefb-5a60-45a1-b36b-83a176ba4031"> |  <img width="314" alt="image" src="https://github.com/Azure/communication-ui-library/assets/109105353/f7f3071d-5afc-4e18-bb7b-d70a36d12a42"> | 
bug fix
sample app
enable RTE
send a message with any attachments

[Chat] Fixed the issue where RTE doesn't send HTML messages if there are attached files

---

change-beta/@azure-communication-react-6d999d69-0527-4c82-96c8-3dd5dded13a2.json
change/@azure-communication-react-6d999d69-0527-4c82-96c8-3dd5dded13a2.json
packages/react-components/src/components/ParticipantList.tsx

Fix missing pinned icon when it is the only icon by updating logic for onRenderIcon prop in ParticipantList
https://skype.visualstudio.com/SPOOL/_workitems/edit/3765795
Testing locally on CallWithChat app

[Beta blocking] Fix missing pinned icon when it is the only icon

---

change-beta/@azure-communication-react-1f618629-3200-482d-8f7e-d013383f6b8c.json
change/@azure-communication-react-1f618629-3200-482d-8f7e-d013383f6b8c.json
packages/react-components/src/components/InputBoxButton.tsx
packages/react-components/src/components/RichTextEditor/RichTextInputBoxComponent.tsx

Show richTextEditor should indicate to Voice Over whether its expanded or collapsed.

[RTE][A11Y] Resolve A11Y issue where show richTextEditor button didn't have aria-expanded attribute

---

change-beta/@azure-communication-react-d66256a5-944b-4963-b815-254ca8594d91.json
change/@azure-communication-react-d66256a5-944b-4963-b815-254ca8594d91.json
packages/react-components/src/components/styles/RichTextEditor.styles.ts

As part of new A11Y guidelines, button size must be a minimum of 24x24.

[RTE][A11Y] Resolve A11Y issue around rich text editor table size selection buttons.

---

change-beta/@azure-communication-react-ef9e339c-0b46-428e-93b5-28a479eddf65.json
change/@azure-communication-react-ef9e339c-0b46-428e-93b5-28a479eddf65.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-composites/src/composites/CallComposite/components/buttons/EndCall.tsx
packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
packages/react-composites/src/composites/common/types/CommonCallControlOptions.tsx
samples/Calling/src/app/views/CallCompositeContainer.tsx

Introduces new API to hide the end call modal
Allows the user to end the call without the prompt if configured correctly
https://skype.visualstudio.com/SPOOL/_workitems/edit/3767128

[End Call options] Add option to hide the end call prompt

---

packages/storybook8/stories/Components/MessageStatusIndicator/Docs.mdx
packages/storybook8/stories/Components/MessageStatusIndicator/MessageStatusIndicator.story.tsx
packages/storybook8/stories/Components/MessageStatusIndicator/index.stories.tsx
packages/storybook8/stories/Components/MessageStatusIndicator/snippets/MessageStatusIndicator.snippet.tsx

Migrating to new storybook v8 
Migration
in `packages/storybook8` 
run `rushx start`

[Storybook] Introduce MessageStatusIndicator component to storybook v8

---

change-beta/@azure-communication-react-afc2afcd-8293-436e-a619-de53bd78b010.json
change/@azure-communication-react-afc2afcd-8293-436e-a619-de53bd78b010.json
packages/react-composites/src/composites/common/ParticipantContainer.tsx

- Update Participant pane title to h2 heading
- Accessibility requirement https://skype.visualstudio.com/SPOOL/_workitems/edit/3741235

[A11y][Chat] Update Participant pane title to h2 heading

---

change-beta/@azure-communication-react-79a14e38-b554-456d-b853-44e099501e51.json
change/@azure-communication-react-79a14e38-b554-456d-b853-44e099501e51.json
packages/react-components/src/components/RichTextEditor/Plugins/PlaceholderPlugin.tsx

When editing a message with a large amount text, the placeholder fails to hide.

[RTE] Resolve issue where placeholder didn't always hide.

---

change-beta/@azure-communication-react-c115b8a8-0e97-4435-a191-627982b65631.json
change/@azure-communication-react-c115b8a8-0e97-4435-a191-627982b65631.json
packages/acs-ui-common/src/common.ts
packages/react-components/src/components/ResponsiveHorizontalGallery.tsx
packages/react-components/src/components/ResponsiveVerticalGallery.tsx
packages/react-components/src/components/utils/responsive.ts
samples/Calling/src/app/views/CallCompositeContainer.tsx

Fix vulnerability of having NaN from calculations in horizontal or vertical overflow gallery. Function `parseFloat` can return NaN according to the documentation
To resolve an issue EZRA is experiencing when HorizontalGallery is present where the composite crashes when it is re-rendered.
Could not reproduce issue on my side because EZRA is using an Angular wrapper around our composite. 
Confirmed with EZRA that they are seeing NaN when children per page is being calculated for the horizontal gallery.

Fix vulnerability of having NaN from calculations in overflow gallery

---

samples/Calling/src/app/App.tsx

* Make targetCallee to undefined when it is not set

Set targetCallee to undefined in sample when it is not set (#4857)

---

packages/storybook8/stories/Components/GettingStarted/Docs.mdx
packages/storybook8/stories/Components/GettingStarted/snippets/App.snippet.tsx
packages/storybook8/stories/Components/GettingStarted/snippets/CallingComponents.tsx
packages/storybook8/stories/Components/GettingStarted/snippets/ChatComponents.tsx
packages/storybook8/stories/Components/GettingStarted/snippets/CompletedComponentsApp.story.tsx
packages/storybook8/stories/Components/Overview.mdx

- Migrate top level Components pages to storybook8: : Overview, Get Started
- Known issue
- styling issue for Get Started story

Migrate top level Components pages to storybook8

---

change-beta/@azure-communication-react-314ab8c9-a41f-4f74-bbd4-3c31d086f35a.json
change/@azure-communication-react-314ab8c9-a41f-4f74-bbd4-3c31d086f35a.json
packages/react-composites/src/composites/CallComposite/utils/TrackCapabilityChangedNotifications.ts

Stop showing initial notifications of capabilities being present when joining a call
Note: the work to move these old style notifications to the the improved notifications is to be done in the future
https://skype.visualstudio.com/SPOOL/_workitems/edit/3811980
Tested in CTE scenario in stable where the bug above was originally reproduced and verified that the fix works. 
Also verified that mid-call role changes in ACS Teams meeting and Rooms calls still produced notifications for loss/gain of mic, audio, and screen share capabilities

Stop showing initial notifications of capabilities being present when joining a call

---

packages/react-composites/src/composites/ChatComposite/ImageUpload/ImageUploadUtils.tsx

- Store the image upload respond id under the image src attribute and when send, replace it internal message id using the image src attribute
- We cannot add a new prop to store the response id under AttachmentMetaData because currently we use the metadata.id and metadata.url to calculate the length of the content string and displaying message too long errors

[Chat] Store the image upload respond id under the image src attribute

---

packages/acs-ui-common/src/constants.ts
packages/acs-ui-common/src/index.ts
packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx
packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
packages/react-composites/src/composites/ChatComposite/ImageUpload/ImageUploadUtils.tsx
packages/react-composites/src/composites/common/constants.ts
packages/storybook/stories/MessageThread/MessageThread.stories.tsx
packages/storybook/stories/SendBox/RichTextSendBox.stories.tsx
packages/storybook8/stories/Components/MessageThread/MessageThread.story.tsx

Rooster doesn't not provide clipboard data for redo images.
Need to read it from the imageAttributes

[Chat]Get image file name for redo images

---

packages/storybook8/stories/Composites/CallWithChatComposite/BasicExample.stories.tsx
packages/storybook8/stories/Composites/CallWithChatComposite/Docs.mdx
packages/storybook8/stories/Composites/CallWithChatComposite/JoinExample.stories.tsx
packages/storybook8/stories/Composites/CallWithChatComposite/Utils.tsx
packages/storybook8/stories/Composites/CallWithChatComposite/snippets/CallWithChat.snippet.tsx
packages/storybook8/stories/Composites/CallWithChatComposite/snippets/CallWithChatWithErrorChecks.snippet.tsx
packages/storybook8/stories/Composites/CallWithChatComposite/snippets/Server.snippet.tsx
packages/storybook8/stories/controlsUtils.ts

Added in CallWithChat stories
- had to hide additional controls on the ControlUtils
- can't  create multi line string variables so I had to do inline multi line strings in source components
- most of the links are broken since we don't seem to use ids anymore

[Storybook8Migration] adding in callWithChat stories

---

common/config/package.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
common/scripts/changelog/change.mjs
common/scripts/changelog/changelog.mjs
common/scripts/changelog/check.mjs
common/scripts/changelog/collect.mjs
common/scripts/changelog/constants.mjs

- Update beachball version to `2.44.0` that has  `changeDir` options from https://github.com/microsoft/beachball/pull/969
- Stop moving files from `change-beta` to `change` and instead use the `changeDir` option
Our changelogs weren't grabbing the correct PR. Once the file was moved from change-beta to change, it no longer had any associated commit behind it.
Generated both stable and beta changelogs locally and they pulled commits and PRs

Fix missing PR links in changelogs - Update to use new `changeDir` option in beachball

---

change-beta/@azure-communication-react-cc8ce792-335e-4d9c-a07a-84eedc869f5e.json
change/@azure-communication-react-cc8ce792-335e-4d9c-a07a-84eedc869f5e.json
packages/chat-component-bindings/src/baseSelectors.ts
packages/chat-component-bindings/src/messageThreadSelector.ts

1. Change type return of getReadReceipt base selector
2. Avoid potentially calling filter when readReceipts is undefined
When I initialize a new chat adapter for my breakout rooms feature I get this error:
Fixed the above error with fix.

Read receipts selector fix

---

change-beta/@azure-communication-react-338b3032-95c2-4539-9187-37939d37c21e.json
change/@azure-communication-react-338b3032-95c2-4539-9187-37939d37c21e.json
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts

Fix error when listening to spotlight and capabilities events for call with chat adapter
The following error shows when you subscribe to 'spotlightChanged' event of the AzureCommunicationCallWithChatAdapter
Similar error is shown for 'capabilitiesChanged' event
Verified listening to 'spotlightChanged' and 'capabilitiesChanged' in local CallWithChat works in this video:
https://github.com/user-attachments/assets/c6d7984f-9435-4c74-8df3-7d5015ab57c8

Fix error when listening to spotlight and capabilities events for call with chat adapter

---

packages/calling-stateful-client/src/BreakoutRoomsSubscriber.ts
packages/calling-stateful-client/src/CallContext.ts
packages/communication-react/review/beta/communication-react.api.md
packages/react-composites/src/composites/CallComposite/Strings.tsx
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
packages/react-composites/src/composites/CallComposite/components/Banner.tsx
packages/react-composites/src/composites/CallComposite/components/BreakoutRoomsBanner.tsx
packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
packages/react-composites/src/composites/CallComposite/utils/Utils.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx

1. Add mobile banner for breakout rooms based on [Figma](https://www.figma.com/design/HsKBeDvhCvWobK11FNQfJ9/ACS-UI---Breakout-Rooms?node-id=72-3031&t=zdwqFeYBGUOgrzgI-0)
2. Handle scenario of being unassigned from breakout room
3. Hide join breakout room button when already automatically being moving to breakout room to prevent joining breakout room twice
Breakout rooms feature for beta
Local CallWithChat sample test:
https://github.com/user-attachments/assets/8b4eb5ae-9968-4d82-8c18-8b620a340acb

Add mobile banner for breakout rooms and handle scenario of being unassigned from breakout room

---

change-beta/@azure-communication-react-67710a93-6800-43e9-a606-6e6ea98a2fbf.json
change/@azure-communication-react-67710a93-6800-43e9-a606-6e6ea98a2fbf.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
packages/react-composites/src/composites/CallComposite/adapter/index.ts
packages/react-composites/src/composites/CallComposite/index.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts

- Add new options to adapter.startCaptions and adapter.stopCaptions
- Options allow starting captions in the background without showing the UI
- Added captions start tracking properties to adapter callcontext
- Added a state modifier on setState of the callcontext to use the private captions start tracking properties to not show the captions UI in the composite
Customer request
Ran locally, tested:
- `adapter.startCaptions({ startInBackground: true })` starts captions silently and can listen to adapter state to track captions
- `adpater.startCaptions()` shows UI. As does starting captions from the UI
- `adapter.stopCaptions()` stops UI but keeps captions running only iff `adapter.startCaptions({ startInBackground: true })` has been previously called
- UI stop captions has the same …

Add API to start captions in the background

---

change-beta/@azure-communication-react-7723b22c-642d-4bff-878b-320062337d13.json
change/@azure-communication-react-7723b22c-642d-4bff-878b-320062337d13.json
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/common-versions.json
common/config/rush/variants/stable/pnpm-lock.yaml
packages/calling-component-bindings/package.json
packages/calling-stateful-client/package.json
packages/communication-react/package.json
packages/react-composites/package.json
packages/storybook/package.json
packages/storybook8/package.json
samples/CallWithChat/package.json
samples/Calling/package.json
samples/CallingStateful/package.json
samples/ComponentExamples/package.json
samples/StaticHtmlComposites/package.json
samples/tests/package.json

Update communication calling to 1.29.1-beta.1 and 1.28.1
OCE task to ensure we have the latest from calling SDK
Smoke tested CallWithChat sample app for beta and stable in group and teams meetings

Update calling sdk versions

---

packages/storybook8/stories/Components/MessageStatusIndicator/snippets/MessageStatusIndicator.snippet.tsx

As per discussion during bug bash: Added comment to let developers know they should only call these methods once. 
Update code snippet sample

[Storybook] Update instructions message status indicator

---

change-beta/@azure-communication-react-436f776c-1408-435c-88f8-4d864c2e0c95.json
change/@azure-communication-react-436f776c-1408-435c-88f8-4d864c2e0c95.json
packages/react-composites/src/composites/CallComposite/components/BreakoutRoomsBanner.tsx
packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx

Refactor logic of showing button to join breakout room when the breakout room call is available
The new logic is more correct and does not rely on notifications
Tested in local callwithchat app:
https://github.com/user-attachments/assets/dabc72ff-d80b-40cb-9afe-a5ba69b074ed

Refactor logic to show join breakout room button

---

change-beta/@azure-communication-react-1109da55-934d-4ff6-be59-5b3ef01e4d27.json
change/@azure-communication-react-1109da55-934d-4ff6-be59-5b3ef01e4d27.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
samples/Chat/package.json

There's still another sub-dependency that's using axios <1.7.4. I've submitted a Github issue on their repo:
https://github.com/playwright-community/jest-process-manager/issues/41 and a Github issue on the Storybook/test-runner side: https://github.com/storybookjs/test-runner/issues/510

Update axios to 1.7.5 with a security fix

---

change-beta/@azure-communication-react-e5231fa5-bfbb-4fde-8f01-2e9938d30f30.json
change/@azure-communication-react-e5231fa5-bfbb-4fde-8f01-2e9938d30f30.json
packages/react-composites/src/composites/CallComposite/components/SvgWithWordWrapping.tsx
packages/react-composites/src/composites/CallComposite/pages/ConfigurationPage.tsx

* Add Role to SvgWithWordWrapping
* Add heading role in ConfigurationPage use
Video of the Fix in action. Turn up audio to hear. Go to the Why section to see the original problem in video.
https://github.com/user-attachments/assets/69d2a14d-b8c7-400a-9976-69cf3a7a5d2c
* A11y bug where when using Windows narrator the SvgWithWordWrapping announces "Graphic" when focused. Should not announce Graphic and should announce heading. 
Graphic announced. Turn up audio to hear it in the video:
https://github.com/user-attachments/assets/c6eb1df0-5de4-4baa-856f-ae33599374e0
Window 11 Devbox

[A11y][bugfix] Add Role to SvgWithWordWrapping 

---

packages/react-composites/src/composites/CallComposite/components/buttons/EndCall.tsx

Wrap the end call button and the prompt for the options in a stack so that the parent doesn't try to put space between them.
The parent Stack for the CommonControlBar was adding space between the 0 sized span for the prompt's modal-anchor. 
https://skype.visualstudio.com/SPOOL/_workitems/edit/3870948
Validated locally, snapshots to update

[Ezra bug] Fix issue where end call button shifts to left

---

packages/storybook8/stories/Components/VideoGallery/Docs.mdx

- added Grid Layout link
- added additional backtick characters to highlight specific types 
Before:
After:

fixing documentation issues during video gallery migration around content sharing

---

change-beta/@azure-communication-react-3609656d-b6a9-4253-93ee-50eacf1719e2.json
change/@azure-communication-react-3609656d-b6a9-4253-93ee-50eacf1719e2.json
packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts

Issue found during OCE rotation! 
Today there is a race condition where `useAzureCommunicationChatAdapter` can be called twice, and if the second call happens before the adapter has been created by the first call, events can be missed / lost. 
The `AzureCommunicationCallAdapter` and `AzureCommunicationCallWithChatAdapter` already implement logic exactly like this one, so adding this missing logic to be consistent across all adapter methods. 
There is bug where:
- If user A joins an empty chat thread
- User B joins the chat thread 
- User A cannot see User B 
- User B can see User A
In this case, messages sent from User A are lost, but User A can still receive messages from User B 

[Chat] Flagging when the adapter is being created

---

packages/storybook8/stories/Components/ImageOverlay/Docs.mdx
packages/storybook8/stories/Components/MessageStatusIndicator/Docs.mdx
packages/storybook8/stories/Components/MessageThread/Docs.mdx
packages/storybook8/stories/Components/SendBox/RichTextSendBox/Docs.mdx
packages/storybook8/stories/Components/SendBox/SendBox/Docs.mdx
packages/storybook8/stories/Components/TypingIndicator/Docs.mdx

Fixing the padding around the canvas to match closer to storybook 6 
Padding look and feel issue

[Storybook] Fixing canvas padding in storybook components

---

packages/storybook8/stories/BetaBanners/ImportantBannerHeading.tsx
packages/storybook8/stories/Composites/ChatComposite/Docs.mdx

Beta banner i icon alignment was off
Extra padding between the title was incorrect

[Storybook] Fixing alignment and betabanner padding

---

packages/storybook8/stories/controlsUtils.ts

Hiding extra controls that cannot be interacted with. 
Match controls in current prod storybook

[Storybook8] Hiding the onFetchParticipantsMenuItems control from the stories

---

packages/communication-react/tsconfig.preprocess.json

fix build issues with beta-release build
enforces that when we pull the react composites package we make sure that we are only pulling in the public deps to communication react. otherwise the test packages will be included as a result of the new deps from acs-ui-javascript-loaders package
Built locally

[js-loaders] fix beta-release build

---

change-beta/@azure-communication-react-4a7eb3ab-7f30-4012-9a9a-d8813f2deaf0.json
change/@azure-communication-react-4a7eb3ab-7f30-4012-9a9a-d8813f2deaf0.json
packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx
packages/react-components/src/components/styles/MessageThread.styles.ts

| Messages | Before the update | After the update |
|------|--------|-------|
| ![image](https://github.com/user-attachments/assets/74324d43-efe0-4228-afc3-f03c05d249a3) | ![image](https://github.com/user-attachments/assets/145c15f2-1ac6-454a-ad15-a62dc66e6368) | ![image](https://github.com/user-attachments/assets/06bab2d5-ce0c-4032-9569-9f9f5bb01e79) |

[Chat] White spaces handling update for text messages in message components

---

change/@azure-communication-react-a33f45ab-78c2-4cc2-bc1d-426376fad0cc.json
packages/react-components/src/components/HorizontalGallery.tsx
packages/react-components/src/components/LocalVideoTile.tsx
packages/react-components/src/components/VerticalGallery.tsx
packages/react-components/src/components/VideoGallery.test.tsx
packages/react-components/src/components/VideoGallery/ScrollableHorizontalGallery.tsx

Cherry-pick #5240 into release branch 1.20.0-beta.1
Release blocking bug - https://skype.visualstudio.com/SPOOL/_workitems/edit/3904972
Not tested

[Cherry-pick] Fix runtime error when starting screenshare alone in a call (#5240)

---

samples/tests/StaticHtmlComposites/CompositeJavascriptTest.test.ts

- Don't wait for 1s, instead wait for selectors
Fixes #5253 
Ran locally and tests were passing when they weren't, CI will be a better test however

Add more robust checks to composite javascript tests to fix flakey tests

---

.github/workflows/deploy-storybook.yml

Ensure storybook8 is built instead of storybook6
We are migrating to s8, this is just a fix that was missed
Cannot test e2e, that'll happen right after beta release

Fix deploy command for storybook 8 prod deploy

---

samples/CallWithChat/src/app/views/RichTextEditorToggle.tsx
samples/Chat/src/app/RichTextEditorToggle.tsx

Set RTE toggle visual state to default to checked.

---

common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
common/scripts/prepare-package-json.js
packages/acs-ui-common/package.json
packages/acs-ui-javascript-loaders/package.json
packages/calling-component-bindings/package.json
packages/calling-stateful-client/package.json
packages/chat-component-bindings/package.json
packages/chat-stateful-client/package.json
packages/communication-react/package.json
packages/fake-backends/package.json
packages/react-components/package.json
packages/react-composites/package.json
packages/storybook8/package.json
samples/CallWithChat/package.json
samples/Calling/package.json
samples/CallingStateful/package.json
samples/Chat/package.json
samples/ComponentExamples/package.json
samples/Server/package.json
tools/check-treeshaking/package.json
tools/check-typescript-regression/package.json

Reverts Azure/communication-ui-library#5289

Revert "Fix random eslint errors "

---

common/config/rush/command-line.json
docs/contributing-guide/1. getting-set-up.md
docs/contributing-guide/6. submitting-a-pr.md
docs/infrastructure/rush.md
packages/react-composites/tests/README.md
samples/StaticHtmlComposites/README.md

- Add rush update:beta
- Update documentation to use `update:beta` instead of `update`
We've had confusion from local development flavors. We are encouraging these explicit commands help ensure that developers do not update the wrong flavor.
Tried using `RUSH_VARIANT` as well to allow rush update to detect the flavor and update the current variant when `rush update` is called but there is no way to ensure that env var is set after switching flavor (in the case where someone opens a new terminal window) so this is not a good solution
Ran locally

Add rush update:beta

---

common/config/babel/features.js
packages/acs-ui-common/src/common.ts
packages/chat-component-bindings/src/messageThreadSelector.ts
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/src/index.ts
packages/react-components/src/components/Attachment/AttachmentDownloadCards.tsx
packages/react-components/src/components/ChatMessage/ChatMessageComponentWrapper.tsx
packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx
packages/react-components/src/components/ChatMessage/MessageComponents/ChatMessageComponentAsMessageBubble.tsx
packages/react-components/src/components/ChatMessage/MessageComponents/FluentChatMessageComponent.tsx
packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsEditBoxPicker.tsx
packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx
packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponentAsMessageBubble.tsx
packages/react-components/src/components/ChatMessage/MyMessageComponents/FluentChatMyMessageComponent.tsx
packages/react-components/src/components/MessageThread.tsx
packages/react-components/src/components/utils/ChatMessageComponentUtils.tsx
packages/react-components/src/theming/icons.tsx
packages/react-components/src/types/ChatMessage.ts

Remove conditional-compile lines for file-sharing-teams-interop
Housekeeping. Cleaning up lines now that feature is in stable release
CI only

Remove conditional-compile lines for file-sharing-teams-interop

---

change-beta/@azure-communication-react-0a7c2e93-9abf-4776-879f-87c5f9fd9271.json
change/@azure-communication-react-0a7c2e93-9abf-4776-879f-87c5f9fd9271.json
packages/react-composites/src/composites/CallComposite/components/LocalDeviceSettings.tsx

Removed disabled prop for proper contrasted labels
Labels did not meet required contrast requirements
https://skype.visualstudio.com/SPOOL/_workitems/edit/3911558 
Calling sample, macOS Chrome

[a11y][bugfix] Remove unnecessary disabled prop from label for contrast requirement

---

change-beta/@azure-communication-react-3f2cb505-b6c4-4379-81fb-240ccd1eea31.json
change-beta/@azure-communication-react-88f67533-e295-47ba-b755-11969a29471e.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-composites/src/composites/CallComposite/components/Prompt.tsx
packages/react-composites/src/composites/CallComposite/utils/spotlightUtils.ts
packages/react-composites/src/composites/localization/locales/en-US/strings.json

Add aria label close to spotlight prompt
There was no indicator of what action the button performs 
Local calling composite sample, MacOs Chrome

[a11y][bugfix] Add Close aria label for spotlight prompt

---

change-beta/@azure-communication-react-292cc963-998b-46d9-a6ca-5637ff94189d.json
change/@azure-communication-react-292cc963-998b-46d9-a6ca-5637ff94189d.json
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/common-versions.json
common/config/rush/variants/stable/pnpm-lock.yaml
packages/calling-component-bindings/package.json
packages/calling-stateful-client/package.json
packages/communication-react/package.json
packages/react-composites/package.json
packages/react-composites/tests/browser/call/hermetic/fixture.ts
packages/storybook8/package.json
samples/CallWithChat/package.json
samples/Calling/package.json
samples/CallingStateful/package.json
samples/ComponentExamples/package.json
samples/StaticHtmlComposites/package.json
samples/tests/package.json

Update communication-calling stable version from 1.29.1 to 1.30.2
1.30.1-beta.2 to 1.31.1-beta.1

Update communication calling stable version to 1.30.2 and beta to 1.31.1-beta.1

---

change-beta/@azure-communication-react-6c93277e-53fd-4565-bfd7-09aa7c8c10e1.json
change/@azure-communication-react-6c93277e-53fd-4565-bfd7-09aa7c8c10e1.json
packages/react-composites/src/composites/CallComposite/components/HoldPane.tsx
packages/react-composites/src/composites/CallComposite/components/NetworkReconnectTile.tsx
packages/react-composites/src/composites/CallComposite/styles/NetworkReconnectTile.styles.ts

Add announcements to these two screens for accessibility reasons

[a11y][bugfix] Add announcements to hold screen and attempting to reconnect screen

---

change-beta/@azure-communication-react-9d8a539c-35da-4ba2-b3a5-7737dd5a08c2.json
change/@azure-communication-react-9d8a539c-35da-4ba2-b3a5-7737dd5a08c2.json
packages/react-components/src/components/RaiseHandButton.tsx
packages/react-components/src/components/ReactionButton.tsx

add aria descriptions to reaction and raise buttons
announces more information about what the buttons do based on their tooltip information
https://skype.visualstudio.com/SPOOL/_workitems/edit/3905978

[Bugfix A11y] Add aria descriptions to react, and raise buttons

---

change-beta/@azure-communication-react-6705e3b1-5b5a-424e-831b-0c4dbd341e8c.json
change/@azure-communication-react-6705e3b1-5b5a-424e-831b-0c4dbd341e8c.json
packages/calling-stateful-client/src/CallSubscriber.ts
packages/calling-stateful-client/src/TypeGuards.ts

Check if the call is a teams call when trying to get the conference details
Fix console error that requested teams conference details in unsupported calls
Ran locally, no error in ACS group calls, Teams meeting conference details still work

Fix console error that requested teams conference details in unsupported calls

---

.github/workflows/alpha-release.yml
.github/workflows/breaking-change-check.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/create-api-view-feature-level.yml
.github/workflows/create-prerelease-branch.yml
.github/workflows/create-release-branch.yml
.github/workflows/deploy-azure-webapps.yml
.github/workflows/deploy-feature-azure-webapps.yml
.github/workflows/deploy-release-azure-webapps.yml
.github/workflows/deploy-storybook.yml
.github/workflows/nightly-cd.yml
.github/workflows/npm-release-publish.yml
.github/workflows/publish-chromatic.yml
.github/workflows/stress-test-ui-tests.yml
.github/workflows/update-api-files.yml
.github/workflows/update-chat-snapshots.yml
.github/workflows/update-snapshots.yml

Use a github repo variable (https://github.com/Azure/communication-ui-library/settings/variables/actions) `RUNS_ON` to dictate the ubuntu version runners run on.
This has been set to `ubuntu-22.04`
Runners are about to be slowly updated to `ubuntu-24.04` December 5th -> January 25th. Our build fails on this new version: https://github.com/Azure/communication-ui-library/actions/runs/12055450770/job/33615831319

Use a github repo variable to dictate the ubuntu version runners run on

---

GROOMME.md
packages/communication-react/CHANGELOG.beta.md

Groom changelog branch

---

change-beta/@azure-communication-react-d907f4b1-65ab-4f14-a725-3090ce2d3130.json
packages/react-components/src/types/TogetherModeTypes.ts

Updated the API by removing redundant interface
- Created a new interface TogetherModeStreamOptions. This options interface will be used to select what kind of together mode to be created
-  Removed duplicate interface TogetherModeStream  and used VideoGalleryStream since they both have similar properties
locally

Updated together mode types

---

packages/storybook8/stories/Components/UnsupportedBrowser/Docs.mdx

- Show code button is covering the UI in canvas
Before
After

[Storybook] Fix storybook Unsupported Browser canvas padding

---

change-beta/@azure-communication-react-05df919a-0892-4766-8264-47a1ada378c7.json
change/@azure-communication-react-05df919a-0892-4766-8264-47a1ada378c7.json
packages/react-components/src/components/CameraButton.tsx
packages/react-components/src/components/MicrophoneButton.tsx

Change the camera and mic announcers to only be present when the controls are focused
- stops them from being announced by readers when the button is not in focus (scan mode)
https://skype.visualstudio.com/SPOOL/_workitems/edit/3832354
Tested locally

[Bugfix] Conditionaly render camera and mic announcers

---

.github/workflows/ci.yml
change-beta/@azure-communication-react-a7e8be69-cfac-4bc0-99b4-883defecf226.json
common/config/workflows/matrix.json

We needed to create a new token since we don't have access to the communication-ui-bot. With the different user minting the token we needed to have a new set of gists that are accessible by the token. I am also making sure we include the last entry to each of these gists so we have consistency when this change goes to main and is ci.yml is run against main once again.
1. We need to create gists with the last entry 
2. We update the matrix.json for the communication-react-jest-beta/json  gist ids
3. We need to update the ci.yaml for how we are using the matrix.json as well as how we are dealing with the composite bundle sizes.
For handling the communication-react-jest-(beta/stable).json we
| Stable (Old) | Stable (New) |
|--------|--------|
| …

temporary change to get coverage / bundle size updates to work again

---

change-beta/@azure-communication-react-6b224443-1be4-4542-98c4-16d89f6842b4.json
change/@azure-communication-react-6b224443-1be4-4542-98c4-16d89f6842b4.json
packages/react-components/src/components/VideoEffects/VideoEffectsItem.tsx

Update the container width to match Teams when there are long strings in the locale for video effects.
without the cap in size the text runs off the button to the left and right
https://skype.visualstudio.com/SPOOL/_workitems/edit/3996876
Validated locally to match Teams

[Bugfix] update text container width to cap text for longer locale strings

---

change-beta/@azure-communication-react-19209e7d-098c-4cfc-b0e5-40636320691b.json
packages/calling-component-bindings/src/captionsSelector.ts
packages/calling-stateful-client/src/CallClientState.ts
packages/calling-stateful-client/src/CallContext.ts
packages/calling-stateful-client/src/Converter.ts
packages/communication-react/review/beta/communication-react.api.md
packages/react-components/src/components/CaptionsBanner.tsx

Change id to sequence id as this id is not unique. This id can be used to differentiate between partial messages from different origin, but the partial/final messages from the same origin all have the same sequence id. 

RTT Feature: Change id to sequence id 

---

common/config/webpack/sampleapp.webpack.config.js
samples/Server/package.json

Undo PR https://github.com/Azure/communication-ui-library/pull/4567 as it's causing codespace to not load samples correctly. 
Temporary fix while we try to understand this issue further.
Believe issue occurred after node and webpack update. Have not pinpointed exactly when yet. Will dive deeper into this when time allows. In the meantime this pr is to help unblock others using codespace.

Remove HMR causing codespace to not load samples correctly

---

change-beta/@azure-communication-react-6ebb0895-7f83-4c53-bb1b-a3dfaa10a46f.json
change/@azure-communication-react-6ebb0895-7f83-4c53-bb1b-a3dfaa10a46f.json
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts

Fix undefined chat thread in main meeting when breakout room is immediately closed. 
The chat state in context is set to undefined when joining a breakout room so as to not show the main meeting chat thread.
The chat state will continue to be undefined until the local user is added to the breakout room chat thread. But when the breakout room is closed immediately the chat state will be stuck as undefined. So when the breakout room is closed we should compare the thread id from the chat state context (which is undefined) to the thread id of the origin call chat adapter.
Bug found during bug bash where we see the chat thread is stuck on spinner when immediately returning to main meeting from a closed breakout room.
Tested locally

Fix undefined chat thread in main meeting when breakout room is immediately closed

---

change-beta/@azure-communication-react-6e9ffc1d-2c5a-4cab-ae81-766d581dc33b.json
change/@azure-communication-react-6e9ffc1d-2c5a-4cab-ae81-766d581dc33b.json
packages/react-composites/src/composites/CallComposite/components/SvgWithWordWrapping.tsx

Update the aria level for the heading SVG on the config screen
Makes sure our elements are the correct level for screen readers
https://skype.visualstudio.com/SPOOL/_workitems/edit/4031933
Validated locally with A11y insights

[A11y bugfix] config heading aria level

---

.github/workflows/touchdown-pipeline/touchdown-build.yml

Update touchdown build pipeline to resolve run errors (will be blocking by the end of Mar 2025) by following this doc:
https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/changemanagement/official-template-check
and update TouchdownBuild task version to latest
There are Touchdown build pipeline errors and a warning found in runs like in this run https://skype.visualstudio.com/SCC/_build/results?buildId=67822589&view=results
Errors: ![image](https://github.com/user-attachments/assets/f630f79f-e622-44ee-8527-badc85744538)
Warning: 
Test run here showing the above errors and warning are resolved:
https://skype.visualstudio.com/SCC/_build/results?buildId=67826845&view=results
(There is still a legal alert which I have to schedule a meeting …

Update touchdown build pipeline to resolve run errors and warning

---

change-beta/@azure-communication-react-30587b02-9f12-4a63-b4da-2233507bb692.json
change/@azure-communication-react-30587b02-9f12-4a63-b4da-2233507bb692.json
packages/react-components/src/components/ScreenShareButton.tsx

Update screenshare button stylings to match a regular primary button
Screenshare button icon was black but text was white. Both should be black.
| -- | -- |
| ![image](https://github.com/user-attachments/assets/1d3926da-013a-4629-a02c-d2b41ebfad61) |  ![image](https://github.com/user-attachments/assets/6b9591cf-d9c0-4908-b719-325b706e4b51) |
No impact to high contrast modes:
| aquatic | desert | dusk | night sky |
| -- | -- | -- | -- |
| ![image](https://github.com/user-attachments/assets/17da407f-62ff-40d4-bb55-03299101b116) | ![image](https://github.com/user-attachments/assets/ca8f2ab7-49e6-4dd2-9707-572253cd1c91) | ![image](https://github.com/user-attachments/assets/5b2ad41e-7224-45a8-854f-510db8f66d81) | ![image](https://github.com/user-attachments/assets/77015ac3-fc …

Fix screenshare button text to be black in dark mode 

---

change-beta/@azure-communication-react-f3a7790e-0c51-4994-852a-e636b2cfd18b.json
change/@azure-communication-react-f3a7790e-0c51-4994-852a-e636b2cfd18b.json
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts

Updates the max number of event listeners that can be applied to an event.
The warning that we were seeing was sepcifically caused by the max number of event subscriptions on the `'stateChanged'` event for the adapter. This was previously set to `50` as the max.
Recently we started making changes to how we were getting data from the state of the adapter by writing selectors for all of the data that we would be retrieving. This is what sent us over the limit. when we call `useSelector` like so 
this under the hood calls a special hook for the adapter called `useAdaptedSelector`. in this hook we have a useEffect defined as follows 
for every render that would go by all of the different selectors would unmount, removing listeners from the event. Then when the components of the composite …

[Bugfix] Update max number of listeners on stateChange event for CallAdapter

---

docs/releases/creating-a-release.md

Change link for release bug bash setup to use ADO test plan
So that we can use ADO test plans for release bug bashes
New linked document test ran in small scale in previous releases

Change link for release bug bash setup to use ADO test plan

---

samples/tests/StaticHtmlComposites/CompositeJavascriptTest.test.ts

Fix chat composite snapshot

---

change-beta/@azure-communication-react-ae4dd794-8396-42ec-b246-234e9dfc7214.json
change/@azure-communication-react-ae4dd794-8396-42ec-b246-234e9dfc7214.json
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts

Ensure createChatAdapterCallback is set for AzureCommunicationCallWithChatAdapter in `createAzureCommunicationCallWithChatAdapterFromClients`  so that a new ChatAdapter can be created when joining a breakout room
To resolve #5675
I tested using `createAzureCommunicationCallWithChatAdapterFromClients` to create a CallWithChatAdapter for a CallWithChatComposite in the quickstarts repo and first verified I got the same error in the issue above:
`Unable to create chat adapter for thread because createChatAdapterCallback is not set
at AzureCommunicationCallWithChatAdapter.createNewChatAdapterForThread`
I then tested this branch by packaging the communication-react package for the quickstarts repo and verified that the error was resolved and a new ChatAdapter was created when joining a breakout …

Fix createAzureCommunicationCallWithChatAdapterFromClients for breakout rooms

---

change-beta/@azure-communication-react-a6582b31-bc20-4f03-9520-efd5fb814b21.json
change/@azure-communication-react-a6582b31-bc20-4f03-9520-efd5fb814b21.json
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts

Update the max number of event listeners that the CallWithChatAdapter can have
We are subscribing to `'stateChanged'` event on the adapter when we use the `useSelector` hook to fetch the data we need from the adapter. We had this issue in the CallAdapter as well but the CallWithChat adapter manages its own max listeners since it has to manage both Adapters; Call and Chat.
https://github.com/Azure/communication-ui-library/issues/5688

[bugfix] call with chat listeners fix

---

change-beta/@azure-communication-react-2486d3fd-5b86-4ae4-ada4-bca3f53046fb.json
change/@azure-communication-react-2486d3fd-5b86-4ae4-ada4-bca3f53046fb.json
packages/react-components/src/components/styles/RichTextEditor.styles.ts

Force link to be primary, this matches the message thread itself and teams.
Correct behaviour:

Resolve issue where link color was incorrect in dark mode

---

change-beta/@azure-communication-react-364a17bc-d253-45ca-8155-63469c3e5c64.json
change/@azure-communication-react-364a17bc-d253-45ca-8155-63469c3e5c64.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/communication-react/src/mergedHooks.ts

With the previous implementation Typescript couldn't correctly infer the return type of the `useCallingPropsFor` and `useChatPropsFor` hooks. Change the return type to fix the issue

Fixed an issue with types for usePropsFor

---

change-beta/@azure-communication-react-2e4a29d5-272c-4225-9f4f-add54c5646f1.json
change-beta/@azure-communication-react-4a805157-c696-47df-8490-c10e6c9370f2.json
change-beta/@azure-communication-react-bc219d8c-b452-49b5-b84d-fda5e16c9e1f.json
change/@azure-communication-react-2e4a29d5-272c-4225-9f4f-add54c5646f1.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/communication-react/src/mergedHooks.ts
packages/storybook8/stories/StatefulClient/BestPractices.mdx

Reverts Azure/communication-ui-library#5684

Revert "specific usePropsFor to treeshake out unncessary calling/chat code"

---

samples/Chat/src/app/ChatHeader.tsx

- Add tooltip for Leave Chat button in Chat sample
- In narrower window there's no text to indicate what the button does, adding a tooltip

[A11y][Chat sample] Add tooltip for Leave Chat button in Chat sample

---

change-beta/@azure-communication-react-f284b77c-7245-43ab-a075-70286742e975.json
common/config/babel/features.js
packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
packages/calling-component-bindings/src/videoGallerySelector.ts
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-components/src/components/VideoGallery.tsx
packages/react-components/src/components/VideoGallery/TogetherModeStream.tsx
packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts

Cherry pick #5724 and #5742 to release/1.26.0-beta.1
Ensure release/1.26.0-beta.1 has latest code
Smoke tested calling together mode

Together mode cherry picks to release/1.26.0-beta.1

---

change-beta/@azure-communication-react-876f80cc-fe37-43ca-8af5-93b7118ab9fa.json
change/@azure-communication-react-876f80cc-fe37-43ca-8af5-93b7118ab9fa.json
packages/react-components/src/components/VideoGallery.tsx
packages/react-components/src/components/VideoGallery/FloatingLocalVideoLayout.tsx

Update video gallery logic to use localVideoTileSize to make sure when on desktop, we are always showing the desktop video gallery view 
fix bug https://skype.visualstudio.com/SPOOL/_workitems/edit/4035618

Update video gallery logic to show desktop view always when on Desktop

---

change-beta/@azure-communication-react-38bd8537-9167-4bee-818d-e0da918622dd.json
change/@azure-communication-react-38bd8537-9167-4bee-818d-e0da918622dd.json
packages/react-components/src/components/CaptionsBanner.tsx

Add a filter to ensure captions/rtt data is available to set a key to.
Empty elements were being listed without key values. 
We should not be presenting empty elements at all.
MacOS Chrome calling sample app

[bugfix] Add a filter to ensure only captions/rtt data is presented and no empty elements without keys

---

packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-components/src/components/utils.ts
packages/react-components/src/theming/icons.tsx

Fix casing in API icon name for notification type
fix the naming for the type
Built API files

[Notifications] fix naming typo with notification icon name

---

change-beta/@azure-communication-react-8050440c-53e4-4704-8ede-16f4a0a6c0f8.json
change/@azure-communication-react-8050440c-53e4-4704-8ede-16f4a0a6c0f8.json
packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
samples/CallWithChat/src/app/views/CallScreen.tsx

Add map of listeners for chat events so that old chat adapter listeners can be propagated to newly created chat adapters. This will fix listeners for chat events when:
- the thread Id is resolved late in callInfo when joining a Teams meeting link 
- the thread Id is changed when moving to and from breakout rooms
Resolves one of the issue from #5755 regarding not being able chat event listeners not working when joining a breakout room
Tested with code from reverted [commit](https://github.com/Azure/communication-ui-library/commit/5e1c04305ce3314027d1636afd6ca17d370f3832) on this branch

Fix listeners for chat events of AzureCommunicationCallWithChatAdapter when the threadId changes

---

change-beta/@azure-communication-react-fdcffbdb-2066-4b9d-9539-9c1fa2a7eaa9.json
change/@azure-communication-react-fdcffbdb-2066-4b9d-9539-9c1fa2a7eaa9.json
packages/react-components/src/components/CaptionsSettingsModal.tsx
packages/react-components/src/components/RealTimeTextModal.tsx

https://skype.visualstudio.com/SPOOL/_workitems/edit/4111262

[Accessibility Bug Fix] RTT Modal heading is not defined as heading

---

change-beta/@azure-communication-react-866200b1-cae4-404a-b452-82a33f1cefb3.json
change/@azure-communication-react-866200b1-cae4-404a-b452-82a33f1cefb3.json
packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx

Repo steps:
1. Enable RTE
2. Upload a large file
3. While uploading, click on the send button
4. After file loaded, click on the send button and observe the issue
5. Remove the files and try to send a plain text message, fail to send the message as well
After the fix:
https://github.com/user-attachments/assets/f9a463c1-1c95-457b-9f4c-9b74876e1454

Fix RTE send button disabled after uploading is completed

---

change-beta/@azure-communication-react-231c0a17-7d2b-4688-8543-8e193e4ec533.json
change/@azure-communication-react-231c0a17-7d2b-4688-8543-8e193e4ec533.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
samples/Server/package.json

- Upgrade supertest for formidable Component Governance
https://github.com/Azure/communication-ui-library/security/dependabot/325
https://github.com/Azure/communication-ui-library/security/dependabot/326
- `formidable` needs to be upgraded to 3.5.3 or higher

Upgrade supertest for formidable Component Governance

---

change-beta/@azure-communication-react-8c58c3e1-000c-452f-b51a-33cc3be306ee.json
packages/calling-stateful-client/src/StatefulCallClient.ts
packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts

Add missing CallClient dispose handler to the stateful client
Keeps the stateful client up to date with the latest changes in the calling SDK
Validated locally with JS loaders

[Bugfix] callclient dispose

---

change-beta/@azure-communication-react-4b170639-a671-4920-b5d6-0f5348f02b5f.json
change-beta/@azure-communication-react-dddcb5df-0075-426b-8012-314e9c29ae97.json
packages/react-composites/src/composites/CallComposite/components/LocalDeviceSettings.tsx

Revert a11y dropdown group announcement
Causing a ghost element to take precedence when selecting a new item in the dropdown every other time.
MacOS Chrome

Revert a11y dropdown group announcement

---

change-beta/@azure-communication-react-d44320f8-4979-4572-87c6-b666454a9377.json
packages/communication-react/review/beta/communication-react.api.md
packages/communication-react/review/stable/communication-react.api.md
packages/react-components/src/components/Drawer/DrawerMenuItem.tsx
packages/react-composites/src/composites/common/ControlBar/CustomButton.tsx
packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx

Add new prop to auto dismiss drawer menu for custom button injection
Custom buttons clicked in overflow would not dismiss the drawermenu. Would cause issues when opening dialogs as drawermenu would overlay on top

Custom Button Injection auto dismiss drawer menu when actioned

---

change-beta/@azure-communication-react-acd9ca3e-b6a3-45ae-be9e-3f99f4986602.json
change/@azure-communication-react-acd9ca3e-b6a3-45ae-be9e-3f99f4986602.json
packages/react-components/src/components/RaiseHandButton.tsx

Before:
After:
https://skype.visualstudio.com/SPOOL/_workitems/edit/4045402

Fix for dark text for raise hand button in dark theme

---

common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
packages/react-composites/package.json
samples/CallWithChat/package.json
samples/Calling/package.json
samples/CallingStateful/package.json
samples/Chat/package.json
samples/ComponentExamples/package.json

Update webpack-dev-server to latest (5.2.2)
Fix dependabot alerts:
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/336
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/337
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/338
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/339
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/340
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/341
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/342
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/343
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/344
Fixes …

Update webpack-dev-server to 5.2.2

---

change-beta/@azure-communication-react-05227330-4bee-42f1-a6a1-c9a2c7158ba5.json
change/@azure-communication-react-05227330-4bee-42f1-a6a1-c9a2c7158ba5.json
packages/react-components/src/components/CaptionsAndRTTAnnouncer.tsx
packages/react-components/src/components/CaptionsBanner.tsx

Refactor captions component, move the announcer to an internal component
Help make the captions component smaller and more readable
Tested with samples 

Refactor captions component, move the announcer to an internal component

---

change-beta/@azure-communication-react-cadd1df4-cd5c-458c-a027-e4bcdd9260d7.json
change/@azure-communication-react-cadd1df4-cd5c-458c-a027-e4bcdd9260d7.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml

Update brace-expansion to 1.1.12 and 2.0.2
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/357
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/358
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/359
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/360
CI only

Update brace-expansion to 1.1.12 and 2.0.2

---

change-beta/@azure-communication-react-a9d5fe68-a874-4d68-bef5-a3a814c33298.json
change/@azure-communication-react-a9d5fe68-a874-4d68-bef5-a3a814c33298.json
packages/communication-react/review/beta/communication-react.api.md
packages/react-components/src/components/Attachment/AttachmentCard.tsx
packages/react-components/src/components/Attachment/AttachmentUploadCards.tsx
packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
packages/react-components/src/components/SendBox.tsx
packages/react-components/src/components/utils/common.ts
packages/react-components/src/localization/locales/en-US/strings.json

- Add aria-label for upload progress

[A11y] Add aria-label for upload progress

---

change-beta/@azure-communication-react-ccd05f12-b863-40d4-b7f5-a60988f4bdf6.json
change/@azure-communication-react-ccd05f12-b863-40d4-b7f5-a60988f4bdf6.json
packages/react-composites/src/composites/CallComposite/components/SidePane/SidePane.tsx

[A11y]Change role to dialog to fix accessible name for effects pane
https://skype.visualstudio.com/SPOOL/_queries/edit/3832365/?queryId=b6ea9791-8605-4d46-840c-f240e55fd13d

[A11y]Change role to dialog to fix accessible name for effects pane

---

.vscode/settings.json
common/config/package.json
common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml

Update eslint settings to correctly show linting red squigglies, update the node modules in the common folder to have access to required deps
Currently the vscode eslint extension is not working, it fails internally with: `Error: Config file could not be found`. (under the hood this is because it is searching for the config in the root of the repo, and not crawling up from the current file)
Setting this setting seems to fix it.
On testing seems to be working now:

Fix vscode not showing live linting errors

---

.github/workflows/create-prerelease-branch.yml
.github/workflows/deploy-feature-azure-webapps.yml
.github/workflows/deploy-release-azure-webapps.yml

- Add option to choose beta vs stable in feature-deploy GH action
- Stop cancelling action in create-prerelease-branch if another one is triggered (to allow beta and stable to run at the same time)
- Remove auto deploy to beta-validation branch to stop cherry-picks clobbering deployments
Quick first step in better supporting dual releases
untested

Small GitHub action fixups for better supporting dual releases

---

common/config/rush/pnpm-lock.yaml
common/config/rush/variants/stable/pnpm-lock.yaml
samples/Chat/package.json

Update Chat sample usage of axios to 1.12.2
Dependabot alert
- https://github.com/Azure/communication-ui-library/security/dependabot/377
- https://github.com/Azure/communication-ui-library/security/dependabot/378
Storybook playwright test runner also uses an older axios package but we do not make use of that

Update Chat sample usage of axios to 1.12.2
