samples/Calling/README.md, samples/Chat/README.md, samples/OneToOneCall/README.md
Update the readmes for the samples to align with the new build system (rush)
Help resolve issue #396
=> Update Sample readmes

change/react-composites-2bb08016-3aca-43a6-b23e-2a5c33863474.json, packages/communication-react/review/communication-react.api.md, packages/react-composites/review/react-composites.api.md, packages/react-composites/src/composites/CallComposite/Call.tsx, packages/react-composites/src/composites/CallComposite/CallScreen.tsx, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, samples/Calling/src/app/App.tsx, samples/Calling/src/app/CallScreen.tsx
Added custom page for removed call participants
https://skype.visualstudio.com/SPOOL/_workitems/edit/2354047
Local sample test
=> Small: Added custom page for removed call participants

packages/storybook/stories/Examples/TeamsInterop/Lobby.stories.tsx, packages/storybook/stories/Examples/TeamsInterop/__snapshots__/Lobby.stories.storyshot, packages/storybook/stories/Examples/TeamsInterop/snippets/Lobby.snippet.tsx
Fixing alignment and design issues to be closer to FIGMA. 
Screenshot of what it looks like in localhost.
Align to figma design
=> [Lobby] Fixing storybook to align 

change/react-composites-71d6a71c-0651-4511-b625-5eee037841a3.json, packages/communication-react/review/communication-react.api.md, packages/react-composites/review/react-composites.api.md, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/storybook/stories/CallComposite/snippets/Container.snippet.tsx, packages/storybook/stories/CallComposite/snippets/CustomDataModelExampleContainer.snippet.tsx, packages/storybook/stories/CallComposite/snippets/JoinExistingCall.tsx, packages/storybook/stories/CallComposite/snippets/Server.snippet.tsx, packages/storybook/stories/QuickStarts/snippets/QuickstartCompositeAdapter.snippet.tsx, packages/storybook/stories/QuickStarts/snippets/QuickstartCompositeComplete.snippet.tsx
A step towards deleting the hack for extracting user ID from token.
=> Add userID argument to CallAdapter factory function

.github/workflows/nightly-ci.yml
My math was wrong and currently we trigger at 7pm not 5pm ⏰
=> Change nightly CI time to 5pm

packages/communication-react/package.json
Reduces the bundle size of an app with this:
```ts
import { EndCallButton, useCallingPropsFor } from "@azure/communication-react";
function App() {
const endCallProps = useCallingPropsFor(EndCallButton);
return (
<div className="App">
<EndCallButton {...endCallProps} />
</div>
);
}
export default App;
```
from 3.73 MB -> 2.79 MB (parsed), a reduction of 25%.
to
Better treeshaking. Less code, more happy kittens.
Built a brand new CRA app. Looked at source map and bundle analyzer reports.
=> Declare @azure/communication-react to be sideEffects free

.github/workflows/deploy-azure-webapps.yml
In preparation to turn it down.
=> Stop auto-deploying One To One sample

samples/Chat/src/app/selectors/baseSelectors.ts
Leaked into an earlier PR. Unfortunately `rush build` doesn't catch this.
=> Fix Chat sample typo

samples/Calling/package.json, samples/Calling/src/app/App.tsx, samples/Calling/src/app/CallControls.tsx, samples/Calling/src/app/CallScreen.tsx, samples/Calling/src/app/CommandPanel.tsx, samples/Calling/src/app/ConfigurationScreen.tsx, samples/Calling/src/app/Lobby.tsx, samples/Calling/src/app/LobbyControlBar.tsx, samples/Calling/src/app/LocalDeviceSettings.tsx, samples/Calling/src/app/LocalPreview.tsx, samples/Calling/src/app/MediaGallery.tsx, samples/Calling/src/app/ScreenShare.tsx, samples/Calling/src/app/hooks/useAzureCommunicationHandlers.ts, samples/Calling/src/app/selectors/baseSelectors.ts, samples/Calling/src/app/selectors/lobbySelector.ts, samples/Calling/src/app/theming/SwitchableFluentThemeProvider.tsx, samples/Chat/package.json, samples/Chat/src/app/App.tsx, samples/Chat/src/app/ChatArea.tsx, samples/Chat/src/app/ChatHeader.tsx, samples/Chat/src/app/ChatScreen.tsx, samples/Chat/src/app/ParticipantManagement.tsx, samples/Chat/src/app/SidePanel.tsx, samples/Chat/src/app/selectors/baseSelectors.ts, samples/Chat/src/app/selectors/chatHeaderSelector.ts
Migrate sample app to merged hook to make it pass the build
=> Migrate sample app to merged hook

change/react-components-447a1741-c1a5-4463-a421-0c0eefe880a2.json, change/react-composites-31e587a5-697c-4465-b4c6-82f67aacb3de.json, packages/react-components/src/components/VideoTile.tsx, packages/react-components/src/components/styles/VideoTile.styles.ts, packages/react-composites/src/composites/CallComposite/ScreenShare.tsx, packages/storybook/stories/Examples/IncomingCallAlerts/__snapshots__/IncomingCallAlerts.stories.storyshot, packages/storybook/stories/Examples/Layouts/__snapshots__/Layouts.stories.storyshot, packages/storybook/stories/Examples/LocalPreview/__snapshots__/LocalPreview.stories.storyshot, packages/storybook/stories/Examples/TeamsInterop/__snapshots__/Lobby.stories.storyshot, packages/storybook/stories/Examples/Themes/__snapshots__/TeamsTheme.stories.storyshot, packages/storybook/stories/GridLayout/__snapshots__/GridLayout.stories.storyshot, packages/storybook/stories/VideoGallery/__snapshots__/VideoGallery.stories.storyshot, packages/storybook/stories/VideoTile/__snapshots__/VideoTile.stories.storyshot
Mute indicator will be shown for participants during screen sharing.
Padding has been fixed for new mute indicator fluent icon. And will work RTL
=> 2495879 bug mute indicator

change/react-components-1e04f33c-d819-47f7-a07e-6e4464e9f5ac.json, packages/react-components/src/components/SendBox.tsx, packages/react-components/src/components/styles/SendBox.styles.ts, packages/storybook/stories/SendBox/__snapshots__/SendBox.stories.storyshot
Small fix for send button style
Before
After
=> Small fix for send button style

change/react-composites-1dcc5467-de96-4f5c-853a-c27f7d74f026.json, packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts, packages/react-composites/src/composites/ChatComposite/hooks/useHandlers.ts
Use class method syntax uniformly.
https://github.com/Azure/communication-ui-library/pull/449#discussion_r652949367
`rush build`
=> Use uniform method style in chat adapter

change/chat-stateful-client-2159fe32-56f4-4a4a-9ef6-f86da52b469f.json, packages/chat-stateful-client/src/ChatContext.ts, packages/chat-stateful-client/src/StatefulChatClient.test.ts, packages/chat-stateful-client/src/StatefulChatClient.ts
See `ReportingErrors.md` for explanation.
unittests
=> When an operation succeeds, clear related errors from state

change/chat-stateful-client-d2e04766-6de6-403d-ac21-82a4961e6dfc.json, packages/chat-stateful-client/src/ChatContext.ts, packages/chat-stateful-client/src/StatefulChatClient.test.ts, packages/chat-stateful-client/src/StatefulChatClient.ts
=> Add a couple more error handlers in stateful chat and fix spurious event trigger

packages/storybook/stories/Stateful Client/UsePropsForHook.stories.mdx, packages/storybook/stories/Stateful Client/UseSelector.stories.mdx
* Update usePropsFor doc for merged hooks
* Update code piece to make it more complete
* Address comments
Co-authored-by: Nan Jiang <jinan@microsoft.com>
=> [Cherry-pick PR 518 to beta-candidate] Jinan/update use props for doc (#518)

packages/storybook/stories/NonReact/NonReactComposites.stories.mdx, samples/StaticHtmlComposites/index.html, samples/StaticHtmlComposites/src/callComposite.js, samples/StaticHtmlComposites/src/chatComposite.js
=> Small adjustments to the doc

packages/storybook/stories/IdentityManagement/snippets/ChatBackend.snippet.ts
=> cherry-pick: Fix displayname for first user in generated chat thread

change/@internal-react-components-458074d4-5553-42a7-881a-697074ea1149.json, packages/react-components/src/components/styles/ControlBar.styles.ts
cursor: pointer added to control button styles
Fix #553 
https://skype.visualstudio.com/SPOOL/_workitems/edit/2515804
Manual check on all buttons in storybook
=> [Github issue] Control button label cursor fix

packages/storybook/stories/NonReact/NonReactComposites.stories.mdx
Merging markdown issue in our storybook documentation into the release branch as well
It formats incorrectly in the documentation
Ran it locally
=> cherry-picking markdown url issue into rel branch

change/@internal-react-composites-5cd5f3a1-0589-4eb6-a434-31ccd4314017.json, change/@internal-react-composites-fc54afea-88af-4bfd-b28f-43533ecefd56.json, packages/communication-react/review/communication-react.api.md, packages/react-composites/review/react-composites.api.md, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.test.ts, packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts, packages/react-composites/src/composites/ChatComposite/index.ts, packages/react-composites/tests/browser/call/app/index.tsx, packages/react-composites/tests/browser/chat/app/index.tsx, packages/storybook/stories/CallComposite/snippets/Container.snippet.tsx, packages/storybook/stories/CallComposite/snippets/CustomDataModelExampleContainer.snippet.tsx, packages/storybook/stories/ChatComposite/CustomBehaviorExampleContainer.tsx, packages/storybook/stories/ChatComposite/snippets/Container.snippet.tsx, packages/storybook/stories/ChatComposite/snippets/CustomDataModelExampleContainer.snippet.tsx, packages/storybook/stories/ChatComposite/snippets/CustomizeBehavior.snippet.tsx, packages/storybook/stories/QuickStarts/snippets/QuickstartCompositeAdapter.snippet.tsx, packages/storybook/stories/QuickStarts/snippets/QuickstartCompositeComplete.snippet.tsx, packages/storybook/stories/Stateful Client/snippets/CallAdapterExample.snippet.tsx, packages/storybook/stories/Stateful Client/snippets/ChatAdapterExample.snippet.tsx, samples/Calling/src/app/views/CallScreen.tsx, samples/StaticHtmlComposites/src/callComposite.js, samples/StaticHtmlComposites/src/chatComposite.js
Adds the following PRs to release candidate 1.0.0-beta.3
https://github.com/Azure/communication-ui-library/pull/625
https://github.com/Azure/communication-ui-library/pull/626#pullrequestreview-721572732
=> Cherrypick james adapter signature changes

packages/storybook/stories/Examples/TeamsInterop/snippets/Lobby.snippet.tsx
Removing the use of an internal util in snippet file
Related to this bug
https://skype.visualstudio.com/SPOOL/_workitems/edit/2460682
=> Removing the use of an internal util in snippet file

change/@internal-calling-component-bindings-093579e8-d5d3-4f2b-afb3-5a7043ee3fac.json, change/@internal-react-composites-52dd24f5-44e6-4530-957f-7cb20404d5d2.json, packages/calling-component-bindings/review/calling-component-bindings.api.md, packages/calling-component-bindings/src/handlers/createHandlers.ts, packages/communication-react/review/communication-react.api.md, packages/react-composites/src/composites/CallComposite/CallControls.tsx, packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
* Ensure the ParticipantList inside the ParticipantButton is getting the necessary handlers. In this case it is `onParticipantRemove`.
Adds in the option to remove participants in the people list in the participant button
In Calling Sample (ignore the RTL, that is a separate bug that crept into main branch):
=> Add Call Composite Remove Participant

packages/communication-react/CHANGELOG.md
Updated changelog for communication-react package
=> update changelog for beta4

change/@internal-react-composites-f66f2f14-6f80-44f3-a42f-3e198a508459.json, packages/react-composites/src/composites/MeetingComposite/ChatButton.tsx, packages/react-composites/src/composites/MeetingComposite/MeetingComposite.tsx, packages/react-composites/src/composites/MeetingComposite/PeopleButton.tsx
Cherry pick #783 into release branch
=> Cherry pick #783 into release branch

.vscode/settings.json, packages/communication-react/CHANGELOG.md
Prune the changelog down for humans.
=> Prune changelog for beta.6

samples/Calling/src/app/views/CallError.tsx, samples/Calling/src/app/views/EndCall.tsx, samples/Calling/src/app/views/HomeScreen.tsx, samples/Chat/src/app/ConfigurationScreen.tsx, samples/Chat/src/app/EndScreen.tsx, samples/Chat/src/app/ErrorScreen.tsx, samples/Chat/src/app/HomeScreen.tsx
Added heading tags when needed in Chat and Composite samples
a11y bug https://skype.visualstudio.com/SPOOL/_workitems/edit/2582726
ran Chat and Calling composites, and opened Narrator
=> heading tags missing in Chat and Calling composites

packages/communication-react/CHANGELOG.md
Adding release notes for 1.0.0-beta.7
Developers are able to determine what new and exciting updates are part of this beta release
=> release notes

samples/Chat/src/app/ConfigurationScreen.tsx, samples/Chat/src/app/styles/ConfigurationScreen.styles.ts
Updated Chat avatar focus to be more visible when navigating through keyboard
a11y bug: https://skype.visualstudio.com/SPOOL/_workitems/edit/2582960
Ran Chat sample locally
=> updated Avatar style when focused on

change/@internal-calling-component-bindings-caafb3a6-36c7-42a8-87a2-a9a13d8eea14.json, packages/calling-component-bindings/src/participantListSelector.ts
Adds name based sorting to participant list selector so it returns ascending list of participants.
When a large number of participants are present in a call, it becomes difficult to find a participant if they are not sorted.
=> Bugfix 2648152 sorted participants

change/@internal-react-components-bddd646f-2eb7-431f-8a18-7bba870da292.json, packages/react-components/src/localization/locales/de-DE/strings.json, packages/react-components/src/localization/locales/es-ES/strings.json, packages/react-components/src/localization/locales/fr-FR/strings.json, packages/react-components/src/localization/locales/it-IT/strings.json, packages/react-components/src/localization/locales/ja-JP/strings.json, packages/react-components/src/localization/locales/nl-NL/strings.json, packages/react-components/src/localization/locales/pt-BR/strings.json, packages/react-components/src/localization/locales/ru-RU/strings.json, packages/react-components/src/localization/locales/tr-TR/strings.json
Updates from TDBuild
Pull in translations because TDBuild was not updated in time and only updated on Dec 2, 2021
=> Touchdown update 5

common/config/beachball/changelog-custom-renders.ts, packages/communication-react/CHANGELOG.md
* Prune changelog
* Fix changelog links
* Release notes
=> Prune changelog

docs/references/accessibility-tools.md
Remove point of contact for a11y onboarding
Info needed in wiki page only
=> remove a11y team contact info

change/@internal-react-components-e1a7a6db-31c5-46a4-8206-5f8d4d69d349.json, change/@internal-storybook-b27ec54d-b118-4b50-b9a5-cc84eb4ac378.json, packages/react-components/src/components/MessageStatusIndicator.tsx, packages/react-components/src/components/SystemMessage.tsx, packages/react-components/src/components/TypingIndicator.tsx, packages/storybook/stories/MessageStatusIndicator/__snapshots__/MessageStatusIndicator.stories.storyshot, packages/storybook/stories/TypingIndicator/__snapshots__/TypingIndicator.stories.storyshot
Cherry-picked PR https://github.com/Azure/communication-ui-library/pull/1220
=> [Cherry-pick] a11y chat strings fix

docs/references/accessibility-tools.md
cherry-pick of PR https://github.com/Azure/communication-ui-library/pull/1226 to add to release branch
=> [cherry pick] remove a11y contact from doc

change/@internal-storybook-c1613779-fdd3-43b2-b6d9-053f9640138e.json, packages/storybook/stories/Overview.stories.mdx
Cherry-pick #1216 (Dademath-overview-narrative)
=> (Docs) Cherry-pick #1216 (Dademath-overview-narrative) to release

packages/communication-react/CHANGELOG.md
Add release notes to changelog
=> Add release notes to changelog

change/@internal-storybook-20025b25-b7e1-48b8-8cde-8656fcb663a9.json, packages/storybook/stories/MessageStatusIndicator/snippets/AllDefaultIndicators.snippet.tsx
Bugfix for https://skype.visualstudio.com/SPOOL/_workitems/edit/2667116
=> Bugfix for tooltip alignment in message status indicator storybook 

change/@internal-storybook-0af53090-636f-4286-84f5-1a8ca092a459.json, packages/storybook/.storybook/manager-head.html, packages/storybook/.storybook/preview-head.html
Fixes https://skype.visualstudio.com/SPOOL/_workitems/edit/2675408
=> bugfix storybook canvas

change/@internal-react-components-59dbe480-1613-47b6-a865-6464220a7cd3.json, packages/react-components/src/components/styles/HorizontalGallery.styles.ts
* fix  bug-2674356
* Change files
=> [Cherry-Pick] Horizontal Gallery left/right button height fixed (#1285)

.github/CODEOWNERS
Add carocao-msft, edwardlee-msft and prabhjot-msft as codeowners. Removed alcail as codeowner.
More reviewers :)
=> Add carocao-msft, edwardlee-msft and prabhjot-msft as codeowners

samples/Meeting/.eslintrc.js, samples/Meeting/package.json, samples/Meeting/src/app/utils/pushQSPUrl.ts
chat sdk, fixed URL rewrite issue affecting deploy.
Removed not needed eslint fields, updated chatSDK information in package.json, fixed a URL rewrite function to return a string to the push state
fixes minor issues with the meeting sample.
https://skype.visualstudio.com/SPOOL/_workitems/edit/2691295
https://skype.visualstudio.com/SPOOL/_workitems/edit/2691317
Ran locally to ensure new bugs weren't introduced.
=> fixed eslint no var, added correct chat sdk version to meeting sample.

samples/Server/src/routes/addUser.ts, samples/Server/src/routes/createThread.ts, samples/Server/src/routes/getEndpointUrl.ts, samples/Server/src/routes/isValidThread.ts, samples/Server/src/routes/issueToken.ts, samples/Server/src/routes/refreshToken.ts, samples/Server/src/routes/userConfig.ts
Documented routes in Server/src/routes
https://skype.visualstudio.com/SPOOL/_workitems/edit/2691330
=> Documented routes in Server/src/routes

samples/Server/src/lib/envHelper.ts
Quick fix for a bug from #1310
=> Parse URL before accessing parts

samples/Server/src/public/stylesheets/style.css
Removed styles file from server folder
https://skype.visualstudio.com/SPOOL/_queries/edit/2691377/
=> Removed styles file from server folder

samples/Meeting/src/app/App.tsx, samples/Meeting/src/app/utils/AppUtils.ts
cherry picks in teams interop into meeting sample
Adds teams interop to released meeting sample
ran locally to verify functionality.
=> [Cherry Pick]Teams interop meeting sample

common/scripts/babel-conditional-preprocess.js
Babel can now conditionally remove class methods
https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md
=> Update babel preprocessing to conditionally remove class methods

packages/communication-react/CHANGELOG.md
Updating changelog for 1.0.1-beta.2
We want to create an easier to read list of relevant changes in this update.
=> updating changelog for 1.0.1-beta.2

common/scripts/babel-conditional-preprocess.js
Add handler for removing ClassProperty in babel preprocess
=> Add handler for removing ClassProperty in babel preprocess

packages/storybook/.storybook/preview.tsx, packages/storybook/stories/CallComposite/CallCompositeDocs.tsx, packages/storybook/stories/CallComposite/CustomButtonInjection.stories.tsx, packages/storybook/stories/CallComposite/snippets/CustomButtonInjectionExampleContainer.snippet.tsx, packages/storybook/stories/CustomButtonInjection.stories.mdx, packages/storybook/stories/MeetingComposite/CustomButtonInjection.stories.tsx, packages/storybook/stories/MeetingComposite/MeetingCompositeDocs.tsx, packages/storybook/stories/MeetingComposite/snippets/CustomButtonInjection.snippet.tsx, packages/storybook/stories/controlsUtils.ts
Added Storybook elements for custom button injection
=> Storybook for custom button injection

change/@internal-react-composites-960282a0-9b20-4cdb-9043-6ed93db0495e.json, packages/communication-react/review/communication-react.api.md, packages/react-composites/review/react-composites.api.md, packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx, packages/react-composites/src/composites/ChatComposite/file-sharing/FileUploadHandler.tsx
Change userId to string in FileUploadHandler
We simplify user id for end users.
=> Making userId string in uploadHandler

packages/communication-react/CHANGELOG.md
=> Updating changelog for 1.1.0

change/@internal-storybook-78cd5006-78c1-4cd8-bbfa-48dbc57ec27e.json, packages/communication-react/README.md, packages/storybook/stories/QuickStarts/QuickstartComposite.stories.mdx, packages/storybook/stories/QuickStarts/QuickstartStatefulCall.stories.mdx, packages/storybook/stories/QuickStarts/QuickstartStatefulChat.stories.mdx, packages/storybook/stories/QuickStarts/QuickstartUIComponents.stories.mdx, packages/storybook/stories/Stateful Client/OverviewStateful.stories.mdx
=> [Cherry Pick #1504] Update documentation for installing core ACS `peerDependencies`

change/@internal-storybook-9e4d32c4-4edd-4404-aa3c-e2e89f094d5f.json, packages/storybook/stories/Localization.stories.mdx
Added missing locale in storybook documentation table
https://skype.visualstudio.com/SPOOL/_workitems/edit/2771021
Chromatic
=> Added missing locale in storybook documentation

change/@internal-react-components-bdef5c5e-4362-4040-a789-8acbbf32fe34.json, change/@internal-react-composites-2bcf2e50-6495-424c-aee5-f98a108b3952.json, packages/react-components/src/localization/locales/de-DE/strings.json, packages/react-components/src/localization/locales/en-GB/strings.json, packages/react-components/src/localization/locales/es-ES/strings.json, packages/react-components/src/localization/locales/fr-FR/strings.json, packages/react-components/src/localization/locales/it-IT/strings.json, packages/react-components/src/localization/locales/ja-JP/strings.json, packages/react-components/src/localization/locales/ko-KR/strings.json, packages/react-components/src/localization/locales/nl-NL/strings.json, packages/react-components/src/localization/locales/pt-BR/strings.json, packages/react-components/src/localization/locales/ru-RU/strings.json, packages/react-components/src/localization/locales/tr-TR/strings.json, packages/react-components/src/localization/locales/zh-CN/strings.json, packages/react-components/src/localization/locales/zh-TW/strings.json, packages/react-composites/src/composites/localization/locales/de-DE/strings.json, packages/react-composites/src/composites/localization/locales/en-GB/strings.json, packages/react-composites/src/composites/localization/locales/es-ES/strings.json, packages/react-composites/src/composites/localization/locales/fr-FR/strings.json, packages/react-composites/src/composites/localization/locales/it-IT/strings.json, packages/react-composites/src/composites/localization/locales/ja-JP/strings.json, packages/react-composites/src/composites/localization/locales/ko-KR/strings.json, packages/react-composites/src/composites/localization/locales/nl-NL/strings.json, packages/react-composites/src/composites/localization/locales/pt-BR/strings.json, packages/react-composites/src/composites/localization/locales/ru-RU/strings.json, packages/react-composites/src/composites/localization/locales/tr-TR/strings.json, packages/react-composites/src/composites/localization/locales/zh-CN/strings.json, packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Merge strings into stable release
=> Merge strings into stable release 

change/@internal-react-components-03a59ef9-47ee-4518-90df-3f8cb8d51790.json, change/@internal-react-composites-702e49bc-ae87-46ef-b41e-946faaedb33a.json, change/@internal-storybook-1ab2bd43-fc36-42dc-adeb-85f0254cbe08.json, packages/communication-react/review/communication-react.api.md, packages/react-components/review/react-components.api.md, packages/react-components/src/components/VideoGallery.tsx, packages/react-composites/src/composites/CallComposite/components/MediaGallery.tsx, packages/storybook/stories/VideoGallery/VideoGallery.stories.tsx, packages/storybook/stories/VideoGallery/snippets/LocalCameraSwitcher.snippet.tsx
Fix typo: `CamerSwitcher` -> `CameraSwitcher`
PR build should pass
=> Fix typo: `CamerSwitcher` -> `CameraSwitcher`

change/@internal-react-composites-5b45107f-ec66-48b5-b37c-25435d6893b1.json, packages/communication-react/review/communication-react.api.md, packages/react-composites/review/react-composites.api.md, packages/react-composites/src/composites/CallWithChatComposite/index.ts
export `createAzureCommunicationCallWithChatAdapterFromClients`
Exporting feature added in #1457
=> export createAzureCommunicationCallWithChatAdapterFromClients

change/@internal-react-components-4a8467a8-a479-432b-9aa0-957d3a83c2a1.json, change/@internal-react-composites-c1e22e7e-e9e6-4595-8437-e6ee7df3e81c.json, packages/communication-react/review/communication-react.api.md, packages/communication-react/stable-review/communication-react.api.md, packages/react-components/review/react-components.api.md, packages/react-components/src/components/InputBoxComponent.tsx, packages/react-components/src/components/SendBox.tsx, packages/react-components/stable-review/react-components.api.md, packages/react-composites/review/react-composites.api.md, packages/react-composites/src/composites/ChatComposite/ChatComposite.tsx, packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx, packages/react-composites/stable-review/react-composites.api.md
Cherry picking https://github.com/Azure/communication-ui-library/commit/c8edd8a8244665c6e25108d760426af3f254decf into release branch for resolving ARB comment around an API.
The above commit has already been merged to main.
=> Cherry Picking - InputBox API update (#1518) for resolving ARB comment

.github/workflows/npm-release-publish.yml
Cherry Pick Nan's Release branch changes
https://github.com/Azure/communication-ui-library/commit/b1630de62a9c6622b676952a6ff716d5754d3bb1
https://github.com/Azure/communication-ui-library/commit/25c050e5cdfafb935ed1bff38d7cab153d818e91
=> Cherry Pick Nan's Release branch changes

packages/storybook/.storybook/manager.tsx
Cherry pick #1567 to 1.1.1-beta.1
=> Cherry pick #1567 to 1.1.1-beta.1 release (Storybook fullscreen button)

packages/communication-react/CHANGELOG.md
=> Changelog for 1.1.1-beta.1 release

change/@internal-react-composites-c2394a1c-41b7-4565-83ea-463a81eb42c4.json, packages/communication-react/review/communication-react.api.md, packages/react-composites/review/react-composites.api.md, packages/react-composites/src/composites/CallWithChatComposite/CallWithChatControlBar.tsx, packages/react-composites/src/composites/CallWithChatComposite/PeopleButton.tsx, packages/react-composites/src/composites/CallWithChatComposite/Strings.tsx, packages/react-composites/src/composites/localization/locales/en-US/strings.json
Add strings for tooltips
Adds tooltips to the people and chat buttons
https://skype.visualstudio.com/SPOOL/_workitems/edit/2781989
Ran locally and visually inspected the tooltips.
=> Add tooltips to chat and people button

change/@internal-react-composites-3b5f8747-669a-4326-96de-2c36b8016cb0.json, packages/react-composites/src/composites/ChatComposite/selectors/fileUploadsSelector.ts
Change selector output to match the input prop expected by SendBox
=> Filesharing - Upload Bugfix

change/@internal-react-composites-c4d94f58-0530-462b-b937-0c68368a5798.json, packages/communication-react/review/communication-react.api.md, packages/react-composites/review/react-composites.api.md, packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx, packages/react-composites/src/composites/CallWithChatComposite/EmbeddedChatPane.tsx, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedChatAdapter.ts, packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx, packages/react-composites/src/composites/ChatComposite/FileUploadCards.tsx, packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts, packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationFileUploadAdapter.ts, packages/react-composites/src/composites/ChatComposite/adapter/ChatAdapterProvider.tsx
Add filesharing feature to CallWithChat Composite
To use file sharing with self host app. We need this feature in CallWithChat Composite
Manually
=> Add filesharing feature to CallWithChat Composite

change/@internal-react-components-80e8e213-e1c6-46f9-80ea-c3a12450e773.json, change/@internal-react-composites-19503169-970b-4348-bff0-1e6bfe43b1ed.json, packages/react-components/src/components/VideoGallery.tsx, packages/react-composites/src/composites/common/icons.tsx
VideoGallery.tsx and icons.tsx conditional compile comments for LocalCameraSwticher modified to include CallWithChat Conditional Compile.
LocalCameraSwitcher dependent on CallWithChat.
=> Add missing call-with-chat Conditional Compile with local-camera-switcher Conditional Compile

packages/communication-react/CHANGELOG.md
Clean up CHANGELOG.md for `1.2.0`.
=> Clean up CHANGELOG.md for `1.2.0`

packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
Hide file upload button if upload handler not provided
=> Hide file upload button if upload handler not provided

.github/workflows/run-td-build.yml
Fix the syntax used for string literal in github action event.
String translation workflow is currently broken.
Prayers.
=> Use single quotes in event expression literal

.github/workflows/run-td-build.yml
=> Cherry-Pick: Strings translation workflow cleanup

change/@internal-react-components-aa07ccb3-5aa3-4eed-99c3-6876b3504e9b.json, packages/react-components/src/components/ParticipantItem.tsx, packages/react-components/src/components/styles/ParticipantItem.styles.ts, packages/storybook/stories/Examples/IncomingCallAlerts/__snapshots__/IncomingCallToast.stories.storyshot, packages/storybook/stories/Examples/Themes/__snapshots__/TeamsTheme.stories.storyshot, packages/storybook/stories/GridLayout/__snapshots__/GridLayout.stories.storyshot, packages/storybook/stories/ParticipantItem/__snapshots__/ParticipantItem.stories.storyshot, packages/storybook/stories/ParticipantList/__snapshots__/ParticipantList.stories.storyshot, packages/storybook/stories/VideoGallery/__snapshots__/VideoGallery.stories.storyshot, packages/storybook/stories/VideoTile/__snapshots__/VideoTile.stories.storyshot
Update cursor styles in participant pane items to detect current user.
fixes cursor behavior where incorrectly showing you could act on your own listing in the participant list.
https://skype.visualstudio.com/SPOOL/_workitems/edit/2781983
Ran locally and visually inspected behavior.
=> Dmceachernmsft/ParticipantCursorFix (#1690)

change/@internal-storybook-f3c9a9c9-ac39-4cc4-8514-f70bf7581428.json, packages/storybook/stories/Overview.stories.mdx
Avoid confusion as in #1712 
Closes #1712
=> Fix documentation of minimum supported browser verisons

change/@internal-react-composites-0e4e14af-e41c-4eeb-9ffe-ff501df46f7b.json, change/@internal-storybook-9bdfece0-f9da-40f1-a625-185a2eb29f38.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/react-composites/package.json, packages/storybook/package.json, packages/storybook/stories/ControlBar/Buttons/Devices/__snapshots__/Devices.stories.storyshot, packages/storybook/stories/ControlBar/Buttons/EndCall/__snapshots__/EndCall.stories.storyshot, packages/storybook/stories/ControlBar/Buttons/Microphone/__snapshots__/Microphone.stories.storyshot, packages/storybook/stories/ControlBar/Buttons/Participants/__snapshots__/Participants.stories.storyshot, packages/storybook/stories/ControlBar/Buttons/ScreenShare/__snapshots__/ScreenShare.stories.storyshot, packages/storybook/stories/ControlBar/__snapshots__/ControlBar.stories.storyshot, packages/storybook/stories/ErrorBar/__snapshots__/ErrorBar.stories.storyshot, packages/storybook/stories/Examples/DevicesDropdown/__snapshots__/DeviceSettingsDropDown.stories.storyshot, packages/storybook/stories/Examples/IncomingCallAlerts/__snapshots__/IncomingCallModal.stories.storyshot, packages/storybook/stories/Examples/LocalPreview/__snapshots__/LocalPreview.stories.storyshot, packages/storybook/stories/Examples/TeamsInterop/__snapshots__/Lobby.stories.storyshot, packages/storybook/stories/Examples/Themes/__snapshots__/TeamsTheme.stories.storyshot, packages/storybook/stories/MessageStatusIndicator/__snapshots__/MessageStatusIndicator.stories.storyshot, packages/storybook/stories/ParticipantItem/__snapshots__/ParticipantItem.stories.storyshot, packages/storybook/stories/ParticipantList/__snapshots__/ParticipantList.stories.storyshot, packages/storybook/stories/SendBox/__snapshots__/SendBox.stories.storyshot, packages/storybook/stories/VideoGallery/__snapshots__/VideoGallery.stories.storyshot, samples/CallWithChat/package.json, samples/Calling/package.json, samples/Chat/package.json, samples/ComponentExamples/package.json, samples/Server/package.json, samples/StaticHtmlComposites/package.json, tools/check-treeshaking/package.json
Update all dependencies for beta and stable builds to latest SemVer.
Housekeeping.
This also unblocks some security fixes in the downstream hero sample projects.
Locally ran storybook, CallWithChat and Calling samples.
=> Update all dependencies `rush update --full`

change/@internal-chat-component-bindings-82459451-1502-436b-bf85-94bc70a93fc2.json, packages/chat-component-bindings/src/messageThreadSelector.ts
=> Disable RR in meeting interop

change/@internal-chat-component-bindings-cdf4f9b9-4292-41f0-b43e-c287b82c2ffd.json, packages/chat-component-bindings/src/errorBarSelector.ts
=> Cherry-pick #1737 - Squelch not in thread error

packages/communication-react/README.md, packages/storybook/stories/QuickStarts/QuickstartComposite.stories.mdx, packages/storybook/stories/QuickStarts/QuickstartStatefulCall.stories.mdx, packages/storybook/stories/QuickStarts/QuickstartStatefulChat.stories.mdx, packages/storybook/stories/QuickStarts/QuickstartUIComponents.stories.mdx, packages/storybook/stories/Stateful Client/OverviewStateful.stories.mdx
=> Update references to headless calling version

packages/communication-react/stable-review/communication-react.api.md, packages/react-components/src/components/MessageThread.tsx, packages/react-components/stable-review/react-components.api.md
Cherry pick of #1744 
Remove leaked beta-only API.
=> Hide FileSharing API from stable build

packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx
=> Correctly set readBy count when mobileView is set

.github/workflows/publish-chromatic.yml
Ignore chromatic errors in CI
Allows the CI to pass and storybook URLs to be posted in PR comments
=> Ignoring chromatic test errors

change/@internal-react-composites-96e93e30-0a88-4f3e-bb71-b4d3b6cb6e4e.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/react-composites/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/Chat/package.json, samples/ComponentExamples/package.json
Update webpack dependency.
updates webpack-dev-server dependency across the samples to help with updating other dependencies.
Ran locally to make sure new version of webpack still works.
=> update calling webpack-dev-server dep

common/config/webpack/sampleapp.webpack.config.js, samples/StaticHtmlComposites/webpack.config.js
update sample app webpack config file
Fixes errors on start around bad types in the dev server. (oops) 
Ran all samples to verify issue is fixed.
=> update sample app config

samples/Chat/src/app/ChatHeader.tsx
Added aria labels to chat Participant Button 
https://skype.visualstudio.com/SPOOL/_workitems/edit/2756510
=> Participant Button should announce open and close state 

GROOMME.md, packages/communication-react/CHANGELOG.md
TODO:
* Groom the CHANGELOG file.
* Delete the GROOMME marker file.
Merge this PR *before* kicking off the release branch creation.
=> Groom branch for 1.2.2-beta.1

.github/workflows/ci.yml, change/@internal-acs-ui-common-d53791ad-80f4-4ca2-a959-fbe3aec7a613.json, change/@internal-calling-component-bindings-3232790a-2215-4e10-a978-fb58a6a083a1.json, change/@internal-calling-stateful-client-80fbfe66-c6d2-4688-a64b-4312c0bf5c56.json, change/@internal-chat-component-bindings-f3f2975a-29f1-4c1e-9100-ef21ffb687d4.json, change/@internal-chat-stateful-client-2d81888c-89b9-4fbc-8ae9-9f0ad2496cdb.json, change/@internal-react-components-468d4bab-b099-49ee-8730-3af3bb4f2c70.json, change/@internal-react-composites-973aa683-da76-4cd6-957a-b99a34bfba13.json, change/@internal-storybook-b010a147-464d-4fc0-a1b8-9b8d4d234267.json
Disable stable ci and add dummy changelogs
helps with Cherrypicks into release
=> disable stable ci in beta release

change/@internal-storybook-fec8e214-2663-4bb5-99d2-5bb2d01df605.json, packages/storybook/.storybook/preview.tsx, packages/storybook/stories/BestPractices.stories.mdx
Add a best practices doc with some initial best practices
We need to highlight some of the things we say Contoso should implement. This will be built out over time
Please review by checking the storybook link when generated by PR.
=> Add a best practices doc with some initial best practices

packages/react-composites/src/composites/localization/locales/de-DE/strings.json, packages/react-composites/src/composites/localization/locales/en-GB/strings.json, packages/react-composites/src/composites/localization/locales/es-ES/strings.json, packages/react-composites/src/composites/localization/locales/fr-FR/strings.json, packages/react-composites/src/composites/localization/locales/it-IT/strings.json, packages/react-composites/src/composites/localization/locales/ja-JP/strings.json, packages/react-composites/src/composites/localization/locales/ko-KR/strings.json, packages/react-composites/src/composites/localization/locales/nl-NL/strings.json, packages/react-composites/src/composites/localization/locales/pt-BR/strings.json, packages/react-composites/src/composites/localization/locales/ru-RU/strings.json, packages/react-composites/src/composites/localization/locales/tr-TR/strings.json, packages/react-composites/src/composites/localization/locales/zh-CN/strings.json, packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Updates localization strings for 1.3.0
Update locale strings added in 1.3.0
=> 1.3.0 localization strings

packages/react-components/src/localization/locales/de-DE/strings.json, packages/react-components/src/localization/locales/en-GB/strings.json, packages/react-components/src/localization/locales/es-ES/strings.json, packages/react-components/src/localization/locales/fr-FR/strings.json, packages/react-components/src/localization/locales/it-IT/strings.json, packages/react-components/src/localization/locales/ja-JP/strings.json, packages/react-components/src/localization/locales/ko-KR/strings.json, packages/react-components/src/localization/locales/nl-NL/strings.json, packages/react-components/src/localization/locales/pt-BR/strings.json, packages/react-components/src/localization/locales/ru-RU/strings.json, packages/react-components/src/localization/locales/tr-TR/strings.json, packages/react-components/src/localization/locales/zh-CN/strings.json, packages/react-components/src/localization/locales/zh-TW/strings.json
Cherry pick in localization strings
Updates strings per GH action
=> Update localization strings 1.3.0

.github/workflows/ci.yml, packages/react-composites/playwright.config.ts
Start generating a JSON test results artifact for playwright tests in CI.
First step towards tracking runtime / flakiness of these tests.
=> Generate test results artifact for `playwright` tests in CI

.github/workflows/ci.yml
Set CI flavors for beta cherry picks
allow for testing of cherry picked code
=> Update CI for Beta release

change/@internal-calling-component-bindings-1675e7f0-3e7f-455d-aabc-732a2193129d.json, change/@internal-react-composites-46de2528-8074-49d1-9dbc-4789bdb2ff6c.json, packages/calling-component-bindings/review/beta/calling-component-bindings.api.md, packages/calling-component-bindings/src/callControlSelectors.ts, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/src/composites/CallComposite/components/buttons/ScreenShare.tsx
Update screen share button selector
Fixes issue where end user could share screen in interop scenario and join with their screen being shared
https://skype.visualstudio.com/SPOOL/_workitems/edit/2896710
Checked with CallWithChat sample and interop meeting
=> In lobby screen share fix

samples/Chat/src/app/ChatHeader.tsx, samples/Chat/src/app/ChatScreen.tsx, samples/Chat/src/app/PeopleButton.tsx
Learnt there were missing conditional compilation directives when porting over sources to the hero sample repo: https://github.com/Azure-Samples/communication-services-web-chat-hero/pull/69
Run sample locally for beta  && stable build flavor.
=> Add missing conditional compilation directives to chat sample

common/config/workflows/matrix.json
Similar to #2192, backporting workflow config
=> Backport workflow config

change/@internal-react-composites-5e69a332-7de4-4d99-8ad4-d9a8216eeda6.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallComposite/Strings.tsx, packages/react-composites/src/composites/CallComposite/components/CallControls.tsx, packages/react-composites/src/composites/CallWithChatComposite/Strings.tsx, packages/react-composites/src/composites/CallWithChatComposite/components/DesktopMoreButton.tsx, packages/react-composites/src/composites/CallWithChatComposite/components/MoreDrawer.tsx, packages/react-composites/src/composites/localization/locales/en-US/strings.json
Change show dialpad button label name to follow naming conventions
=> Change show dialpad button label name

change/@internal-react-composites-2c33e66a-05c4-4eb5-a830-5b35fdc8a6f1.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
=> Sort enum variants 

change/@internal-react-composites-36aefc17-d7f8-41c0-963f-7ed35d3596c0.json, packages/react-composites/src/composites/CallComposite/utils/Utils.ts
Add helper comment to Utils function handling end call screen
=> Add helper comment to Utils function handling end call screen

change/@internal-react-components-d82957db-3d0c-4bad-94f6-dd5b1639426a.json, change/@internal-react-composites-59bf493f-f02c-4cc1-a136-7069c8023113.json, packages/react-components/src/components/RemoteVideoTile.tsx, packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
Cherry pick #2392 to 1.3.2-beta.1 release
=> Cherry pick #2392

change/@internal-react-composites-45166d46-6c6b-463b-9288-f2967910b838.json, packages/react-composites/src/composites/CallComposite/components/buttons/Devices.tsx
Add permissions for Camera and Microphone in devices options
https://skype.visualstudio.com/SPOOL/_workitems/edit/3015752
=> Add permissions for Camera and Microphone in devices options

change/@internal-react-composites-45166d46-6c6b-463b-9288-f2967910b838.json, packages/react-composites/src/composites/CallComposite/components/buttons/Devices.tsx
* Add permissions for Camera and Microphone in devices options
* Change files
* minor change
(cherry picked from commit f0c90da7db7f12fcc036638701f3166ce94f678d)
=> Add permissions for Camera and Microphone in devices options (#2402)

change/@internal-react-composites-f16f9b8d-c4e9-46fa-b28c-22e02b63227a.json, packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
Cherry pick of https://github.com/Azure/communication-ui-library/pull/2407
=> [cherry pick] Point fix for blank call ended page

change/@internal-react-composites-825c806c-7788-4a9c-be79-e02c2c17464f.json, packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx, packages/react-composites/src/composites/CallComposite/pages/ConfigurationPage.tsx
cherry-picks for beta branch from PR https://github.com/Azure/communication-ui-library/pull/2404
=> [cherry-pick] Suppress camera access error bar error for consumer.

change/@internal-react-composites-5c5b138d-56e9-4522-8fd5-640b55398642.json, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
Bugfix for Config screen flashing for 2 seconds after leaving a call
=> Bugfix for Config screen flashing for 2 seconds after leaving a call

change/@internal-react-composites-cee95ec4-d426-45f2-8eac-6e7aa158b0c1.json, packages/react-composites/src/composites/common/SidePaneHeader.tsx
Fix theming of side pane close button
https://skype.visualstudio.com/SPOOL/_workitems/edit/3007783
Tested on sample with custom theme.semanticColors.bodyBackground
=> Fix theming of side pane close button

change/@internal-react-composites-0c1fbf71-b066-4288-b003-a41e925191df.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/review/stable/react-composites.api.md, packages/react-composites/src/composites/CallComposite/Strings.tsx, packages/react-composites/src/composites/CallComposite/components/CallControls.tsx, packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx, packages/react-composites/src/composites/CallWithChatComposite/Strings.tsx, packages/react-composites/src/composites/localization/locales/en-US/strings.json
=> [Cherry Pick] Fix dtmfDialpadPlaceHolderText spelling and restrict it to beta builds

packages/communication-react/CHANGELOG.md, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/review/stable/react-components.api.md, packages/react-components/src/components/MessageThread.tsx
Cherry pick #2449 to stable release branch
=> Cherry pick #2449 to stable release branch (and update changelog with new change)

change/@internal-react-composites-40288e5b-06bf-4b35-afe3-f33e70b2d9ed.json, packages/react-composites/src/composites/common/PeoplePaneContent.tsx
Cherry pick changes from this PR https://github.com/Azure/communication-ui-library/pull/2454 into release for 1.4.0
fixes blocking bug:  https://skype.visualstudio.com/SPOOL/_workitems/edit/3030567
=> [1.4.0 fix] remove teams user fix cherry pick

change/@internal-react-composites-4588bf72-bbfd-44d0-bd37-38ce8574b55e.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/review/stable/react-composites.api.md, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts
=> [cherry-pick] Revert breaking API change in CallEndedListener callback

change/@internal-calling-stateful-client-e108bf17-9cc5-4189-9c8f-66acc0b48938.json, packages/calling-stateful-client/review/stable/calling-stateful-client.api.md, packages/calling-stateful-client/src/index.ts, packages/communication-react/review/stable/communication-react.api.md, packages/communication-react/src/index.ts
=> [cherry-pick] Only export DeclarativeCallAgent in beta builds

samples/CallWithChat/src/app/App.tsx, samples/Calling/src/app/App.tsx
Call Readiness feature is incomplete, opting it out for samples for now
when working on call readiness features need to flip those values to True
=> Opt out call readiness features from samples

change/@internal-react-components-07857752-97a4-45c4-aa09-94d66add76de.json, change/@internal-react-composites-3f887cc4-39ab-422a-805e-0acda349314c.json, packages/react-components/src/localization/LocalizationProvider.tsx, packages/react-composites/src/composites/CallComposite/CallComposite.tsx, packages/react-composites/src/composites/CallComposite/Strings.tsx, packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx, packages/react-composites/src/composites/CallComposite/components/CallControls.tsx, packages/react-composites/src/composites/CallComposite/components/CallPane.tsx, packages/react-composites/src/composites/common/AddPeopleButton.tsx, packages/react-composites/src/composites/common/PeoplePaneContent.tsx, packages/react-composites/src/composites/common/SidePaneHeader.tsx, packages/react-composites/src/composites/common/TabHeader.tsx
Add missing PSTN and 1-N conditional compilation primarily for people pane
If one of the two (PSTN or 1-N) GA's first, then all dependencies should be available.
=> Add missing PSTN and 1-N conditional compilation

change-beta/@azure-communication-react-c8a91d1a-3ad8-40e0-9ee6-af0097bf2411.json, change/@azure-communication-react-c8a91d1a-3ad8-40e0-9ee6-af0097bf2411.json, samples/CallWithChat/package.json
Add conditional start to callwithchat, so CallWithChat start command will take the right flavor
=> Add conditional start to callwithchat

change-beta/@azure-communication-react-d9966a93-50ec-4519-83d3-4a1afa04536d.json, change/@azure-communication-react-d9966a93-50ec-4519-83d3-4a1afa04536d.json, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/storybook/stories/CallComposite/snippets/QuickstartPSTN.snippet.tsx
Update documentation for alternateCallerId format
To prevent errors during runtime stemming from the usage of a poorly formatted caller id
=> Update documentation for alternateCallerId format

change-beta/@azure-communication-react-faa449f6-83d2-4e33-b62a-40d339d953b9.json, change/@azure-communication-react-faa449f6-83d2-4e33-b62a-40d339d953b9.json, packages/react-components/src/components/MessageThread.tsx
* moving check into the while loop condition
* Change files
* nan suggestions
=> moving check into the while loop condition (#2550)

change-beta/@azure-communication-react-f7481d0f-808c-4c03-a7a5-5f3f93017de2.json, change/@azure-communication-react-f7481d0f-808c-4c03-a7a5-5f3f93017de2.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/Dialpad/Dialpad.tsx, packages/react-components/src/components/VideoTile.test.tsx, packages/react-components/src/components/VideoTile.tsx, packages/react-components/src/components/utils/useLongPress.ts
VideoTile 'onLongTouch' support
=> VideoTile 'onLongTouch' support

.github/workflows/npm-release-publish.yml, .github/workflows/run-td-build.yml, change/@azure-communication-react-92511221-c33b-456e-9e79-313396460d94.json
Print inputs on npm-release workflow in summary as suggested in this article: https://nakamasato.medium.com/how-to-review-github-actions-dispatch-workflows-inputs-with-environment-protection-f981428e3514
https://skype.visualstudio.com/SPOOL/_workitems/edit/3038839
Ran npm-release.yml and produced this run summary:
https://github.com/Azure/communication-ui-library/actions/runs/3595224897
(the run failed because it didn't pass the branch name protection rule)
=> Print inputs on npm-release workflow in summary

change-beta/@azure-communication-react-dce48b29-fb24-4998-a482-9260568af83c.json, change/@azure-communication-react-dce48b29-fb24-4998-a482-9260568af83c.json, samples/CallWithChat/src/app/App.tsx, samples/Calling/src/app/App.tsx
Enable Call Readiness for samples
Enable Call Readiness for samples so it's ready for bug bash
=> Enable Call Readiness for samples

change-beta/@azure-communication-react-97b146b9-4459-4ba6-9538-7f529351ffa8.json, change/@azure-communication-react-97b146b9-4459-4ba6-9538-7f529351ffa8.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update calling SDK beta version to `1.10.0-beta.1`
New version released (and it will be needed for video background work)
CI should verify regressions here
=> Update calling SDK beta version to `1.10.0-beta.1`

change-beta/@azure-communication-react-762fe1bf-86d0-41db-a024-5b8a62f7e074.json, change/@azure-communication-react-762fe1bf-86d0-41db-a024-5b8a62f7e074.json, packages/react-composites/src/composites/CallComposite/utils/MediaGalleryUtils.ts
fix spelling error in function name
Makes Edward happy. (correct spelling)
validated functionality locally and run in CI tests.
=> [styling fix] Fix spelling mistake in mediaGalleryUtils

change-beta/@azure-communication-react-77512195-cb86-4a65-8c90-1fd39cfac690.json, change/@azure-communication-react-77512195-cb86-4a65-8c90-1fd39cfac690.json, packages/acs-ui-common/src/identifier.test.ts, packages/acs-ui-common/src/identifier.ts
* update parsing function to handle phone numbers
* add test for E.164 formatting
* Change files
=> [BugFix BetaBlocking] Fix PSTN start Call (#2739)

change-beta/@azure-communication-react-e840e1e1-da2b-449d-8b82-237eacbbffd0.json, change/@azure-communication-react-e840e1e1-da2b-449d-8b82-237eacbbffd0.json, packages/calling-component-bindings/src/utils/callUtils.ts
* update parsing function to handle phone numbers
* add test for E.164 formatting
* Change files
* update lobby check to include early media state
* Change files
=> [BugFix] PSTN connecting to call dont show config screen (#2740)

change-beta/@azure-communication-react-fecac74b-e7cc-487a-8c4c-78b5251452cf.json, change/@azure-communication-react-fecac74b-e7cc-487a-8c4c-78b5251452cf.json, packages/calling-component-bindings/src/handlers/createCommonHandlers.ts, packages/calling-component-bindings/src/utils/videoGalleryUtils.ts
* Switch video seamlessly from different devices
---------
Co-authored-by: Nan Jiang <jinan@microsoft.com>
=> Cherrypick multiple stream fix

change-beta/@azure-communication-react-3403a61e-01e3-4fc3-a75c-6b80a7e66cf2.json, change/@azure-communication-react-3403a61e-01e3-4fc3-a75c-6b80a7e66cf2.json, packages/storybook/stories/snippets/CommunicationAsTeamsUser.snippet.tsx
Update storybook for cte display name
=> Update storybook for cte display name

change-beta/@azure-communication-react-3403a61e-01e3-4fc3-a75c-6b80a7e66cf2.json, change-beta/@azure-communication-react-c2fee8c8-af95-431d-a3de-921bb984dfb7.json, change/@azure-communication-react-3403a61e-01e3-4fc3-a75c-6b80a7e66cf2.json, change/@azure-communication-react-c2fee8c8-af95-431d-a3de-921bb984dfb7.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallComposite/adapter/OnFetchProfileCallback.ts, packages/storybook/stories/snippets/CommunicationAsTeamsUser.snippet.tsx
[Update storybook for cte display name (](https://github.com/Azure/communication-ui-library/commit/5015084db2de7044b745cae4fd994db6227a2ece)https://github.com/Azure/communication-ui-library/pull/2766[)](https://github.com/Azure/communication-ui-library/commit/5015084db2de7044b745cae4fd994db6227a2ece) 
* Add code snippet for displayName override
=> Cherry-pick displayname storybook snippet

change-beta/@azure-communication-react-9fa8ccc6-8812-4f7c-af2c-90eaf345f5ce.json, change/@azure-communication-react-9fa8ccc6-8812-4f7c-af2c-90eaf345f5ce.json, change/@internal-storybook-04144a15-3059-4900-8bf8-b951a1ba65fe.json, packages/storybook/stories/NonReact/NonReactComposites.stories.mdx
Cherry picking js bundle page change from storybook and porting into release branch
=> Revert "Alkwa/update js storybook (#2127)" (#2768)

change-beta/@azure-communication-react-58d77579-064e-4c19-8f74-7b62d5a4222b.json, change/@azure-communication-react-58d77579-064e-4c19-8f74-7b62d5a4222b.json, packages/react-components/review/beta/react-components.api.md, packages/react-components/review/stable/react-components.api.md, packages/react-components/src/components/Caption.tsx, packages/react-components/src/components/index.ts, packages/storybook/stories/INTERNAL/Captions/Caption/Caption.stories.tsx
Caption component containing avatar, username and caption text 
Storybook 
=> Caption component

packages/calling-component-bindings/review/beta/calling-component-bindings.api.md, packages/calling-component-bindings/src/baseSelectors.ts, packages/calling-component-bindings/src/captionsSelector.ts, packages/calling-component-bindings/src/hooks/usePropsFor.ts, packages/calling-component-bindings/src/index.ts, packages/calling-stateful-client/src/CallDeclarativeCommon.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/src/index.ts, packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts
selectors for captions realted components
=> Captions selectors

change-beta/@azure-communication-react-c74fc2ab-4923-4214-9404-49c12187cba7.json, change/@azure-communication-react-c74fc2ab-4923-4214-9404-49c12187cba7.json, packages/react-components/src/components/VideoGallery/DefaultLayout.tsx, packages/react-components/src/components/VideoGallery/FloatingLocalVideoLayout.tsx, packages/react-components/src/components/VideoGallery/OverflowGallery.tsx, packages/react-components/src/components/VideoGallery/utils/videoGalleryLayoutUtils.test.tsx, packages/react-components/src/components/VideoGallery/utils/videoGalleryLayoutUtils.ts
Refactor to rename horizontal gallery to overflow gallery appropriately
Cleaner code
Relying on CI.
=> [Refactor] Rename horizontal gallery to overflow gallery appropriately

packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx, packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx, packages/react-composites/src/composites/common/CaptionsBanner.tsx
Captions component in call and callwithchat composite
Uploading demo.mov…
=> Captions component in composite

change-beta/@azure-communication-react-d0d9fb45-5c61-4302-bae6-b5f8c43c4f97.json, change/@azure-communication-react-d0d9fb45-5c61-4302-bae6-b5f8c43c4f97.json, packages/react-composites/src/composites/CallWithChatComposite/styles/CallWithChatCompositeStyles.ts
Cherry pick of PR https://github.com/Azure/communication-ui-library/pull/2861
Cherry-pick to beta release branch
=> [Cherry-pick] Fix call with chat flickering

change-beta/@azure-communication-react-60c12cb5-66b2-4e8f-a06f-5a574969d38e.json, change/@azure-communication-react-60c12cb5-66b2-4e8f-a06f-5a574969d38e.json, packages/calling-component-bindings/review/beta/calling-component-bindings.api.md, packages/calling-component-bindings/src/handlers/createCommonHandlers.ts, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
Rename arguments to have the full word 'background'
Beta release ARB review feedback https://apiview.dev/Assemblies/Review/42fe51ace1e24184a42351ff89044352/845d376ba6994d87a3d02a3aee6a1c14?diffRevisionId=b0c9851682b3416da8d054c8993c77ea&doc=False&diffOnly=True
=> Rename blurred background callback args

change-beta/@azure-communication-react-a44490ad-73fc-48b8-9ca5-47be397384fd.json, change/@azure-communication-react-a44490ad-73fc-48b8-9ca5-47be397384fd.json, packages/communication-react/CHANGELOG.beta.md, packages/react-components/src/components/VideoGallery.tsx, packages/react-components/src/components/VideoGallery/FloatingLocalVideoLayout.tsx, packages/react-components/src/components/VideoGallery/styles/VideoGalleryResponsiveVerticalGallery.styles.ts
Cherry pick #2863 to release/1.5.1 beta.2
=> Cherry pick #2863 to release/1.5.1 beta.2

change-beta/@azure-communication-react-60c12cb5-66b2-4e8f-a06f-5a574969d38e.json, change/@azure-communication-react-60c12cb5-66b2-4e8f-a06f-5a574969d38e.json, packages/calling-component-bindings/review/beta/calling-component-bindings.api.md, packages/calling-component-bindings/src/handlers/createCommonHandlers.ts, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
Cherry pick #2866 to release/1.5.1 beta.2
=> Cherry pick #2866 to release/1.5.1 beta.2

change-beta/@azure-communication-react-c50ae151-9bc3-48d4-914b-ba33a2d815f3.json, change/@azure-communication-react-c50ae151-9bc3-48d4-914b-ba33a2d815f3.json, packages/react-components/src/components/CameraButton.tsx
Remove effects options from camera button in case handler is not passed
=> Remove effects options from camera button in case handler is not passed

change-beta/@azure-communication-react-261b7c4f-670c-4035-96f4-b7656e22b635.json, change/@azure-communication-react-261b7c4f-670c-4035-96f4-b7656e22b635.json, packages/communication-react/CHANGELOG.beta.md
Better release note for vertical gallery
=> Better release note for vertical gallery

change-beta/@azure-communication-react-e5de7bc8-8a32-434a-a337-10b8869f5f68.json, change/@azure-communication-react-e5de7bc8-8a32-434a-a337-10b8869f5f68.json, common/scripts/babel-conditional-preprocess.js
Give it a quick try:
https://astexplorer.net/#/gist/543b36b851a91eb90b49633d9003a008/ce81044c709fa401ec6ea3833a2f088b21ce9d43
=> Update cc plugin for array and classMethod params

change-beta/@azure-communication-react-b5c59c38-b83a-466c-ac6e-ca06b99ae9b7.json, change/@azure-communication-react-b5c59c38-b83a-466c-ac6e-ca06b99ae9b7.json, packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
Add Video Effects Pane to Call Composite
=> Add Video Effects Pane to Call Composite

change-beta/@azure-communication-react-1232d1f2-3332-47d1-b1e7-11f15b17de6b.json, change/@azure-communication-react-1232d1f2-3332-47d1-b1e7-11f15b17de6b.json, packages/communication-react/CHANGELOG.beta.md
Sync updates to changelog with release branch release/1.5.1-beta.2
=> Prerelease changelog sync 

change-beta/@azure-communication-react-05815eee-b018-418a-a89a-c79d7e92ab17.json, change/@azure-communication-react-05815eee-b018-418a-a89a-c79d7e92ab17.json, common/scripts/babel-conditional-preprocess.js, packages/react-composites/src/composites/CallComposite/CallComposite.tsx
Add switch case support for cc
=> Add switch case support for cc

packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
=> Bubble up captions event

packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx, packages/react-composites/src/composites/common/CaptionsBanner.tsx
Captions banner should not show up when on local hold
https://skype.visualstudio.com/SPOOL/_workitems/edit/3217743
Tested with samples 
=> Captions banner should not show up when on local hold

packages/react-components/src/components/Caption.tsx, packages/react-components/src/components/CaptionsSettingsModal.tsx, packages/react-components/src/components/styles/Captions.style.ts, packages/react-components/src/components/styles/CaptionsSettingsModal.styles.ts, packages/react-composites/src/composites/common/Drawer/SpokenLanguageDrawer.styles.ts
Fix captions ui bug
https://skype.visualstudio.com/SPOOL/_workitems/edit/3217733
https://skype.visualstudio.com/SPOOL/_workitems/edit/3217735
https://skype.visualstudio.com/SPOOL/_workitems/edit/3217737
https://skype.visualstudio.com/SPOOL/_workitems/edit/3217740
Tested on samples
=> Fix captions ui bug

packages/react-components/src/components/CaptionsSettingsModal.tsx, packages/react-composites/src/composites/common/CaptionsBannerMoreButton.tsx, packages/react-composites/src/composites/common/ControlBar/DesktopMoreButton.tsx
Fix captions dropdown dismiss when new captions come
=> Fix captions dropdown

packages/communication-react/review/beta/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/CaptionsSettingsModal.tsx, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallComposite/Strings.tsx, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/index.ts, packages/react-composites/src/composites/CallComposite/index.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/common/CaptionsSettingsModal.tsx, packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx, packages/react-composites/src/composites/common/Drawer/SpokenLanguageDrawer.tsx
=> Captions API changes

packages/calling-component-bindings/review/beta/calling-component-bindings.api.md, packages/calling-component-bindings/src/handlers/createCommonHandlers.ts, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/CaptionsSettingsModal.tsx, packages/react-components/src/components/StartCaptionsButton.tsx, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts
=> Change name from captionsOptions to options

packages/storybook/stories/INTERNAL/Captions/CaptionsBanner/CaptionsBanner.stories.tsx
Fixed Captions banner storybook bug
=> Fixed captions storybook

change-beta/@azure-communication-react-84db7e54-3eb9-4bf4-8c4b-4e99dd807e72.json, change/@azure-communication-react-84db7e54-3eb9-4bf4-8c4b-4e99dd807e72.json, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update @azure/communication-calling stable version to 1.12.1
Housekeeping
n/a - CI should validate this
=> Update @azure/communication-calling stable version to 1.12.1

change-beta/@azure-communication-react-acf4142d-6b4c-4890-920c-35155cb27b64.json, change/@azure-communication-react-acf4142d-6b4c-4890-920c-35155cb27b64.json, packages/calling-component-bindings/src/errorBarSelector.ts, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/ErrorBar.tsx, packages/react-components/src/localization/locales/en-US/strings.json
Add errors for video effects
https://skype.visualstudio.com/SPOOL/_workitems/edit/3210924
https://skype.visualstudio.com/SPOOL/_workitems/edit/3210929
=> Add errors for video effects

GROOMME.md, change-beta/@azure-communication-react-1a3d5b11-5584-423b-98bc-2df894e072b2.json, change/@azure-communication-react-1a3d5b11-5584-423b-98bc-2df894e072b2.json, packages/communication-react/CHANGELOG.beta.md
=> Groom changelog /1.5.1 beta.3

change-beta/@azure-communication-react-91244af4-0dbf-4946-ab8c-181e1c776bfe.json, change/@azure-communication-react-91244af4-0dbf-4946-ab8c-181e1c776bfe.json, packages/calling-stateful-client/review/beta/calling-stateful-client.api.md, packages/calling-stateful-client/src/TypeGuards.ts, packages/calling-stateful-client/src/index.ts, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/utils/Utils.ts
Fix captions related console error on ACS call 
=> Fix captions related console error on ACS call 

packages/calling-stateful-client/review/beta/calling-stateful-client.api.md, packages/calling-stateful-client/src/TypeGuards.ts, packages/calling-stateful-client/src/index.ts, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/utils/Utils.ts
Cherry picking captions console error PR into release branch
https://github.com/Azure/communication-ui-library/pull/2974
https://github.com/Azure/communication-ui-library/pull/2974 should be included in release
=> Cherry picking captions console error PR into release branch

change-beta/@azure-communication-react-37bf2a7b-cabb-4727-9258-83bbab1eef41.json, change/@azure-communication-react-37bf2a7b-cabb-4727-9258-83bbab1eef41.json, packages/chat-component-bindings/src/messageThreadSelector.ts, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx, packages/react-components/src/types/ChatMessage.ts, packages/storybook/stories/MessageThread/snippets/CustomBlockedMessage.snippet.tsx
removing false from type
ARB request
=> [Chat] Updating the warning text to be string | undefined

GROOMME.md, change-beta/@azure-communication-react-4430d3ca-af2b-4217-93f7-23b95854cc09.json, change/@azure-communication-react-4430d3ca-af2b-4217-93f7-23b95854cc09.json, packages/communication-react/CHANGELOG.beta.md
=> Groom changelog /1.5.1 beta.4

change-beta/@azure-communication-react-5e45f329-b422-4de0-b3ce-72e024036579.json, change/@azure-communication-react-5e45f329-b422-4de0-b3ce-72e024036579.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
Fix breaking changes of create adapter from client
=> Fix breaking changes of create adapter from client

change-beta/@azure-communication-react-37bf2a7b-cabb-4727-9258-83bbab1eef41.json, change-beta/@azure-communication-react-46cbf89c-7094-4b7d-b374-951e2d5f9121.json, change-beta/@azure-communication-react-5e45f329-b422-4de0-b3ce-72e024036579.json, change-beta/@azure-communication-react-f6b4b8a1-c762-4136-8285-d8cd9166436f.json, change/@azure-communication-react-37bf2a7b-cabb-4727-9258-83bbab1eef41.json, change/@azure-communication-react-46cbf89c-7094-4b7d-b374-951e2d5f9121.json, change/@azure-communication-react-5e45f329-b422-4de0-b3ce-72e024036579.json, change/@azure-communication-react-f6b4b8a1-c762-4136-8285-d8cd9166436f.json, packages/chat-component-bindings/src/messageThreadSelector.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/ChatMessage/ChatMessageComponent.tsx, packages/react-components/src/components/ChatMessage/ChatMessageComponentAsEditBox.tsx, packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx, packages/react-components/src/components/MessageThread.tsx, packages/react-components/src/types/ChatMessage.ts, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/review/stable/react-composites.api.md, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts, packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts, packages/react-composites/src/composites/ChatComposite/index.ts, packages/storybook/stories/Adapters/Adapters.stories.mdx, packages/storybook/stories/MessageThread/snippets/CustomBlockedMessage.snippet.tsx, packages/storybook/stories/MessageThread/snippets/Default.snippet.tsx
Cherry pick the changes from release branch into main
Updating main with changes
=> [Chat] Cherry pick the changes into main

change-beta/@azure-communication-react-889046ea-997d-4116-acc6-b463c36bcded.json, change/@azure-communication-react-889046ea-997d-4116-acc6-b463c36bcded.json, common/config/babel/.babelrc.js, common/config/webpack/sampleapp.webpack.config.js, packages/acs-ui-common/jest.config.js, packages/calling-component-bindings/jest.config.js, packages/calling-stateful-client/jest.config.js, packages/chat-component-bindings/jest.config.js, packages/chat-stateful-client/jest.config.js, packages/react-components/jest.config.js, packages/react-components/src/components/VideoGallery.tsx, packages/react-composites/jest.config.js, packages/react-composites/tests/app/testapp.webpack.config.js, samples/StaticHtmlComposites/webpack.config.js
Allows for CC^2 of the click to call feature
to make sure the in progress feature does not also go out in the release until ready.
CI will guide us.
=> [Click to Call] Move the conditional flag to be in progress as well

change-beta/@azure-communication-react-ec1ea006-42b0-4426-bcb4-7f278db85f6b.json, change/@azure-communication-react-ec1ea006-42b0-4426-bcb4-7f278db85f6b.json, packages/react-components/src/components/VideoGallery.test.tsx, packages/react-components/src/components/VideoTile.tsx, packages/react-composites/src/composites/CallComposite/components/MediaGallery.tsx
Cherrypick #3051 to 1.5.1-beta.5 release branch
=> Cherry-pick `No default persona coin size` to 1.5.1-beta.5 release branch

packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallComposite/index.ts, packages/react-composites/src/composites/common/VideoEffectsPane.tsx
Rename None videoeffect as per ARB feedback
=> Rename None videoeffect as per ARB feedback

change-beta/@azure-communication-react-4c67c679-9d78-4791-b7b5-a15318b90729.json, change/@azure-communication-react-4c67c679-9d78-4791-b7b5-a15318b90729.json, packages/react-components/src/components/DevicesButton.tsx
* Prevent device contextMenu to be dismissed
=> Fix device dismiss when new captions come (#3102)

change-beta/@azure-communication-react-0adf6835-f5d4-495c-87cb-b3f65f3bddb4.json, change/@azure-communication-react-0adf6835-f5d4-495c-87cb-b3f65f3bddb4.json, packages/react-components/package.json
clean up
same package defined two times in the `package.json`
CI
=> Removed Duplicated Package Reference

.github/workflows/npm-release-publish.yml, change-beta/@azure-communication-react-bdab6ffd-dd12-4bc7-b296-70ac6e063871.json, change/@azure-communication-react-bdab6ffd-dd12-4bc7-b296-70ac6e063871.json
* Fix release pipeline for switch flavor
=> Fix release pipeline for switch flavor to support CCC (#3124)

packages/communication-react/CHANGELOG.beta.md
Update changelog from cherrypicks
=> Update release/1.5.1.-beta.5 changelog after cherry picks

change-beta/@azure-communication-react-8672c364-da36-42d0-9e59-8bd81916245b.json, change/@azure-communication-react-8672c364-da36-42d0-9e59-8bd81916245b.json, packages/react-components/src/components/InputBoxComponent.tsx, packages/react-components/src/components/utils.ts
Implement clean up changes from previous PRs
Clean up and clarify
Storybook
=> [Chat] Mention Refactor Part 1

.github/workflows/alpha-release.yml, .github/workflows/ci.yml, .github/workflows/create-prerelease-branch.yml, .github/workflows/deploy-azure-webapps.yml, .github/workflows/deploy-release-azure-webapps.yml, .github/workflows/deploy-storybook.yml, .github/workflows/nightly-cd.yml, .github/workflows/npm-release-publish.yml, .github/workflows/publish-chromatic.yml, .github/workflows/stress-test-ui-tests.yml, .github/workflows/update-api-files.yml, .github/workflows/update-snapshots.yml, change-beta/@azure-communication-react-2a5ed691-ddc2-4916-aa65-9e4dd3abc54f.json, change/@azure-communication-react-2a5ed691-ddc2-4916-aa65-9e4dd3abc54f.json
- Increase `rush install` with options for --max-install-attempts to 3
- Mitigate sporadic installation failure
Fixes #3144
=> [CI] Increase 'rush install' max retry attemps to 3

change-beta/@azure-communication-react-20ceb770-a1a1-47e2-902d-b8cd5d4210a9.json, change/@azure-communication-react-20ceb770-a1a1-47e2-902d-b8cd5d4210a9.json, packages/react-components/src/components/TextFieldWithMention/mentionTagUtils.test.ts, packages/react-components/src/components/TextFieldWithMention/mentionTagUtils.ts
Add unit tests for the mention logic handlers
Verify robustness and confidence in future changes
Command line `rushx test`
=> [Chat] Mention logic unit tests

change-beta/@azure-communication-react-69f99fff-de17-4e71-a4c4-4e40dd534c61.json, change/@azure-communication-react-69f99fff-de17-4e71-a4c4-4e40dd534c61.json, packages/react-composites/src/composites/CallComposite/CallComposite.tsx, packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx
* using the correct host layer id for the pipip
* Change files
* uploading changelog
* the layerhost for the modal is not being created in stable and it looks like we used the wrong drawer layerhost
=> Alkwa/pipip modal layer fix (#3204)

change-beta/@azure-communication-react-dab29af7-5620-4f22-b378-de7057d65448.json, change/@azure-communication-react-dab29af7-5620-4f22-b378-de7057d65448.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/review/stable/react-components.api.md, packages/react-components/src/components/MicrophoneButton.tsx, packages/react-components/src/localization/locales/ar-SA/strings.json, packages/react-components/src/localization/locales/de-DE/strings.json, packages/react-components/src/localization/locales/en-GB/strings.json, packages/react-components/src/localization/locales/en-US/strings.json, packages/react-components/src/localization/locales/es-ES/strings.json, packages/react-components/src/localization/locales/fi-FI/strings.json, packages/react-components/src/localization/locales/fr-FR/strings.json, packages/react-components/src/localization/locales/he-IL/strings.json, packages/react-components/src/localization/locales/it-IT/strings.json, packages/react-components/src/localization/locales/ja-JP/strings.json, packages/react-components/src/localization/locales/ko-KR/strings.json, packages/react-components/src/localization/locales/nb-NO/strings.json, packages/react-components/src/localization/locales/nl-NL/strings.json, packages/react-components/src/localization/locales/pl-PL/strings.json, packages/react-components/src/localization/locales/pt-BR/strings.json, packages/react-components/src/localization/locales/ru-RU/strings.json, packages/react-components/src/localization/locales/sv-SE/strings.json, packages/react-components/src/localization/locales/tr-TR/strings.json, packages/react-components/src/localization/locales/zh-CN/strings.json, packages/react-components/src/localization/locales/zh-TW/strings.json
Change micPrimaryActionSplitButtonTitle to microphonePrimaryActionSplitButtonTitle
For 1.6.0 stable release. microphone is consistent with other strings in this interface
n/a
=> API feeedback: Update mic -> microphone

.github/workflows/deploy-azure-webapps.yml, change-beta/@azure-communication-react-588952f4-83aa-456c-ac32-acfd3fe0e0b8.json, change/@azure-communication-react-588952f4-83aa-456c-ac32-acfd3fe0e0b8.json
-  Change deploy azure webapp to use OIDC
=> [CI] Change deploy azure webapp to use OIDC

change-beta/@azure-communication-react-3d4a9eaf-29d5-4829-b0dd-305d061945d8.json, change/@azure-communication-react-3d4a9eaf-29d5-4829-b0dd-305d061945d8.json, packages/acs-ui-common/review/beta/acs-ui-common.api.md, packages/acs-ui-common/review/stable/acs-ui-common.api.md, packages/acs-ui-common/src/identifier.ts, packages/acs-ui-common/src/index.ts, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/utils/Utils.ts, packages/react-composites/src/composites/ChatComposite/adapter/AzureCommunicationChatAdapter.ts
porting util function refactor to common 041d76135f9fca377caa4a99ecf91c65c90153e3
git cherry-pick 041d76135f9fca377caa4a99ecf91c65c90153e3
=> Alkwa/move util func to common (#3221)

.github/workflows/deploy-feature-azure-webapps.yml, .github/workflows/deploy-release-azure-webapps.yml, change-beta/@azure-communication-react-fed1b30a-b166-4ae0-8a71-87efd5a9bd80.json, change/@azure-communication-react-fed1b30a-b166-4ae0-8a71-87efd5a9bd80.json
Build the library prior to the sample apps
Build was failing due to not finding the dependencies
CI
=> Fix up deploy pipelines

change-beta/@azure-communication-react-7d52f99e-a511-4b68-9e24-d63abb254863.json, change/@azure-communication-react-7d52f99e-a511-4b68-9e24-d63abb254863.json, packages/storybook/.storybook/preview.tsx, packages/storybook/stories/AdhocCalling.stories.mdx, packages/storybook/stories/Transfer.stories.mdx, packages/storybook/stories/snippets/AdhocCalling.snippet.tsx, packages/storybook/stories/snippets/transfer/Transfer.snippet.tsx, packages/storybook/stories/snippets/transfer/TransferWithDialogPrompt.snippet.tsx
Add Adhoc calling conceptual docs page to storybook. 
This PR also includes: 
- a code snippet to show how to customize display name and avatars in the context of adhoc calling.
- code snippet fixes
To provide Contoso with knowledge about Adhoc calling.
Tested in local storybook
=> Update storybook with adhoc calling page

change-beta/@azure-communication-react-d3823cc2-b7ab-4269-875d-7f4d3a5e983e.json, change/@azure-communication-react-d3823cc2-b7ab-4269-875d-7f4d3a5e983e.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/review/stable/react-components.api.md, packages/react-components/src/components/ChatMessage/ChatMessageComponent.tsx, packages/react-components/src/components/MessageThread.tsx, packages/storybook/stories/MessageThread/snippets/Default.snippet.tsx
update onCancelMessageEdit to onCancelEditMessage for 1.6.0 release
ARB feedback
n/a
=> update onCancelMessageEdit to onCancelEditMessage for 1.6.0 release

change-beta/@azure-communication-react-5165355b-4190-44d9-a35f-a2bd2ce57002.json, change/@azure-communication-react-5165355b-4190-44d9-a35f-a2bd2ce57002.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/storybook/.storybook/main.js, packages/storybook/package.json
Update webpack4 dependency to webpack5
Preparing for storybook v7
CI
=> Remove webpack4 dependency from storybook

change-beta/@azure-communication-react-140086ee-f15c-43ce-939a-7e65c9ea8d82.json, change/@azure-communication-react-140086ee-f15c-43ce-939a-7e65c9ea8d82.json, common/config/babel/.babelrc.js
Moves c2c changes to be in next beta release
open up new form factors in new release
=> [Click to call] remove in progress c2c feature from ccc

change-beta/@azure-communication-react-beede71f-91a1-455c-bb0c-d5e5e3adbd1b.json, change/@azure-communication-react-beede71f-91a1-455c-bb0c-d5e5e3adbd1b.json, common/config/babel/.babelrc.js
=> Removing OVC from in progress features

change-beta/@azure-communication-react-9eb17401-fd1a-40a0-b2a1-f6ba96400203.json, change/@azure-communication-react-9eb17401-fd1a-40a0-b2a1-f6ba96400203.json, packages/storybook/stories/CallComposite/CallCompositeDocs.tsx, packages/storybook/stories/VideoGallery/VideoGallery.stories.tsx
bumps the versioning in storybook entries for click to call related feature beta banners
lets contoso know which beta they need to use to try the new feature
=> [Click to Call] Bump versioning in c2c configuration storybook pages.

change-beta/@azure-communication-react-ded23d85-6181-4d41-838c-68d37699b65b.json, change/@azure-communication-react-ded23d85-6181-4d41-838c-68d37699b65b.json, packages/react-components/src/components/VideoGallery/styles/FloatingLocalVideo.styles.ts, samples/Calling/src/app/App.tsx, samples/Calling/src/app/utils/AppUtils.ts, samples/Calling/src/app/views/CallScreen.tsx, samples/Calling/src/app/views/HomeScreen.tsx
- Fix CTE query arg
- Remove console log in FloatingLocalVideo.styles.ts
- Update adhoc calling TextBox strings and styles
Calling sample is not working as intended:
https://github.com/Azure/communication-ui-library/assets/79475487/99fdd295-fa33-4e95-9651-fc39ebbdbdc0
Local Calling sample testing
https://github.com/Azure/communication-ui-library/assets/79475487/16d9910d-367d-4ebb-b115-9e27f046e888
=> [Release] Fix CTE query arg in Calling sample and remove console log

change-beta/@azure-communication-react-2b5d44f4-6271-4681-bf8e-0d15501d7e5e.json, change/@azure-communication-react-2b5d44f4-6271-4681-bf8e-0d15501d7e5e.json, packages/storybook/stories/Examples/TeamsInterop/TeamsInteropDocs.tsx
- Update permission for File Sharing storybook page
=> [Doc] Update permission for File Sharing storybook page

change-beta/@azure-communication-react-ed7ac1bd-5912-4128-bc0e-2e3550d64152.json, change/@azure-communication-react-ed7ac1bd-5912-4128-bc0e-2e3550d64152.json, packages/communication-react/CHANGELOG.beta.md
Update Changelog
Add public preview to file sharing and fix indentation for Bug Fixes section
=> Add public preview to file sharing and fix indentation for Bug Fixes section

change-beta/@azure-communication-react-13b17c76-b8b4-40dd-8e19-523f37d59a91.json, change/@azure-communication-react-13b17c76-b8b4-40dd-8e19-523f37d59a91.json, packages/react-components/src/components/ChatMessage/ChatMessageComponentAsEditBox.tsx
Cherry Pick - Resolve issue where the number zero appeared in edit box
=> Cherry Pick - Resolve issue where the number zero appeared in edit box (#3295)

change-beta/@azure-communication-react-a5db2a2a-c837-489f-8680-96084cc58fc5.json, change/@azure-communication-react-a5db2a2a-c837-489f-8680-96084cc58fc5.json, packages/communication-react/CHANGELOG.beta.md
=> Update changelog for hotfixes

change-beta/@azure-communication-react-715db8e2-a925-4606-9665-b6f2bc32d280.json, change/@azure-communication-react-715db8e2-a925-4606-9665-b6f2bc32d280.json, packages/communication-react/CHANGELOG.beta.md
Add adhoc calling feature description in release notes
To have a more complete description of new features available
=> Add adhoc calling feature description

change-beta/@azure-communication-react-2ce4a42a-2913-4636-b910-6291ab403e2e.json, change/@azure-communication-react-2ce4a42a-2913-4636-b910-6291ab403e2e.json, packages/chat-component-bindings/src/messageThreadSelector.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/src/index.ts, packages/react-components/review/beta/react-components.api.md, packages/react-components/review/stable/react-components.api.md, packages/react-components/src/components/ChatMessage/ChatMessageContent.tsx, packages/react-components/src/components/FileDownloadCards.tsx, packages/react-components/src/components/MessageThread.test.tsx, packages/react-components/src/components/MessageThread.tsx, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/review/stable/react-composites.api.md, packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx, packages/react-composites/src/mocks/FakeChatAdapterArgs.ts, packages/react-composites/tests/app/chat/FakeAdapterApp.tsx, packages/react-composites/tests/browser/chat/hermetic/FileSharing.test.ts, packages/storybook/stories/MessageThread/placeholdermessages.ts, packages/storybook/stories/MessageThread/snippets/WithInlineImageMessage.snippet.tsx
- Introduce BaseFileMetadata that is used for different type fileMetadata types
=> [Chat] New file metadata types

change-beta/@azure-communication-react-8e753589-87e6-4a35-89be-cd4390f79131.json, change/@azure-communication-react-8e753589-87e6-4a35-89be-cd4390f79131.json, packages/storybook/stories/VideoGallery/VideoGallery.stories.tsx
Fix small issues with videoGallery storybook page
fixes issues found during OCE rotation
tested locally
=> [Bugfix] VideoGallery storybook page updates

change-beta/@azure-communication-react-b0b4088c-70b0-4fa9-928e-d4e1641fb2fa.json, change/@azure-communication-react-b0b4088c-70b0-4fa9-928e-d4e1641fb2fa.json, packages/react-components/src/components/FileCard.test.tsx
Increasing code coverage by adding missing unit tests
Increase code coverage
Under `/packages/react-components/src/components`
`rushx test`
=> [Chat] Adding Unit Test for FileCard

.github/workflows/alpha-release.yml, .github/workflows/breaking-change-check.yml, .github/workflows/ci.yml, .github/workflows/create-prerelease-branch.yml, .github/workflows/create-release-branch.yml, .github/workflows/deploy-azure-webapps.yml, .github/workflows/deploy-feature-azure-webapps.yml, .github/workflows/deploy-release-azure-webapps.yml, .github/workflows/deploy-storybook.yml, .github/workflows/nightly-cd.yml, .github/workflows/npm-release-publish.yml, .github/workflows/publish-chromatic.yml, .github/workflows/stress-test-ui-tests.yml, .github/workflows/update-api-files.yml, .github/workflows/update-snapshots.yml, change-beta/@azure-communication-react-543ae4c7-38dc-4f97-86e1-25c419c987ec.json, change/@azure-communication-react-543ae4c7-38dc-4f97-86e1-25c419c987ec.json, rush.json
Migrate to current Node JS
Keep current with node, prior to major feature dev.
https://github.com/nodejs/release#release-schedule
Local build; CI
=> [v2.0] Update to NodeJS v20

packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts, packages/react-composites/tests/app/lib/MockCallAdapter.ts
=> Remove joinCallwithOptions from release branch

change-beta/@azure-communication-react-cc6abe33-9676-4a91-98f0-48fa10744b3a.json, change/@azure-communication-react-cc6abe33-9676-4a91-98f0-48fa10744b3a.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/react-components-v2/jest.config.js, packages/react-components-v2/jestSetup.js, packages/react-components-v2/package.json, packages/react-components-v2/src/test-utils/isConformant.ts
- Add react conformance griffel dependency
- Removed some of the disabled tests
- Updated how tests warning are processed because of ReactDOM.render usage in `@fluentui/react-conformance-griffel` and `@fluentui/react-conformance`
Add checks for styling
Tests run
=> Add react conformance griffel dependency

change-beta/@azure-communication-react-6c9ae46c-b180-4800-91d4-946cdbd88264.json, change/@azure-communication-react-6c9ae46c-b180-4800-91d4-946cdbd88264.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/chat-stateful-client/package.json, packages/chat-stateful-client/src/StatefulChatClient.test.ts, packages/fake-backends/package.json, packages/fake-backends/src/FakeChatClient.ts, packages/fake-backends/src/FakeChatThreadClient.ts, packages/fake-backends/src/utils.ts, packages/react-composites/package.json
Bump version to 1.0.0-beta.10
New version bump
=> [Chat] Update the Signaling SDK dependencies

.github/workflows/create-prerelease-branch.yml, .github/workflows/create-release-branch.yml, change-beta/@azure-communication-react-4dc7ebde-7ad3-450f-9ce9-4463d0054dc9.json, change/@azure-communication-react-4dc7ebde-7ad3-450f-9ce9-4463d0054dc9.json, docs/releases/creating-a-release.md
Fixed a script for release branch creation
The values weren't up to date
=> Fixed a script for release branch creation

change-beta/@azure-communication-react-49ee0bd7-2b10-41df-a89c-c75a2caae92e.json, change/@azure-communication-react-49ee0bd7-2b10-41df-a89c-c75a2caae92e.json, samples/CallWithChat/src/app/utils/ShakeToSendLogs.tsx, samples/Calling/src/app/utils/ShakeToSendLogs.tsx, samples/Chat/src/app/utils/ShakeToSendLogs.tsx
Add check to make sure `DeviceOrientationEvent` exists before referencing it
Threw an error in safari
=> Add check to make sure `DeviceOrientationEvent` exists before referencing it

change-beta/@azure-communication-react-49ee0bd7-2b10-41df-a89c-c75a2caae92e.json, change/@azure-communication-react-49ee0bd7-2b10-41df-a89c-c75a2caae92e.json, samples/CallWithChat/src/app/utils/ShakeToSendLogs.tsx, samples/Calling/src/app/utils/ShakeToSendLogs.tsx, samples/Chat/src/app/utils/ShakeToSendLogs.tsx
=> Cherry pick #3453 to 1.7.0 release branch

change-beta/@azure-communication-react-842ee2f3-f8df-428b-92b2-c8cbcf790422.json, change/@azure-communication-react-842ee2f3-f8df-428b-92b2-c8cbcf790422.json, samples/Calling/src/app/views/HomeScreen.tsx
=> Fix sample teamslink cc bugs

change-beta/@azure-communication-react-842ee2f3-f8df-428b-92b2-c8cbcf790422.json, change/@azure-communication-react-842ee2f3-f8df-428b-92b2-c8cbcf790422.json, samples/Calling/src/app/views/HomeScreen.tsx
=> Remove redundant cc comment(Cherry pick from #3455)

change-beta/@azure-communication-react-6bc62996-6bef-42e9-aef3-3367f46c667e.json, change/@azure-communication-react-6bc62996-6bef-42e9-aef3-3367f46c667e.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/src/index.ts, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/ImageGallery.tsx, packages/react-components/src/components/index.ts
Not exposing the styles as props in public api
Developers will not have the ability to change styles of the image gallery ui component
=> [Chat] Remove the styles prop from the image gallery

change-beta/@azure-communication-react-13912d78-a82f-408a-812a-35882aee63f9.json, change/@azure-communication-react-13912d78-a82f-408a-812a-35882aee63f9.json, packages/react-composites/src/composites/localization/locales/ar-SA/strings.json, packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json, packages/react-composites/src/composites/localization/locales/de-DE/strings.json, packages/react-composites/src/composites/localization/locales/es-ES/strings.json, packages/react-composites/src/composites/localization/locales/fi-FI/strings.json, packages/react-composites/src/composites/localization/locales/fr-FR/strings.json, packages/react-composites/src/composites/localization/locales/he-IL/strings.json, packages/react-composites/src/composites/localization/locales/it-IT/strings.json, packages/react-composites/src/composites/localization/locales/ja-JP/strings.json, packages/react-composites/src/composites/localization/locales/ko-KR/strings.json, packages/react-composites/src/composites/localization/locales/nb-NO/strings.json, packages/react-composites/src/composites/localization/locales/nl-NL/strings.json, packages/react-composites/src/composites/localization/locales/pl-PL/strings.json, packages/react-composites/src/composites/localization/locales/pt-BR/strings.json, packages/react-composites/src/composites/localization/locales/ru-RU/strings.json, packages/react-composites/src/composites/localization/locales/sv-SE/strings.json, packages/react-composites/src/composites/localization/locales/tr-TR/strings.json, packages/react-composites/src/composites/localization/locales/zh-CN/strings.json, packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
new localization strings are fetched
Update before 1.7.0 release
=> Updating localized resource files

change-beta/@azure-communication-react-13912d78-a82f-408a-812a-35882aee63f9.json, change/@azure-communication-react-13912d78-a82f-408a-812a-35882aee63f9.json, packages/react-composites/src/composites/localization/locales/ar-SA/strings.json, packages/react-composites/src/composites/localization/locales/cs-CZ/strings.json, packages/react-composites/src/composites/localization/locales/de-DE/strings.json, packages/react-composites/src/composites/localization/locales/es-ES/strings.json, packages/react-composites/src/composites/localization/locales/fi-FI/strings.json, packages/react-composites/src/composites/localization/locales/fr-FR/strings.json, packages/react-composites/src/composites/localization/locales/he-IL/strings.json, packages/react-composites/src/composites/localization/locales/it-IT/strings.json, packages/react-composites/src/composites/localization/locales/ja-JP/strings.json, packages/react-composites/src/composites/localization/locales/ko-KR/strings.json, packages/react-composites/src/composites/localization/locales/nb-NO/strings.json, packages/react-composites/src/composites/localization/locales/nl-NL/strings.json, packages/react-composites/src/composites/localization/locales/pl-PL/strings.json, packages/react-composites/src/composites/localization/locales/pt-BR/strings.json, packages/react-composites/src/composites/localization/locales/ru-RU/strings.json, packages/react-composites/src/composites/localization/locales/sv-SE/strings.json, packages/react-composites/src/composites/localization/locales/tr-TR/strings.json, packages/react-composites/src/composites/localization/locales/zh-CN/strings.json, packages/react-composites/src/composites/localization/locales/zh-TW/strings.json
Cherry picked from commit 0dec467fa8ae588dbc358b9671af6ff058d3b1be (#3467)
=> [Cherry pick]Updating localized resource files 

change-beta/@azure-communication-react-026218a3-76c7-4924-bbdb-113d20f9ffc9.json, change/@azure-communication-react-026218a3-76c7-4924-bbdb-113d20f9ffc9.json, samples/Calling/src/app/App.tsx, samples/Calling/src/app/utils/AppUtils.ts, samples/Calling/src/app/views/HomeScreen.tsx
Fixed CC statements for the stable build
CI and hero apps
=> [Calling] Fixed CC statements for the calling sample app

.github/workflows/create-prerelease-branch.yml, change-beta/@azure-communication-react-d854ae98-d28c-4983-ae37-29904c437cb5.json, change/@azure-communication-react-d854ae98-d28c-4983-ae37-29904c437cb5.json, docs/releases/creating-a-release.md, samples/tests/package.json
- Updated stable-remove-beta-version option to stable-remove-beta-suffix in create-prerelease-branch.yml
- Removed duplicate for communication-chat dependency
=> Updated stable-remove-beta-version option to stable-remove-beta-suffix in create-prerelease-branch.yml

change-beta/@azure-communication-react-dd16bf3b-7cab-4e8e-b20b-21874b9e9b8e.json, change/@azure-communication-react-dd16bf3b-7cab-4e8e-b20b-21874b9e9b8e.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/chat-component-bindings/package.json, packages/chat-stateful-client/package.json, packages/communication-react/package.json, packages/fake-backends/package.json, packages/react-composites/package.json, packages/storybook/package.json, samples/CallWithChat/package.json, samples/Chat/package.json, samples/ComponentExamples/package.json, samples/Server/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Upgrade Chat stable version to 1.3.2
=> Upgrade Chat stable version to 1.3.2

change-beta/@azure-communication-react-0a84a13c-bd96-4cf4-b4cd-2fb12d1e14ec.json, change/@azure-communication-react-0a84a13c-bd96-4cf4-b4cd-2fb12d1e14ec.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/chat-stateful-client/package.json, packages/chat-stateful-client/src/StatefulChatClient.test.ts, packages/fake-backends/package.json, packages/fake-backends/src/FakeChatClient.ts, packages/fake-backends/src/FakeChatThreadClient.ts, packages/fake-backends/src/utils.ts, packages/react-composites/package.json
- updated @azure/communication-signaling to 1.0.0-beta.20
- commented changes that were added to 1.0.0-beta.19 as they were skipped in 1.0.0-beta.20 but will be added later
=> Signaling update

change-beta/@azure-communication-react-44ac2ec4-d5af-47ee-849a-1f3ac688ba81.json, change/@azure-communication-react-44ac2ec4-d5af-47ee-849a-1f3ac688ba81.json, packages/react-components/src/components/MessageThread.tsx, packages/react-components/src/components/styles/MessageThread.styles.ts, packages/storybook/stories/MessageThread/MessageThread.stories.tsx
Ensure scroll to bottom still works and mentions still look the same
Storybook
=> Fix up scrolling and mention styling

change-beta/@azure-communication-react-b1b92f0f-0ec1-4ddc-ae7c-595830df52fc.json, change/@azure-communication-react-b1b92f0f-0ec1-4ddc-ae7c-595830df52fc.json, packages/react-components/src/components/FileUploadCards.test.tsx
Creating new unit test for FileUploadCards
Increasing test coverage
`rushx test FileUploadCards.test.tsx`
=> [Chat] Adding unit test to FileUploadCards

change-beta/@azure-communication-react-7ce65af2-0c5f-4dc6-92ad-175f10cad45c.json, change/@azure-communication-react-7ce65af2-0c5f-4dc6-92ad-175f10cad45c.json, packages/storybook/stories/INTERNAL/Captions/CaptionsSettingsModal/CaptionsSettingsModal.stories.tsx
Add missing properties
SB story was broken
See storybook link in PR
=> Fix captions setting modal storybook page

change-beta/@azure-communication-react-ccbbcda2-ea1d-4bcc-975e-f0275412307f.json, change/@azure-communication-react-ccbbcda2-ea1d-4bcc-975e-f0275412307f.json, packages/react-components/src/components/styles/MessageThread.styles.ts, packages/react-components/src/theming/FluentThemeProvider.tsx, packages/react-composites/tests/app/index.html, samples/StaticHtmlComposites/index.css
=> Add NorthStar CSS to Theme

GROOMME.md, change-beta/@azure-communication-react-aea13c8a-88fd-4dec-8304-b6c3250bb28e.json, change/@azure-communication-react-aea13c8a-88fd-4dec-8304-b6c3250bb28e.json, packages/communication-react/CHANGELOG.stable.md
Groomed changelog
1.8.0 stable release
=> Groom changelog for 1.8.0 stable release

packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx
Resolve issues with avatar size and overlap for the composite component.
=> Resolve issues with avatar size and overlap for composite component.

change-beta/@azure-communication-react-c6fe0d7b-d3c5-4068-820e-f4bf68563a4e.json, change/@azure-communication-react-c6fe0d7b-d3c5-4068-820e-f4bf68563a4e.json, packages/react-components/src/components/MessageThread.tsx
Wrap the custom renderer with ChatMessage for styling purposes.
=> Wrap custom message renderer

change-beta/@azure-communication-react-17ce0b3a-5996-49b9-8042-28377c78bd8e.json, change/@azure-communication-react-17ce0b3a-5996-49b9-8042-28377c78bd8e.json, packages/storybook/stories/Setup.stories.mdx
Updated setup steps fro testing library version and beta features
Some info weren't clear and included mistakes
Ran the steps from the Setup page
=> Updated dependencies for Setup page in storybook

change-beta/@azure-communication-react-2500a9e1-d78a-4c0c-bfa5-b92e6ef17012.json, change/@azure-communication-react-2500a9e1-d78a-4c0c-bfa5-b92e6ef17012.json, packages/react-components/src/components/ChatMessage/ChatMessageComponentAsEditBox.tsx, packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx, packages/react-components/src/components/MessageThread.tsx, packages/react-components/src/components/styles/ChatMessageComponent.styles.ts, packages/react-components/src/components/styles/MessageThread.styles.ts, packages/react-components/src/components/styles/v8StyleShim.ts, packages/react-components/src/theming/v9ThemeShim.ts, packages/storybook/stories/MessageThread/MessageThread.stories.tsx, packages/storybook/stories/MessageThread/snippets/CustomMessages.snippet.tsx
- added shims for translating v8 styles to react css ones to be used in style prop
- fixed custom rendering for messages
- updated styling
storybook
=> Styles update for FluentUI v9 components

packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx, packages/react-components/src/components/MessageThread.tsx, packages/react-components/src/components/styles/MessageThread.styles.ts
=> [FluentUI] Resolve issue with read receipt layout and appearance for fluent migration.

change-beta/@azure-communication-react-0234eef3-0f43-4703-b1d2-1706d50157c9.json, change/@azure-communication-react-0234eef3-0f43-4703-b1d2-1706d50157c9.json, packages/react-components/src/components/ChatMessage/ChatMessageActionMenu.tsx, packages/react-components/src/components/ChatMessage/ChatMessageActionsFlyout.tsx
Updated styles for menu and pop up
Storybook
=> Menu paddings update

.github/workflows/create-release-branch.yml, change-beta/@azure-communication-react-ca2da813-c291-487f-b53d-dad836c0e951.json, change/@azure-communication-react-ca2da813-c291-487f-b53d-dad836c0e951.json
=> [Pipeline] New comment to explain issue

change-beta/@azure-communication-react-8c68ab31-f111-45c0-89c2-48462a534a66.json, change/@azure-communication-react-8c68ab31-f111-45c0-89c2-48462a534a66.json, packages/react-components/src/components/ChatMessage/ChatMessageComponentAsEditBox.tsx, packages/react-components/src/components/MessageThread.tsx, packages/react-components/src/components/styles/ChatMessageComponent.styles.ts, packages/react-components/src/components/styles/EditBox.styles.ts, packages/react-components/src/components/styles/MessageThread.styles.ts
Updated styles for hover and select actions
Updated pointer style for menu button
Update for edit message width
| Was | Now |
|----|-----|
| ![image](https://github.com/Azure/communication-ui-library/assets/98852890/90edbd04-234e-4aac-a884-020c35fc75fb)| ![image](https://github.com/Azure/communication-ui-library/assets/98852890/0c039a72-08fe-47ea-a6c6-79d70aa65848)|
Storybook
=> Edit message styles update

.github/workflows/update-chat-snapshots.yml, change-beta/@azure-communication-react-ce6b90c9-164d-472a-84ec-86e43e1dd5c5.json, change/@azure-communication-react-ce6b90c9-164d-472a-84ec-86e43e1dd5c5.json, packages/react-components/src/components/ChatMessage/ChatMessageActionMenu.tsx
=> Fix up padding when action button is not visible

change-beta/@azure-communication-react-b1c7047f-a4ac-49d8-9c44-eb61b551b2d3.json, change/@azure-communication-react-b1c7047f-a4ac-49d8-9c44-eb61b551b2d3.json, packages/react-components/src/components/styles/ChatMessageComponent.styles.ts, packages/react-components/src/components/styles/MessageThread.styles.ts
Font weight was off and layout with large names caused the date to be squished.
Visually incorrect
Storybook, CI
=> Fix up font and layout for date / name in messages

packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx, packages/react-components/src/components/MessageThread.tsx, packages/react-components/src/components/styles/MessageThread.styles.ts, packages/react-components/src/theming/FluentV9ThemeProvider.tsx
Fluent requires the MakeStyles Use Hooks to be called inside of components that are nested inside a fluentProvider.
This PR Restructures MessageThreads and FluentProvider, so that these calls happen in wrapper components that are nested in fluentProvider.
=> More RTL Fixes

packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx, packages/react-components/src/components/styles/MessageThread.styles.ts
=> [FluentUI] Correct padding between messages

packages/react-components/src/components/styles/MessageThread.styles.ts, packages/react-components/src/theming/v9ThemeShim.ts
Fixed:
- position for edit button for CallWithChat
- new message button
- black border
=> Fixed P2 issues from bug bash #3

change-beta/@azure-communication-react-2202f831-4c53-48ce-817d-b1796b9f6b89.json, change/@azure-communication-react-2202f831-4c53-48ce-817d-b1796b9f6b89.json
=> [Image Gallery] Release notes Changelogs

change-beta/@azure-communication-react-09b67249-b797-47a9-b54d-956318dd74ac.json, change/@azure-communication-react-09b67249-b797-47a9-b54d-956318dd74ac.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/VerticalGallery.tsx, packages/react-components/src/components/VideoGallery.test.tsx, packages/react-components/src/components/VideoGallery.tsx, packages/react-components/src/components/VideoGallery/DefaultLayout.tsx, packages/react-components/src/components/VideoGallery/FloatingLocalVideoLayout.tsx, packages/react-components/src/components/VideoGallery/LargeGalleryLayout.tsx, packages/react-components/src/components/VideoGallery/Layout.ts, packages/react-components/src/components/VideoGallery/OverflowGallery.tsx, packages/react-components/src/components/VideoGallery/SpeakerVideoLayout.tsx, packages/react-components/src/components/VideoGallery/styles/FloatingLocalVideo.styles.ts, packages/react-components/src/localization/LocalizationProvider.tsx, packages/react-components/src/localization/locales/en-US/strings.json, packages/react-composites/src/composites/CallComposite/CallComposite.tsx, packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx, packages/react-composites/src/composites/CallComposite/components/MediaGallery.tsx, packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx, packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx, packages/react-composites/src/composites/common/ControlBar/DesktopMoreButton.tsx, packages/storybook/stories/VideoGallery/VideoGallery.stories.tsx, packages/storybook/stories/VideoGallery/snippets/WithHorizontalGallery.snippet.tsx, packages/storybook/stories/VideoGallery/snippets/WithVerticalGallery.snippet.tsx, packages/storybook/stories/controlsUtils.ts
API updates to address ARB and internal reviewer concerns
Couple comments to resolve in API diff: https://apiview.dev/Assemblies/Review/42fe51ace1e24184a42351ff89044352/d9084cc81bf3489d9b2224775c900651?diffRevisionId=b7aa4cf82821453ab0fa5fe06d33eb6e&doc=False&diffOnly=True
built and tested locally
=> [Gallery layouts] ARB updates

change-beta/@azure-communication-react-1d3ed886-3d29-4086-979b-8000c81018f6.json, change/@azure-communication-react-1d3ed886-3d29-4086-979b-8000c81018f6.json, packages/react-composites/tests/browser/call/hermetic/OverflowGallery.test.ts, packages/react-composites/tests/browser/call/hermetic/VideoGallery.test.ts
Updates CC for the snapshot tests and gallery layouts
Release is including snapshot tests for layouts that are not being shipped
tested tests locally
=> [Gallery layouts] fix gallery layout cc in snapshot tests

change-beta/@azure-communication-react-865026b1-1716-448a-a708-fb12cc4e5f14.json, change/@azure-communication-react-865026b1-1716-448a-a708-fb12cc4e5f14.json, common/config/webpack/sampleapp.webpack.config.js, packages/communication-react/scripts/verifyDependencies.js, packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx, packages/react-composites/tests/app/testapp.webpack.config.js, packages/storybook/.storybook/main.js, packages/storybook/jest.config.js, packages/storybook/stories/Examples/IncomingCallAlerts/IncomingCallAlertsDocs.tsx, packages/storybook/stories/Theming.stories.mdx, packages/storybook/tsconfig.json, samples/CallWithChat/tsconfig.json, samples/Calling/tsconfig.json, samples/Chat/tsconfig.json
Removed North* Wrapper dependency and updated documentation
No need for it anymore
Sample apps
=> Documentation update to remove NorthStar dependency information

change-beta/@azure-communication-react-0faa6b35-8492-49a8-845c-a485ec42ab50.json, change/@azure-communication-react-0faa6b35-8492-49a8-845c-a485ec42ab50.json, packages/react-composites/tests/browser/call/hermetic/VideoGallery.test.ts
Same as last PR more CC to fix snapshot updates for beta release
gets stuck on layout not supported
Tested locally
=> [Gallery layouts] more gallery cc fixes for beta release

change-beta/@azure-communication-react-0faa6b35-8492-49a8-845c-a485ec42ab50.json, change-beta/@azure-communication-react-1d3ed886-3d29-4086-979b-8000c81018f6.json, change-beta/@azure-communication-react-865026b1-1716-448a-a708-fb12cc4e5f14.json, change-beta/@azure-communication-react-bb6d5502-a3b8-44ea-8d64-ca46a6b009a9.json, change/@azure-communication-react-0faa6b35-8492-49a8-845c-a485ec42ab50.json, change/@azure-communication-react-1d3ed886-3d29-4086-979b-8000c81018f6.json, change/@azure-communication-react-865026b1-1716-448a-a708-fb12cc4e5f14.json, change/@azure-communication-react-bb6d5502-a3b8-44ea-8d64-ca46a6b009a9.json, common/config/webpack/sampleapp.webpack.config.js, packages/communication-react/scripts/verifyDependencies.js, packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx, packages/react-composites/tests/app/testapp.webpack.config.js, packages/react-composites/tests/browser/call/hermetic/OverflowGallery.test.ts, packages/react-composites/tests/browser/call/hermetic/VideoGallery.test.ts, packages/storybook/.storybook/main.js, packages/storybook/jest.config.js, packages/storybook/stories/Examples/IncomingCallAlerts/IncomingCallAlertsDocs.tsx, packages/storybook/stories/Theming.stories.mdx, packages/storybook/tsconfig.json, samples/CallWithChat/tsconfig.json, samples/Calling/tsconfig.json, samples/Chat/tsconfig.json
- Documentation update to remove NorthStar dependency information
- Fix gallery layout cc in snapshot tests
- Update MyMessage options menu to correct size/visibility on mobile browsers
- More gallery cc fixes for beta release
=> Release 1.9.0 beta.1 Cherry Picks

change-beta/@azure-communication-react-cb09d724-b482-4d5c-a9d3-14770c38a710.json, change/@azure-communication-react-cb09d724-b482-4d5c-a9d3-14770c38a710.json, packages/react-components/src/localization/locales/ar-SA/strings.json, packages/react-components/src/localization/locales/cs-CZ/strings.json, packages/react-components/src/localization/locales/de-DE/strings.json, packages/react-components/src/localization/locales/en-GB/strings.json, packages/react-components/src/localization/locales/es-ES/strings.json, packages/react-components/src/localization/locales/fi-FI/strings.json, packages/react-components/src/localization/locales/fr-FR/strings.json, packages/react-components/src/localization/locales/he-IL/strings.json, packages/react-components/src/localization/locales/it-IT/strings.json, packages/react-components/src/localization/locales/ja-JP/strings.json, packages/react-components/src/localization/locales/ko-KR/strings.json, packages/react-components/src/localization/locales/nb-NO/strings.json, packages/react-components/src/localization/locales/nl-NL/strings.json, packages/react-components/src/localization/locales/pl-PL/strings.json, packages/react-components/src/localization/locales/pt-BR/strings.json, packages/react-components/src/localization/locales/ru-RU/strings.json, packages/react-components/src/localization/locales/sv-SE/strings.json, packages/react-components/src/localization/locales/tr-TR/strings.json, packages/react-components/src/localization/locales/zh-CN/strings.json, packages/react-components/src/localization/locales/zh-TW/strings.json
Updates the verticalGallery string key
ARB API changes needed the key to be camelCase, this is to mitigate waiting on strings from translation to come back. Strings already have translations just need a key change
Built locally
=> [Vertical Gallery] vertical gallery string update

change-beta/@azure-communication-react-494b2dcf-5c51-49c3-9bc6-8154aeccdeea.json, change/@azure-communication-react-494b2dcf-5c51-49c3-9bc6-8154aeccdeea.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update communication calling dependency, beta and stable
Make sure we have the latest calling version
=> Update communication calling dependency

GROOMME.md, change/@azure-communication-react-38471fb2-ad18-4a41-bac9-2318ec49f7ae.json, change/@azure-communication-react-f5d83c0b-27de-4ba7-9e01-e66384a2d53f.json, packages/communication-react/CHANGELOG.beta.md
Changelog grooming for 1.10.0-beta.1
Release time!
=> Create groom me file for groom changelog branch

change-beta/@azure-communication-react-e44b7afb-dc09-45d2-b4a9-7b262c2f91f8.json, change/@azure-communication-react-e44b7afb-dc09-45d2-b4a9-7b262c2f91f8.json, packages/calling-component-bindings/review/beta/calling-component-bindings.api.md, packages/calling-component-bindings/review/stable/calling-component-bindings.api.md, packages/calling-component-bindings/src/handlers/createCommonHandlers.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
Updates the start call handler to reference the type `CommunicationIdentifier`
Simplifies the code to be more readable as well as resolving issue where if identifier is passed in returns with a 480 network error
None
Validated locally. to be CP's into beta and smoke tested there as well
=> [Bugfix] StartCall updates

change-beta/@azure-communication-react-e44b7afb-dc09-45d2-b4a9-7b262c2f91f8.json, change/@azure-communication-react-e44b7afb-dc09-45d2-b4a9-7b262c2f91f8.json, packages/calling-component-bindings/review/beta/calling-component-bindings.api.md, packages/calling-component-bindings/review/stable/calling-component-bindings.api.md, packages/calling-component-bindings/src/handlers/createCommonHandlers.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
* Fix start call to handle identifiers
* Change files
Cherrypick in startcall handler updates
We want this in for this release to help with C2C
Tested locally when went into main will validate on release branch as well
=> [Bugfix] StartCall updates (#3712)

change-beta/@azure-communication-react-88b901bc-e801-48a5-9ebd-f2f41a2f9308.json, change/@azure-communication-react-88b901bc-e801-48a5-9ebd-f2f41a2f9308.json, packages/react-composites/src/composites/common/PeoplePaneContent.tsx
Cherry picks participant removal into release
Fixes issue for release to remove participants
tested locally and merged into main
=> [Cherry-pick] Participant removal cp

change-beta/@azure-communication-react-7138979a-ff04-486b-b662-2bc8ef86c2da.json, change/@azure-communication-react-7138979a-ff04-486b-b662-2bc8ef86c2da.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Updates to the most recent calling SDK
Keeps us up to date with the calling SDK
- fixes issue in previous version that broke background blur
Validated blur is back locally
=> [SDK updates] update beta calling version to 1.19.1-beta.2

change-beta/@azure-communication-react-7138979a-ff04-486b-b662-2bc8ef86c2da.json, change/@azure-communication-react-7138979a-ff04-486b-b662-2bc8ef86c2da.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
=> [SDK update] Update Calling SDK in release

change-beta/@azure-communication-react-778f1a13-3eb0-4d0a-bebd-73e2d5ff5d27.json, change/@azure-communication-react-778f1a13-3eb0-4d0a-bebd-73e2d5ff5d27.json, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/calling-stateful-client/src/CallAgentDeclarative.test.ts, packages/communication-react/package.json, packages/react-composites/package.json, packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts, packages/storybook/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
* update calling stable
* update stable lock
* Change files
* fix testing types
=> [SDK update] Update Calling SDK stable version (#3738)

change-beta/@azure-communication-react-5a6aa299-b88c-4198-9b91-e441d521f529.json, change/@azure-communication-react-5a6aa299-b88c-4198-9b91-e441d521f529.json, packages/react-components/src/components/ChatMessage/ChatMessageActionMenu.tsx
- fixed navigate by keyboard for the menu button
Chat sample app
=> [Chat] Add handlers for Enter and Space keys for message menu button

change-beta/@azure-communication-react-f4a54c37-e352-4b1b-b77e-b7b6656f098f.json, change/@azure-communication-react-f4a54c37-e352-4b1b-b77e-b7b6656f098f.json, packages/communication-react/package.json
=> Update @azure/communication-chat peerDependency to match devDependency

change-beta/@azure-communication-react-6d5238cf-08ac-40d5-a583-bf48d7dd50b4.json, change/@azure-communication-react-6d5238cf-08ac-40d5-a583-bf48d7dd50b4.json, packages/calling-stateful-client/src/CallSubscriber.ts
Cherry-pick #3779 to release/1.10.0
incude in stable release
=> [Cherry-pick to 1.10.0] Fix local stream rendering when screensharing

change-beta/@azure-communication-react-00b18e5f-5847-4bd0-8d7d-0e7a6b239ceb.json, change/@azure-communication-react-00b18e5f-5847-4bd0-8d7d-0e7a6b239ceb.json, common/config/babel/.babelrc.js
Conditonal compiled out in progress features 
=> Conditonal compiled out in progress features 

packages/communication-react/CHANGELOG.beta.md
=> Update prerelease branch changelog

change-beta/@azure-communication-react-00b18e5f-5847-4bd0-8d7d-0e7a6b239ceb.json, change/@azure-communication-react-00b18e5f-5847-4bd0-8d7d-0e7a6b239ceb.json, common/config/babel/.babelrc.js, packages/communication-react/CHANGELOG.beta.md
Cherry pick the following PR to the release branch and update changelog to reflect removed features
https://github.com/Azure/communication-ui-library/pull/3815/commits
=> Cherry pick changes to the release branch

change-beta/@azure-communication-react-bf47e3ac-ff4c-49e0-a749-e2d6378ae361.json, change/@azure-communication-react-bf47e3ac-ff4c-49e0-a749-e2d6378ae361.json, packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
Fix prop propagation from CWC -> CC
Broken in #3806 
Verified locally in CWC sample
=> Fix custom branding props

packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md
=> Update release branch API

change-beta/@azure-communication-react-70f155a3-1f29-4187-934a-10445fadfd0c.json, change/@azure-communication-react-70f155a3-1f29-4187-934a-10445fadfd0c.json, packages/storybook/stories/MessageThread/MessageThread.stories.tsx
=> [Bugfix] Re-enable image gallery from inline images in story book

change-beta/@azure-communication-react-8a749599-7ff0-4339-8ceb-d4e8ca772d2c.json, change/@azure-communication-react-8a749599-7ff0-4339-8ceb-d4e8ca772d2c.json, rush.json
Ongoing dependency updates.
Drop node <16
=> [Deps] Update rush and pnpm to latest.

change-beta/@azure-communication-react-bd803e15-0466-423a-9236-286d712b34b1.json, change/@azure-communication-react-bd803e15-0466-423a-9236-286d712b34b1.json, packages/react-components/src/components/ChatMessage/ChatMessageComponentAsMessageBubble.tsx, packages/react-components/src/components/styles/MessageThread.styles.ts
Cherry picked from commit 8884bd965a9a11c3e1897af0b937431ade941add
See https://github.com/Azure/communication-ui-library/pull/3911 for more details
=> [Cherry-Pick] Fix for image placeholder issue for GA release

change-beta/@azure-communication-react-d99780b3-de43-4231-b959-61152ac12f71.json, change/@azure-communication-react-d99780b3-de43-4231-b959-61152ac12f71.json, common/config/babel/features.js, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/RTE/RTESendBox.tsx, packages/react-components/src/components/index.ts, packages/storybook/stories/INTERNAL/RTE/RTESendBox, packages/storybook/stories/INTERNAL/RTE/RTESendBox.stories.tsx
- Added a Storybook page for RTESendBox under Internal folder
- Added a feature flag for RTE
Storybook
=> [Chat][RTE] RTE feature setup

change-beta/@azure-communication-react-dc493c99-51c2-4422-8b96-4bdff0edb5ca.json, change/@azure-communication-react-dc493c99-51c2-4422-8b96-4bdff0edb5ca.json, packages/chat-component-bindings/src/errorBarSelector.ts, packages/chat-component-bindings/src/hooks/usePropsFor.ts, packages/chat-component-bindings/src/typingIndicatorSelector.test.ts, packages/chat-component-bindings/tsconfig.json
=> Enable noImplicitAny in chat-stateful-client

change-beta/@azure-communication-react-184251aa-48c3-4124-9bd0-1d30b32402ab.json, change/@azure-communication-react-184251aa-48c3-4124-9bd0-1d30b32402ab.json, samples/ComponentExamples/src/utils/utils.ts, samples/ComponentExamples/tsconfig.json
Enable TS noImplicitAny for component-examples packlet.
=> Update component examples for noImplicitAny

change-beta/@azure-communication-react-9e1334ad-dd3e-48ae-996a-e86cf96d460e.json, change/@azure-communication-react-9e1334ad-dd3e-48ae-996a-e86cf96d460e.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/src/composites/CallComposite/CallComposite.tsx, packages/react-composites/src/composites/CallComposite/pages/NoticePage.tsx, packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx
Change hidesurvey to disablesurvey based on ARB 
ARB suggestion
=> Change hidesurvey to disablesurvey based on ARB 

change-beta/@azure-communication-react-5fb78aa9-9d3c-44a7-a6c7-a2ea0d3ea24e.json, change/@azure-communication-react-5fb78aa9-9d3c-44a7-a6c7-a2ea0d3ea24e.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/ReactionButton.tsx, packages/react-components/src/components/styles/ReactionButton.styles.ts, packages/react-components/src/localization/locales/en-US/strings.json, packages/react-composites/src/composites/CallComposite/components/buttons/Reaction.tsx
* Tooltip for each of the reaction
* accessibility of each button through keyboard navigation
* theme applying in the button menu
* Emoji enlarge on hover
=> [Calling] Tooltip for each of the reaction button applied

change-beta/@azure-communication-react-e712e081-7c3e-46a5-bf82-f5034211d007.json, change/@azure-communication-react-e712e081-7c3e-46a5-bf82-f5034211d007.json, packages/calling-component-bindings/src/participantListSelector.ts, packages/calling-component-bindings/src/utils/participantListSelectorUtils.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/src/index.ts, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/ParticipantList.tsx, packages/react-components/src/index.ts, packages/react-components/src/theming/icons.tsx, packages/react-components/src/types/ParticipantListParticipant.ts, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/tests/browser/common/utils.ts
Add spotlight icon to participant list on call composites
https://skype.visualstudio.com/SPOOL/_workitems/edit/3568872
Local calling sample
=> Show icon for spotlighted participants in participant list

change-beta/@azure-communication-react-65cb5884-7d6d-4847-b1f4-77ea3d43b167.json, change-beta/@azure-communication-react-99395a6a-8d70-47ee-9baa-127fbd9da46e.json, change/@azure-communication-react-184251aa-48c3-4124-9bd0-1d30b32402ab.json, change/@azure-communication-react-388a0edc-7d5e-4a87-85d5-f71a8c159ccc.json, change/@azure-communication-react-5c14cb09-5dfb-45d6-bc50-688d6e2623c2.json, change/@azure-communication-react-67634b96-2fa6-445c-a183-71be3bdf597e.json, change/@azure-communication-react-6b674465-0af5-403c-8825-1461c8c69fc7.json, change/@azure-communication-react-7665db60-acd2-46d1-9f24-fc3d3853e856.json, change/@azure-communication-react-7de7e249-b854-4e93-a1d6-2718913424f3.json, change/@azure-communication-react-83fe8c56-c493-4f0f-8165-c0c50b78b872.json, change/@azure-communication-react-977a7370-7c8c-4df5-bdd8-363f75818dc5.json, change/@azure-communication-react-9dbf5871-898c-403d-b5e7-99a29e88b117.json, change/@azure-communication-react-9e1334ad-dd3e-48ae-996a-e86cf96d460e.json, change/@azure-communication-react-9ff30e7e-231d-47cc-b328-a08b49f6a0bb.json, change/@azure-communication-react-a58efe07-f827-48de-b634-a0c87bad4bb2.json, change/@azure-communication-react-b9775229-d90b-4d3d-8453-7751d837ce3d.json, change/@azure-communication-react-bb4d5cf8-48cd-4afc-8cf0-a4a512e492cd.json, change/@azure-communication-react-bf062fd8-9f04-46e1-a051-e37a4ebe5f04.json, change/@azure-communication-react-c4a56c27-3634-4cef-9aa2-3521b8f9078f.json, change/@azure-communication-react-d3f773e7-fede-431d-bd66-acd8454a8dfb.json, change/@azure-communication-react-d8b97a4e-2910-456e-b394-ba3467eb21fc.json, change/@azure-communication-react-dc493c99-51c2-4422-8b96-4bdff0edb5ca.json, change/@azure-communication-react-e712e081-7c3e-46a5-bf82-f5034211d007.json, change/@azure-communication-react-ebc3a747-4050-4580-b9fc-76e95e28d3ee.json, change/@azure-communication-react-f1b90cbb-1522-4d82-9f92-b0e1b31e21bd.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml
=> Merge main to RTE

change-beta/@azure-communication-react-d3572c18-4f2f-4d2f-b19a-3f3e3067b72d.json, change/@azure-communication-react-d3572c18-4f2f-4d2f-b19a-3f3e3067b72d.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, rush.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/Chat/package.json, samples/ComponentExamples/package.json, samples/Server/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Renamed packages in the rush file and package.json for internal samples and packages for testing to fix CG legal alerts 
CI, CG checks for the builds
=> Rename of internal samples and packages for testing

change-beta/@azure-communication-react-1466d23d-73bc-4aa9-8a92-4537c310db9c.json, change/@azure-communication-react-1466d23d-73bc-4aa9-8a92-4537c310db9c.json, packages/chat-component-bindings/src/messageThreadSelector.ts, packages/chat-stateful-client/src/ChatContext.ts
=> [CherryPick][Release][Chat] Bug fix Img via file share with no message content (#4084)

change-beta/@azure-communication-react-74550d0c-51e2-4584-8fb7-77fbe2539615.json, change/@azure-communication-react-74550d0c-51e2-4584-8fb7-77fbe2539615.json, packages/chat-stateful-client/src/convertChatMessage.ts
=> [CherryPick][Release] Cherrypick DLP fix

.github/workflows/deploy-storybook.yml, change-beta/@azure-communication-react-091ea800-6a2e-4253-aa0d-d4ecf2c46936.json, change/@azure-communication-react-091ea800-6a2e-4253-aa0d-d4ecf2c46936.json
=> [Github] Add missing permissions to storybook deploy action

.github/workflows/deploy-storybook.yml, change-beta/@azure-communication-react-091ea800-6a2e-4253-aa0d-d4ecf2c46936.json, change/@azure-communication-react-091ea800-6a2e-4253-aa0d-d4ecf2c46936.json
* Add missing permissions to storybook deploy action
* Change files
=> [CherryPick][Release] Cherry pick GitHub permission fix storyboard

change-beta/@azure-communication-react-77bdcdd5-bd98-44c9-8885-e6f671cf2e22.json, change/@azure-communication-react-77bdcdd5-bd98-44c9-8885-e6f671cf2e22.json, packages/chat-component-bindings/src/messageThreadSelector.test.ts
Add messageThreadSelector tests
Tests run
=> [Chat] Add messageThreadSelector tests

change-beta/@azure-communication-react-bb3758ca-73e7-4997-9a36-ac7e97c60110.json, change/@azure-communication-react-bb3758ca-73e7-4997-9a36-ac7e97c60110.json, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/review/stable/react-composites.api.md, packages/react-composites/src/composites/CallComposite/CallComposite.tsx, packages/react-composites/src/composites/CallComposite/Strings.tsx, packages/react-composites/src/composites/CallComposite/pages/LobbyPage.tsx, packages/react-composites/src/composites/CallComposite/pages/NoticePage.tsx, packages/react-composites/src/composites/CallComposite/utils/MediaGalleryUtils.ts, packages/react-composites/tests/browser/call/hermetic/fixture.ts
Cherry pick improvements relating to startCall into release
Updates call screen behaviours for startCall in stable 
Validated locally and merged main
=> [Cherry pick] start call imp cp

change-beta/@azure-communication-react-a75999d4-5192-4b9c-8872-dc4848345959.json, change/@azure-communication-react-a75999d4-5192-4b9c-8872-dc4848345959.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/review/stable/react-composites.api.md, packages/react-composites/src/composites/CallComposite/Strings.tsx, packages/react-composites/src/composites/CallComposite/pages/LobbyPage.tsx, packages/react-composites/src/composites/CallComposite/pages/NoticePage.tsx, packages/react-composites/src/composites/CallComposite/utils/MediaGalleryUtils.ts
Make updates to main that were in Cherry pick for 1.13.0
Updates the API to have the optional string as well
Built API validated locally
=> [Start-call] start call imp cp back main

change-beta/@azure-communication-react-e02626a7-13b2-4d47-a5d3-0955b5944267.json, change/@azure-communication-react-e02626a7-13b2-4d47-a5d3-0955b5944267.json, packages/chat-stateful-client/src/ChatContext.test.ts, packages/chat-stateful-client/src/ResourceDownloadQueue.test.ts
Add dummy tests to Chat side for beta only test files
unblocks stable runs of jest tests
Ran tests locally
=> [Release bug fix] test chat fix release

change-beta/@azure-communication-react-38a3eb04-8eae-4e80-9aac-88acd0c0c07c.json, change/@azure-communication-react-38a3eb04-8eae-4e80-9aac-88acd0c0c07c.json, packages/chat-stateful-client/src/ResourceDownloadQueue.ts
=> [Inline] Resolve issue where images previews would not show in a message if the message also had a file attachment.

change-beta/@azure-communication-react-4ad11a03-2cf7-411b-90dd-9420f2b443bc.json, change/@azure-communication-react-4ad11a03-2cf7-411b-90dd-9420f2b443bc.json, packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
The cursor setting for inline image got lost in other changes. Bringing it back in this PR
=> [Chat] Change inline image cursor to pointer

change-beta/@azure-communication-react-3e058818-233a-4e31-86f2-47186cf4b156.json, change/@azure-communication-react-3e058818-233a-4e31-86f2-47186cf4b156.json, packages/calling-component-bindings/review/beta/calling-component-bindings.api.md, packages/calling-component-bindings/src/handlers/createCommonHandlers.ts, packages/calling-component-bindings/src/utils/participantListSelectorUtils.ts, packages/calling-component-bindings/src/utils/videoGalleryUtils.ts, packages/calling-stateful-client/review/beta/calling-stateful-client.api.md, packages/calling-stateful-client/src/CallClientState.ts, packages/calling-stateful-client/src/CallContext.ts, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/LocalVideoTile.tsx, packages/react-components/src/components/ReactionButton.tsx, packages/react-components/src/components/VideoTile.tsx, packages/react-components/src/types/ParticipantListParticipant.ts, packages/react-composites/review/beta/react-composites.api.md, packages/react-composites/review/stable/react-composites.api.md, packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatTypeAssertions.ts, packages/react-composites/tests/app/lib/MockCallAdapter.ts
* Api update due to ARB feedback
=> [Calling] API naming update from ARB feedback

change-beta/@azure-communication-react-678df3f7-61a2-47ba-8113-6d292930a836.json, change/@azure-communication-react-678df3f7-61a2-47ba-8113-6d292930a836.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/MentionPopover.tsx
This argument is needed in the pubic API. Requested in the following issue #3836 
=> Update mention api to include isActive argument

.github/workflows/npm-release-publish.yml
Changes to handling of appsettings.json needs the NPM workflow to be updated.
 
=> Fix up NPM publish workflow

change-beta/@azure-communication-react-946f168f-c9f9-47f1-b88c-61eb0f2f4a64.json, change/@azure-communication-react-946f168f-c9f9-47f1-b88c-61eb0f2f4a64.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
=> [Calling] Update sdk version

change-beta/@azure-communication-react-bc35126b-1e1c-4535-abd9-6fb4db254eaf.json, change/@azure-communication-react-bc35126b-1e1c-4535-abd9-6fb4db254eaf.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/review/beta/react-components.api.md, packages/react-components/src/components/ReactionButton.tsx, packages/react-components/src/localization/locales/en-US/strings.json
* The changes include reaction button expected announcement for ally
=> [Calling] Reaction button ally bug for announcement

change/@azure-communication-react-b79f855a-3fd6-4820-a932-50cd538bc136.json, packages/storybook/stories/Stateful Client/OverviewStateful.stories.mdx
Add reference to the stateful client storybook page
=> [Chat] Add reference to the stateful client storybook page

change-beta/@azure-communication-react-04072408-0390-46c8-b8ce-1aa004cf6dae.json, change-beta/@azure-communication-react-9ee3f1a0-b296-45d4-b15a-5ab2c0a067e2.json, change/@azure-communication-react-9ee3f1a0-b296-45d4-b15a-5ab2c0a067e2.json, packages/chat-component-bindings/src/messageThreadSelector.ts, packages/chat-stateful-client/review/beta/chat-stateful-client.api.md, packages/chat-stateful-client/review/stable/chat-stateful-client.api.md, packages/chat-stateful-client/src/ChatContext.ts, packages/chat-stateful-client/src/types/ChatMessageWithStatus.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
Cherry pick Making sourceUrl optional into release branch
=> [Chat] Cherry pick Making sourceUrl optional into release branch

change-beta/@azure-communication-react-bbbe05bd-2d77-4c98-b0a6-30b2264090dc.json, change/@azure-communication-react-bbbe05bd-2d77-4c98-b0a6-30b2264090dc.json, packages/calling-component-bindings/src/utils/videoGalleryUtils.ts, packages/calling-component-bindings/src/videoGallerySelector.ts
Fix the parameter does not match for stable build 
=> [Calling][Bug] Fix videoGalleryUtil

packages/calling-component-bindings/src/utils/videoGalleryUtils.ts, packages/calling-component-bindings/src/videoGallerySelector.ts
=> [Calling][Bug] Fix ppt live mismatch cherry pick to main 

change-beta/@azure-communication-react-bbbe05bd-2d77-4c98-b0a6-30b2264090dc.json, change/@azure-communication-react-bbbe05bd-2d77-4c98-b0a6-30b2264090dc.json, change/@azure-communication-react-f694dabd-e0be-449a-a19b-deae6778e560.json, common/config/babel/features.js, packages/calling-component-bindings/src/utils/videoGalleryUtils.ts, packages/calling-component-bindings/src/videoGallerySelector.ts, packages/calling-stateful-client/review/stable/calling-stateful-client.api.md, packages/communication-react/CHANGELOG.stable.md, packages/communication-react/review/stable/communication-react.api.md
Remove PPTLive from stable release
Important bug needs fixed
Will be bug bashed.This reverts commit 2c9de76.
=> Move PPTLive from stable to beta in release branch

GROOMME.md, packages/communication-react/CHANGELOG.beta.md
Changelog refinement for our beta release
We want to prune the changelog so developers can understand what bug fixes, features, and improvements they will have access to with 1.15.0-beta.1
It would be helpful for people to mainly review the beta changelog in communication-react packlet
packages/communication-react/CHANGELOG.beta.md
=> Groom changelog /1.15.0 beta.1

packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx
=> [Cherry Pick] Captions should not shown for beta release 

packages/react-composites/src/composites/common/PeoplePaneContent.tsx
Cherry-pick of this PR: https://github.com/Azure/communication-ui-library/pull/4359
To fix our beta release build
=> [Cherry-pick] Fix missing remove participant drawer menu item

change-beta/@azure-communication-react-a7122a70-c861-4ec3-9524-de8f6510dbd4.json, change/@azure-communication-react-a7122a70-c861-4ec3-9524-de8f6510dbd4.json, common/config/babel/features.js, packages/calling-stateful-client/src/CallClientState.ts, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts
=> [Calling][Bug]Remove pptlive

packages/react-composites/src/composites/localization/locales/ru-RU/strings.json
Cherry pick new translations into 1.15.0-beta.1 release
=> Cherry pick new translations into 1.15.0-beta.1 release

change-beta/@azure-communication-react-4479b7d2-ebdb-429b-b2da-a1a7a78ab387.json, change/@azure-communication-react-4479b7d2-ebdb-429b-b2da-a1a7a78ab387.json, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update stable version to 1.23.1
=> [Calling][Refactor] Bump Calling SDK stable version

change-beta/@azure-communication-react-b3437ff9-cac9-4e4b-993c-ce8af9098fcd.json, change/@azure-communication-react-b3437ff9-cac9-4e4b-993c-ce8af9098fcd.json, packages/react-components/src/components/VideoGallery/ParticipantVideoTileOverlay.tsx
* [VideoTile MeetingReactionOverlay corner missing rounded style]
=> [Calling] VideoTile MeetingReactionOverlay corner missing rounded style

change/@azure-communication-react-643120cf-40f1-47c6-9081-49cb43392e55.json, docs/releases/hotfix-release.md
=> [Docs] Correct the instructions for a hotfix on beta release.

change/@azure-communication-react-09025757-4ceb-4db0-b80b-d32a16b6a853.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-components/src/components/VideoGallery/ParticipantVideoTileOverlay.tsx, packages/react-components/src/components/VideoGallery/utils/videoGalleryLayoutUtils.ts, packages/react-components/src/types/ReactionTypes.ts
Remove size as this will be readded later with a different interface
We want to change it
CI only.
=> Remove size from reaction interface

packages/storybook/stories/AddingReaction.stories.mdx
* Adding reaction resource links to download in the storybook
=> [Calling] Adding reaction resource links to download in the storybook

GROOMME.md, change/@azure-communication-react-52bb94c8-240b-4290-a9bd-8a4bb6dcc16f.json, packages/communication-react/CHANGELOG.stable.md
Changelog time! 
lets announce all the things!
Inspected locally, just a doc change
=> Groom changelog /1.15.0

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, packages/chat-component-bindings/package.json, packages/chat-stateful-client/package.json, packages/communication-react/package.json, packages/fake-backends/package.json, packages/react-composites/package.json, packages/storybook/package.json, samples/CallWithChat/package.json, samples/Chat/package.json, samples/ComponentExamples/package.json, samples/Server/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Bump azure/communication-chat to version 1.5.0-beta.2
Only for release
=> Update communication-chat dependency to hotfix version

change-beta/@azure-communication-react-9de05cab-d5e1-439d-9490-1ccb51ac4000.json, change/@azure-communication-react-9de05cab-d5e1-439d-9490-1ccb51ac4000.json, packages/react-components/src/components/MeetingReactionOverlay.tsx, packages/react-components/src/components/VideoTile.tsx, packages/react-components/src/components/styles/VideoGallery.styles.ts
* fix local tile switcher action
* Change files
Cherry pick from main
=> [Release blocker CP] local tile switcher fix (#4447)

change-beta/@azure-communication-react-64d50c32-80ee-4208-a2dd-868f88de14fa.json, change/@azure-communication-react-64d50c32-80ee-4208-a2dd-868f88de14fa.json, packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx
Add caching for `inlineImageOptions`
Chat sample app
=> [Chat] Fix an issue where all messages were re-rendered when a new message is sent

change/@azure-communication-react-8b2cb719-c74e-4f00-853b-2cac906187c0.json, packages/react-components/src/components/styles/RichTextEditor.styles.ts
Fix table selection dropdown's width
=> Fix table selection dropdown's width

change-beta/@azure-communication-react-8fba3a51-f8ea-44e8-a44b-d946074af9c0.json, change/@azure-communication-react-8fba3a51-f8ea-44e8-a44b-d946074af9c0.json, change/@azure-communication-react-9a0878ac-6f30-402c-b07c-5c232bab83d6.json, packages/react-components/src/components/RemoteVideoTile.tsx, packages/react-components/src/components/VideoGallery.tsx, packages/react-components/src/components/VideoGallery/useVideoStreamLifecycleMaintainer.ts
Cherry pick in release blocker
getting this show on the road
=> [Cherry pick] Android video fix

.github/workflows/ci.yml, change/@azure-communication-react-7332768d-224e-4d3a-969b-4894509a690b.json, packages/storybook8/package.json
Until ready, remove from the regular rush build
=> [Storybook8] Remove from build path 

change-beta/@azure-communication-react-e0ae4d56-2bb1-468d-90ef-7497d0bde748.json, change/@azure-communication-react-e0ae4d56-2bb1-468d-90ef-7497d0bde748.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/src/index.ts, packages/react-components/src/components/index.ts, packages/react-components/src/types/Attachment.ts, packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx, packages/react-composites/src/composites/ChatComposite/file-sharing/AttachmentUpload.ts, packages/react-composites/src/composites/ChatComposite/file-sharing/index.ts, packages/react-composites/src/composites/ChatComposite/index.ts, packages/react-composites/tests/app/chat/FakeAdapterApp.tsx, packages/react-composites/tests/app/chat/LiveTestApp.tsx, samples/Chat/src/app/utils/uploadHandler.ts
address review feedback, introducing:
- handleAttachmentSelection
- handleAttachmentRemoval
general improvement
CI
=> [Chat] Updated Upload Options

change/@azure-communication-react-a53b1b4d-d385-4dec-b16d-ef05f81ed38a.json, packages/react-components/src/components/styles/RichTextEditor.styles.ts
Fix a layout issue for the insert table menu
Before:
After:
Storybook and chat sample app
=> [RTE] Fix a layout issue for the insert table menu

change/@azure-communication-react-597b8fd4-4f78-401e-b5ca-e86152139268.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/storybook8/package.json
=> Include storybook 8 CLI package

packages/calling-stateful-client/src/Converter.ts
=> Fix beta release build issue

change/@azure-communication-react-56131719-373c-46ba-8eb7-f243e21498c8.json, change/@azure-communication-react-fd4c3b03-99a0-4eaa-acfc-7161f0645cd0.json
=> Remove changelog None type

common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/calling-stateful-client/src/CallAgentDeclarative.test.ts, packages/communication-react/package.json, packages/react-composites/package.json, packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts, packages/storybook/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
update stable Calling SDK
Keeps us up to date with the SDK
https://skype.visualstudio.com/SPOOL/_workitems/edit/3680401
Built and tested locally
=> [OCE] Calling stable sdk updates

change-beta/@azure-communication-react-f694a4eb-bf80-4d20-9e65-4d25715fa09e.json, change/@azure-communication-react-f694a4eb-bf80-4d20-9e65-4d25715fa09e.json, packages/calling-component-bindings/src/captionsSelector.ts
Fix bug where there are duplicate captions 
=> Fix bug where there are duplicate captions 

packages/calling-component-bindings/src/captionsSelector.ts
Cherry pick captions bug fix into release branch
=> Cherry pick captions bug fix into release branch

change-beta/@azure-communication-react-fda0563f-1d07-44a9-b28f-c1e635e0b286.json, change/@azure-communication-react-fda0563f-1d07-44a9-b28f-c1e635e0b286.json, common/config/jest/jestSetup.js, packages/react-components/src/components/Dialpad/Dialpad.test.tsx, packages/react-composites/src/composites/CallComposite/CallComposite.test.tsx, packages/react-composites/src/composites/CallComposite/CallComposite.tsx, packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.test.tsx, packages/react-composites/src/composites/common/AudioProvider.tsx, packages/react-composites/src/composites/common/BaseComposite.tsx
Cherry pick #4539 to release/1.16.0-beta.1
Fix release blocker on release branch
=> [Cherry-pick][Release-blocker] composite audio context updates

packages/storybook/stories/MessageThread/MessageThread.stories.tsx
=> Add documentation to indicate the RTE edit box doesn't support mention

change-beta/@azure-communication-react-431d792b-1af7-44f1-bf5d-114f8089157e.json, change/@azure-communication-react-431d792b-1af7-44f1-bf5d-114f8089157e.json, packages/storybook/stories/Adapters/Adapters.stories.mdx
https://skype.visualstudio.com/SPOOL/_workitems/edit/3702161
=> Update SDK ref for Hide Attendee Names

change/@azure-communication-react-a6be18c4-8750-497c-98ff-f509be659bf7.json, common/config/babel/features.js, packages/calling-stateful-client/src/CallClientState.ts, packages/calling-stateful-client/src/Converter.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, samples/Calling/src/app/views/HomeScreen.tsx
Move meeting id join to beta release
=> Update meeting Id join to stable

change/@azure-communication-react-5e86ae5b-6832-4e90-ad70-0d8f6d1a23a2.json
unblocks `rush changelog`
fixes error thrown on `none` change type
ran locally
=> delete bad changelog

GROOMME.md, packages/communication-react/CHANGELOG.stable.md
=> Groom changelog

packages/react-components/src/components/styles/VideoTile.styles.ts
=> Cherry pick raise hand fix into release branch

change-beta/@azure-communication-react-9a1cbf7f-3e6c-4a67-a7e3-13a112569d6a.json, change/@azure-communication-react-9a1cbf7f-3e6c-4a67-a7e3-13a112569d6a.json, packages/react-components/src/components/styles/VideoTile.styles.ts
https://skype.visualstudio.com/SPOOL/_workitems/edit/3718941
=> Raise Hand bug fix 

packages/react-components/src/components/RichTextEditor/Plugins/ContextMenuPlugin.tsx, packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx, packages/react-components/src/components/utils/RichTextEditorUtils.ts
Context menu update to remove the need of `render` call
=> [RTE] Context menu update

packages/storybook8/stories/MessageThread/snippets/MessageWithAttachment.snippet.tsx, packages/storybook8/stories/MessageThread/snippets/MessageWithCustomAttachment.snippet.tsx
=> Update storybook 8 with new AttachmentMetadata

packages/communication-react/review/beta/communication-react.api.md, packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx, packages/react-components/src/localization/locales/en-US/strings.json
=> Added strings for rich text editor

.github/workflows/alpha-release.yml, .github/workflows/nightly-cd.yml, .github/workflows/npm-release-publish.yml, docs/releases/updating-npm-publishing-credentials.md
Cherry pick #4597 to release branch
=> Cherry pick OIDC npm release pipeline fixes to release branch

GROOMME.md, packages/communication-react/CHANGELOG.beta.md
=> Groom changelog for 1.17.0 beta.1

.github/workflows/alpha-release.yml, .github/workflows/nightly-cd.yml, .github/workflows/npm-release-publish.yml, docs/releases/updating-npm-publishing-credentials.md
Cherry-pick #4649 to current release branch
=> Cherry Pick OIDC pipeline updates to release/1.17.0-beta.1

common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/react-components/src/components/Dialpad/Dialpad.tsx, packages/storybook/package.json, packages/storybook/stories/Dialpad/Dialpad.stories.tsx, packages/storybook/stories/Dialpad/snippets/CustomDialpad.snippet.tsx, packages/storybook/stories/Dialpad/snippets/Dialpad.snippet.tsx, packages/storybook/stories/Dialpad/snippets/DialpadDialer.snippet.tsx
Fix dialpad keyboard nav bug and storybook double button press on mobile
Dialpad keyboard nav bug:
https://skype.visualstudio.com/SPOOL/_workitems/edit/3736082
Storybook double button press issue on mobile:
#4636
Local storybook validation.
Testing keyboard navigation after:
https://github.com/Azure/communication-ui-library/assets/79475487/cc8f730b-a385-43df-9430-adf724d81bd1
Testing double button press on mobile after:
https://github.com/Azure/communication-ui-library/assets/79475487/8d05c345-9fcd-4a9d-9b5d-f2b9edc6f47d
=> Fix dialpad keyboard nav bug and storybook snippets on mobile

change-beta/@azure-communication-react-e0da7f34-a10c-4b0d-b745-26283379e8f4.json, change/@azure-communication-react-e0da7f34-a10c-4b0d-b745-26283379e8f4.json, packages/storybook/stories/CallWithChatComposite/CallWithChatCompositeDocs.tsx
cherry pick PR (https://github.com/Azure/communication-ui-library/pull/4692) to release branch
remove beta banner and link to MSdoc
=> [Chat] Removed Beta Banner (#4692)

change-beta/@azure-communication-react-0c94ca43-f8f9-4cb6-aa30-64cdc9ca54b1.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/src/components/NotificationBar.tsx, packages/react-components/src/components/Notifications.tsx, packages/storybook/stories/INTERNAL/NotificationBar/NotificationBar.stories.tsx, packages/storybook/stories/INTERNAL/NotificationBar/snippets/ExampleNotificationBar.snippet.tsx
Add primary and secondary button to notification bar 
Storybook
=> Add primary and secondary button to notification bar 

change-beta/@azure-communication-react-ceb3c4e8-b045-49b3-94c9-e8006db80d23.json, change/@azure-communication-react-ceb3c4e8-b045-49b3-94c9-e8006db80d23.json, packages/chat-component-bindings/src/handlers/createHandlers.ts
this PR fixes the issue where user cannot update chat message content in stable build
bug fix
bug bash app
=> [Chat] Fixed the Issue Where Message Not Being Updated

change-beta/@azure-communication-react-ceb3c4e8-b045-49b3-94c9-e8006db80d23.json, change/@azure-communication-react-ceb3c4e8-b045-49b3-94c9-e8006db80d23.json, packages/chat-component-bindings/src/handlers/createHandlers.ts
original PR is here: https://github.com/Azure/communication-ui-library/pull/4701
cherry picking it to release branch
=> [Chat] Chery Pick - Fixed the Issue Where Message Not Being Updated 

change-beta/@azure-communication-react-610bd9bf-e266-4b51-9f30-365e1ae2b320.json, change/@azure-communication-react-610bd9bf-e266-4b51-9f30-365e1ae2b320.json, packages/react-components/src/components/ReactionButton.tsx
Fix bug where new captions dismiss reaction flyout 
Tested with samples 
=> Fix bug where new captions dismiss reaction flyout 

packages/chat-stateful-client/src/ChatClientState.ts, packages/communication-react/review/beta/communication-react.api.md
=> Add createdBy to ChatThreadProperties for RTE Image upload

.github/workflows/create-prerelease-branch.yml
Updates action to fix bump type
bad input retrieval so sad branch name
https://skype.visualstudio.com/SPOOL/_workitems/edit/3761635
Ran action on branch
=> fix naming bump type in pre-release

GROOMME.md, packages/communication-react/CHANGELOG.beta.md
=> Groom changelog beta release beta/1.18.0 beta.1

change-beta/@azure-communication-react-1e82b11b-a35f-444f-a874-420748dd8ac0.json, change/@azure-communication-react-1e82b11b-a35f-444f-a874-420748dd8ac0.json, packages/react-components/src/components/RichTextEditor/RichTextEditor.tsx
This now matches the behavior of 'Teams'
=> [RTE][A11Y] Add missing aria label for placeholder on editor

change-beta/@azure-communication-react-6d999d69-0527-4c82-96c8-3dd5dded13a2.json, change/@azure-communication-react-6d999d69-0527-4c82-96c8-3dd5dded13a2.json, packages/react-components/src/components/ParticipantList.tsx
Cherry-pick #4751
https://skype.visualstudio.com/SPOOL/_workitems/edit/3765795
=> [Cherry-pick #4751] Fix missing pinned icon when it is the only icon

packages/communication-react/CHANGELOG.beta.md
=> Update changelog link

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, packages/chat-component-bindings/package.json, packages/chat-stateful-client/package.json, packages/communication-react/package.json, packages/fake-backends/package.json, packages/react-composites/package.json, packages/storybook/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Chat/package.json, samples/ComponentExamples/package.json, samples/Server/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
bumped Chat SDK to beta.3
version bump
CI
=> [Chat] Update Chat SDK to Beta.3

change-beta/@azure-communication-react-f2bed93f-9111-42a9-a8b4-c3ce46cacc95.json, change/@azure-communication-react-f2bed93f-9111-42a9-a8b4-c3ce46cacc95.json, packages/acs-ui-common/.eslintignore, packages/calling-component-bindings/.eslintignore, packages/calling-stateful-client/.eslintignore, packages/chat-component-bindings/.eslintignore, packages/chat-stateful-client/.eslintignore, packages/communication-react/.eslintignore, packages/fake-backends/.eslintignore, packages/react-components/.eslintignore, packages/react-composites/.eslintignore, packages/storybook/.eslintignore, packages/storybook8/.eslintignore, samples/CallWithChat/.eslintignore, samples/Calling/.eslintignore, samples/Chat/.eslintignore
updated lint ignore list to include preprocessed folder
bug fix
CI
=> Added preprocessed folder to lint ignore list 

.github/workflows/ci.yml
=> Fix permissions for CI when creating comments

.github/workflows/alpha-release.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-api-view-feature-level.yml, .github/workflows/create-prerelease-branch.yml, .github/workflows/create-release-branch.yml, .github/workflows/deploy-azure-webapps.yml, .github/workflows/deploy-feature-azure-webapps.yml, .github/workflows/deploy-release-azure-webapps.yml, .github/workflows/deploy-storybook.yml, .github/workflows/nightly-cd.yml, .github/workflows/npm-release-publish.yml, .github/workflows/publish-chromatic.yml, .github/workflows/run-td-build.yml, .github/workflows/stress-test-ui-tests.yml, .github/workflows/update-api-files.yml, .github/workflows/update-chat-snapshots.yml, .github/workflows/update-snapshots.yml
Update jobs to latest for warning removal
=> Update github checkout and setup-node actions to latest

common/config/babel/features.js, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
Move soft mute to beta and address arb comments
=> Move Soft mute to beta and address arb comment

change-beta/@azure-communication-react-58022293-11ec-42c3-9152-e3c9fe24d5c1.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/src/components/Notification.tsx, packages/react-components/src/localization/locales/en-US/strings.json, packages/storybook/stories/INTERNAL/NotificationBar/Notification.stories.tsx, packages/storybook/stories/INTERNAL/NotificationBar/snippets/ExampleNotification.snippet.tsx
=> Change Close to Dismiss for button aria label

packages/react-composites/src/composites/CallWithChatComposite/CallWithChatComposite.tsx, samples/CallWithChat/src/app/App.tsx, samples/CallWithChat/src/app/views/CallScreen.tsx, samples/CallWithChat/src/app/views/HomeScreen.tsx, samples/CallWithChat/src/app/views/RichTextEditorToggle.tsx
Added toggle for RichTextEditor
=> [RTE] Add toggle for RichTextEditor to CallWithChat Sample

change-beta/@azure-communication-react-8d3a5b27-5c04-4b00-8a98-e3ce437e0d1e.json, packages/communication-react/review/stable/communication-react.api.md, packages/react-components/src/theming/icons.tsx
Remove inbound Icons from the stable API
accidentally added icons to stable when added component
Built API locally
=> [Incoming call] cc inbound icons

change-beta/@azure-communication-react-12886c21-001b-4ca5-b5c9-5023dfba1271.json, change/@azure-communication-react-12886c21-001b-4ca5-b5c9-5023dfba1271.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/communication-react/package.json, packages/react-components/package.json
=> FluentUI contrib dependency update

GROOMME.md, packages/communication-react/CHANGELOG.stable.md
Grooming of changelog for stable release 
Preparing for release.
=> [Changelog] Groomed change log

change-beta/@azure-communication-react-c115b8a8-0e97-4435-a191-627982b65631.json, change/@azure-communication-react-c115b8a8-0e97-4435-a191-627982b65631.json, packages/acs-ui-common/src/common.ts, packages/react-components/src/components/ResponsiveHorizontalGallery.tsx, packages/react-components/src/components/ResponsiveVerticalGallery.tsx, packages/react-components/src/components/utils/responsive.ts
Cherry-pick of #4861
To fix Horizontal Gallery issue that causes Calling app to crash for customer EZRA
=> [Cherry-pick #4861] Fix vulnerability of having NaN from calculations in overflow gallery

packages/chat-stateful-client/src/ChatClientState.ts, packages/communication-react/review/beta/communication-react.api.md
As per recommendation from ARB, we are changing this to be an interface.
=> [RTE] Change msgPolicy to be an interface.

packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx, packages/react-components/src/components/RichTextEditor/Plugins/CopyPastePlugin.tsx, packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx, packages/react-components/src/components/styles/MessageThread.styles.ts, packages/react-components/src/components/styles/RichTextEditor.styles.ts, packages/react-components/src/components/utils/SendBoxUtils.ts
Thank you @jpeng-ms for finding the solution for this!
1. Render image to determine width and height, then set this in the image before sending to teams.
2. Set maxWidth to 100%
=> [RTE] Set image width height

packages/acs-ui-javascript-loaders/package.json
Stops testing in new package
eslint is causing a problem for the testing of the new package but is not to be in this release to we will stop the testing for now.
Ran test locally
=> [Release blocker] remove js test

packages/react-composites/src/composites/ChatComposite/ChatScreen.tsx, packages/react-composites/src/composites/common/SendBoxPicker.tsx
=> [RTE] CC Fix

packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx, packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMyMessageComponent.tsx, packages/react-components/src/components/utils/SendBoxUtils.ts
=> [RTE] Resolve issue where image height was incorrect when editing a message and then resubmitting

packages/react-components/src/components/RichTextEditor/RichTextSendBox.tsx
=> [RTE] CC fix for RichTextSendBox

packages/storybook8/stories/Concepts/Localization/CustomLocale.story.tsx, packages/storybook8/stories/Concepts/Localization/Docs.mdx, packages/storybook8/stories/Concepts/Localization/LocalizationProvider.story.tsx, packages/storybook8/stories/Concepts/Localization/LongTranslations.story.tsx, packages/storybook8/stories/Concepts/Localization/SetRTL.story.tsx, packages/storybook8/stories/Concepts/Localization/StringsProperty.story.tsx, packages/storybook8/stories/Concepts/Localization/Truncation.story.tsx, packages/storybook8/stories/Concepts/Localization/snippets/CustomLocale.snippet.tsx, packages/storybook8/stories/Concepts/Localization/snippets/LocalizationProvider.snippet.tsx, packages/storybook8/stories/Concepts/Localization/snippets/LocalizedComposites.snippet.tsx, packages/storybook8/stories/Concepts/Localization/snippets/LongTranslations.snippet.tsx, packages/storybook8/stories/Concepts/Localization/snippets/SetRTL.snippet.tsx, packages/storybook8/stories/Concepts/Localization/snippets/StringsProperty.snippet.tsx, packages/storybook8/stories/Concepts/Localization/snippets/Truncation.snippet.tsx
=> [Storybook] Adding new files for localization

change-beta/@azure-communication-react-68cab783-8ad1-4e91-bcf8-c8ca6295ef48.json, common/config/babel/features.js
=> [beta] softmute changelog

packages/calling-stateful-client/src/DeviceManager.test.ts
=> Fix Jest Text Failure in PRs 

samples/tests/ComponentExamples/ComponentExamples.test.ts
Skip failing test
Infra problem, will take some time to fix.
CI
=> Temporarily skip failing test due to infra to get CI green

packages/storybook8/stories/Concepts/Transfer/Docs.mdx, packages/storybook8/stories/Concepts/Transfer/snippets/Transfer.snippet.tsx
Migrate Transfer page under Concepts to Storybook 8
Storybook 8 migration
Locally ran fine
=> [Storybook 8] Concepts/Transfer Page

packages/storybook8/stories/Concepts/Icons/Docs.mdx, packages/storybook8/stories/Concepts/Icons/IconGrid.tsx
=> [Storybook] Migration for Icons page

packages/storybook8/stories/Concepts/BestPractices/Docs.mdx
=> [Storybook] Migration for best practices

packages/storybook8/stories/Concepts/ErrorHandling/Docs.mdx, packages/storybook8/stories/Concepts/ErrorHandling/snippets/ErrorHandlingAdapters.snippet.tsx, packages/storybook8/stories/Concepts/ErrorHandling/snippets/ErrorHandlingStatefulClient.snippet.tsx
=> [Storybook] Storybook migration of error handling

packages/storybook8/stories/Components/ErrorBar/Docs.mdx, packages/storybook8/stories/Components/ImageOverlay/Docs.mdx, packages/storybook8/stories/Components/MessageStatusIndicator/Docs.mdx, packages/storybook8/stories/Components/MessageThread/Docs.mdx, packages/storybook8/stories/Components/SendBox/Docs.mdx, packages/storybook8/stories/Components/TypingIndicator/Docs.mdx
Introduce ArgTypes example to populate props
=> [Storybook] Introducing the ArgTypes 

packages/storybook/stories/controlsUtils.ts
Fixing build error for storybook 
Build error caused at run time because of missing default value
=> [Storybook6] Fixing the default value for participant item

packages/storybook8/stories/Composites/Adapters/Docs.mdx, packages/storybook8/stories/Concepts/Capabilities/Docs.mdx, packages/storybook8/stories/Concepts/Transfer/Docs.mdx, packages/storybook8/stories/StatefulClient/Call/Docs.mdx, packages/storybook8/stories/StatefulClient/Chat/Docs.mdx
Updating the broken links for the storybook 8 migration
Missing files have been completed
=> [Storybook] Fixing the known internal links

packages/react-components/src/localization/locales/ar-SA/strings.json, packages/react-components/src/localization/locales/cs-CZ/strings.json, packages/react-components/src/localization/locales/de-DE/strings.json, packages/react-components/src/localization/locales/en-GB/strings.json, packages/react-components/src/localization/locales/es-ES/strings.json, packages/react-components/src/localization/locales/fi-FI/strings.json, packages/react-components/src/localization/locales/fr-FR/strings.json, packages/react-components/src/localization/locales/he-IL/strings.json, packages/react-components/src/localization/locales/it-IT/strings.json, packages/react-components/src/localization/locales/ja-JP/strings.json, packages/react-components/src/localization/locales/ko-KR/strings.json, packages/react-components/src/localization/locales/nb-NO/strings.json, packages/react-components/src/localization/locales/nl-NL/strings.json, packages/react-components/src/localization/locales/pl-PL/strings.json, packages/react-components/src/localization/locales/pt-BR/strings.json, packages/react-components/src/localization/locales/ru-RU/strings.json, packages/react-components/src/localization/locales/sv-SE/strings.json, packages/react-components/src/localization/locales/tr-TR/strings.json, packages/react-components/src/localization/locales/zh-CN/strings.json, packages/react-components/src/localization/locales/zh-TW/strings.json
Cheery pick localized strings to release branch
=> [Release] Cheery pick localized strings to release branch (#5015)

packages/storybook8/stories/INTERNAL/VideoEffects/Docs.mdx, packages/storybook8/stories/INTERNAL/VideoEffects/VideoEffects.story.tsx, packages/storybook8/stories/INTERNAL/VideoEffects/index.stories.tsx, packages/storybook8/stories/INTERNAL/VideoEffects/snippets/SelectableVideoEffects.snippet.tsx, packages/storybook8/stories/INTERNAL/VideoEffects/snippets/VideoBackgroundEffectsPicker.snippet.tsx
Migrate INTERNAL components for video effects
https://skype.visualstudio.com/SPOOL/_workitems/edit/3810837
=> [Storybook8] Migrate INTERNAL components for video effects

packages/storybook8/stories/Composites/CallComposite/1ton/Docs.mdx, packages/storybook8/stories/Composites/CallComposite/1ton/Start1toN.story.tsx, packages/storybook8/stories/Composites/CallComposite/1ton/components/IncomingCallAlerts.tsx, packages/storybook8/stories/Composites/CallComposite/1ton/components/SimpleCallScreen.tsx, packages/storybook8/stories/Composites/CallComposite/1ton/components/SimpleInboundHomeScreen.tsx, packages/storybook8/stories/Composites/CallComposite/1ton/index.stories.tsx, packages/storybook8/stories/Composites/CallComposite/1ton/snippets/Container1toNInbound.snippet.tsx, packages/storybook8/stories/Composites/CallComposite/1ton/snippets/Container1toNOutbound.snippet.tsx, packages/storybook8/stories/Composites/CallComposite/1ton/snippets/Quickstart1ToN.snippet.tsx, packages/storybook8/stories/Composites/CallComposite/1ton/snippets/Utils.tsx
Migrate 1:N call composite page
https://skype.visualstudio.com/SPOOL/_workitems/edit/3786003
=> [Storybook8] Migrate 1:N call composite page

packages/storybook8/stories/INTERNAL/ComplianceBanner/ComplianceBanner.story.tsx, packages/storybook8/stories/INTERNAL/ComplianceBanner/Docs.mdx, packages/storybook8/stories/INTERNAL/ComplianceBanner/index.stories.tsx, packages/storybook8/stories/INTERNAL/ComplianceBanner/snippets/ComplianceBanner.snippet.tsx
Migrate compliance banner to v8
https://skype.visualstudio.com/SPOOL/_workitems/edit/3810831
=> [Storybook8] Migrate compliance banner to v8

packages/storybook8/stories/INTERNAL/CaptionsBanner/CaptionsBanner.story.tsx, packages/storybook8/stories/INTERNAL/CaptionsBanner/Docs.mdx, packages/storybook8/stories/INTERNAL/CaptionsBanner/index.stories.tsx, packages/storybook8/stories/INTERNAL/CaptionsBanner/mockCaptions.ts, packages/storybook8/stories/INTERNAL/CaptionsBanner/snippets/CaptionsBanner.snippet.tsx
=> [Storybook8] Migrate captions banner to v8

change-beta/@azure-communication-react-74563221-eef7-4d5a-ad93-71af47706da1.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update communication calling to 1.28.1-beta.4 and 1.27.5
=> Update communication calling to 1.28.1-beta.4 and 1.27.5

common/config/babel/features.js, packages/calling-component-bindings/src/utils/videoGalleryUtils.ts, packages/calling-stateful-client/src/CallClientState.ts, packages/calling-stateful-client/src/CallContext.ts, packages/calling-stateful-client/src/Converter.ts, packages/calling-stateful-client/src/RemoteVideoStreamSubscriber.ts, packages/calling-stateful-client/src/StreamUtils.test.ts
Remove CC for video-stream-is-recieving feature
cleans up the code base
https://skype.visualstudio.com/SPOOL/_workitems/edit/3813481
Validated build locally, CI to check again
=> [VideoStreamAvailable] remove stream available cc comment

common/config/babel/features.js, packages/calling-component-bindings/src/hooks/usePropsFor.ts, packages/calling-component-bindings/src/index.ts, packages/calling-component-bindings/src/notificationStackSelector.ts, packages/communication-react/src/index.ts, packages/react-components/src/components/NotificationStack.tsx, packages/react-components/src/components/index.ts, packages/react-components/src/components/utils.ts, packages/react-components/src/localization/LocalizationProvider.tsx, packages/react-components/src/theming/icons.tsx, packages/react-composites/src/composites/CallComposite/CallComposite.tsx, packages/react-composites/src/composites/CallComposite/components/CallArrangement.tsx, packages/react-composites/src/composites/CallComposite/pages/CallPage.tsx, packages/react-composites/src/composites/CallComposite/pages/HoldPage.tsx, packages/react-composites/src/composites/CallComposite/pages/LobbyPage.tsx, packages/react-composites/src/composites/CallComposite/pages/TransferPage.tsx, packages/react-composites/src/composites/CallComposite/types/ErrorTracking.ts, packages/react-composites/src/composites/CallComposite/utils/TrackErrors.ts, packages/react-composites/src/composites/CallComposite/utils/Utils.ts
=> Remove notifications cc

change-beta/@azure-communication-react-59e6959f-de97-409a-a1d1-20784e61652a.json, change/@azure-communication-react-59e6959f-de97-409a-a1d1-20784e61652a.json, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
Fix bug where adapter captions event is not firing 
https://skype.visualstudio.com/SPOOL/_workitems/edit/3810382
=> Fix bug where adapter captions event is not firing 

common/config/babel/features.js, packages/react-composites/src/composites/CallComposite/components/BreakoutRoomsBanner.tsx
Promote breakout rooms feature to beta
Release breakout rooms for beta
Locally tested call with chat sample app with 'beta-release' flavor and verified that breakout rooms is working
=> Promote breakout rooms feature to beta

GROOMME.md, packages/communication-react/CHANGELOG.beta.md
=> Groom changelog beta release beta/1.19.0 beta.2

change-beta/@azure-communication-react-adee31e2-62cb-4055-8a4d-851707056dc5.json, change/@azure-communication-react-adee31e2-62cb-4055-8a4d-851707056dc5.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-components/src/components/CameraButton.tsx, packages/react-components/src/components/MicrophoneButton.tsx, packages/react-components/src/components/VideoGallery/useVideoTileContextualMenuProps.ts, packages/react-components/src/localization/locales/en-US/strings.json
Updates aria labels to match visible name requirements for
- pinning
- camera button
- mic button
Fixes issue where announced name does not match the visible name
https://skype.visualstudio.com/SPOOL/_workitems/edit/3832398
=> [A11y Ezra] Fix visible names for pinning, camera and mic buttons

change/@azure-communication-react-59e6959f-de97-409a-a1d1-20784e61652a.json, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts
=> Revert "Fix bug where adapter captions event is not firing

packages/storybook8/stories/Components/ParticipantList/Docs.mdx, packages/storybook8/stories/Composites/GettingStarted.mdx, packages/storybook8/stories/Concepts/CustomUserDataModel/Docs.mdx, packages/storybook8/stories/StatefulClient/Overview.mdx, packages/storybook8/stories/UseCases.mdx
Fixing broken links
Bugs found during bug bash
=> [Storybook8] Fixing broken links found during bugbash

packages/storybook8/stories/Concepts/Styling/ControlBar.story.tsx, packages/storybook8/stories/Concepts/Styling/Docs.mdx, packages/storybook8/stories/Concepts/Styling/VideoTile.story.tsx, packages/storybook8/stories/Concepts/Styling/snippets/StylingVideoTile.snippet.tsx
Updating the styles concept with examples
Updated the content for video tile
=> [Storybook] Updating the Styles concept with the live examples

packages/storybook8/stories/Composites/CallWithChatComposite/JoinExample.stories.tsx
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/331c9afe-50db-43d4-b486-677b50f2f630) |  ![image](https://github.com/user-attachments/assets/1450a717-3ef3-465a-b6b2-a0bd241f9370) |
=> [Storybook] Removing extra arguments from call with chat story

packages/storybook/stories/CallComposite/Quickstart1ToNDocs.stories.mdx, packages/storybook/stories/CallComposite/QuickstartPSTNDocs.stories.mdx, packages/storybook/stories/Dialpad/Dialpad.stories.tsx, packages/storybook8/stories/Composites/CallComposite/1ton/Docs.mdx, packages/storybook8/stories/Composites/CallComposite/pstn/Docs.mdx
Remove beta banners for outbound stories
Mark the outbound pages as GA
Validate locally checked the link generated
=> [Inbound-outbound] remove beta banners from storybook

common/config/jest/jest.config.js, common/config/jest/resolver.js, common/config/package.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/acs-ui-common/package.json, packages/acs-ui-javascript-loaders/package.json, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/chat-component-bindings/package.json, packages/chat-stateful-client/jest.config.js, packages/chat-stateful-client/package.json, packages/communication-react/package.json, packages/fake-backends/package.json, packages/react-components/package.json, packages/react-composites/jest.config.js, packages/react-composites/package.json, samples/tests/package.json, tools/check-typescript-regression/package.json
Added resolved to fix issues for Jest when resolving between ESM and CommonJS versions for node
Tests, CI
=> Jest config update to fix an issue with dependencies

common/config/rush/pnpm-lock.yaml, packages/storybook/package.json
Fix a storybook issue caused by recent package updates. The resolutions filed is added to help `storybook-docs-toc` to resolve `tocbot` dependency correctly. Otherwise, an error about init issue (caused by tocbot import) will be thrown when running storybook
=> Resolve tocbot package to a version supported by storybook 6 addons

packages/storybook8/stories/Components/MessageThread/Docs.mdx, packages/storybook8/stories/Components/MessageThread/MessageThread.story.tsx, packages/storybook8/stories/Components/MessageThread/index.stories.tsx
Fixing arg tables to display proper arguments
Fixing Controls to remove what is not relevant
=> [Storybook] Fixing the args table and story controls

change-beta/@azure-communication-react-37eb3183-231d-470a-a079-4233c7907215.json, packages/calling-component-bindings/src/handlers/createHandlers.ts, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallComposite/components/CallControls.tsx, packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts, packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx
=> Address ARB comments for DNS

change-beta/@azure-communication-react-b61075b9-55ef-466f-b1f0-ce91924112bb.json, change/@azure-communication-react-b61075b9-55ef-466f-b1f0-ce91924112bb.json, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/chat-component-bindings/package.json, packages/chat-stateful-client/package.json, packages/communication-react/package.json, packages/fake-backends/package.json, packages/react-composites/package.json, packages/storybook/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Chat/package.json, samples/ComponentExamples/package.json, samples/Server/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Chat SDK and signaling dependencies update
Build and run tests locally
=> Chat SDK and Signaling dependencies update

common/config/babel/features.js
Included together mode dev tag. This tag will be used for conditional builds/releases
This is needed to ensure together mode dev changes do not block new releases and builds
Tested locally
=> Include dev tag for conditional build for together mode

change-beta/@azure-communication-react-999d9f34-b162-40fd-b153-3fba2004323d.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
Add default option in CallWithChat
=> Add default option in CallWithChat

packages/communication-react/CHANGELOG.beta.md
=> Changelog update for text only messaging policy

GROOMME.md, packages/communication-react/CHANGELOG.stable.md
=> Groom changelog stable remove beta suffix/1.19.0

packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
=> Address arb comments from 1.19.0

packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts
=> Cherypick in arb comments suggestions (already merged in main)

packages/acs-ui-javascript-loaders/src/callCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/chatCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.test.tsx
=> Cherry-pick: fix test mock imports (#5172)

packages/communication-react/CHANGELOG.stable.md
=> Update release notes for adhoc

packages/communication-react/CHANGELOG.stable.md
=> Cherrypick release notes update for adhoc

packages/communication-react/CHANGELOG.stable.md
=> Update changelogs, remove rte changelogs from stable md

packages/communication-react/CHANGELOG.stable.md
=> Cherrypick release note updates, remove rte releted notes

samples/CallWithChat/src/app/utils/AppUtils.ts, samples/CallWithChat/src/app/utils/ShakeToSendLogs.tsx, samples/CallWithChat/src/app/utils/createThread.ts, samples/CallWithChat/src/app/utils/credential.ts, samples/CallWithChat/src/app/utils/getEndpointUrl.ts, samples/CallWithChat/src/app/utils/joinThread.ts, samples/CallWithChat/src/app/utils/refreshToken.ts, samples/CallWithChat/src/app/views/CallScreen.tsx, samples/Calling/src/app/App.tsx, samples/Calling/src/app/utils/AppUtils.ts, samples/Calling/src/app/utils/ShakeToSendLogs.tsx, samples/Calling/src/app/utils/credential.ts, samples/Calling/src/app/views/CallScreen.tsx, samples/CallingStateful/src/utils/AppUtils.ts, samples/CallingStateful/src/utils/credential.ts, samples/Chat/src/app/App.tsx, samples/Chat/src/app/utils/ShakeToSendLogs.tsx, samples/Chat/src/app/utils/createThread.ts, samples/Chat/src/app/utils/credential.ts, samples/Chat/src/app/utils/emojiCache.ts, samples/Chat/src/app/utils/getEndpointUrl.ts, samples/Chat/src/app/utils/getToken.ts, samples/Chat/src/app/utils/joinThread.ts, samples/Chat/src/app/utils/refreshToken.ts, samples/Chat/src/app/utils/setEmoji.ts, samples/ComponentExamples/src/utils/getEndpointUrl.ts, samples/ComponentExamples/src/utils/getToken.ts, samples/StaticHtmlComposites/src/service.js
Ensure all links to resources or to `home` are relative and not pointed at the root route
Creates difficulty. One friction point is in hosting samples under sub routes (e.g. mysite.com/chatApp, this won't work if the links are relative as links will hit mysite.com/main.js instead of mysite.com/chatApp/main.js)
Ran locally and made sure everything was working as expected including assets such as video backgrounds and sound effects:
| app | screenshot |
| -- | -- |
| calling |  ![image](https://github.com/user-attachments/assets/1197f0bb-5ebe-4e6f-ac06-c527e381b1fe) |
| call with chat | ![image](https://github.com/user-attachments/assets/69181c3b-6f6f-4540-923b-0dcf8634724e) |
| chat | ![image](https://github.com/user-attachments/assets/08534978-0f20-47ab-8ab1-c9f975f8d419) |
=> Ensure all sample links are relative and not pointed at the root route

change-beta/@azure-communication-react-2370b346-59bb-4073-9237-5f3206c9dbc0.json, change/@azure-communication-react-2370b346-59bb-4073-9237-5f3206c9dbc0.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/src/composites/common/ControlBar/DesktopMoreButton.tsx, packages/react-composites/src/composites/common/Drawer/MoreDrawer.tsx, packages/react-composites/src/composites/common/types/CommonCallControlOptions.tsx
Fix bugs with hiding:
- hold button
- Gallery options
- DTMF Dialer button
Fix broken or missing API's for customizing the CallComposite and CWCComposite
https://skype.visualstudio.com/SPOOL/_workitems/edit/3883982
https://skype.visualstudio.com/SPOOL/_workitems/edit/3884054
https://skype.visualstudio.com/SPOOL/_workitems/edit/3884056
=> [Bug fixes] update control API's

common/scripts/install-run-rush-pnpm.js, common/scripts/install-run-rush.js, common/scripts/install-run-rushx.js, common/scripts/install-run.js, rush.json
Merge in changes from https://github.com/Azure/communication-ui-library/pull/5195
Merge commit will include appropriate Co-authored-by
=> Pull in 5195

packages/storybook8/.storybook/preview.tsx, packages/storybook8/stories/Components/SendBox/RichTextSendBox/snippets/RichTextSendBoxAttachmentUploads.snippet.tsx, packages/storybook8/stories/Components/SendBox/SendBox/snippets/AttachmentUploads.snippet.tsx
Storybook 8 bug bash issue found where icons were missing 
Fixing missing icons
=> [Storybook] Adding method to initialize icons 

rush.json
bumped rush to latest stable release
OCE
=> [OCE] Rush Version Bump

packages/react-composites/src/composites/localization/locales/de-DE/strings.json, packages/react-composites/src/composites/localization/locales/it-IT/strings.json, packages/react-composites/src/composites/localization/locales/nl-NL/strings.json, packages/react-composites/src/composites/localization/locales/sv-SE/strings.json, packages/react-composites/src/composites/localization/locales/tr-TR/strings.json
Update strings for new release
new translations are happy translations
inspected locally
=> [1.20.0-beta.1 release] TDBuild latest localization

common/config/babel/features.js
Move JS loaders into beta flavor
Moves feature out of alpha
built and tested locally
=> [JS-loaders] beta js-loaders

packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallNotification/Docs.mdx
Fix bad header
bad header in sb
Caught and validated locally
=> fix sb issue inbound calling

packages/storybook8/stories/Components/IncomingCallNotification/IncomingCallNotification/Docs.mdx
Fix header issues in sb 8 for IncomingCallNotification
Fixes header issue
Validated locally check link
=> [Inbound Calling] SB Page fix in v8

packages/acs-ui-javascript-loaders/src/callCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/chatCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.ts
Fix issues where composite options were not being set appropriately by the spread
Allows composite options to be set correctly
Validate locally with tgz
=> [JS-loaders] fix composite options spread

packages/acs-ui-javascript-loaders/src/callCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/chatCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.ts
Cherry pick js loaders fix
fixes composite options issue with cherrypick from main
validated on main
=> [Cherry-pick] js loaders fix

packages/storybook8/stories/Concepts/InboundCalling/Docs.mdx
* fix page
* fix links
* Update packages/storybook8/stories/Concepts/InboundCalling/Docs.mdx
---------
=> [SB8] inbound calling fix page Meta import and links (#5254)

samples/CallWithChat/src/app/views/HomeScreen.tsx, samples/Chat/src/app/App.tsx
=> Enable rich editor by default in samples

packages/react-components/src/components/VideoGallery.test.tsx, packages/storybook/stories/Localization.stories.mdx, packages/storybook/stories/locales.ts, packages/storybook8/stories/Concepts/Localization/Docs.mdx, packages/storybook8/stories/locales.ts
Cherry pick #5248 to release/1.20.0-beta.1
Ensure latest storybook content is in release branch
=> [Cherry-pick] Add Welsh to storybook (#5248)

.github/workflows/update-api-files.yml, change/@azure-communication-react-1613cd0b-4030-4c16-a819-73169c2cae7f.json
Sanitize checkout command by using git builtin actions.
It was possible for someone to RCE (remote code execution) by creating a new branch with a name that has command injection names like `nameofbranch;id`
=> Sanitize pr branch in update-api-files ci yaml file

README.md, packages/communication-react/README.md
Fixing storybook links after storybook 8 migration
=> [ReadMe] Fixing readme storybook links

packages/storybook8/stories/Composites/Adapters/Docs.mdx
Fixing bug found during bug bash where method signature was empty.
=> [Storybook] BugFix to fill in the sendMessage method signature

common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml
=> Remove stale ref to http in stable lock

packages/acs-ui-javascript-loaders/src/callCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/callCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.ts
Updates per ARB comments
ARB wanted some of the naming updated
API checked locally
=> [JS-loaders] js loader arb comments

GROOMME.md, packages/communication-react/CHANGELOG.stable.md
Grooming of changelog for 1.20.0 release
=> 1.20.0 changelog

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, common/scripts/force-build-flavor.mjs, packages/calling-component-bindings/package.json, packages/communication-react/package.json, packages/react-composites/package.json
Updates peers deps and enables common versions for the package
Deps for release will be wrong for DNS
Updated locally testing in bug bash
=> update calling-effects to be right peer-dep

change-beta/@azure-communication-react-9027708a-39a4-4de9-bc14-a6f55681f927.json, change/@azure-communication-react-9027708a-39a4-4de9-bc14-a6f55681f927.json, packages/acs-ui-javascript-loaders/src/callCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/callCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/chatCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/chatCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md
* update API per ARB
* Change files
* fix per comment
=> [JS-loaders] update API per ARB (#5322)

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, common/scripts/force-build-flavor.mjs, packages/calling-component-bindings/package.json, packages/communication-react/package.json, packages/react-composites/package.json
Cherrypick #5320 to release/1.20.0
=> Cherrypick communication effects updates (#5320) to release/1.20.0

change/@azure-communication-react-b66a19ea-69f9-407f-9826-28640b4162f8.json, change/@azure-communication-react-f71cc622-5f0e-4a3b-bd13-1c85b9438135.json, packages/react-composites/src/composites/common/HiddenFocusStartPoint.tsx
Cherry pick #5311 to release branch
* Resolve console errors for aria-hidden
* Fix aria-hidden bug
=> Resolve console errors for aria-hidden (#5311)

common/config/babel/features.js, packages/calling-component-bindings/src/handlers/createCommonHandlers.ts, packages/calling-component-bindings/src/handlers/createHandlers.ts, packages/calling-component-bindings/src/handlers/createTeamsCallHandlers.ts, packages/calling-component-bindings/src/index.ts, packages/communication-react/src/index.ts, packages/react-components/src/components/MicrophoneButton.tsx, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/createHandlers.ts, packages/react-composites/src/composites/CallComposite/components/CallControls.tsx, packages/react-composites/src/composites/CallComposite/components/buttons/Microphone.tsx, packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts, packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/state/CallWithChatAdapterState.ts, packages/react-composites/src/composites/common/ControlBar/CommonCallControlBar.tsx, packages/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependency.ts, packages/react-composites/src/composites/common/resolveDeepNoiseSuppressionDependencyLazy.ts, packages/react-composites/src/composites/index.ts, samples/CallWithChat/src/app/views/CallScreen.tsx, samples/Calling/src/app/views/CallScreen.tsx
Remove conditional-compile lines for DNS
Housekeeping now this feature is stabilized
CI only
=> Remove conditional-compile lines for DNS

common/config/babel/features.js, packages/acs-ui-javascript-loaders/src/callCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/chatCompositeLoader.test.tsx, packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.test.tsx, packages/communication-react/src/api-summary.ts, packages/communication-react/src/javascript-loaders.ts
remove conditional-compile lines for composite-js-helpers
housekeeping now the feature is stable
CI only
=> remove conditional-compile lines for composite-js-helpers

common/config/babel/features.js
remove `notifications` from features.js
It's already been stabilized and conditional-compile lines removed, just wasn't removed from this file
CI only
=> remove `notifications` from features.js

packages/storybook8/stories/Composites/CallComposite/Docs.mdx, packages/storybook8/stories/Composites/CallWithChatComposite/Docs.mdx
The vertical alignment was off 
| Before | After |
|-------|------|
| ![image](https://github.com/user-attachments/assets/9579d623-b26d-4eb6-b1dc-7e00d904d3a3) | ![image](https://github.com/user-attachments/assets/4fd7ba65-2298-4b99-9192-921b83d0ecbc) |
=> [Storybook] Fixing vertical alignment on banner 

change-beta/@azure-communication-react-27b510f4-06e8-4bad-b2cd-bd161ee4156c.json, change/@azure-communication-react-27b510f4-06e8-4bad-b2cd-bd161ee4156c.json, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/chat-component-bindings/package.json, packages/chat-stateful-client/package.json, packages/communication-react/package.json, packages/fake-backends/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Chat/package.json, samples/ComponentExamples/package.json, samples/Server/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
bump Chat SDK and Signaling to latest stable release
OCE
=> [Chat] Bump Chat SDK & Signaling to Latest Stable

.github/workflows/ci.yml, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, rush.json, samples/CallingStateful/package.json, samples/CallingStateful/src/App.tsx, samples/CallingStateful/src/utils/AppUtils.ts, samples/CallingStateful/src/views/Homescreen.tsx
Fix calling build error, add PR validation to prevent it from happening again
=> Fix calling build error, add PR validation to prevent it from happening again

packages/storybook8/stories/Composites/TypeScriptLoading/Docs.mdx
Update docs for new API released to stable in 1.20.0
Makes sure that the code snippets that are shown are complete for Contoso developers
Validated and tested locally in angular application
=> [JS loaders] update docs for new API

GROOMME.md, packages/communication-react/CHANGELOG.beta.md
Groom changelog for 1.21.0-beta.1
=> Groom changelog beta release beta/1.21.0-beta.1

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update Calling SDK
OCE duties
- possible fix for pptlive issues
https://skype.visualstudio.com/SPOOL/_workitems/edit/3936837
=> [Calling OCE] update SDK and lock file

change-beta/@azure-communication-react-1ac98c80-317f-4cb7-bec3-13148744e063.json, common/scripts/install-run-rush.js, common/scripts/install-run.js, packages/acs-ui-common/package.json, packages/acs-ui-javascript-loaders/package.json, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/chat-component-bindings/package.json, packages/chat-stateful-client/package.json, packages/communication-react/package.json, packages/fake-backends/package.json, packages/react-components/package.json, packages/react-composites/package.json, rush.json, tools/custom-eslint-rules/package.json
Update rush and upper node version dependency
New stable node version 22.11.0 dropped 
Locally on Mac. Tested a majority of the rush commands and also all samples on stable and beta.
=> Update rush and allowed upper node version dependency

change-beta/@azure-communication-react-f123417c-ad8d-4b6b-b2b1-bc4c3dab23dd.json, change/@azure-communication-react-f123417c-ad8d-4b6b-b2b1-bc4c3dab23dd.json, packages/react-components/src/components/ChatMessage/MyMessageComponents/ChatMessageComponentAsRichTextEditBox.tsx
=> [Bugfix] Add enter key support for rich text edit box

change-beta/@azure-communication-react-5f11122d-43e1-41c2-8a05-e6a229f6f4e0.json, common/config/package.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/chat-stateful-client/package.json, packages/communication-react/package.json, packages/react-components/package.json, packages/react-components/src/components/styles/ControlBar.styles.ts, packages/react-composites/package.json, packages/react-composites/src/composites/CallComposite/styles/Buttons.styles.ts, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/Server/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json, tools/check-typescript-regression/package.json
Update lock files
Update controlBar style that was impacted due to updated lock files
Update minimum typescript version to be azure minimum version compliant and to work with new 22 node version
To address Dependabot alert for http-proxy-middleware
=> Update lock files and minimum typescript version

GROOMME.md, packages/communication-react/CHANGELOG.stable.md
Groom changelog
gets changelog ready for 1.21.0
https://skype.visualstudio.com/SPOOL/_workitems/edit/3951122
=> Groom changelog stable remove beta suffix/1.21.0

change-beta/@azure-communication-react-9feaa64e-c9a2-4735-bcb4-4575f297e9b8.json, change-beta/@azure-communication-react-f238271e-67ab-425c-9992-fe015c0f720b.json, change/@azure-communication-react-9feaa64e-c9a2-4735-bcb4-4575f297e9b8.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update @azure/communication-calling to 1.31.2-beta.1 and `@azure/communication-calling-effects` to 1.1.2
Housekeeping
CI only
=> Update @azure/communication-calling to 1.31.2-beta.1 and `@azure/communication-calling-effects` to 1.1.2

packages/storybook8/stories/Composites/GettingStarted.mdx
As per feedback from partner team, just a quick easy way to make things easier for developers.
=> [Storybook] Updating the title of links as per feedback

packages/storybook8/stories/Composites/GettingStarted.mdx
As per feedback from partner team, it looks like the documentation was linking to an old or unrelated MSDocs page
=> [Storybook] Updating the MSDocs link

change-beta/@azure-communication-react-607ea308-d603-4e67-937f-e27ee4d302bd.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/src/composites/CallComposite/Strings.tsx, packages/react-composites/src/composites/localization/locales/en-US/strings.json
Localization string for together mode feature
This will be used for label description of the feature
locally
=> localization string for together mode

change-beta/@azure-communication-react-72977404-64c6-4c7b-b986-1d0577780573.json, packages/calling-stateful-client/src/Converter.ts
Fix conditional compiling issue when building apiview
locally
=> Fix conditional compile

docs/releases/creating-a-release.md
=> Updated release documentation to include Storybook bug bash

common/autoinstallers/rush-prettier/pnpm-lock.yaml
Update rush-prettier to. cross-spawn 7.0.6
Mitigate a CVE
=> Update deps for auto installer rush prettier

common/config/rush/variants/stable/pnpm-lock.yaml
=> Update cross-spawn to 7.0.6

packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/src/composites/common/AvatarPersona.tsx
=> Revert changes to add undefined return type so we are not introducing breaking change

packages/calling-stateful-client/src/StatefulCallClient.test.ts
=> Revert Jest Test changes

packages/storybook8/stories/Components/Overview.mdx
=> Fixed broken link to video gallery storybook page

change-beta/@azure-communication-react-c5279882-64d8-46d1-bc3a-d8db400c1aad.json, change/@azure-communication-react-c5279882-64d8-46d1-bc3a-d8db400c1aad.json, samples/CallingStateful/src/components/CallingComponents.tsx
Build caption components inside Calling Stateful sample
=> Build caption components inside Calling Stateful sample

common/config/rush/variants/stable/pnpm-lock.yaml
- Update cross-spawn to 7.0.6 
- Update path-to-regexp to 0.1.12
=> Update pnpm-lock.yaml for stable

GROOMME.md, packages/communication-react/CHANGELOG.stable.md
Groom changelog 
Release task https://skype.visualstudio.com/SPOOL/_sprints/taskboard/ACS%20Calling%20Web%20UI/SPOOL/CY2024-H2/CY2024-Q4/Sprint%20130%20(Ends%20Dec%2022)?workitem=3980475
Not tested
=> Groom changelog stable remove beta suffix/1.22.0

samples/Calling/src/app/App.tsx, samples/Calling/src/app/theming/SwitchableFluentThemeProvider.tsx, samples/Calling/src/app/theming/ThemeSelector.tsx, samples/Calling/src/app/views/CallScreen.tsx, samples/Calling/src/app/views/Footer.tsx, samples/Calling/src/app/views/HomeScreen.tsx
Remove empty lines left over from CC removal
Creates a cleaner codebase and removes unnecessary lines
https://skype.visualstudio.com/SPOOL/_workitems/edit/3990959
white space removal, not needed CI to validate
=> [Calling Sample Cleanup] remove empty lines

change-beta/@azure-communication-react-d8ba7749-9ddc-42f0-b17b-50765eeca2c8.json, change/@azure-communication-react-d8ba7749-9ddc-42f0-b17b-50765eeca2c8.json, packages/react-components/src/components/ParticipantItem.tsx, packages/react-components/src/components/VideoGallery.tsx
1.Fix a condition compile, one line change
2.Fix comments on video gallery props
=> Fix condition compile for hard mute.

common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update to new Calling version of 1.32.1
Keeps us up to date
https://skype.visualstudio.com/SPOOL/_workitems/edit/3996775
Built and tested locally
=> [Calling OCE] update stable calling version

packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/src/composites/common/icons.tsx
=> Remove together mode api

packages/calling-stateful-client/src/CapabilitiesSubscriber.ts
=> Fuyan/cherry pick to release 1.23.0 hardmute notifications

change-beta/@azure-communication-react-faac48af-e358-4721-94c8-d68d6d0db9fa.json, packages/communication-react/review/beta/communication-react.api.md, packages/react-components/src/components/CaptionsBanner.tsx, packages/react-components/src/localization/locales/en-US/strings.json, packages/react-composites/src/composites/CallComposite/Strings.tsx, packages/react-composites/src/composites/common/CallingCaptionsBanner.tsx, packages/react-composites/src/composites/localization/locales/en-US/strings.json
Display warning message when RTT exceed max length 2000
=> Display warning message when RTT exceed max length 2000

common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/react-components/src/components/RichTextEditor/Plugins/PlaceholderPlugin.tsx
- Ran `rush update --full` command for both flavors
- Updated the Watermark plugin as the same code is added to rooster plugin: https://github.com/microsoft/roosterjs/blob/54c7dbe316cc2a6ccc986490390a2dcc954dfece/packages/roosterjs-content-model-plugins/lib/watermark/WatermarkPlugin.ts#L108
The projects can be built
=> Updated the dependencies to fix security alerts

change-beta/@azure-communication-react-4392d66a-977b-41c7-b958-fd05d29b3566.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update to latest communication calling beta
=> Update to 1.33.1-beta.1 communication calling version

change-beta/@azure-communication-react-72804e5e-cf17-4d1b-8d4a-bbd6b22a1c26.json, packages/calling-component-bindings/src/baseSelectors.ts, packages/calling-component-bindings/src/captionsSelector.ts, packages/calling-component-bindings/src/handlers/createCommonHandlers.ts, packages/calling-stateful-client/src/CallClientState.ts, packages/calling-stateful-client/src/CallContext.ts, packages/calling-stateful-client/src/CallSubscriber.ts, packages/calling-stateful-client/src/Converter.ts, packages/calling-stateful-client/src/RealTimeTextSubscriber.ts, packages/calling-stateful-client/src/StreamUtils.test.ts, packages/calling-stateful-client/src/index-public.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-composites/src/composites/CallComposite/MockCallAdapter.ts, packages/react-composites/src/composites/CallComposite/Strings.tsx, packages/react-composites/src/composites/CallComposite/adapter/AzureCommunicationCallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallComposite/adapter/index.ts, packages/react-composites/src/composites/CallComposite/hooks/useHandlers.ts, packages/react-composites/src/composites/CallComposite/index.ts, packages/react-composites/src/composites/CallComposite/selectors/baseSelectors.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/AzureCommunicationCallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatBackedCallAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts, packages/react-composites/src/composites/localization/locales/en-US/strings.json, packages/react-composites/tests/app/lib/MockCallAdapter.ts, packages/react-composites/tests/browser/call/hermetic/fixture.ts
Stateful and component binding layer API changes and adapters 
=> RTT Feature: Stateful and component binding layer API changes and adapters 

change-beta/@azure-communication-react-2638c945-5b3c-465d-b43a-f7ce6a958c99.json, change/@azure-communication-react-2638c945-5b3c-465d-b43a-f7ce6a958c99.json, packages/calling-component-bindings/src/baseSelectors.ts, packages/calling-component-bindings/src/handlers/createCommonHandlers.ts, packages/calling-component-bindings/src/notificationStackSelector.ts, packages/calling-component-bindings/src/participantListSelector.ts, packages/calling-component-bindings/src/utils/participantListSelectorUtils.ts, packages/calling-component-bindings/src/utils/videoGalleryUtils.ts, packages/calling-component-bindings/src/videoGallerySelector.ts
Part 2 PR to remove "media-access" conditional compile
=> Remove hard mute conditional compile part 2

packages/storybook8/stories/Components/CaptionsBanner/snippets/CaptionsBanner.snippet.tsx
Storybook Update: Captions Banner snippet
=> Storybook Update: Captions Banner snippet

GROOMME.md, packages/communication-react/CHANGELOG.beta.md
Groomed changelogs. 
Many logs regarding feature work has been removed as they are added as a feature release notes.
=> Groom changelog beta release beta/1.24.0 beta.1

packages/storybook8/stories/Composites/GettingStarted.mdx, packages/storybook8/stories/StatefulClient/Chat/Docs.mdx
- Fix storybook deadlink and grammar
=> [Storybook] Fix storybook deadlink and grammar

packages/storybook8/stories/Components/ControlBar/Buttons/Participants/Docs.mdx, packages/storybook8/stories/Components/VideoGallery/Docs.mdx, packages/storybook8/stories/Concepts/Rooms/Docs.mdx, packages/storybook8/stories/Concepts/Theming/Docs.mdx
Update storybook deadlinks found during 1.24.0-beta.1 storybook bugbash
=> Update storybook deadlinks

packages/storybook8/stories/Components/ControlBar/Buttons/Participants/Docs.mdx, packages/storybook8/stories/Components/VideoGallery/Docs.mdx, packages/storybook8/stories/Composites/GettingStarted.mdx, packages/storybook8/stories/Concepts/Rooms/Docs.mdx, packages/storybook8/stories/Concepts/Theming/Docs.mdx, packages/storybook8/stories/StatefulClient/Chat/Docs.mdx
=> Cherry pick storybook deadlink fixes to 1.24.0 beta.1

GROOMME.md, packages/communication-react/CHANGELOG.stable.md
Groom changelog for 1.24.0
Updates the changelog for users looking to update to new release
https://skype.visualstudio.com/SPOOL/_workitems/edit/4024659
Edited locally, feature owners to validate
=> Groom changelog stable remove beta suffix/1.24.0

common/config/package.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml
https://github.com/Azure/communication-ui-library/security/dependabot/291
=> Update octokit versions to resolve dependabot alert 

samples/tests/StaticHtmlComposites/CompositeJavascriptTest.test.ts
Cherrypick the fix of chat snapshot
=> Fix chat composite snapshot (#5667)

common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/react-composites/package.json, samples/Server/package.json, samples/Server/src/routes/issueToken.ts, samples/tests/package.json
=> Update Express to v5

packages/storybook8/stories/Components/GettingStarted/Docs.mdx, packages/storybook8/stories/Composites/GettingStarted.mdx, packages/storybook8/stories/Setup.mdx, packages/storybook8/stories/StatefulClient/Call/Docs.mdx, packages/storybook8/stories/StatefulClient/Chat/Docs.mdx
Remove the reference to specific node versions in storybook
To encourage developers to use the LTS of node when working with the UI Library
https://skype.visualstudio.com/SPOOL/_workitems/edit/4051730
Removed and inspected locally
=> [BugFix] Remove node versions from storybook

change-beta/@azure-communication-react-f1119615-cc1f-466d-b6a2-36963f51adbe.json, change/@azure-communication-react-f1119615-cc1f-466d-b6a2-36963f51adbe.json, packages/react-composites/src/composites/CallComposite/components/SidePane/SidePane.tsx
Add aria-modal to sidepane as required by Ezra's A11y requirements
Ezra accessibility requirement
=> [bugfix][A11Y] Add aria-modal to sidepane

change-beta/@azure-communication-react-2391dbc0-f978-47bd-bdb0-74d5b222f1ef.json, change/@azure-communication-react-2391dbc0-f978-47bd-bdb0-74d5b222f1ef.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/calling-stateful-client/src/CallAgentDeclarative.test.ts, packages/calling-stateful-client/src/TestUtils.ts, packages/communication-react/package.json, packages/react-composites/package.json, packages/react-composites/src/composites/CallWithChatComposite/adapter/TestUtils.ts, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update calling to 1.34.1 beta.1 and 1.33.3.
OCE task: https://skype.visualstudio.com/SPOOL/_workitems/edit/4054441
Smoke tested group and interop call in beta and stable
=> Update calling to 1.34.1 beta.1 and 1.33.3

common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, samples/Chat/package.json
Update axios to 1.8.2. Retry of this PR #5697
Not tested
=> Update axios to 1.8.2

change-beta/@azure-communication-react-364a17bc-d253-45ca-8155-63469c3e5c64.json, change/@azure-communication-react-364a17bc-d253-45ca-8155-63469c3e5c64.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/communication-react/src/mergedHooks.ts
Reverts Azure/communication-ui-library#5723
=> Revert "Fixed an issue with types for usePropsFor"

change-beta/@azure-communication-react-e0545c42-a60f-4d36-adc9-ceeed3fb9614.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update @azure/communication-calling to 1.34.1-beta.2
Housekeeping
CI only
=> Update @azure/communication-calling to 1.34.1-beta.2

GROOMME.md, packages/communication-react/CHANGELOG.beta.md
Groom changelog beta release beta/1.26.0 beta.1
Release task - https://skype.visualstudio.com/SPOOL/_workitems/edit/4067225
Not tested
=> Groom changelog beta release beta/1.26.0 beta.1

change-beta/@azure-communication-react-1656d4b5-c12e-4210-a04f-ff68329560e7.json, change/@azure-communication-react-1656d4b5-c12e-4210-a04f-ff68329560e7.json, samples/StaticHtmlComposites/src/callWithChatComposite.js
Add adapter options for CallWithChat JS bundle
Customer issue - Rabibank
=> Add adapter options for CallWithChat JS bundle

change-beta/@azure-communication-react-1656d4b5-c12e-4210-a04f-ff68329560e7.json, change/@azure-communication-react-1656d4b5-c12e-4210-a04f-ff68329560e7.json, samples/StaticHtmlComposites/src/callWithChatComposite.js
* Add adapter options for CallWithChat JS bundle
* Change files
=> Add adapter options for CallWithChat JS bundle 

change-beta/@azure-communication-react-f284b77c-7245-43ab-a075-70286742e975.json, common/config/babel/features.js, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-components/src/components/VideoGallery.tsx, packages/react-composites/src/composites/CallComposite/adapter/CallAdapter.ts, packages/react-composites/src/composites/CallWithChatComposite/adapter/CallWithChatAdapter.ts
This PR takes together mode back to beta in main
Discussion for the fix for together mode is still in progress
locally
=> Revert back to beta in main

packages/storybook8/stories/Composites/GettingStarted.mdx, packages/storybook8/stories/StatefulClient/BestPractices.mdx, packages/storybook8/stories/StatefulClient/Chat/Docs.mdx
Minor fixes for storybook pages for 1.26.0-beta.1 release
Ensure our storybook pages are working and have high quality
Tested on generated chromatic link
=> Minor fixes for storybook pages

packages/storybook8/stories/Composites/GettingStarted.mdx, packages/storybook8/stories/StatefulClient/BestPractices.mdx, packages/storybook8/stories/StatefulClient/Chat/Docs.mdx
Cherry-pick from #5746
Update release branch before deploying storybook
Relying on chromatic links
=> [Cherry-pick] Minor fixes for storybook pages

packages/storybook8/stories/Composites/CallComposite/Docs.mdx, packages/storybook8/stories/Composites/CallWithChatComposite/Docs.mdx
=> Cherry pick lint error fix to release branch

change-beta/@azure-communication-react-4ac69105-f2b1-4fc4-84d2-be54da13084b.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, packages/storybook8/package.json
Updating dependency that was using lower version. 
As per governance compliance
=> Updating dependency as per component governance compliance

packages/storybook8/stories/UseCases.mdx
=> Fix typo in use cases storybook page

GROOMME.md, packages/communication-react/CHANGELOG.stable.md
Groom changelog
Provide up to date changelog for customers
to be reviewed by team
=> [release 1.26.0] Groom changelog stable remove beta suffix/1.26.0

change-beta/@azure-communication-react-689f960b-b78d-4091-90fa-8d3c95ddd0c6.json, change/@azure-communication-react-689f960b-b78d-4091-90fa-8d3c95ddd0c6.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/communication-react/package.json, packages/react-composites/package.json
Update calling effects
gets us up to date for next release
Updated locally to be bug bashed in 1.26.0 release
=> [Release] update calling effects 1.1.4

change-beta/@azure-communication-react-689f960b-b78d-4091-90fa-8d3c95ddd0c6.json, change/@azure-communication-react-689f960b-b78d-4091-90fa-8d3c95ddd0c6.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/communication-react/CHANGELOG.stable.md, packages/communication-react/package.json, packages/react-composites/package.json
Cherry pick calling effects update into release
Takes new package to release
Will be bug bashed in the release
=> [release] calling effect 1.1.4 cp

common/config/jest/jestSetup.js, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/CHANGELOG.stable.md, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Cherry pick stable PR into release branch
=> Cherry pick stable PR into release branch

packages/communication-react/review/stable/communication-react.api.md, packages/react-components/src/components/RealTimeText.tsx, packages/react-components/src/components/RealTimeTextModal.tsx, packages/react-components/src/components/StartRealTimeTextButton.tsx
=> RTT beta tag to public

change-beta/@azure-communication-react-8cd461d2-0d2d-46ae-b339-a3a525a7bc03.json, change/@azure-communication-react-8cd461d2-0d2d-46ae-b339-a3a525a7bc03.json, packages/storybook8/stories/Concepts/OnFetchProfile/Docs.mdx
Storybook Conceptual docs
https://skype.visualstudio.com/SPOOL/_workitems/edit/4081005
https://skype.visualstudio.com/SPOOL/_workitems/edit/4098245
=> [On Fetch Profile] Storybook Conceptual docs

packages/react-components/src/localization/locales/ar-SA/strings.json, packages/react-components/src/localization/locales/cs-CZ/strings.json, packages/react-components/src/localization/locales/cy-GB/strings.json, packages/react-components/src/localization/locales/de-DE/strings.json, packages/react-components/src/localization/locales/en-GB/strings.json, packages/react-components/src/localization/locales/es-ES/strings.json, packages/react-components/src/localization/locales/es-MX/strings.json, packages/react-components/src/localization/locales/fi-FI/strings.json, packages/react-components/src/localization/locales/fr-CA/strings.json, packages/react-components/src/localization/locales/fr-FR/strings.json, packages/react-components/src/localization/locales/he-IL/strings.json, packages/react-components/src/localization/locales/it-IT/strings.json, packages/react-components/src/localization/locales/ja-JP/strings.json, packages/react-components/src/localization/locales/ko-KR/strings.json, packages/react-components/src/localization/locales/nb-NO/strings.json, packages/react-components/src/localization/locales/nl-NL/strings.json, packages/react-components/src/localization/locales/pl-PL/strings.json, packages/react-components/src/localization/locales/pt-BR/strings.json, packages/react-components/src/localization/locales/ru-RU/strings.json, packages/react-components/src/localization/locales/sv-SE/strings.json, packages/react-components/src/localization/locales/tr-TR/strings.json, packages/react-components/src/localization/locales/zh-CN/strings.json, packages/react-components/src/localization/locales/zh-TW/strings.json
Add strings for release 1.26.0
keeps the strings up to date
https://skype.visualstudio.com/SPOOL/_workitems/edit/4084477
Strings inspected for localization
=> TDBuild latest localization

change-beta/@azure-communication-react-525ff3b4-cfad-4925-94d8-15236a6e93f7.json, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-components/src/components/RealTimeText.tsx, packages/react-components/src/components/RealTimeTextModal.tsx, packages/react-components/src/components/StartRealTimeTextButton.tsx
Change RTT beta tags to public 
=> Change RTT beta tags to public 

change-beta/@azure-communication-react-d737d8c0-d516-4f69-b8a6-3eadf602bfe5.json, change/@azure-communication-react-d737d8c0-d516-4f69-b8a6-3eadf602bfe5.json, packages/react-components/src/components/styles/Captions.style.ts
Ensure Text Wrap for long words without white space
=> Ensure Text Wrap for long words without white space

change-beta/@azure-communication-react-55b6b4ee-06ab-4550-916a-9a73a3db34ae.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
remade the branch and pushed the relevant changes
=> updating calling beta to 1.35.1-beta.1

change-beta/@azure-communication-react-59154632-56c2-4db8-8f13-8a751f330602.json, change/@azure-communication-react-59154632-56c2-4db8-8f13-8a751f330602.json, packages/react-components/src/components/Attachment/AttachmentCard.tsx
- Enable tooltip mouse hover by adding delay to tooltip
https://github.com/user-attachments/assets/0be9ba77-8e8e-46c1-ae36-3511f31aecc8
- Previously not able to hover mouse over tooltip, and will just disappear
=> [A11y] Enable tooltip mouse hover

change-beta/@azure-communication-react-91789f9f-671a-47b8-b1f7-567a3546beee.json, change/@azure-communication-react-91789f9f-671a-47b8-b1f7-567a3546beee.json, common/config/babel/features.js, packages/communication-react/review/stable/communication-react.api.md, samples/CallWithChat/src/app/views/CallScreen.tsx
=> [onFetchPRofile] Move onFetchProfile to stable

change-beta/@azure-communication-react-a5c3b979-eaac-4a2f-b2e9-633e0d468346.json, change/@azure-communication-react-a5c3b979-eaac-4a2f-b2e9-633e0d468346.json, packages/react-components/src/components/CaptionsBanner.tsx
[Accessibility Bug Fix] RTT list should not have direct child 'div'
https://skype.visualstudio.com/SPOOL/_workitems/edit/4111302
=> [Accessibility Bug Fix] RTT list should not have direct child 'div'

change-beta/@azure-communication-react-58c8d0bf-2aab-47a7-84ce-77ce88c56275.json, change/@azure-communication-react-58c8d0bf-2aab-47a7-84ce-77ce88c56275.json, packages/react-components/src/components/CaptionsSettingsModal.tsx, packages/react-components/src/components/RealTimeTextModal.tsx, packages/react-components/src/components/styles/CaptionsSettingsModal.styles.ts
https://skype.visualstudio.com/SPOOL/_workitems/edit/4111149
=> [Accessibility bug fix] Cancel button not have enough contrast when keyboard focused

GROOMME.md, packages/communication-react/CHANGELOG.beta.md
Groom changelog for 1.27.0-beta.1 release
=> 1.27.0-beta.1 changelog

packages/storybook8/stories/Components/CaptionsBanner/Docs.mdx, packages/storybook8/stories/Components/RealTimeText/Docs.mdx, packages/storybook8/stories/Components/RealTimeTextModal/Docs.mdx, packages/storybook8/stories/Components/StartRealTimeTextButton/Docs.mdx, packages/storybook8/stories/Concepts/RealTimeText/Docs.mdx
=> Remove Beta Banner for RTT

GROOMME.md, packages/communication-react/CHANGELOG.stable.md
Groom changelog for stable 1.27.0
=> Groom changelog for stable 1.27.0

change-beta/@azure-communication-react-51d3293f-d29e-432c-bd77-abb3e7d6f3b4.json, change/@azure-communication-react-51d3293f-d29e-432c-bd77-abb3e7d6f3b4.json, packages/acs-ui-javascript-loaders/src/callCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/callWithChatCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/chatCompositeLoader.ts, packages/acs-ui-javascript-loaders/src/outboundCallCompositeLoader.ts, packages/communication-react/CHANGELOG.stable.md, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md
* update to use interface
* Change files
* add comments
* update API files
=> [Bugfix] update to use interface (#5836)

change-beta/@azure-communication-react-325e6ec7-6ec7-42b8-a864-835bbef4bb8e.json, change/@azure-communication-react-325e6ec7-6ec7-42b8-a864-835bbef4bb8e.json, packages/storybook8/stories/Composites/CallComposite/Docs.mdx
=> Remove Beta Banner for PSTN and 1:N

change-beta/@azure-communication-react-bdde495d-0b1c-420e-8bb4-72187929f532.json, change/@azure-communication-react-bdde495d-0b1c-420e-8bb4-72187929f532.json, common/config/rush/pnpm-lock.yaml, samples/Calling/src/app/views/HomeScreen.tsx, samples/Server/package.json
Update lock file to include latest rooms sdk for collaborator role. 
Stable lock file already has latest rooms sdk.
Update samples to include new collaborator role
Confirmed role is properly limiting remove and muteothers restrictions.
Even after switching back from presenter role to collaborator role.
=> Update lock file to include latest rooms sdk for collaborator role

change-beta/@azure-communication-react-bdde495d-0b1c-420e-8bb4-72187929f532.json, change/@azure-communication-react-bdde495d-0b1c-420e-8bb4-72187929f532.json, common/config/rush/pnpm-lock.yaml, samples/Calling/src/app/views/HomeScreen.tsx, samples/Server/package.json
…5842)
* Update lock file to include latest rooms sdk for collaborator role
* Change files
* linter is always right
=> [cherry-pick] Update lock file to include latest rooms sdk for collaborator role

common/config/rush/pnpm-lock.yaml
=> [cherry-pick] Remove duplicate sha key

GROOMME.md, packages/communication-react/CHANGELOG.beta.md
=> Groom changelog beta release beta/1.28.0 beta.1

change-beta/@azure-communication-react-3813001b-0be0-479e-8f7e-efc9106084e9.json, change/@azure-communication-react-3813001b-0be0-479e-8f7e-efc9106084e9.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, samples/Server/package.json
=> Update Multer for security patch

change-beta/@azure-communication-react-1fbe85ce-7063-4111-ab55-0577bbe1599f.json, change/@azure-communication-react-1fbe85ce-7063-4111-ab55-0577bbe1599f.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
=> bumping calling beta to 1.36.3-beta.1

GROOMME.md, packages/communication-react/CHANGELOG.stable.md
=> Groom changelog stable remove beta suffix/1.28.0

common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, samples/Server/package.json
Update multer to latest (2.0.1)
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/352
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/353
Fixes https://github.com/Azure/communication-ui-library/security/dependabot/354
=> Update multer to latest (2.0.1)

change-beta/@azure-communication-react-34f07369-28bb-4798-8778-64aaf8da54d1.json, change/@azure-communication-react-34f07369-28bb-4798-8778-64aaf8da54d1.json, samples/CallingStateful/eslint.config.ts, samples/CallingStateful/src/App.tsx, samples/CallingStateful/src/components/CallManager.tsx, samples/CallingStateful/src/components/CallingComponents.tsx, samples/CallingStateful/src/styles/HomeScreen.styles.ts, samples/CallingStateful/src/utils/AppUtils.ts, samples/CallingStateful/src/views/CallScreen.tsx, samples/CallingStateful/src/views/Homescreen.tsx, samples/CallingStateful/src/views/Login.tsx
=> [KTLO][ESLINT] Calling stateful sample

change-beta/@azure-communication-react-bf500f55-e029-446a-9fbe-f81238ea783f.json, change/@azure-communication-react-bf500f55-e029-446a-9fbe-f81238ea783f.json, packages/calling-component-bindings/src/captionsSelector.ts, packages/communication-react/review/beta/communication-react.api.md, packages/communication-react/review/stable/communication-react.api.md, packages/react-components/src/components/CaptionsBanner.tsx, packages/react-components/src/components/styles/Captions.style.ts
Cherry pick group me hot fix into release branch
=> Cherry pick hot fix into release branch

packages/communication-react/CHANGELOG.beta.md
=> Changelog for hotfix

packages/react-components/src/components/DevicesButton.tsx
Remove console log
Left in incorrectly in #5900
n/a
=> Remove console log around default mic device

packages/storybook8/stories/Composites/Adapters/Docs.mdx
Add section on how to use dispose for our adapters
Shows contoso how and when to cleanup the adapters for better memory usage
Validated similar snippet in samples
=> update docs for cleaning up our adapters

change-beta/@azure-communication-react-1a1377c0-d7fe-4201-bfce-5fdeca5f1d15.json, change/@azure-communication-react-1a1377c0-d7fe-4201-bfce-5fdeca5f1d15.json, packages/communication-react/CHANGELOG.stable.md
Cherry pick #5927 to release/1.29.0
=> Fix together mode local label (Cherry pick #5927)

packages/react-components/src/localization/locales/ar-SA/strings.json, packages/react-components/src/localization/locales/cs-CZ/strings.json, packages/react-components/src/localization/locales/cy-GB/strings.json, packages/react-components/src/localization/locales/de-DE/strings.json, packages/react-components/src/localization/locales/en-GB/strings.json, packages/react-components/src/localization/locales/es-ES/strings.json, packages/react-components/src/localization/locales/es-MX/strings.json, packages/react-components/src/localization/locales/fi-FI/strings.json, packages/react-components/src/localization/locales/fr-CA/strings.json, packages/react-components/src/localization/locales/fr-FR/strings.json, packages/react-components/src/localization/locales/he-IL/strings.json, packages/react-components/src/localization/locales/it-IT/strings.json, packages/react-components/src/localization/locales/ja-JP/strings.json, packages/react-components/src/localization/locales/ko-KR/strings.json, packages/react-components/src/localization/locales/nb-NO/strings.json, packages/react-components/src/localization/locales/nl-NL/strings.json, packages/react-components/src/localization/locales/pl-PL/strings.json, packages/react-components/src/localization/locales/pt-BR/strings.json, packages/react-components/src/localization/locales/ru-RU/strings.json, packages/react-components/src/localization/locales/sv-SE/strings.json, packages/react-components/src/localization/locales/tr-TR/strings.json, packages/react-components/src/localization/locales/zh-CN/strings.json, packages/react-components/src/localization/locales/zh-TW/strings.json
=> TDBuild latest localization - cherry pick to 1.29.0

README.md
=> Update Storybook Quickstarts page link in README.md

common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml, samples/Chat/package.json
Axios version update to fix CG alert
=> Axios version update

common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/pnpm-lock.yaml
=> Updated remaining axios dependencies

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update calling dependencies
OCE task to ensure UI Library has the latest updates from calling dependencies
Tested video effects, audio, reactions, and raised hand in CallWithChat samples on beta and stable flavor in group and Teams calls
=> Update calling dependencies

change-beta/@azure-communication-react-b0f2be55-7758-452c-91c7-1b2cec49ab99.json, change/@azure-communication-react-b0f2be55-7758-452c-91c7-1b2cec49ab99.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/variants/stable/common-versions.json, common/config/rush/variants/stable/pnpm-lock.yaml, packages/calling-component-bindings/package.json, packages/calling-stateful-client/package.json, packages/calling-stateful-client/src/TestUtils.ts, packages/communication-react/package.json, packages/react-composites/package.json, packages/storybook8/package.json, samples/CallWithChat/package.json, samples/Calling/package.json, samples/CallingStateful/package.json, samples/ComponentExamples/package.json, samples/StaticHtmlComposites/package.json, samples/tests/package.json
Update calling sdk versions
Housekeeping
CI only
=> Update @azure/communication-calling sdks to latest (`1.39.1` stable and `1.40.1-beta.1` beta)
